### ISSUE TITLE
'audioplayers/AudioplayersPlugin.h' file not found while using audio file in flutter in the ios device

### ISSUE THREAD

**Issue by yash365** [luanpotter/audioplayers#101]
This is my code : pubspec.yaml (using audioplayers: ^0.7.8 plugin for playing audio)
`dependencies:
	  flutter:
		sdk: flutter

	  # The following adds the Cupertino Icons font to your application.
	  # Use with the CupertinoIcons class for iOS style icons.
	  cupertino_icons: ^0.1.2
	  # lib for adding sound
	  audioplayers: ^0.7.8
	  
	dev_dependencies:
	  flutter_test:
		sdk: flutter

	flutter:

	  # the material Icons class.
	  uses-material-design: true

	  # To add assets to your application, add an assets section, like this:
	  assets:
		- assets/sound/correct_answer.mp3
		- assets/sound/wrong_answer.mp3`

	
    
play_audio.dart file Importing audio_cache.dart file to play the audio. I have imported the audio files in assets folder of the project. The same code works fine in the android devices
`import 'package:audioplayers/audio_cache.dart';
	import "package:flutter/material.dart";

	// audio file path
	const correctSoundPath = "sound/correct_answer.mp3";
	const inCorrectSoundPath = "sound/wrong_answer.mp3";

	class PlayAudio extends StatefulWidget {
	_PlayAudioState createState() => _PlayAudioState();
	}

	class _PlayAudioState extends State {
	AudioCache player;

	@override
	void initState() {
	// TODO: implement initState
	super.initState();
	player = AudioCache(); // initialising audio cache
	debugPrint("inside initState");
	}

	Future _playCorrect() async {
	player.play(correctSoundPath);
	debugPrint("inside _playCorrect()");
	}

	Future _playIncorrect() async {
	player.play(inCorrectSoundPath);
	debugPrint("inside _playIncorrect()");
	}

	@override
	Widget build(BuildContext context) {
	return Scaffold(
	body: Column(
	mainAxisAlignment: MainAxisAlignment.center,
	crossAxisAlignment: CrossAxisAlignment.center,
	children: [

		  // correct button
		  MaterialButton(
			child: Text("Correct"),
			onPressed: () {
			  _playCorrect();
			},
		  ),
		  // incorrect button
		  MaterialButton(
			child: Text("Incorrect"),
			onPressed: () {
			  _playIncorrect();
			},
		  )
		],
	  ),
	);
	}
	}`
         
The above code run proper without using audio file. If there is something that i am missing to add, please tell me, and I am using Microsoft visual Studio Code as my IDE

Getting the following error while running this project in iOS device using flutter run :
Error output from Xcode build:
    ** BUILD FAILED **

Xcode's output:

    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support
    Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support
    Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    /Users/quiz/Documents/Project/Flutter_Project/TODO_Flutter_Projects/Quiz/multiple_choice_ios/ios/Runner/Genera
    tedPluginRegistrant.m:6:9: fatal error: 'audioplayers/AudioplayersPlugin.h' file not found
    #import <audioplayers/AudioplayersPlugin.h>

**Comment by jorg1piano** [comment]
I get the same error when trying to archive the app. It seems to build sometimes while testing when running "flutter run", but not always :/

Build time log displays:
```
Lexical or Preprocessor Issue Group
   'audioplayers/AudioplayersPlugin.h' file not found
      GeneratedPluginRegistrant.m
```

Anyone have any ideas?

**Comment by luanpotter** [comment]
Have you tried running `flutter clean && flutter pub get`? Might fix these kinds of issues

**Comment by jorg1piano** [comment]
Yes, It will build the debug build but not the release build. So after thinking about it for a while its probably not a issue with the plugin, but probably some xCode release build configuration thats messed up... Sorry about that

**Comment by jorg1piano** [comment]
It turns out I'm a complete idiot😅 Its been a while since i´ve done any iOS work, but I should have realised this earlier. The reason it didn't work was because I was trying to archive in Runner.xcodeproj instead of Runner.xcworkspace.

Nothing wrong with the awesome work you´ve done! 

I thought I would just mention this if someone else was stuck on this or are running into "Lexical or Preprocessor Issue Group". If none of the other "fixes" work you are probably just doing the same stupid mistake I was.

Anyways, thanks @luanpotter for responding to my inquiry :)

**Comment by WorthPly** [comment]
Open Podfile inside app-dir/ios/
at the top of the file replace
#platform :ios, '9.0'
with
platform :ios, '10.0' use_frameworks!
save the file
then open terminal at app-dir/ios/
run the command
pod install
this will install the required dependency
Thats it, Cheers.

**Comment by yash365** [comment]
Re-installing this command working for me :

In terminal type this command :
brew install --HEAD usbmuxd
 brew link usbmuxd
 brew install --HEAD libimobiledevice
 brew install ideviceinstaller ios-deploy cocoapods
 pod setup

I got the error while using pod setup command 

Following step solved it for me
In Mac open terminal type: rm -rf ~/.cocoapods/repos then type pod setup
