### ISSUE TITLE
Stop audiocache playback

### ISSUE THREAD

**Issue by vikdenic** [luanpotter/audioplayers#102]
I am playing local assets by calling:

`    player.loop(sound.fileName);
`

It successfully loops the audio, but is there any way to then STOP this audio?

**Comment by VarthanV** [comment]
Attempt to perform seekTo in wrong state: mPlayer=0x781b3fd240, mCurrentState=0
when i try to use the stop function as you said please solve this error   error (-38, 0)

**Comment by LiveLikeCounter** [comment]
Hi @luanpotter,
Nice work on the lib!

I tried to stop de audio when played, with the following code:

```
  static AudioCache player = AudioCache(prefix: 'audio/vehicles/');
  
  void playSound(String vehicleSound) {
    player.stop();
    player.loop("$vehicleSound");
  }
```

But the player.stop isnt available: The method 'stop' isn't defined for the class 'AudioCache'.
Try correcting the name to the name of an existing method, or defining a method named 'stop'.

Do you have any suggestions?

**Comment by luanpotter** [comment]
@LiveLikeCounter, the method stop is from AudioPlayer, not AudioCache. You need to access it from the instance returned by the cache's methods (play and loop), as per example and instructions I provided above. Please read our guides and code for more details, and if you then have more questions, feel free to open new issues.

**Comment by LiveLikeCounter** [comment]
Hi @luanpotter thank you for your response! I know the stop method is from AudioPlayer, but I I don't have instantiated AudioPlayer, but I only use Audio cache.

Please, see my repo: https://github.com/LiveLikeCounter/Flutter-Vehicle-Sounds/blob/a30ffd10f274e60b6a43132ed7254ef39fdc9e8a/lib/main.dart#L87 in the onTap, I want stop any current playing sound and start the new one. Can you maybe help me with a little example?

**Comment by erickzanardo** [comment]
@LiveLikeCounter when you call the `play` method from the `AudioCache` class, it returns an instance of the `AudioPlayer` class, you can use that instance.

**Comment by aparadeway** [comment]
https://medium.com/@pongpiraupra/a-comprehensive-guide-to-playing-local-mp3-files-with-seek-functionality-in-flutter-7730a453bb1a

**Comment by willvlad** [comment]
> Hi @luanpotter thank you for your response! I know the stop method is from AudioPlayer, but I I don't have instantiated AudioPlayer, but I only use Audio cache.
> 
> Please, see my repo: https://github.com/LiveLikeCounter/Flutter-Vehicle-Sounds/blob/a30ffd10f274e60b6a43132ed7254ef39fdc9e8a/lib/main.dart#L87 in the onTap, I want stop any current playing sound and start the new one. Can you maybe help me with a little example?

Have you figured out how to stop ALL players that might be playing within the app? Run into a similar issue as I've got potentially more than one player and not necessarily from the same page/file...

**Comment by luanpotter** [comment]
@willvlad no, there is no way to do that. You must hold a reference to all the players you use and stop then as desired.

**Comment by Osama7869** [comment]
I used Audio cache, I play my audio with assets. But now, I want to put stop and play button in it, There is a no properties of stop and play in Audio Cache, How I play and stop audio in Audio Cache.
Please Help me...

**Comment by deepersolids** [comment]
> 
> 
> I used Audio cache, I play my audio with assets. But now, I want to put stop and play button in it, There is a no properties of stop and play in Audio Cache, How I play and stop audio in Audio Cache.
> Please Help me...



Yes, i actually have same error, but i try this:

 `final playerx = new AudioCache(fixedPlayer: AudioPlayer());`

then on my action:

```
playerx.fixedPlayer.stop();
playerx.play('turn2.mp3');
```

i most stop stream my mplayer before i start it. and that make error gone from the world..
