### ISSUE TITLE
Duration Handler gets called multiple times on Android

### ISSUE THREAD

**Issue by IrosTheBeggar** [luanpotter/audioplayers#107]
Sorry for making so many tickets.  I've been using this plugin a lot lately.

I noticed on Android that the duration handler is called repeatedly while streaming.

<img width="694" alt="screen shot 2019-02-01 at 7 25 26 pm" src="https://user-images.githubusercontent.com/1396994/52156588-2bc74280-2657-11e9-9983-07b82c580efa.png">

That screenshot is just from a few seconds of streaming.  It might get called hundreds of times during the entire song.  On iOS the durationHandler gets called just once.

This isn't critical.  It lags my emulator, but things work just fine on my actual phone.

**Comment by pobrejuanito** [comment]
I can confirm

**Comment by pobrejuanito** [comment]
This issue seems to have been resolved with v.0.9.0

**Comment by erickzanardo** [comment]
Great to hear that, closing this then.

**Comment by Kretin1** [comment]
Not sure if it's back or was never resolved, but I'm getting constant duration updates in 0.10.0

**Comment by erickzanardo** [comment]
@Kretin1 have you tried on 0.10.1?

**Comment by Kretin1** [comment]
Yes. Also occurring in 0.10.1. Every position update is accompanied by a duration update.
