### ISSUE TITLE
Incompatible with uuid 2.0.0

### ISSUE THREAD

**Issue by pepie** [luanpotter/audioplayers#114]
```Because every version of audioplayers_with_rate depends on uuid ^1.0.3 and <app name> depends on uuid 2.0.0, audioplayers_with_rate is forbidden.```

**Comment by luanpotter** [comment]
Hi, @pepie , we should update to uuid 2.0.0 right away!

There seems to be a few breaking the dependencies, but just minor api stuff. This lib is used in only one place so it should be easy to update and verify if it's working.

Also only dart side, so you can test on a single platform.

Would you be willing to send us a PR with the update?

Thanks a lot!

**Comment by gustavobrian** [comment]
hi, older librarys requiered uuid 2.0, its a problem.
Please... update dependencie...
VERY VERY THANKS

**Comment by jinfagang** [comment]
@luanpotter Same issue here, to be clear, as for incompatible with uuid, many base package can not be installed.

```
Because flutter_cache_manager >=0.3.0 depends on uuid ^2.0.0 and audioplayers >=0.7.5 depends on uuid ^1.0.3, flutter_cache_manager >=0.3.0 is incompatible with audioplayers >=0.7.5.
```

**Comment by luanpotter** [comment]
Thanks! Release 0.9.0 with this
