### ISSUE TITLE
NoSuchMethodError: The method 'seek' was called on null with AudioCache

### ISSUE THREAD

**Issue by ilkin** [luanpotter/audioplayers#119]
```
AudioCache audioCache = new AudioCache();
audioCache.play('sound3.mp3');
audioCache.fixedPlayer.seek(new Duration(milliseconds: 2000));
```

E/flutter ( 4350): [ERROR:flutter/shell/common/shell.cc(186)] Dart Error: Unhandled exception:
E/flutter ( 4350): NoSuchMethodError: The method 'seek' was called on null.
E/flutter ( 4350): Receiver: null
E/flutter ( 4350): Tried calling: seek(Instance of 'Duration')

**Comment by erickzanardo** [comment]
Try this:

```
AudioCache audioCache = new AudioCache();
var player = await audioCache.play('sound3.mp3');
player.seek(new Duration(milliseconds: 2000));
```

Fixed player property must be set before using it, it is meant to be used if you want to have a single player instance on your code, because AudioCache will create a player otherwise

**Comment by erickzanardo** [comment]
Closing this, due inactivity, if you still got problems, please open a new issue.
