### ISSUE TITLE
onDurationChanged never called !?

### ISSUE THREAD

**Issue by tomrobin-teschner** [luanpotter/audioplayers#124]
This seems to be related / similar (the same?!) as this issue (but since durationHandler is deprecated, I wonder if this is a new issue ...): https://github.com/luanpotter/audioplayers/issues/57

Basically I create a new instance of an audio player and want to subscribe to the streams onAudioPositionChanged and onDurationChanged, which I do like this:

    void initMusicPlayer() {
      _audioPlayer = new AudioPlayer();

      _positionSubscription = _audioPlayer.onAudioPositionChanged.listen((position) => setState(() {
        _position = position;
      }));

      _durationSubscription = _audioPlayer.onDurationChanged.listen((duration) => setState(() {
        print("my duration is " + duration.toString());
        _duration = duration;
      }));
    }

I call this method in the constructor of my player widget where I also play the first song of my playlist with isLocal: true (my files are locally stored on my device). 
Now I have no issue getting the position of the song and can display `_position` just fine in my widget, however `onDurationChanged` is never called and so accessing `_duration` results in `null`. 

The code above is pretty much copied and adjusted so it resembles the example provided here but I can't seem to get the duration, any idea what I could be doing wrong?

**Comment by luanpotter** [comment]
This was probably fixed already by 7959fe1367e4ac6e2afde3ac8c443b720c18f6d8 .

Could you please verify, @tomrobin-teschner ?

Thanks!

**Comment by tomrobin-teschner** [comment]
ahh, that makes so much sense (and I didn't spot the issue because I was looking at the code here at github, not at my local copy of it (version 0.9.0)). in fact, I noticed that `onAudioPositionChanged` fired both the current position and the duration so i fetched the duration from their through some ugly hack, but now it is working like a charm, thanks for the prompt answer and this amazing plugin :)

**Comment by abdullah432** [comment]
> ahh, that makes so much sense (and I didn't spot the issue because I was looking at the code here at github, not at my local copy of it (version 0.9.0)). in fact, I noticed that `onAudioPositionChanged` fired both the current position and the duration so i fetched the duration from there through some ugly hack, but now it is working like a charm, thanks for the prompt answer and this amazing plugin :)

```
_audioPlayer.onAudioPositionChanged.listen((position) => setState(() {
    _position = position;
  }));
```
is never firing/triggering. Can you provide code, which shows how to trigger this method, so we can update the value of _position.

**Comment by PaoloGi** [comment]
same issue as abdullah432

audioPlayer.onAudioPositionChanged
and
audioPlayer.onDurationChanged
are never triggered in flutter web

**Comment by anasssanba1** [comment]
same issue on android

**Comment by jamontes79** [comment]
Same as @PaoloGi
