### ISSUE TITLE
AudioCache plays only the last part of an m4a on Android 9

### ISSUE THREAD

**Issue by Babelfisch** [luanpotter/audioplayers#127]
I try to play some m4a audio files on a Android 9 device but AudioCache plays only the last part of every file. The example file is located in my assets and I play it with `player.play("h_5.m4a")`.

The complete text is „Möchten Sie Fleisch essen?“ (German) but it plays only „essen“. Also with `player.loop("h_5.m4a")` it plays only „esse … essen … essen …“

On iOS it works fine. Any idea, what’s wrong?

Example file: [h_5.m4a](https://www.dropbox.com/s/uul344asbgtxzkm/h_5.m4a?dl=0)

**Comment by erickzanardo** [comment]
Hello, I will try testing, but some questions to help us try to target the
problem:

Does any stacktrace or error log shows up?

Have you tried testing on other android versions?

Have you tried playing this sound native? Like in an android media player
app?

Em qua, 6 de mar de 2019 17:43, Mario Müller <notifications@github.com>
escreveu:

**Comment by erickzanardo** [comment]
Closing this due inactivity, please report back if you still have problems and we will reopen this.
