### ISSUE TITLE
Can not play internet url on android 9

### ISSUE THREAD

**Issue by careyc** [luanpotter/audioplayers#128]
V/MediaHTTPService(23860): MediaHTTPService(android.media.MediaHTTPService@350b07e): Cookies: null
V/MediaHTTPService(23860): makeHTTPConnection: CookieManager created: java.net.CookieManager@e95b9df
V/MediaHTTPService(23860): makeHTTPConnection(android.media.MediaHTTPService@350b07e): cookieHandler: java.net.CookieManager@e95b9df Cookies: null
I/DpmTcmClient(23860): RegisterTcmMonitor from: $Proxy0
D/NetworkSecurityConfig(23860): No Network Security Config specified, using platform default
E/MediaPlayerNative(23860): error (1, -2147483648)
E/MediaPlayer(23860): Error (1,-2147483648)
E/MediaPlayerNative(23860): stop called in state 0, mPlayer(0x7a4b501c00)
E/MediaPlayerNative(23860): error (-38, 0)
V/MediaPlayer(23860): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(23860): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(23860): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(23860): cleanDrmObj: mDrmObj=null mDrmSessionId=null

**Comment by erickcchoi** [comment]
I have the same problem when set "targetSdkVersion"  to 28 in bundle.gradle file and try to open a stream from url "https://metroradio-lh.akamaihd.net/i/104_h@349798/master.m3u8" .

**Comment by Pebsie** [comment]
I have the same problem.

**Comment by Pebsie** [comment]
The solution lies somewhere in project configuration. I could not for the life of me figure out what the offending file is but copying my dart files into the example project made it work, so do that if like me you were totally lost and spent hours trying to fix ^^

**Comment by lucasromanojf** [comment]
I have the same problem with internet radio. Changing to 27 doesn't fix it too.

**Comment by darekaze** [comment]
> Starting with Android 9.0 (API level 28), cleartext support is disabled by default. Because of this, the MediaPlayer was not able to open the provided URL.
> 
> Options are to:
>   - set android:usesCleartextTraffic="true" in AndroidManifest.xml
>   - Use HTTPS

Solutions are explained here Android 8: [Cleartext HTTP traffic not permitted](https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted)

Without this change, the plugin is not able to play any remote file.

**Comment by erickzanardo** [comment]
I have tested and the solution on the link provided by @darekaze works! I am closing this. Thanks @darekaze

**Comment by gordonnchy** [comment]
Allow this permission in Android manifest
android:usesCleartextTraffic="true"

Your manifest should look like this

<application

        android:name="io.flutter.app.FlutterApplication"
        android:label="ui_challenge_gordon"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true"
        >
