### ISSUE TITLE
Sound playing on iPhone even when hardware mute switch is on.

### ISSUE THREAD

**Issue by mploigt** [luanpotter/audioplayers#132]
When I set my iPhone to not disturb me with any sound with the hardware mute switch, I don't want to hear ANY sound (except alarm clock). But `audioplayers` does play sounds regardless of the switch.

**Comment by mploigt** [comment]
OK, I just found the `respectSilence: true` parameter. Maybe it is a good idea to have this set to `true` by default?

**Comment by erickzanardo** [comment]
Hmm, Yeah, I think this could be true by default, in the majority of the time people will want to respect silence I guess

**Comment by luanpotter** [comment]
Even on, say, music players, @erickzanardo ? If so, I totally agree that that should indeed be the default option.

**Comment by erickzanardo** [comment]
@luanpotter lets keep the default to `false`, closing this, since OP found the `respectSilence` flag.
