### ISSUE TITLE
App won't start with plugin installed

### ISSUE THREAD

**Issue by indiepaul** [luanpotter/audioplayers#133]
The plugin completely breaks my app and I've tried installing the plugin several times even on a fresh install. I get this output:

> Launching lib/main.dart on iPhone X in debug mode...
Xcode build done.                                           11.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    === BUILD TARGET audioplayers OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/paul/dev/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.10.1/ios/Classes/AudioplayersPlugin.m:74:47: warning: format specifies type 'double' but the argument has type 'int' [-Wformat]
                        NSLog(@"position: %f %@", milliseconds, call.arguments[@"positions"] );
                                          ~~      ^~~~~~~~~~~~
                                          %d
    /Users/paul/dev/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.10.1/ios/Classes/AudioplayersPlugin.m:104:61: warning: format specifies type 'double' but the argument has type 'int' [-Wformat]
                          NSLog(@"Seeking to: %f milliseconds", milliseconds);
                                              ~~                ^~~~~~~~~~~~
                                              %d
    /Users/paul/dev/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.10.1/ios/Classes/AudioplayersPlugin.m:232:5: error: use of undeclared identifier 'AVAudioSessionCategory'; did you mean 'AVAudioSessionCategoryRecord'?
        AVAudioSessionCategory category;
        ^~~~~~~~~~~~~~~~~~~~~~
        AVAudioSessionCategoryRecord
    In module 'AVFoundation' imported from /Users/paul/dev/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.10.1/ios/Classes/AudioplayersPlugin.m:4:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.3.sdk/System/Library/Frameworks/AVFoundation.framework/Frameworks/AVFAudio.framework/Headers/AVAudioSession.h:642:28: note: 'AVAudioSessionCategoryRecord' declared here
    AVF_EXPORT NSString *const AVAudioSessionCategoryRecord;
                               ^
    /Users/paul/dev/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.10.1/ios/Classes/AudioplayersPlugin.m:232:27: error: expected ';' after expression
        AVAudioSessionCategory category;
                              ^
                              ;
    /Users/paul/dev/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.10.1/ios/Classes/AudioplayersPlugin.m:232:28: error: use of undeclared identifier 'category'
        AVAudioSessionCategory category;
                               ^
    /Users/paul/dev/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.10.1/ios/Classes/AudioplayersPlugin.m:234:9: error: use of undeclared identifier 'category'
            category = AVAudioSessionCategoryAmbient;
            ^
    /Users/paul/dev/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.10.1/ios/Classes/AudioplayersPlugin.m:236:9: error: use of undeclared identifier 'category'
            category = AVAudioSessionCategoryPlayback;
            ^
    /Users/paul/dev/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.10.1/ios/Classes/AudioplayersPlugin.m:239:34: error: use of undeclared identifier 'category'
                        setCategory: category
                                     ^
    /Users/paul/dev/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.10.1/ios/Classes/AudioplayersPlugin.m:232:5: warning: expression result unused [-Wunused-value]
        AVAudioSessionCategory category;
        ^~~~~~~~~~~~~~~~~~~~~~
    3 warnings and 6 errors generated.
Could not build the application for the simulator.
Error launching application on iPhone X.
Exited (sigterm)

**Comment by codediodeio** [comment]
Confirming this issue as well, only fails on iOS. Downgrading to `0.9.0` fixes it.

**Comment by erickzanardo** [comment]
@indiepaul have you tried running the plugin example app? Which xcode version are you using?

**Comment by indiepaul** [comment]
@erickzanardo I have tried the example but I get the same message. 
I am using xcode version 9.3.1, could that be an issue? Everything else works fine though.
I will try it again after I update maybe.

**Comment by erickzanardo** [comment]
I am not an ios expert, but this could be a reason, I guess xcode 9.3.1 is a little old already, can you upgrade it?

**Comment by indiepaul** [comment]
I will try and do that and let you know

**Comment by erickzanardo** [comment]
Closing this due inactivity, please open a new issue in case you still have problems.
