### ISSUE TITLE
Android audio out of sync

### ISSUE THREAD

**Issue by Kretin1** [luanpotter/audioplayers#137]
I'm attempting to play 4-7 audio tracks in sync with each other. 

I load local mp3 files into a list of AudioPlayers by setUrl. When all are loaded I resume them all.
```
    players = new List<AudioPlayer>(7); // 1 backing and 6 vocal
    for (var i = 0; i < 7; i++) {
      players[i] = new AudioPlayer();
      players[i].setReleaseMode(ReleaseMode.STOP);
    }

    players[0].onAudioPositionChanged.listen((p){
      print('0 pos ' + position.value.toString());
      position.add(p);
    });
    for (var i = 1; i < players.length; i++) {
      players[i].onAudioPositionChanged.listen((p){
        print(i.toString() + ' pos ' + position.value.toString());
      });
    }

    for (var i = 0; i < trackCount; i++) {
        print('getting ' + audioPaths[i]);
        await players[i].setUrl(audioPaths[i], isLocal: true);
        //await players[i].play(audioPaths[i], isLocal: true);
      }
      print('resume ' + DateTime.now().toString());
      for (var i = 0; i < trackCount; i++) {
        players[i].resume();
      }
```
When I pause or change position, I resync the files:
```
    for (var i = 0; i < trackCount; i++) {
      players[i].pause();
    }
    for (var i = 0; i < trackCount; i++) {
      await players[i].seek(position.value);
    }

    if (playing) {
      for (var i = 0; i < trackCount; i++) {
        players[i].resume();
      }
    }

```
Doing this I've managed to get all the AudioPlayer's position listeners to report exactly the same position.

However on Android the tracks are wildly out of sync with each other, often by a second or more. 

It's working pretty well on iOS. For the most part the tracks only manage to drift out of sync by a few milliseconds.

I'm not sure how to approach fixing the problem when the positions are being reported as being in sync even when they're not?

I'll try different file formats, and if that doesn't work I'm wondering if adding a batch resume method might work? But hoping someone might have some insight as to why it's happening?

**Comment by erickzanardo** [comment]
Hello @Kretin1, the android media player has a lot of perfomance issues, that would be my guess of will you are experiencing this problem.

You could try using the [low latency play](https://github.com/luanpotter/audioplayers#usage), which works with a better perfomance on Android, just be aware that the low latency api has limitations of playing files with the max size of 1mb.

**Comment by Kretin1** [comment]
Thanks for your suggestion. Unfortunately I can't use the low latency version because I need the ability to adjust the position. It would also be tricky to get my files under 1mb.

**Comment by erickzanardo** [comment]
Keeping this open to remind us to try to find a solution for this.

**Comment by Kretin1** [comment]
I appreciate that, but I think my use case is probably outside the scope of the plugin. I'm currently looking at Superpowered as a potential solution

**Comment by erickzanardo** [comment]
@luanpotter what do you think about this? Do you think this is something on the scope of this library?

**Comment by erickzanardo** [comment]
Closing this in favor of #857
