### ISSUE TITLE
Need getCurrentPosition() method.

### ISSUE THREAD

**Issue by hariom08** [luanpotter/audioplayers#138]
To get Current playing position is a default method in Android media player and I also see it implemented in the 'Player' Abstract class. And there is no method from the plugin. Not sure regarding iOS side. I guess its pretty straight forward to include this method in the plugin. Would be really helpful if added. 
Thanks.

**Comment by erickzanardo** [comment]
This is already implemented by the PositionEvent

https://github.com/luanpotter/audioplayers#position-event

**Comment by hariom08** [comment]
Yes, I checked it already. But the problem with 'onAudioPositionChanged' Stream is that it fire roughly every 200 milliseconds. Since the project that i'm working with needs precise duration of the audio being played (For manipulating word by word text highlight with reference to the audio which needs exact audio timings and also for phrase repeat for learning the words kinda functionality), This 'onAudioPositionChanged' solution will not help. 

Moreover, this is a stream, which is like a workaround. What i'm looking for is a Straight method that just does this as in MediaPlayer.getCurrentPosition() in Android and AVAudioPlayer.currentTime in iOS. Guess this is a meaning request and also easy to accomodate. Since there is no other plugin that does this(getCurrentPosition) and also 'AudioPlayers' only has muple audio playing option, i choosed this one.
Waiting for a positive response.

Ref from Code: 
 /// Stream for subscribing to audio position change events. Roughly fires
  /// every 200 milliseconds. Will continuously update the position of the
  /// playback if the status is [AudioPlayerState.PLAYING].
  Stream<Duration> get onAudioPositionChanged => _positionController.stream;

**Comment by erickzanardo** [comment]
Fair enough, I will re open this and try to take a look, although I don't know how long will take to resolve since we are a bit overwhelmed, so if you can contribute with a PR, would be a lot a help.

**Comment by luanpotter** [comment]
Fixed by #220
