### ISSUE TITLE
error building for ios

### ISSUE THREAD

**Issue by hjc22** [luanpotter/audioplayers#140]
Running pod install...
Running Xcode build...
Xcode build done.                                            2.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET connectivity OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/hjc1/.pub-cache/hosted/pub.flutter-io.cn/audioplayers-0.10.1/ios/Classes/AudioplayersPlugin.m:74:47: warning: format specifies type 'double' but the argument has type 'int' [-Wformat]
                        NSLog(@"position: %f %@", milliseconds, call.arguments[@"positions"] );
                                          ~~      ^~~~~~~~~~~~
                                          %d
    /Users/hjc1/.pub-cache/hosted/pub.flutter-io.cn/audioplayers-0.10.1/ios/Classes/AudioplayersPlugin.m:104:61: warning: format specifies type 'double' but the argument has type 'int' [-Wformat]
                          NSLog(@"Seeking to: %f milliseconds", milliseconds);
                                              ~~                ^~~~~~~~~~~~
                                              %d
    /Users/hjc1/.pub-cache/hosted/pub.flutter-io.cn/audioplayers-0.10.1/ios/Classes/AudioplayersPlugin.m:232:33: error: expected ';' after expression
        AVAudioSessionCategoryRecord category;
                                    ^
                                    ;
    /Users/hjc1/.pub-cache/hosted/pub.flutter-io.cn/audioplayers-0.10.1/ios/Classes/AudioplayersPlugin.m:232:34: error: use of undeclared identifier 'category'
        AVAudioSessionCategoryRecord category;
                                     ^
    /Users/hjc1/.pub-cache/hosted/pub.flutter-io.cn/audioplayers-0.10.1/ios/Classes/AudioplayersPlugin.m:234:9: error: use of undeclared identifier 'category'
            category = AVAudioSessionCategoryAmbient;
            ^
    /Users/hjc1/.pub-cache/hosted/pub.flutter-io.cn/audioplayers-0.10.1/ios/Classes/AudioplayersPlugin.m:236:9: error: use of undeclared identifier 'category'
            category = AVAudioSessionCategoryPlayback;
            ^
    /Users/hjc1/.pub-cache/hosted/pub.flutter-io.cn/audioplayers-0.10.1/ios/Classes/AudioplayersPlugin.m:239:34: error: use of undeclared identifier 'category'
                        setCategory: category
                                     ^
    /Users/hjc1/.pub-cache/hosted/pub.flutter-io.cn/audioplayers-0.10.1/ios/Classes/AudioplayersPlugin.m:232:5: warning: expression result unused [-Wunused-value]
        AVAudioSessionCategoryRecord category;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    3 warnings and 5 errors generated.

**Comment by erickzanardo** [comment]
Have you tried running the example app on ios?

**Comment by erickzanardo** [comment]
Closing this due inactivity, please open a new issue in case you still have problems.
