### ISSUE TITLE
Option to continue playing audio when the app is in the background?

### ISSUE THREAD

**Issue by subhash27** [luanpotter/audioplayers#145]
Hi,
Really nice work on the plugin. Just checking if its possible to add an option so that the audio continues to play even when the app is in the background?

**Comment by erickzanardo** [comment]
Hey, this should already be happening by default! Have you encountered any problems?

**Comment by subhash27** [comment]
Sry got confused with the older audioPlayer plugin. Its working here. Again great work on the plugin.

Also while first playing a remote url on ios, it takes abt 5-6 sec for the audio to start. I played around with seturl() but if the url is dynamic like in a music player playing remote audio files, the url to play is not known in advance. Is 5-6 sec expected behaviour then or is there anything that can be done to speed up initial audio load?

**Comment by erickzanardo** [comment]
There were some reports of delay on playing remote urls, but so far we did not found any reason why, some urls plays fast, some has this delays, there were even delays of almost 20 secs. My luck guess is that this delay is a combination of network+device(physical or emulator), so there ins't much for us to track this delay down :(

**Comment by NeroJz** [comment]
Hi, it seemed like the audio stopped playing while it is in background on iOS.

**Comment by erickzanardo** [comment]
Just tested on iOs, and audio continue playing, even on background, closing this.
