### ISSUE TITLE
Improvements for testing

### ISSUE THREAD

**Issue by hugocbpassos** [luanpotter/audioplayers#150]
Audioplayers used to be test-friendly until the implementation of `Stream`s. I can no longer create a AudioPlayerMock implementing `AudioPlayer` because all `StreamController`s are private, so I cannot notify player state's changes in my overridden `play` method . I suggest doing the following change for all `StreamController`s:

    final StreamController<AudioPlayerState> _playerStateController = createPlayerStateController();
    StreamController<AudioPlayerState> createPlayerStateController() => StreamController.broadcast();

So I can override `createPlayerStateController` and make it return my own `StreamController`.

**Comment by luanpotter** [comment]
That makes sense, would be a nice addition.

Would you like to help out with a PR?

**Comment by hugocbpassos** [comment]
There you go.

**Comment by luanpotter** [comment]
Merged. Thanks a lot, @hugocbpassos !
