### ISSUE TITLE
Physical volume controls not working as expected

### ISSUE THREAD

**Issue by jorg1piano** [luanpotter/audioplayers#153]
Currently, on Android, you have to adjust the "Ringtone volume" instead of the "media volume" to adjust the volume of the audio sent through the player. Works as expected on iOS.

It would be useful if you could set the audio "streamType" for Android.

**Comment by luanpotter** [comment]
Hi, @jorg1piano ! Thanks for the feedback.

Currently we use the `respectSilence` flag to set the stream type:

```dart
    .setUsage(respectSilence ? AudioAttributes.USAGE_NOTIFICATION_RINGTONE : AudioAttributes.USAGE_MEDIA)
```

It would be good to have a more advanced option to control exactly what stream type you want, and you could make a PR if you want!

But for your specific case, if you are not setting respectSilence, it should be using the MEDIA stream type...

Not sure why it wouldn't...

**Comment by erickzanardo** [comment]
Any news on that @jorg1piano did the suggestion from luan solved your issue?

**Comment by jorg1piano** [comment]
@erickzanardo 
Sorry, forgot to reply. It solved the issue. I accidentally set the respectSilence flag to true. When set to false the audio player uses the Media stream type :)

**Comment by erickzanardo** [comment]
Glad you got it working! Thanks for reporting back.
