### ISSUE TITLE
playback speed

### ISSUE THREAD

**Issue by Weststreet** [luanpotter/audioplayers#155]
Is there any plan to add a feature to control playback speed?

**Comment by erickzanardo** [comment]
At the moment we are only tried to solve bugs and issue, because of lack os time, we can't add new features.

But would happily accept a PR with this if you are willingly to contribute.

**Comment by dvorapa** [comment]
Discussed further in #224: for iOS already fixed, for Android there is a patch coming: #304

**Comment by erickzanardo** [comment]
Closing in favor of #224
