### ISSUE TITLE
Can't play m4a on Android

### ISSUE THREAD

**Issue by rafante** [luanpotter/audioplayers#156]
I have this app that has a chat screen and I'm adding audios like WhatsApp and IOS generates m4a audio and android generates mp4 audios. IOS can play both, but android will only play mp4 it doesn't play m4a audios. The log generated is down below (that log is generated when I call play(). An observation: The same play() method works like a charm in IOS for both m4a and mp4 (generated in the android version).

Thanks in advance.

[ +19 ms] E/MediaPlayerNative( 6119): error (1, -1007)
[ ] E/MediaPlayerNative( 6119): Attempt to call getDuration in wrong state: mPlayer=0x8c1ac1a0, mCurrentState=0
[ ] E/MediaPlayerNative( 6119): error (-38, 0)
[ ] E/MediaPlayer( 6119): Error (1,-1007)
[ ] E/MediaPlayerNative( 6119): stop called in state 0, mPlayer(0x8c1ac1a0)
[ ] E/MediaPlayerNative( 6119): error (-38, 0)
[ ] V/MediaPlayer( 6119): resetDrmState: mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
[ ] V/MediaPlayer( 6119): cleanDrmObj: mDrmObj=null mDrmSessionId=null
[ ] V/MediaPlayer( 6119): resetDrmState: mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
[ ] V/MediaPlayer( 6119): cleanDrmObj: mDrmObj=null mDrmSessionId=null

**Comment by rafante** [comment]
I have this app that has a chat screen and I'm adding audios like WhatsApp and IOS generates m4a audio and android generates mp4 audios. IOS can play both, but android will only play mp4 it doesn't play m4a audios. The log generated is down below (that log is generated when I call play()

[  +19 ms] E/MediaPlayerNative( 6119): error (1, -1007)
[        ] E/MediaPlayerNative( 6119): Attempt to call getDuration in wrong state: mPlayer=0x8c1ac1a0, mCurrentState=0
[        ] E/MediaPlayerNative( 6119): error (-38, 0)
[        ] E/MediaPlayer( 6119): Error (1,-1007)
[        ] E/MediaPlayerNative( 6119): stop called in state 0, mPlayer(0x8c1ac1a0)
[        ] E/MediaPlayerNative( 6119): error (-38, 0)
[        ] V/MediaPlayer( 6119): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
[        ] V/MediaPlayer( 6119): cleanDrmObj: mDrmObj=null mDrmSessionId=null
[        ] V/MediaPlayer( 6119): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
[        ] V/MediaPlayer( 6119): cleanDrmObj: mDrmObj=null mDrmSessionId=null

**Comment by erickzanardo** [comment]
Is this m4a a local file? Have you tried playing it on other players, like VLC for example?

**Comment by erickzanardo** [comment]
Closing due inactivity.

**Comment by xSuperMu** [comment]
I'm facing same issue @erickzanardo 
with m4a & wav files

**Comment by Gustl22** [comment]
Plz open a new issue with all relevant information @xSuperMu. Also note this PR: https://github.com/bluefireteam/audioplayers/pull/1691
