### ISSUE TITLE
iOS Background 

### ISSUE THREAD

**Issue by ccadieux** [luanpotter/audioplayers#157]
In order to have music play in the background on iOS I need to add the following to info.plist. Would probably be good to add that to the readme.

```
  <key>UIBackgroundModes</key>
  <array>
  	<string>audio</string>
  </array>
```

**Comment by erickzanardo** [comment]
Thanks, I will add it to the troubleshooting

**Comment by erickzanardo** [comment]
Done: https://github.com/luanpotter/audioplayers/commit/6fc148d56597abffb3c2ebfa9792a26b7915d968

Thanks @ccadieux
