### ISSUE TITLE
iOs bug when play after pause

### ISSUE THREAD

**Issue by KarmaEstudio** [luanpotter/audioplayers#158]
When I press Play after pause the audio, the app crashes.

Tried in iOS simulator with the example code. In android simulator works fine.

I didnt try with real ios device

**Comment by vancegillies** [comment]
I fixed this yesterday

It’s because the play button calls play() and not resume() 

Having issued a pull request for it yet

**Comment by vancegillies** [comment]
I’m new to coding so could someone else confirm this is the actual issue

I may very well be missing something.

**Comment by luanpotter** [comment]
Both play and resume should work fine IMHO; @vancegillies , please submit your PR so we can find out together what's going on :)

**Comment by vancegillies** [comment]
@luanpotter Been out of the loop for a while. checked updated versions and was unable to recreate the problem. thinking it was either an Xcode or iOS bug that has since been fixed??

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
