### ISSUE TITLE
Can I fetch all the local audio file in some way?

### ISSUE THREAD

**Issue by SelmerZhang** [luanpotter/audioplayers#159]

**Comment by tnup** [comment]
do you mean loadAll in audioCache? 

https://github.com/luanpotter/audioplayers/blob/master/doc/audio_cache.md

**Comment by SelmerZhang** [comment]
> do you mean loadAll in audioCache?
> https://github.com/luanpotter/audioplayers/blob/master/doc/audio_cache.md

I mean load all local audio file on the disk/storage/sdcard

**Comment by tnup** [comment]
I do not know, have not seen such a thing in the docs, but you can do it in two steps yourself using the info (get all the filenames yourself, then load them using loadAll):

https://stackoverflow.com/questions/54311816/flutter-how-to-get-all-the-image-file-name-from-images-folder

**Comment by IrosTheBeggar** [comment]
@SelmerZhang 

I think this is outside the scope of this plugin.  If you feel like digging through some source code, I have an app that can browse and play local audio files: https://github.com/IrosTheBeggar/mstream-flutter

**Comment by erickzanardo** [comment]
Agreed with @IrosTheBeggar , this is not on our scope.
