### ISSUE TITLE
Android X issue?

### ISSUE THREAD

**Issue by jinfagang** [luanpotter/audioplayers#160]
Just using 0.11 version:

```
* What went wrong:                                                      
Execution failed for task ':audioplayers:verifyReleaseResources'.       
> java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: AAPT2 error: check logs for details
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 10s                                                     
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      10.8s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
```

whole app can not be built now

**Comment by luanpotter** [comment]
This trace mentions some sort of log file... Could you please provide that? This error is a bit cryptic to me

**Comment by jinfagang** [comment]
@luanpotter  Hi. interestingly, when I using `flutter run` rather than `flutter run --release` it can built.

So, I suppose it is something todo with --release mode? Can you test on your case? It seems not work for me under release mode. And this error just can not built through

**Comment by erickzanardo** [comment]
Have you tried following the link suggested on your log? https://goo.gl/CP92wY

**Comment by jinfagang** [comment]
@erickzanardo  I am in China....... google is very far.... to access.......

**Comment by erickzanardo** [comment]
hmmm, sorry to hear that, but given your log, this very much like to be problems with android X, make sure that your project is already migrated to the Android X support lib, there are a lot of good resources online, and you can also use the audioplayers example app as reference.

If for some reason you can't migrate to Android X, I recommend you using the version 0.10.x of audioplayers, which does not require Android X.

**Comment by IrosTheBeggar** [comment]
@jinfagang I hit this problem and found the solution here: https://github.com/flutter/flutter/issues/27106

You need to upgrade grade.build to use `compileSdkVersion` of `28`

**Comment by erickzanardo** [comment]
Closing due inactivity.

**Comment by nni123** [comment]
> @jinfagang I hit this problem and found the solution here: [flutter/flutter#27106](https://github.com/flutter/flutter/issues/27106)
> 
> You need to upgrade grade.build to use `compileSdkVersion` of `28`

that works for me..thanks

**Comment by MonicaTanglu** [comment]
也有可能是你的版本太低了，升级一下audioplayers的版本。（我也是这个问题，升级了就🆗了）
