### ISSUE TITLE
iOS buffering not working. It waits to download the file 

### ISSUE THREAD

**Issue by vmihalachi** [luanpotter/audioplayers#161]
Hi, on the Android the plugin works great but on iOS there is a big initial lag. It seems like it is waiting to download all the file before playing. I can notice the same thing on a Mac by using Safari instead of Chrome/Firefox. Firefox is really immediate. 

Do you know what it could be?

**Comment by erickzanardo** [comment]
This file doesn't look like a streaming audio, when opening on the browser it has a finish time, something that a stream would not have, so I am a little confused about this.

Either way I tested this link on the example app, and everything worked great, there is a small delay, but not major, and this link redirects to another url, redirects take sometime, so that could be one of the reasons for the delay.

**Comment by vmihalachi** [comment]
Hi @erickzanardo, thanks for your time. You are right, I meant buffering instead of streaming. Anyway on slow connections is really noticeable the difference, it seems to me that Android buffers the file while iOS downloads it first. 

Could this links be related to this issue?
https://stackoverflow.com/questions/40442265/avplayer-takes-long-time-to-start-playing
https://gitlab.com/exitlive/music-player/commit/3cea12d101793f050aa7cf6de6948adbd5e248ea
https://stackoverflow.com/questions/39762142/avplayer-does-not-play-video-instantly-on-ios-10-while-audio-playing-only

**Comment by erickzanardo** [comment]
Could be related, I am not expert on iOs but this property `automaticallyWaitsToMinimizeStalling ` would be worth a test, I have not experienced any delays on my tests, would you be willing to test this and sending us a PR, or reporting back if it improves and we them we can change the plugin?

**Comment by guilhermeagostinelli** [comment]
This seems to be fixed in #396

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening

**Comment by chethanprabhakar** [comment]
Hello @erickzanardo
I am facing the same issue in iOS with ^0.20.1 version
