### ISSUE TITLE
resources error

### ISSUE THREAD

**Issue by jinfagang** [luanpotter/audioplayers#162]
```
FAILURE: Build failed with an exception.                                                                                                                                                                        * What went wrong:                                                                                      Execution failed for task ':audioplayers:verifyReleaseResources'.                                       > java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: AAPT2 error: check logs for details
```

I can confirm this is some issue in audioplayers package, any fix on this?

**Comment by jinfagang** [comment]
either work with git:

```
audioplayers:
    git:
      url: "https://github.com/luanpotter/audioplayers"
```
```
Could not find a file named "pubspec.yaml" in https://github.com/luanpotter/audioplayers 7a4c33425ddd78c54aba07d86f3f9a4a0051769b.
```

**Comment by erickzanardo** [comment]
This does seems like a problem with pub, and not audioplayers, I have tested on the example app, using the git dependency, and everything worked fine.

I did a very quick search and find this, I think it is heavily related: 

https://github.com/fluttercommunity/flutter_launcher_icons/issues/50

**Comment by jinfagang** [comment]
@erickzanardo  I just delete all audioplayers codes, as well as upgrade image_picker and then very thing can be built into release

**Comment by erickzanardo** [comment]
What do you mean about deleting all audiplayers code?

Is your problem solved?

**Comment by jinfagang** [comment]
@erickzanardo  I don't know is the auduiplayers problem or not. It's relate to all libs I use (some using androidx some not, those not support android x will not compitable with those support, they can not coexist). And audioplayers has some resouces issue which I dont know why, after comment audioplayers lib and remove all codes related audioplayers, it can built now

**Comment by erickzanardo** [comment]
I still not sure why/or what this resource problem is, audioplayers is working fine, we use it daily, I even tried changing to use the git dependency on the example app e it worked pretty well.

This resource issue seems to be very related to the link I sent you above, with the bug on pub.

About the Android X problem, if you can't use the latest version o audiplayers because of Android X, you can use audioplayers 0.10.1, which still uses the support library. But I highly recommend migrating to Android X, since google has already announced that the support library is going to be deprecated very soon.

**Comment by jinfagang** [comment]
@erickzanardo Thanks for replying. I can find the pub.yml. just ignore this, it's complicated. Just on the opposite side, I need AndroidX support as my other lib all migrated into androidx. 

Since audioplayers already support it, it must be other library problem. I shall test it one more time. Thanks for your suggestions again.
