### ISSUE TITLE
Upgrade audioplayers to use path_provider v1.0

### ISSUE THREAD

**Issue by IrosTheBeggar** [luanpotter/audioplayers#164]
I'm trying to upgrade my app to use path_provider 1.0 but it won't let me because audioplayers is using v0.5

**Comment by luanpotter** [comment]
Hi, @IrosTheBeggar , I think it is very important to keep our dependencies up to date. Could you help us making a PR a testing the new version to see if everything is working? Specially the AudioCache :)

**Comment by IrosTheBeggar** [comment]
@luanpotter I will try to get to it, but I'm currently busy working on my own app where I'm integrating the audioplayers plugin with the audio_service plugin.  So don't wait up for me.

And thanks for the great plugin. My app wouldn't be possible without this

**Comment by erickzanardo** [comment]
I will try to handle this issue this weekend, should be simple

**Comment by erickzanardo** [comment]
Fixed on 89394c05a829c9ed7598e1dec6705d227d015425.

Should be released soon on `0.12.0`.

Thanks @IrosTheBeggar

**Comment by iNima** [comment]
I'm not sure how we can fix this issue but now that audioplayers requires path_provider ^1.1.0, I can't use it anymore along side other packages such as `cached_network_image` and `extended_image` which are dependent on path_provider ^0.5.0+1
Should I give up using audioplayers till the other packages upgrade to path_provider ^1.1.0?
Worst case scenario I can downgrade this audioplayers to 0.11.0, though.

**Comment by erickzanardo** [comment]
@iNima I recommend you downgrading audiplayers to `0.11.0`, where we still uses path_provider `0.5.0`, at least until those packages upgrade their version, which I guess should happen soon.

The difference between 0.11.0 and 0.12.0 is basically only the upgrade of path_provider package, so you should not have any problems doing that.

**Comment by iNima** [comment]
Yes, I think this is a reasonable decision at the moment.
Thanks.
