### ISSUE TITLE
Cannot play online file

### ISSUE THREAD

**Issue by ilovezwq** [luanpotter/audioplayers#165]
V/AudioManager(17587): playSoundEffect   effectType: 0
V/AudioManager(17587): querySoundEffectsEnabled...
D/MediaPlayerNative(17587): MediaPlayer::setVolume(1.000000, 1.000000)
D/MediaPlayerNative(17587): MediaPlayer::setVolume(1.000000, 1.000000)
I/PlayerBase(17587): isRestricted: falseLeftvolume: 1.0 Rightvolume: 1.0mPanMultiplierL: 1.0mPanMultiplierR: 1.0
V/MediaHTTPService(17587): MediaHTTPService(android.media.MediaHTTPService@9966119): Cookies: null
I/MediaPlayerNative(17587): setDataSource(http://192.168.0.101:8080/upload/resource/raz_gogogo_p4_text.mp3)
V/MediaHTTPService(17587): makeHTTPConnection: CookieHandler (java.net.CookieManager@5b97463) exists.
V/MediaHTTPService(17587): makeHTTPConnection(android.media.MediaHTTPService@9966119): cookieHandler: java.net.CookieManager@5b97463 Cookies: null
D/MediaPlayerNative(17587): Message: MEDIA_ERROR(100), ext1=MEDIA_ERROR_UNKNOWN(1), ext2=0x80000000
E/MediaPlayerNative(17587): error (1, -2147483648)
E/MediaPlayer(17587): Error (1,-2147483648)
V/PlayerBase(17587): baseStop() piid=24871
I/MediaPlayer(17587): [HSM] stayAwake false uid: 10627, pid: 17587
E/MediaPlayerNative(17587): stop called in state 0, mPlayer(0x7b87c3f700)
D/MediaPlayerNative(17587): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
E/MediaPlayerNative(17587): error (-38, 0)
V/PlayerBase(17587): baseStop() piid=24871
I/MediaPlayer(17587): [HSM] stayAwake false uid: 10627, pid: 17587
D/MediaPlayerNative(17587): Action:reset_l, CurrentState:MEDIA_PLAYER_IDLE
V/MediaPlayer(17587): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(17587): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/PlayerBase(17587): baseRelease() piid=24871 state=4
I/MediaPlayer(17587): [HSM] stayAwake false uid: 10627, pid: 17587
V/MediaPlayer(17587): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(17587): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/MediaPlayerNative(17587): Pid:17587 MediaPlayer destructor
I/MediaPlayer(17587): [HSM] stayAwake false uid: 10627, pid: 17587

**Comment by erickzanardo** [comment]
Is this file accessible on the internet? I couldn't access it.

Is this on Android 9? If so check out this: https://github.com/luanpotter/audioplayers/blob/master/troubleshooting.md#android

**Comment by erickzanardo** [comment]
Closing due inactivity.
