### ISSUE TITLE
How can I stop it?

### ISSUE THREAD

**Issue by arieslee** [luanpotter/audioplayers#166]
When i used audio_cache ,i can play mp3
`player.loop('play.mp3')`

but, i can't stop play !!

I called player.clear('play.mp3') 

I can't stop using this method.

**Comment by erickzanardo** [comment]
You receive an instance of `Future<AudioPlayer>` when calling `play`.

So
```dart
AudioPlayer instance = await player.loop('play.mp3')
instance.stop()
```

**Comment by arieslee** [comment]
> You receive an instance of `Future<AudioPlayer>` when calling `play`.
> 
> So
> 
> ```dart
> AudioPlayer instance = await player.loop('play.mp3')
> instance.stop()
> ```

Thank you very much~~
