### ISSUE TITLE
How To make interactive notification in Flutter

### ISSUE THREAD

**Issue by qq125183592** [luanpotter/audioplayers#169]
I am making a music player app in Flutter and I am not able to find anyway to make widget or something that is displayed in the notification tray and can play or pause the music. Is it even possible to achieve this in flutter and if yes, how can I do that? Thanks in advance.

**Comment by erickzanardo** [comment]
Hello, this is kind out of scope of this plugin, but there are some people trying to achieve this on this issue, you should take a look: https://github.com/luanpotter/audioplayers/issues/55

**Comment by qq125183592** [comment]
tks~
