### ISSUE TITLE
The Completion Event Does Not Trigger Correctly

### ISSUE THREAD

**Issue by bianyukun1213** [luanpotter/audioplayers#170]
Hi, I am a Dart beginner.
It seems that the completion event does not trigger correctly in my project. It only triggers once when the app initialized. I even didn't call play(). It happens on my Android and iOS devices. I don't know whether I did something wrong. And sorry for my poor English. I hope you can understand.

**Comment by bianyukun1213** [comment]
I temporarily compare the duration and current position to play the next audio in the playlist. It woks well.

**Comment by db-rdz** [comment]
I am having problems with the same thing. I am using a single player instance and changing the location once the mp3 completes to play the next file. It looks like the completion event listener always works for the first audio file but after that the my handler is not fired even though the console says that the listener was triggered.

**Comment by erickzanardo** [comment]
@luanpotter it seems that neither the completion handler, or duration handler is been updated, do you think you can take a look on this?

**Comment by luanpotter** [comment]
No handlers were working on the 0.12.0 version due to a change in the channel mechanics and a bug where we didn't expose some errors. I fixed that on 0.12.1, could you please verify?

**Comment by bianyukun1213** [comment]
Sorry, it's still not working. Maybe I did something wrong.

**Comment by erickzanardo** [comment]
@bianyukun1213 can you provide us with a repository with the error happening so we can track this down?

**Comment by bianyukun1213** [comment]
> @bianyukun1213 can you provide us with a repository with the error happening so we can track this down?

Yes, I can. Thank you! Here's the [link](https://1drv.ms/u/s!AnLK-tZWj_Uvia5bm9Bjq-H9lerIqA). I'm not a programmer, just a student who is interested in programming. So the code is bad. Sorry! 😄

**Comment by GUEYEDSMF** [comment]
Hello , i'm using an AudioCache class , so when i play an audio file in assets folders , 

`playAudio(int nAudio) {
    print('******** Now Playing Audio N* $nAudio ********');
   return audioCache.play('a$nAudio.mp3').then((audio) {
      return audio.onPlayerCompletion.listen((_){
        print("Audio Played");
      });
    });
  }`

but i want to return the audio.onPlayerCompletion... to a future using **asFuture** method but it doesn't work  because the **onDone** never fire. (I saw that inside it uses a **broadcastStream**).

**Comment by guilhermeagostinelli** [comment]
The callback is not firing for me when using LOOP release mode...

**Comment by erickzanardo** [comment]
There isn't enough information on this issue for us to act on. Please edit this, or open a new one and please follow the issue template.

Feel free to comment here and we can re open this eventually.
