### ISSUE TITLE
No Background Media Controls

### ISSUE THREAD

**Issue by BND10706** [luanpotter/audioplayers#173]
There is no background media controls, at least on iOS. While the speaker can be heard in the background, there is no media controls to control it.

**Comment by erickzanardo** [comment]
I don't think you need specific methods to handle the player in the background, the audioplayer instance already have the methods to play, stop and etc.

I think you just need to run those control on the background.

I have never done it myself, but it seems that this link is the way to do it: https://flutter.dev/docs/development/packages-and-plugins/background-processes

**Comment by erickzanardo** [comment]
Closing this due inactivity, please, open a new issue or comment here if the suggestion above did not work for you.
