### ISSUE TITLE
Show player in lock screen

### ISSUE THREAD

**Issue by iNima** [luanpotter/audioplayers#174]
Is it possible to show the player in lock screen on iOS and Android?
Usually, users are listening to the audio while their phone is locked and they control the player right from the lock screen.
I think it is a very important feature for most audio player apps.
Is it already exist or on the todo list?

**Comment by erickzanardo** [comment]
Hello,

This is not on our todo list at the moment, and I am not sure this is inside the scope of this package, what do you think @luanpotter ?

**Comment by luanpotter** [comment]
That's certainly out of scope, but you can look for plugins for specifically showing notifications on the lock screen. Then you can compose this plugin (which handles solely playing audios) with that one.

**Comment by iNima** [comment]
Thanks for your reply @erickzanardo @luanpotter 
I'll try other plugins but I think for showing audio player in lock screen we need to do something specifically related to the audio player and it is not a simple notification. 
For example, in swift 4 we do something like this to show the audio player in lock screen mode:

```
func setupLockScreen(){
        let commandCenter = MPRemoteCommandCenter.shared()
        commandCenter.nextTrackCommand.isEnabled = true
        commandCenter.togglePlayPauseCommand.addTarget(self, action: #selector(controlPause))
        MPNowPlayingInfoCenter.default().nowPlayingInfo = [MPMediaItemPropertyTitle: currentStation]
 }
```

**Comment by Sun3** [comment]
Adding audio controls on the lock screen is a very important feature to add and I sure would love to see it. Thanks
