### ISSUE TITLE
There should be a load method to load the audio so that onDurationChanged can emit the duration before calling play

### ISSUE THREAD

**Issue by jorg1piano** [luanpotter/audioplayers#175]
Maybe it would be a good idea to have a load method or prepare method so that you could get the Duration of the audio clip without calling play...

So when you call load(String url) -> Future
 - The file is loaded and the duration is posted to the onDurationReady stream

**Comment by jorg1piano** [comment]
Some how I missed this part in the docs... Sorry about that.


 await audioPlayer.setUrl('clicking.mp3'); // prepare the player with this audio but do not start playing
  await audioPlayer.setReleaseMode(ReleaseMode.STOP); // set release mode so that it never releases

  // on button click
  await audioPlayer.resume(); // quickly plays the sound, will not release

**Comment by akdu12** [comment]
does setUrl populate onDurationChanage stream?
