### ISSUE TITLE
the method setVolume doesn't work

### ISSUE THREAD

**Issue by JiweiMaster** [luanpotter/audioplayers#176]
when i used the method 'setVolume' to volume up, but it did't work--- -:)

audioPlayer.setVolume(0);
final file = new File('${(await getTemporaryDirectory()).path}/music.mp3');
await file.writeAsBytes((await rootBundle.load('assets/mp3/beep.mp3')).buffer.asUint8List());
await audioPlayer.play(file.path, isLocal: true);

**Comment by luanpotter** [comment]
What do you mean it didn't work? If you set volume to zero, it will not be a volume up... Looks all right to me...

**Comment by erickzanardo** [comment]
Any news on this @JiweiMaster?

Like Luan said, you are setting the volume to zero... Can you provide a better error explanation?

**Comment by JiweiMaster** [comment]
when I set the system volume to some values by manually, then I use the function audioPlayer.setVolume(0);,but it had no effects

**Comment by JiweiMaster** [comment]
I also add the autority '<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>' in android manifest file

**Comment by JiweiMaster** [comment]
similarlly,when i set the system volume to zero by manually , then i use the function 'audioPlayer.setVolume(0.9)',it still has no effects

**Comment by JiweiMaster** [comment]
@luanpotter @erickzanardo  thanks

**Comment by JiweiMaster** [comment]
maybe I known something, the function setVolume() won't have effects, if the system's volume is zero,because the function  depend on the current system volume

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
