### ISSUE TITLE
Icecast live stream (http/MP3) hangs after a while (Android)

### ISSUE THREAD

**Issue by patrickbz** [luanpotter/audioplayers#181]
Hi! I've got some trouble playing an icecast live stream in background in Android. After a while it just hangs without firing any events. Remote play of MP3 files works, on iOS both Icecast and remote files sources work good. Any hints? Thank you :)

**Comment by erickzanardo** [comment]
Is there any error or stack trace that you can provide us? What is icecast live stream?

**Comment by patrickbz** [comment]
Unfortunately no error or stack trace... It simply stop consuming the stream. It is a normal MP3 stream served by an icecast media server (http://icecast.org) the only difference from a standalone MP3 is that the live stream does not have a fixed duration
On iOS it works with no issues, only Android seems affected
On Android i've temporarly switch to flutter_radio to workaround the problem
Have a nice day :)

**Comment by luanpotter** [comment]
closed in favour of #383
