### ISSUE TITLE
Unable to get player on ioS working while using google cloud storage

### ISSUE THREAD

**Issue by raghav85** [luanpotter/audioplayers#183]
G'day,

I am currently experiencing issue with getting to play audio files streamed from Google cloud storage bucket to play on real iOS devices - Iphone 8 and Iphone SE both having the latest iOS updates. 
Tried with both modes of player - Media Player and Streaming.

Cloud storage URL looks like: https://firebasestorage.googleapis.com/v0/b/mybucket.appspot.com/o/w%3g2Fcc59f-1423-4abe.mp4?alt=media&token=xxx

When I try with public URLs, I don't get the error and it plays well:
 https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4 

Error received in _audioPlayer.onPlayerError : AVPlayerItemStatus.failed

Version: 0.12.0

Strangely on Android, there are no issues observed irrespective of the URLs used and works great!

Many Thanks.

**Comment by raghav85** [comment]
After many hours of troubleshooting found that if the **gzip** option is set to true while objects are being uploaded to Cloud storage, then playing it in iOS using AVplayer throws player error as above. Android doesn't seem to care and plays well irrespective of the option set.
This may be useful for someone in the future.
Thanks!

**Comment by erickzanardo** [comment]
Thanks for reporting back, sorry we did not responded in time, we have been very busy lately and not able to respond issue, I will add this to the troubleshoot.md for easy access to this.

**Comment by sakina1403** [comment]
@raghav85 @erickzanardo Thanks for finding the issue. How did you workaround this?

**Comment by toonztudio** [comment]
I got this problem on cloud storage and shared hosting. So I exported file to .m4a instead of .mp3 and it's fixed on both remote location (shared hosting and cloud firestore).

**Comment by sakina1403** [comment]
ohh. So you re-uploaded the audio in a different format?

**Comment by toonztudio** [comment]
yes, i just have 2 audio files. reupload was the easiest way for this
situation.

**Comment by thejacer87** [comment]
> After many hours of troubleshooting found that if the **gzip** option is set to true while objects are being uploaded to Cloud storage, then playing it in iOS using AVplayer throws player error as above. Android doesn't seem to care and plays well irrespective of the option set.
> This may be useful for someone in the future.
> Thanks!

you mention a gzip option. can you link to the docs or an example. im trying to find something but coming up empty handed

**Comment by raghav85** [comment]
Hi,

Gzip option is available on typescript admin sdk in cloud functions where
your function needed to upload incoming recording on to cloud storage. I
did not use cloud storage client sdk as I needed to check few conditions at
Firestore before uploading.

Cheers.

**Comment by thejacer87** [comment]
so is there no way we can play audio from firebase on ios? is there a different url on the object i can use to fetch the data?

**Comment by WaldsonFagundes** [comment]
i'm having trouble using google tts api in ios emulator i'm reading it as BytesSource. On the Android emulator it works OK. Has anyone already achieved something?
