### ISSUE TITLE
iOS addPeriodicTimeObserverForInterval block should use weak self

### ISSUE THREAD

**Issue by shawn736** [luanpotter/audioplayers#185]
In iOS - Classes - AudioplayersPlugin.m,  I think you should use a weak reference to self in the "addPeriodicTimeObserverForInterval" callback block to prevent creating a retain cycle.
https://developer.apple.com/documentation/avfoundation/avplayer/1385829-addperiodictimeobserverforinterv?language=objc

**Comment by erickzanardo** [comment]
Thanks for pointing that out. We are not very expert on iOs development, especially on objc, would you mind submitting a PR with this change?

**Comment by erickzanardo** [comment]
We have migrated our code to swift so maybe this is fixed. If in the new code this is still and issue, let us know so we can take a look, or even better, send us a PR.

Thanks.
