### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by willvlad** [luanpotter/audioplayers#186]
Good plugin! 

I wonder if it's possible to add a timer function so that it plays a track for X hours/minutes?

For example, if say it's set to two hours, then the track will be looping for up to two hours and then stop.

**Comment by erickzanardo** [comment]
Hey @willvlad ,

You could implement this on your app using something like this: https://api.dartlang.org/stable/2.3.1/dart-async/Timer-class.html

I don't think we will implement this kind of thing on audioplayers, I don't think this is in the scope of this package, and you can totally achieve this by other means.

**Comment by willvlad** [comment]
Thanks, I wonder how I could loop a sound for X number of minutes set by the timer?
