### ISSUE TITLE
position parameter in play() doesn't work on ios for remote url

### ISSUE THREAD

**Issue by subhash279** [luanpotter/audioplayers#189]
Hi,
I am trying to play a 'remote' url not from the beginning but let's say from the middle. 
I am trying to pass in position parameter as Duration into play() method.The emulator just seems to crash and I don't even see any error log. I only see

flutter: maxDuration : 3322
isLocal: 0 0
volume: 1.000000 1
 'Lost connection to device.'

Can you pls help?

**Comment by luanpotter** [comment]
I think this was fixed by https://github.com/luanpotter/audioplayers/pull/767
