### ISSUE TITLE
Add ability to play audio through notifications channel

### ISSUE THREAD

**Issue by trevburley** [luanpotter/audioplayers#19]
On iOS when playing music in the background from any other app (Spotify for example) the music stops when you play some audio through this plugin and it doesn't resume when finished. 

When using this plugin as a music player that is absolutely fine but when using it to play motivational audio clips (similar to Strava's pace time updates etc) it doesn't really work since Spotify (in this case) will pause.

I come from a native Android developer background so the code is a little foreign to me but if there is such a thing as being able to treat the audio as a 'notification' instead of 'music' for iOS that would be a nice addition.

I understand this may not be the purpose this plugin was designed, just hoping you are open to the idea!

**Comment by luanpotter** [comment]
Hi, @thirddimensionstudios , this is a very welcome addition, for sure. Makes a lot of sense to have that option. However, I'm not sure how to implement it; I was not even aware it was an option. I might study this soon to see how to, but the lib is nothing but a thin wrapper around the native APIs; so the relevant code would be put [here](https://github.com/luanpotter/audioplayer/blob/master/android/src/main/java/bz/rxla/audioplayer/AudioplayerPlugin.java) and [here](https://github.com/luanpotter/audioplayer/blob/master/ios/Classes/AudioplayerPlugin.m).

If you are acquainted with the native code, a PR is more than welcome. I can help with the dart wrapper if necessary (just add another parameter on the native end and we can add an optional parameter on Dart to match it).

**Comment by thirddimensionstudios** [comment]
Thanks @luanpotter.

For iOS I found this SO which may help (needs modernising to iOS11): https://stackoverflow.com/questions/28985942/best-method-to-play-an-short-audio-sound-on-ios-8-2

Android seems to be pretty straight forward too: https://stackoverflow.com/questions/26931490/android-custom-notification-sound-not-playing

I'll have a play in the next few days but I've never coded in Obj-C so it will need checking over by someone capable! Java isn't a problem though.

**Comment by thirddimensionstudios** [comment]
Adding this to the top of the togglePlay method in the iOS code seems to fix the issue BUT it retains the first file you ask it to play:

`AVAudioSession *session = [AVAudioSession sharedInstance];
if (session) {
    NSError *setCategoryError = nil;
    BOOL success = [session setCategory:AVAudioSessionCategoryAmbient error:&setCategoryError];
    if (success) {
        NSError *activationError = nil;
        [session setActive:YES error:&activationError];
    } else {
        NSLog(@"Failed to set music category to ambient. May interrupt other audio.");
    }
}`

Really out of my depth here with Obj C - any idea why that might happen?

**Comment by ngocdaothanh** [comment]
[Apple's Doc](https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/ConfiguringanAudioSession/ConfiguringanAudioSession.html#//apple_ref/doc/uid/TP40007875-CH2-SW6) has a section "Checking Whether Other Audio Is Playing".

**Comment by Cretezy** [comment]
I believe this would be fixed by using local notifications with a custom sound. In practice, Android and iOS only allow for 1 app to be playing sounds, however notifications with sound will play over them.

**Comment by luanpotter** [comment]
Is this by any chance fixed by the new respectSilence flag?

**Comment by luanpotter** [comment]
I believe this was fixed due to our recent PRs about respectSilence and notification handling. Please re-open if I'm mistaken.

**Comment by volgin** [comment]
As of 0.13.7 (on iOs):

respectSilence: true - sound is turned off as soon as the app goes into background.
respectSilence: false - sound continues as the app goes into background, but if another app is playing (I tried with Safari), both apps will play over each other. Starting/stopping music in Safari has no effect on this plugin - it keeps playing.
