### ISSUE TITLE
Audio Does not play when the screen is off

### ISSUE THREAD

**Issue by BND10706** [luanpotter/audioplayers#190]
I am looking to use this to play audio files I have stored on cloud firestore. The point will be to play long spoken word audio files. I would like it to work when the screen is off. And be able to control the audio file from the lock screen on both iOS and Android. Is this a possible addition?

**Comment by erickzanardo** [comment]
Have you ran into some problem? I just tested on a Android device and the audio kept playing, iOs should have the same behaviour

**Comment by BND10706** [comment]
It keeps playing on iOS but not on Android anymore.

**Comment by BND10706** [comment]
Also Asking for a feature request. To control the media from the lock screen on both iOS and Android. like this example

**Comment by erickzanardo** [comment]
@BND10706 I just rebuild your example app on the last version, and audio keeps playing event when cellphone is locked, are you seeing an error or something?

About the lock screen controls widget, this is out of our scope, we are focusing on providing an api to play audio, not doing this type of integration. This could be another plugin on itself.

**Comment by BND10706** [comment]
It works now, not sure what happened. Thank you!

**Comment by erickzanardo** [comment]
Glad you figured it out! Thanks for reporting back.
