### ISSUE TITLE
Music keeps playing when phone call iOS

### ISSUE THREAD

**Issue by gerritvanesch** [luanpotter/audioplayers#192]
Music keeps playing when receiving a phone call on iOS. Customer wants it to pause and then auto resume afterwards, what am I missing? Is this a bug or an implementation issue?

**Comment by erickzanardo** [comment]
I am not very experienced on iOs, but I think you should listen to lifecycle events and manage the audio pause yourself.

I did a little research on the Internet and did not found much, so I am not really sure, I will try searching more about it though

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
