### ISSUE TITLE
audioplayers fails in 0.12.0 with issues in path_provider 

### ISSUE THREAD

**Issue by AlanGrey** [luanpotter/audioplayers#197]
#### "Because flutter_gongke depends on audioplayers ^0.12.1 which depends on path_provider ^1.1.0, path_provider ^1.1.0 is required.So, because flutter_gongke depends on path_provider ^0.5.0+1, version solving failed."

I don't want to upgrade "path_provider" library , because  "flutter_cache_manager" dosen't support it. Are there other ways to be compatible?

### My Flutter
```
[√] Flutter (Channel dev, v1.6.3, on Microsoft Windows [Version 10.0.17134.829], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] Connected device (1 available)

```

**Comment by subhash279** [comment]
You can do this as a temporary fix to make it compile. Add this in pubspec.yaml

```
dependency_overrides:
  path_provider: ^1.1.0
```

and comment out path_provider in dependencies.

This is a workaround for now but it will work.

**Comment by AlanGrey** [comment]
> You can do this as a temporary fix to make it compile. Add this in pubspec.yaml
> 
> ```
> dependency_overrides:
>   path_provider: ^1.1.0
> ```
> 
> and comment out path_provider in dependencies.
> 
> This is a workaround for now but it will work.

tks. This method works. See if there are any other problems later.
