### ISSUE TITLE
Changing assets directory

### ISSUE THREAD

**Issue by luis901101** [luanpotter/audioplayers#199]
Why forcing devs to put the audio files inside **assets** folder???… what if I want to put audio files in a different folder like **res** or **resources**... I know I can create subfolders inside assets and set it as a prefix but I think it will be better if the developer could choose the entire path from the beginning like **res/sounds/audio.mp3** and not force it to **assets/sounds/audio.mp3**... I think **assets** could be a default, but should be override by any prefix if set...

**Comment by luanpotter** [comment]
That's a pretty generalized standard for flutter itself: https://flutter.dev/docs/development/ui/assets-and-images

We are just respecting that. But surely there could be an optional parameter to change...

**Comment by ivanesi** [comment]
Please implement optional param for changing path to assets. If I can change it in pubspec.yaml I should be able to change it in plugin. You have to respect this too. For example my path for assets is /app/assets, and now I should change it in whole app because audioplayers don't support this.

**Comment by ivanesi** [comment]
> That's a pretty generalized standard for flutter itself: https://flutter.dev/docs/development/ui/assets-and-images
And It's not a standard. On this link you can see that they use `/graphics `
![image](https://user-images.githubusercontent.com/8102865/63560794-e97d3880-c589-11e9-963a-f9d537091c34.png)

**Comment by mockturtl** [comment]
> That's a pretty generalized standard for flutter itself

Not in the sense of hard-coding that part of the path.  For example: 

```dart
Image.asset('assets/img/foo.png')  # expects the full string
``` 
You're essentially breaking from the standard convention here.

**Comment by luanpotter** [comment]
Closing in favour of #309.
