### ISSUE TITLE
Unable to catch exception

### ISSUE THREAD

**Issue by AlanGrey** [luanpotter/audioplayers#201]
I set up some audio addresses that could not be played and tried to get an exception. but 'audioPlayer.play( )' is always return 1 ,  and 'audioPlayer.onPlayerError.listen'  no message.

#### Logcat Message
```
I/flutter (21685): result = 1
E/MediaPlayer(21685): error (1, -2147483648)
E/MediaPlayer(21685): Error (1,-2147483648)
E/MediaPlayer(21685): stop called in state 0, mPlayer(0xb201ad00)
E/MediaPlayer(21685): error (-38, 0)
```

**Comment by fabiangebert** [comment]
I'm having the same issue when the device in in airplane mode or there is no network connection and I'm playing an otherwise correct URL. I'd like to get an exception in this case or some other way to determine whether or not the URL can be loaded.

**Comment by erickzanardo** [comment]
@luanpotter can we confirm if this still happens?

**Comment by erickzanardo** [comment]
This issue is outdated or uses a very old version of the project, could you please test if this happens on newer versions? And in case that this still happens, open a new issue?
