### ISSUE TITLE
android | background audio cuts out after 13 min

### ISSUE THREAD

**Issue by julio-rivera** [luanpotter/audioplayers#202]
Hi! If you build the example project APK in release mode, the audio cuts out after 13 minutes on my Android device (and other users who use my app) when the screen is off. I'm not sure if this is a setting that I am missing in Android or an issue with the package but if you can assist that would be a big help. Thank you!

**Comment by Darren-chenchen** [comment]
I also encountered the same problem, I feel the need to interact and native

**Comment by titasbiswasTM** [comment]
Same issue here. For my app, this happens because of phone battery optimization. When I manually exclude my app from battery optimization task inside **Settings>Battery Optimisation** the issue has been fixed. But don't know how to do by code. This issue is breaking my App and collecting lots of 1 star. **Need help urgent**

**Comment by erickzanardo** [comment]
I did some googling, and there is a flag that can be passed to the MediaPlayer on android:

https://developer.android.com/reference/android/media/MediaPlayer.html#setWakeMode(android.content.Context,%20int)

I can't test/implement atm, if someone were willing to test this and report back, or submit a PR, would be helpful. Otherwise I may have some available time to test this on the weekend.

**Comment by titasbiswasTM** [comment]
This works for me - 
**Add this permission in manifest-**
`<uses-permission  android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>`

**Inside MainActivity.java file add this-**
`if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
      Intent intent = new Intent();
      String packageName = getPackageName();
      PowerManager pm = (PowerManager) getSystemService(POWER_SERVICE);
      assert pm != null;
      if (!pm.isIgnoringBatteryOptimizations(packageName)) {
        intent.setAction(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS);
        intent.setData(Uri.parse("package:" + packageName));
        startActivity(intent);
      }
    }`

**Comment by secretwpn** [comment]
Unfortunately, I think you guys are on the wrong track. 
To my understanding, trying to fix it via modding battery settings is a hack, and you have to go a different route. 

There is a flutter library [audio_service](https://pub.dev/packages/audio_service) that lets you keep playback on while the app is in the background (it also gives you a notification area widget as well as a lock screen widget)

For me though it took quite some time to actually figure how to make things work together nicely, but I was able to sort it out in my app.

**Comment by kaifiappsmaven** [comment]
> Unfortunately, I think you guys are on the wrong track.
> To my understanding, trying to fix it via modding battery settings is a hack, and you have to go a different route.
> 
> There is a flutter library [audio_service](https://pub.dev/packages/audio_service) that lets you keep playback on while the app is in the background (it also gives you a notification area widget as well as a lock screen widget)
> 
> For me though it took quite some time to actually figure how to make things work together nicely, but I was able to sort it out in my app.

Hi, I am trying to do same, but notification area does not shows. App is configured in same way, but its dart code which is messing around. 
I am making changes according to app requirement, but its not working. Can you please explain how to configure.

**Comment by saviourdog** [comment]
same problem,seem author has give up this plugin

**Comment by luanpotter** [comment]
@saviourdog I made this for free on my spare time for the community, and I don't know how to solve this issue. Feel free to provide your PR so solve the problem and I will be glad to merge, instead of expecting other people to solve all your problems for you.

**Comment by saviourdog** [comment]
> @saviourdog I made this for free on my spare time for the community, and I don't know how to solve this issue. Feel free to provide your PR so solve the problem and I will be glad to merge, instead of expecting other people to solve all your problems for you.

sorry, my bad

**Comment by alainseys** [comment]
the only workable fix is by adding `Screen.keepOn(true);` in your main.dart file this will prevent the app to go in wakelock

**Comment by erickzanardo** [comment]
Fixed by #291
