### ISSUE TITLE
iOS Background Audio

### ISSUE THREAD

**Issue by JavierL1** [luanpotter/audioplayers#204]
When the app is minimized or the screen locked the audio pauses, and when the app is reopened the player resumes de audio. This behaviour happens on an iPhone SE (physical device) iOS 12.2, yet it works fine on an iPhone SE Simulator with the same OS.
The app works perfectly on android, both simulators and physical devices.

- I have tried this #157 
- I have tried this #109 
- The device is in perfect shape
- The device is not muted

I read in another issue that you tested this issue and there was no problem, did you tested it on a simulator or a physical device?

Thanks!

**Comment by erickzanardo** [comment]
I have tested on Simulator only, I will try testing on a device when I get some time available, but I can't test on iPhone SE, since I don't have that specific device, I will test on 7 Plus

**Comment by erickzanardo** [comment]
@JavierL1 I have tested on the my device, indeed it did not worked at first. But then I changed the `Info.plist` like instructed on the troubleshooting and on #157 and everything works now, I have recorded a little video to demonstrate it working: https://drive.google.com/open?id=1p5vQIbB2N7S_h7HNVA3mGtndtU4xRwgn

**Comment by JavierL1** [comment]
Thanks for the video! I guess that the problem resides in another side of my app then. 
Whatever the error it is, it must probably be fairly common judging by the amount of track that this issue gets.
Thanks again for the quick reply.

**Comment by erickzanardo** [comment]
No problem, let us know if you need anything else

**Comment by ncaracci** [comment]
We found that the problem was when calling `setUrl()` then `resume()`, we fixed it by calling `play()`. Maybe setUrl should have a respectSilence parameter?
