### ISSUE TITLE
Is it possible for this plugin to play audio while the app is functioning in the background?

### ISSUE THREAD

**Issue by Tormenator1** [luanpotter/audioplayers#205]
Say,if I'm in another app,could I use this plugin to play audio in the background?

**Comment by erickzanardo** [comment]
Yes, this is the default behaviour already. If you play something, and the user go to another app, or home screen, the audio keep on playing.

**Comment by erickzanardo** [comment]
On iOs you need additional configuration, as listed on the troubleshooting guide: https://github.com/luanpotter/audioplayers/blob/master/troubleshooting.md#ios
