### ISSUE TITLE
[🐛 BUG] [Android] Target SDK version 28 breaks this

### ISSUE THREAD

**Issue by andrei-pavel** [luanpotter/audioplayers#206]
Whenever I try to play a remote file, state change subscription triggers, I get no sound and some errors appear in the log:
```
E/MediaPlayerNative( 8436): stop called in state 4, mPlayer(0x78784ff980)
E/MediaPlayerNative( 8436): error (-38, 0)
```

Google Play warns:
```
From August 2019, new apps must target at least Android 9.0 (API level 28).
From November 2019, app updates must target Android 9.0 (API level 28).
```

But target SDK verison 27 works well for now.

Tested on Google Pixel 2.

Dart 2.4.0
Flutter 1.7.8-pre.6 • channel master
audioplayers commit 7bb4fe0ddd0bbce7e2894b949a47575af253c697

**Comment by erickzanardo** [comment]
Please, check the troubleshooting guide on README, this is probably the security issue on Android 9

**Comment by andrei-pavel** [comment]
Yes, the http links I'm working with are not under my control. That solved it, thank you and sorry!

**Comment by erickzanardo** [comment]
No problem! Glad this solved your issue!
