### ISSUE TITLE
Play bytes?

### ISSUE THREAD

**Issue by jinfagang** [luanpotter/audioplayers#21]
Play mp3 bytes from a int8 list in Dart?

**Comment by luanpotter** [comment]
Hi, @jinfagang, thanks for your feedback! That would be a very welcome addition, as it has many use cases! If you are interested, you can contribute with a PR!

I believe you could add a new method parallel to `setUrl`, like `setSourceData`, that takes the int8 list and sets the DataSource in Android/iOS using that.

In the [docs](https://flutter.io/platform-channels/#codec) it looks like the `Uint8List` type on Dart can be automatically converted to a `byte[]` on Java or a `FlutterStandardTypedData typedDataWithBytes` on iOS, so it wouldn't be a problem to cross the bridge with the data.

**Comment by sanu-krishnan** [comment]
Hi,
Expecting this feature

**Comment by DeRealMorgan** [comment]
I need that feature too!

**Comment by ljx0517** [comment]
I need that feature too! +1

**Comment by azizk-araneux** [comment]
I need that feature!

**Comment by luiz-simples** [comment]
me too!

**Comment by luanpotter** [comment]
Closing in favour of https://github.com/luanpotter/audioplayers/issues/182
