### ISSUE TITLE
Audio stopped with app on background when using setUrl

### ISSUE THREAD

**Issue by hilias** [luanpotter/audioplayers#210]
Hi, I said this on #204 but didn't notice it was closed, apologies.
When the audio is started using `AudioPlayer`'s `setUrl` and then `resume` it stops on iOS when the app is in the background or the device is blocked.

**Comment by danielR2001** [comment]
hi there is a new feature 'stayAwake' inside the play method that keeps the media player awake when in background, but if you use this feature you need to add 1 more permission to your manifest - WAKE_LOCK (for more info just read in the plugin readme).

**Comment by erickzanardo** [comment]
Closing due inactivity.
