### ISSUE TITLE
Android not working with error (-38, 0)

### ISSUE THREAD

**Issue by phattranky** [luanpotter/audioplayers#214]
- iOS can working well;

<img width="1032" alt="Screen Shot 2019-06-28 at 7 37 20 AM" src="https://user-images.githubusercontent.com/6443154/60309375-ab8fd980-9977-11e9-92a6-17d0faeea9df.png">

Seems the solution here

https://stackoverflow.com/questions/9008770/media-player-called-in-state-0-error-38-0

**Comment by Matheus-Perez** [comment]
![image](https://user-images.githubusercontent.com/19479787/60322200-39a69880-9955-11e9-94dd-c1ba1adaa1b1.png)
I'm having the same error on android

**Comment by sinequanon-games** [comment]
I'm also having this issue.

**Comment by ljfass** [comment]
need solutions too

**Comment by hamadmarri** [comment]
I think you have to enable http transfer data in the manifest. I have the same problem it worked on emulator and most devices except android version 9. still cannot make it to run. 
see here
https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

**Comment by Cooomma** [comment]
I have the same problem, but my case is to use `audioplayers` to play audio via HLS. Also, it works fine with iOS, but shows the same error with Android.

Given that I have the m3u8Url(with https) without any DRM required,  it shows me about DRM error.

```

V/MediaHTTPService( 8701): MediaHTTPService(android.media.MediaHTTPService@621af3c): Cookies: null
V/MediaHTTPService( 8701): makeHTTPConnection: CookieManager created: java.net.CookieManager@42414c5
V/MediaHTTPService( 8701): makeHTTPConnection(android.media.MediaHTTPService@621af3c): cookieHandler: java.net.CookieManager@42414c5 Cookies: null
D/NetworkSecurityConfig( 8701): No Network Security Config specified, using platform default
E/MediaPlayerNative( 8701): error (1, -1007)
E/MediaPlayer( 8701): Error (1,-1007)
E/MediaPlayerNative( 8701): stop called in state 0, mPlayer(0xd40eb2a0)
E/MediaPlayerNative( 8701): error (-38, 0)
V/MediaPlayer( 8701): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 8701): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 8701): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 8701): cleanDrmObj: mDrmObj=null mDrmSessionId=null
```

the code that let player plays:
```
(using the example codes)
...
final result = await _audioPlayer.play(m3u8Url, isLocal: false, position: playPosition);
...
```

**Comment by Cooomma** [comment]
Here is my guest. 
Would the `audioplayers` be using [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer) as the default player for playing audio? From iOS, it's using AVPlayer to play the audio with given URL. But, in Android, the kinds of HLS or DASH streaming protocol have to use Exoplayer for playing...

**Comment by ruelluna** [comment]
Has someone found a solution to this?

**Comment by erickzanardo** [comment]
Like Cooomma said, we use MediaPlayer under the hood, for a complete list of the supported files, check here: https://github.com/luanpotter/audioplayers#supported-formats

**Comment by hamadmarri** [comment]
To me, it only worked when I used https instead of http. I got a free SSL cert and all setup for my server. After that, it worked.

**Comment by nguyenquynh201** [comment]
> ![hình ảnh](https://user-images.githubusercontent.com/19479787/60322200-39a69880-9955-11e9-94dd-c1ba1adaa1b1.png) Tôi đang gặp lỗi tương tự trên Android

I am also facing this problem, have you solved it yet??
