### ISSUE TITLE
Android app audio not working with error (1,-2147483648)

### ISSUE THREAD

**Issue by Nucl3arSn3k** [luanpotter/audioplayers#215]
Good day. When I attempt to run [this](https://gist.github.com/Nucl3arSn3k/95789ea4ddf707407d8c54907e840c1a) code,and try to use the remote URL audio player, I get this output in my debug console. 

```
Launching lib\main.dart on Moto G4 Plus in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built build\app\outputs\apk\debug\app-debug.apk.
E/MediaPlayer-JNI(32087): JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
E/MediaPlayer-JNI(32087): JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
D/NetworkSecurityConfig(32087): No Network Security Config specified, using platform default
E/MediaPlayer(32087): error (1, -2147483648)
E/MediaPlayer(32087): Error (1,-2147483648)
E/MediaPlayer(32087): stop called in state 0, mPlayer(0x90f8c1c0)
E/MediaPlayer(32087): error (-38, 0)
E/MediaPlayer-JNI(32087): JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
E/MediaPlayer-JNI(32087): JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
E/MediaPlayer(32087): error (1, -2147483648)
E/MediaPlayer(32087): Error (1,-2147483648)
E/MediaPlayer(32087): stop called in state 0, mPlayer(0x9019cae0)
E/MediaPlayer(32087): error (-38, 0)
E/AudioAttributes(32087): Invalid stream type -2147483648 for AudioAttributes
W/SoundPool(32087): App requested 100 channels
E/WVMExtractor(32087): Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found
E/NdkMediaExtractor(32087): sf error code: -1010
E/SoundPool(32087): Unable to load sample
W/SoundPool(32087):   sample 1 not READY
E/MediaPlayer-JNI(32087): JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
E/MediaPlayer-JNI(32087): JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
E/MediaPlayer(32087): error (1, -2147483648)
E/MediaPlayer(32087): Error (1,-2147483648)
E/MediaPlayer(32087): stop called in state 0, mPlayer(0x9019cce0)
E/MediaPlayer(32087): error (-38, 0)
W/SoundPool(32087):   sample 1 not READY

```

Any idea what could be causing this?

**Comment by luanpotter** [comment]
`dlopen failed: library "libwvm.so" not found`

I suspect you are using an emulator, right? probably you are missing this dependency for it, in your linux... Can your emulator play sounds elsewhere?

**Comment by Nucl3arSn3k** [comment]
I'm not using a emulator,I'm running it on a Android phone. I'm not developing this in a Linux environment either. How would I fix the missing dependency?

**Comment by erickzanardo** [comment]
@Nucl3arSn3k this remote url, is playable by other players on the device? You can test this by downloading it and playing on the device default player.

**Comment by Nucl3arSn3k** [comment]
Yes,the file is playable on the device.

**Comment by vikramaggarwal13** [comment]
Same issue i am getting . songs are properly playing on vivo , oppo , mi devices but not working on samsung devices( I am using samsung galaxy s9)
 I am getting above error mentioned by Nucl3arSn3k

**Comment by Nucl3arSn3k** [comment]
@luanpotter  Quick question,I think one of the issues might be the service I'm using to host the audio files,where would you recommend uploading the files I'm planning to use to?

**Comment by Nucl3arSn3k** [comment]
@vikramaggarwal13  @luanpotter  I've figured out the issue. I was having problems with the audio hosting service,and managed to get it to work by hosting the file I was attempting to play on [Jukehost](https://jukehost.co.uk/).
