### ISSUE TITLE
Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by iyuhang** [luanpotter/audioplayers#216]
It works well in iOS, while in android, show the errors

[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method play on channel xyz.luan/audioplayers)

**Comment by iyuhang** [comment]
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.3 18D109, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.36.0)
[✓] Connected device (2 available)

**Comment by luanpotter** [comment]
Hi, @iyuhang , have you tried running flutter clean and flutter pub get again?

**Comment by iyuhang** [comment]
@luanpotter , thanks , it works for me
