### ISSUE TITLE
Audio from stream takes quite some time

### ISSUE THREAD

**Issue by Butzlabben** [luanpotter/audioplayers#218]
When using the audioplayers plugin and trying to play a live stream from the internet, it takes up to 10(!) seconds, until it has loaded. 
The problem is not the stream itself, as you can see here: https://zoneradio.de/live/empfang#two

So it would be cool if the latency would get reduced.

**Comment by danielR2001** [comment]
I have the same problem in my app! Sometimes it takes even more than 10 sec and it's a little bit anoying.

**Comment by Jitan** [comment]
I have the same thing on an iOS just working off the example app, with a local file.

**Comment by vincentjoelkola** [comment]
I have the same issue on android. It is taking more than 10 secs to play the song after calling play method. Calling seturl will solve the latency problem ?

**Comment by todyoga** [comment]
Same here... Just for me it take almost 1 minute. Anyone solved it?

**Comment by mattialorenzutti** [comment]
it happens to me all the time expecially with long file!

**Comment by ashishpatel1992** [comment]
I am trying to play a live stream but it takes more than 30 seconds to wait before the audio appears from phone's speaker.
 Is it possible to play stream instantly as user clicks play button or may be within next 3 seconds?

Wondering still no solution to this issue!

**Comment by erickzanardo** [comment]
This issue is outdated or uses a very old version of the project, could you please test if this happens on newer versions? And in case that this still happens, open a new issue?
