### ISSUE TITLE
audio not playing ios from remote url

### ISSUE THREAD

**Issue by sakina1403** [luanpotter/audioplayers#223]
I am trying to play audio in the example given with my own url, but I am getting the following error on xCode:

The result of await _audioPlayer.play(url) is 1 but audio is still not playing.

Here's the url that I am using right now:

https://minddetox.app/Dashboard/public/assets/imgs/10 Minute Mind Reset.mp3 

> iOS => call play, playerId e99480f9-0705-4361-83f1-c1dcd6de4bdd
> 2019-07-11 18:41:40.047774+0530 Runner[2252:1576821] play!
> 2019-07-11 18:41:40.049354+0530 Runner[2252:1576821] isLocal: 0 0
> 2019-07-11 18:41:40.049473+0530 Runner[2252:1576821] volume: 1.000000 1
> 2019-07-11 18:41:40.049510+0530 Runner[2252:1576821] position: 0 (null)
> 2019-07-11 18:41:40.227439+0530 Runner[2252:1576821] setUrl https://minddetox.app/Dashboard/public/assets/imgs/10 Minute Mind Reset.mp3
> 2019-07-11 18:41:40.272086+0530 Runner[2252:1576897] flutter: RESULT________________
> 2019-07-11 18:41:40.272199+0530 Runner[2252:1576897] flutter: 1
> 2019-07-11 18:42:14.408361+0530 Runner[2252:1576821] Unsupported value: https://sandbox.itunes.apple.com/WebObjects/MZFinance.woa/wa/inAppRegrantPurchaseHistory of type NSURL
> 2019-07-11 18:42:14.408790+0530 Runner[2252:1576821] *** Assertion failure in -[FlutterStandardWriter writeValue:], ../../flutter/shell/platform/darwin/ios/framework/Source/FlutterStandardCodec.mm:330
> 2019-07-11 18:42:14.416511+0530 Runner[2252:1576821] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unsupported value for standard codec'
> *** First throw call stack:
> (0x184b09d04 0x183d58528 0x184b09bd8 0x185499c24 0x100cb4fd0 0x100cb5104 0x100cb5104 0x100cb56e0 0x100ca2ca4 0x10079f7e8 0x10079daa8 0x10079cd7c 0x1849cf900 0x197ee46a4 0x197ee3244 0x197ee4098 0x100b4949c 0x100b4945c 0x100b4e050 0x184ab1eb0 0x184aafa8c 0x1849cffb8 0x186867f84 0x18dfa42e8 0x10072b5e8 0x1844f256c)
> libc++abi.dylib: terminating with uncaught exception of type NSException
> warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.

It's really urgent, please help if possible.

**Comment by luanpotter** [comment]
maybe the spaces in the url? or some mp3 codedc not support by ios? have you tried downloading the file and playing locally? or serving through some other server? maybe the mimetype is incorrect, or some content-type header or something...

**Comment by kevinchin37** [comment]
@sakina1403 @luanpotter 

I've been having the same problem and it looks like it's the simulator that is causing it. It works when I try it on an actual phone.

**Comment by Matheus-Perez** [comment]
I am having the same problem on IOS only as on an Ipad

**Comment by erickzanardo** [comment]
This issue is outdated or uses a very old version of the project, could you please test if this happens on newer versions? And in case that this still happens, open a new issue?
