### ISSUE TITLE
add an ending param to seek

### ISSUE THREAD

**Issue by thejacer87** [luanpotter/audioplayers#235]
i might be missing something, but is there currently a way to play a song for a predetermined amount of time. like say 5 sec preview.

maybe there is an easy way right now via the `positionSubscription` but i can't figure it out.

maybe make a new method `preview(start, end)` that will play the track from start to end.

if there is a simple way to do this without a method, that'd be fine too. i guess just an example would be nice in that case

**Comment by ronaldG19** [comment]
@thejacer87 
As long as you have positionSubs..... everything is easy. I've just came with this simple method:
``
Future<void> _preview(int seconds)async{
  var _seek = _positionSubscription.inSeconds;
   if(_isPlaying && _seek==seconds ){  //playingState
          _pause(); //or _release() or _stop() or dispose()
}
 }
``

Hope you thought the same ting.

**Comment by erickzanardo** [comment]
This not the responsibility of the seek method I suggest using a solution like the one suggested on this thread
