### ISSUE TITLE
Issue with the second audio file

### ISSUE THREAD

**Issue by scripter** [luanpotter/audioplayers#238]
Hi there,

Thanks for this great package

We are using this package for long time, it's working fine, but when trying playing the audio from google drive we are getting duration 0.

i have two audio file in drive one is working fine and from second audio i am getting 0 in duration

First Audio :  https://drive.google.com/uc?id=1v6PHuGruKG0DVnE_KC16VbKEzIsKS4Of&export=download
Second Audio : https://drive.google.com/uc?id=11Aacljj-o_yVQjPmRYCS9hU8ejuxYgvb&export=download

**Comment by MA171** [comment]
Make sure that the audio files are not Stereo  , the plugin plays only Mono files

**Comment by ronaldG19** [comment]
@scripter If that will fail too use Firebase Storage from **Firebase** grasp the download file link and test it directly from your browser.

**Comment by erickzanardo** [comment]
This issue is outdated or uses a very old version of the project, could you please test if this happens on newer versions? And in case that this still happens, open a new issue?
