### ISSUE TITLE
Error copying matching creds

### ISSUE THREAD

**Issue by UtopiaMinT** [luanpotter/audioplayers#24]
When playing an audio from a HTTPS link, the following error occurred.
Link concerned: https://eutopia.sgp1.digitaloceanspaces.com/d62b7d9adb272bcfc796b997f79be54a0cf30756d953f5dc3417c24fc2e9a60d

```
2018-07-15 15:54:34.067455+0800 Runner[295:12533] CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    "r_Attributes" = 1;
    sync = syna;
}
```

I already attempted the iOS App Transport Security trick but no luck.

**Comment by luanpotter** [comment]
The iOS trick is to download a file over HTTP, witch is blocked by default by iOS platform. Your problem, it seems, is that your HTTPS connection is using an untrusted SSL certificate. I tried downloading on the browser and had no problem, so it might be a new CA that is not yet recognized by iOS (like the newer Let's Encrypt certs, they used to cause problem with older versions of the JDK, for example). I think that might be the problem, but don't know how to fix it for iOS, maybe add an option for adding a custom cert or disable SSL altogether (not recommended, though)? To solve your actual problem, you could also upload the file somewhere else, or download it and play it as an Local Asset. If you happen to find out how to provide this functionality for iOS, please help out with a PR! :)

**Comment by erickzanardo** [comment]
Closing due inactivity
