### ISSUE TITLE
How to auto play when connecting to bluetooth device

### ISSUE THREAD

**Issue by angelorobo** [luanpotter/audioplayers#240]
I want to implement a feature like Audible which will stop playing the audio when it is disconnected from the car's Bluetooth and start playing again when it connects to the car's Bluetooth.

**Comment by ronaldG19** [comment]
@angelorobo  I've played with car's Bluetooth, I just used my Bluetooth radio with this plugin [flutter_blue](https://pub.dev/packages/flutter_blue), and it worked as a charm.

**Comment by erickzanardo** [comment]
Not sure how, but I don't think this is something in the scope of this plugin, you should take a look on bluetooth libs for flutter, like the one @ronaldG19 suggested.
