### ISSUE TITLE
Stop playing after big seek 

### ISSUE THREAD

**Issue by MA171** [luanpotter/audioplayers#241]
The audio files stop playing and comes to the end when I seek to a not buffered area(or i think so ).
For example , if i have a file with length 1 hour , when i play it and seek to 50 minutes it stops playing and goes to the end of the file directly.

**Comment by ronaldG19** [comment]
Are you playing directly from the physical device or an emulator?

If it is an emulator, probably memory leak is the problem, I ran through the issue many times.

**Comment by MA171** [comment]
> Are you playing directly from the physical device or an emulator?
> 
> If it is an emulator, probably memory leak is the problem, I ran through the issue many times.

No i'm playing from a physical  device 
And i tested it in android and IOS , both have the same problem

**Comment by vtandrea** [comment]
the same happened to me. Both test on physical android and iOS devices.

**Comment by vtandrea** [comment]
Meanwhile i've tested my app on more devices and I noticed that for iOS it works well, but in android I cannot do big skips. I'm using to stream 2h podcasts.

**Comment by sanjidbillah** [comment]
@vtandrea is this ok now brother? :(

**Comment by vtandrea** [comment]
@sanjidbillah sorry for delay. Not, it still dosn't work.

W/MediaHTTPConnection( 3858): readAt 231836512 / 32768 => java.net.ProtocolException
V/MediaPlayer( 3858): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3858): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 3858): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3858): cleanDrmObj: mDrmObj=null mDrmSessionId=null

**Comment by vtandrea** [comment]
@luanpotter what do you think?

**Comment by timoknapp** [comment]
@vtandrea 

I experience the exact same issue when playing streams longer then 40 minutes:

```
W/MediaHTTPConnection( 3979): readAt 36823797 / 7435 => java.net.ProtocolException: unexpected end of stream
E/MediaPlayerNative( 3979): error (1, -1010)
E/MediaPlayer( 3979): Error (1,-1010)
E/MediaPlayerNative( 3979): stop called in state 0, mPlayer(0xd0464980)
E/MediaPlayerNative( 3979): error (-38, 0)
V/MediaPlayer( 3979): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3979): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 3979): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3979): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaHTTPService( 3979): MediaHTTPService(android.media.MediaHTTPService@b2d3644): Cookies: null
V/MediaHTTPService( 3979): makeHTTPConnection: CookieHandler (java.net.CookieManager@bd7a014) exists.
V/MediaHTTPService( 3979): makeHTTPConnection(android.media.MediaHTTPService@b2d3644): cookieHandler: java.net.CookieManager@bd7a014 Cookies: null
V/MediaPlayer( 3979): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3979): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaHTTPService( 3979): MediaHTTPService(android.media.MediaHTTPService@b144062): Cookies: null
V/MediaHTTPService( 3979): makeHTTPConnection: CookieHandler (java.net.CookieManager@bd7a014) exists.
V/MediaHTTPService( 3979): makeHTTPConnection(android.media.MediaHTTPService@b144062): cookieHandler: java.net.CookieManager@bd7a014 Cookies: null
```

Any progress to this topic?

cc: @luanpotter

**Comment by luanpotter** [comment]
Do we have a sample audio file + the seek millis I need to use to repro?

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
