### ISSUE TITLE
play audio from buffer

### ISSUE THREAD

**Issue by bardiarastin** [luanpotter/audioplayers#242]
Hi, thanks for awesome project.
what i'm trying to build is a music app that when you press play button the song gets both played and cached.

i'm looking for a way to download a mp3 file from server and do both playing and writing it to a file on user device simultaneously. 

https://github.com/luanpotter/audioplayers/issues/182#issuecomment-498647243

this answer says that "you could be writing a temporary file" but I wanna keep that file forever on user device, any idea or samples maybe?!
if I write the audio on file is this plugin able to read it while it's not fully downloaded?!

one more question that I have is that I don't know how to handle loading state, there is nothing anything such as isLoading or isBuffering in AudioPlayerState :(

**Comment by ronaldG19** [comment]
@bardiarastin 
Just call your url(playable) the plugin will buffer while playing. I would do the following If I were you:
1. Call my url (playable link/downloadable).
2.While it is playing save it to cache(for fast playing / reference).
3.On finished take the song unique id & save it to DB or using any API.
4.Finally use dio to download your file to a device path provider may help in Android.

If you want to play you file by using your music app from external directory just use the unique ID existence from DB.

Sorry but it's not everything we want #audioplayers can provide.

**Comment by yringler** [comment]
> one more question that I have is that I don't know how to handle loading state, there is nothing anything such as isLoading or isBuffering in AudioPlayerState :(

This should be it's own issue, IMO.
I ran into this too, It's not a huge deal for me, so I dealt with it by waiting for audio length to be available. This isn't perfect, because there could be another bit until playback can start, in theory. A better solution would be to wait for playback position, but that might fire too late, depending on the precision you need.

**Comment by yringler** [comment]
@ronaldG19 
> Just call your url(playable) the plugin will buffer while playing. I would do the following If I were you:

What do you mean "call your url(playable)"? How do you call a url playable?

**Comment by kbokarius** [comment]
@ronaldG19 "2. While it is playing save it to cache(for fast playing / reference)"

How can the file be saved to the cache? The cache reads from the assets folder which is read only. Is it possible to have this library cache the file in memory so it doesn't have to download it each time? Please advise.
