### ISSUE TITLE
Failed on iOS simulator when trying local audio path

### ISSUE THREAD

**Issue by iDevhang** [luanpotter/audioplayers#243]
try remote audio url success，but failed when trying local audio path. 
isLocal = YES isnt useful

**Comment by erickzanardo** [comment]
Which error? I just tested on the example app and everything is working fine.

**Comment by iDevhang** [comment]
Thx. I've solved the problem. I'll close the question




On 08/05/2019 19:03, Erick (CptBlackPixel) wrote:

Which error? I just tested on the example app and everything is working fine.

**Comment by erickzanardo** [comment]
Thanks for letting us know that you solved.
