### ISSUE TITLE
pause() does not work right after loop()

### ISSUE THREAD

**Issue by PandaGeek1024** [luanpotter/audioplayers#245]
Hi,

For some reason, if I do the following:

```
homeBGM = await Flame.audio.loop('bgm/home.mp3', volume: .25);
homeBGM.pause();
```

the pause() does not work and the music still plays. But calling pause() in a different action(e.g. button click) works. Seems like some kind of async issue? Appreciate if anyone can help.

**Comment by erickzanardo** [comment]
Any reason to call the pause right after the loop method? Maybe I am missing something but that does not makes much sense to me to start something that you are going to pause right on the next statement.

**Comment by volgin** [comment]
I see this problem if a user clicks on pause button before a file from URL starts playing. There may be a delay as a file is loading, so a user has time to change his/her mind and press pause.

**Comment by volgin** [comment]
I may open a new issue, but it's possible that these issues have the same root cause.

**Comment by iktakahiro** [comment]
Here's my use case :

1. Load a backgroung music from an asset.
2. Load (fetch) a main audio file from a network resource.
3. Once both data are loaded, I want to start playing. The background music shoud be looped.

As I understand, I need to call the loop() method to create a new AudioPlayer instance.

```dart
_bgmPlayer = await _bgmCache.loop('file_name.mp3');
```
 
In this case, the BGM is played immediately by the loop(). So, I have stopped the player once as a workaround.

```
_bgmPlayer = await _bgmCache.loop(widget.guide.defaultBgmFileName);
Future.delayed(const Duration(milliseconds: 100), () async {
    await _bgmPlayer.pause();
});
```

Even in this workaround, the paus() returns an error.

```
E/MediaPlayerNative( 5777): pause called in state 4, mPlayer(0x7840149895c0)
E/MediaPlayerNative( 5777): error (-38, 0)
E/MediaPlayer( 5777): Error (-38,0)
```

My ideal would be for an AudioCache to be able to create an AudioPlayer instance without playing music.

Thanks for the great contribution to the Flutter World.

**Comment by erickzanardo** [comment]
This issue is outdated or uses a very old version of the project, could you please test if this happens on newer versions? And in case that this still happens, open a new issue?
