### ISSUE TITLE
No AudioPlayerState?

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [luanpotter/audioplayers#25]
The old package had a way to indicate if the player was playing. What's the reasoning behind removing it?

**Comment by luanpotter** [comment]
Thanks for your feedback! There was no reason behind removing it because it was not removed.

Actually, the original audioplayer package didn't have this feature. It does now, but that was just recently added. There was no built-in way to do it when the fork occurred. However, you can easily control your own state, like [this Widget](https://github.com/luanpotter/audioplayer/blob/master/example/lib/player_widget.dart) in the example does (and it uses a enum just like the one you want).

**Comment by luanpotter** [comment]
Please, contribute with a PR! I'll be glad to merge it in. :)
It can be done completely in the dart code, so it won't interfere with the native behavior.
Just add a variable to the player to hold the current state and update it in every related method call :)

**Comment by ThinkDigitalRepair** [comment]
When I tried forking your fork, it showed me my fork of the original project, how do I submit a PR to your fork directly?

**Comment by luanpotter** [comment]
Hahaha never thought of that problem!

I'm not sure, but I believe you can use the same cloned repo you already have on your machine; just add my repo as a remote (e.g., `git remote add luanpotter_remote git@github.com:luanpotter/audioplayer.git`), and then pull my master branch. Create a new branch from my master, make your commits, and then open the PR from that repo (it will show up, I believe, in my repo's PR page).

Always take a look at the diff of the PR to make sure you are submitting just your changes and not something else that might have come along.

Alternatively you could create a PR without a fork (though I think it'd be harder), check [this](https://help.github.com/articles/about-pull-requests/) out on how to do that. Basically clone my repo, create the branch directly and then you can PR from the terminal (IIRC).

**Comment by ThinkDigitalRepair** [comment]
I’m getting this error in Dart analysis. Is this something that can be ignored? `warning: The option 'enableStrictCallChecks' isn't supported by 'language'. (unsupported_option_with_legal_values at [audioplayers] analysis_options.yaml:4)`

**Comment by ThinkDigitalRepair** [comment]
I’m getting this error in Dart analysis. Is this something that can be ignored? `warning: The option 'enableStrictCallChecks' isn't supported by 'language'. (unsupported_option_with_legal_values at [audioplayers] analysis_options.yaml:4)`

**Comment by luanpotter** [comment]
That is probably an older option that was present in the analysis_options file that is no longer required (maybe [this](https://github.com/dart-lang/sdk/issues/31509) explains it).

You could remove that line from the analysis_options file in your PR if you'd like :)

**Comment by ThinkDigitalRepair** [comment]
Will do

**Comment by luanpotter** [comment]
Thanks, @renancaraujo , fixed due to #68.

**Comment by ThinkDigitalRepair** [comment]
Thanks!
