### ISSUE TITLE
Audio duration is always -1 on playing ogg files. update: now everythings goes wrong with this problem

### ISSUE THREAD

**Issue by jkmpariab** [luanpotter/audioplayers#250]
when playing ogg audio files from net, duration fetched from onDurationChanged stream is -1. but there's no problem on playing other formats.
update: now i cant resume or seek on a specific duration because AudioPlayer duration is null.
any help?

**Comment by erickzanardo** [comment]
Is this android or iOS?

**Comment by jkmpariab** [comment]
> Is this android or iOS?

android

**Comment by erickzanardo** [comment]
Android should play OGG perfectly, how are you playing it? Is it a bundled file with app, remote url, etc?

**Comment by jkmpariab** [comment]
> Android should play OGG perfectly, how are you playing it? Is it a bundled file with app, remote url, etc?

a remote url (that recorded by telegram messenger if this can help :/)

**Comment by erickzanardo** [comment]
humm, where is that file stored? Be aware that android 8+ has restrictions about accessing stuff with http. Must be https or add some configs to enable http.

**Comment by jkmpariab** [comment]
> humm, where is that file stored? Be aware that android 8+ has restrictions about accessing stuff with http. Must be https or add some configs to enable http.

i will check this out soon

**Comment by jkmpariab** [comment]
> humm, where is that file stored? Be aware that android 8+ has restrictions about accessing stuff with http. Must be https or add some configs to enable http.

yea, i fixed the cleartext issue, but duration problem still remains. i'm using an slider to change the audio position. so i'm using the AudioPlayer.seek method. but because the duration is null it throws this error log when changing slider value: "Stream has no duration and is therefore not seekable."

**Comment by erickzanardo** [comment]
This issue is outdated or uses a very old version of the project, could you please test if this happens on newer versions? And in case that this still happens, open a new issue?
