### ISSUE TITLE
Plugin doesn't play short audio files

### ISSUE THREAD

**Issue by mxmzb** [luanpotter/audioplayers#253]
I don't know, what's the threshold here, probably a few seconds: If I play mp3s which are just a second long, they won't play at all.

Note: There is no error, in fact, the result from `await player.play(fileUrl);` is even `1`, it simply stays silent.

**Comment by rg4real** [comment]
Confirming same bug. Or is it intentional?

**Comment by luanpotter** [comment]
Certainly not intentional. Please try with different audio format and devices (android, ios, emulators) and share the results so we can investigate further.

**Comment by mxmzb** [comment]
sorry it took me so long. i have investigated a bit more and it seems like it doesn't have to do anything with the duration of the file. now it looks more like the file url can not be dynamic. 

the reason i assumed it's the duration, is just because i had a lot of very short files. to just make sure it works, i put a url from a sample audio file somewhere on the internet. because that one was longer in duration and i didn't see any other possible issue with the code, i assumed it must be duration (still not 100% sure it's not, but 90%) as it was the only noteworthy difference i was able to see. it's all rather confusing to me.

i'll give some sample code, but here is also some additional info: it actually works (!!) flawlessly on Android. it does not work on iOS (neither simulator, nor device).

here is some sample code to explain what's going on:

```dart
IconButton(
  icon: Icon(Icons.volume_up,
      color: Theme.of(context).textTheme.title.color,
      size: 26.0),
  onPressed: () async {
    String foo =
        "https://d39yykiboizsia.cloudfront.net/audio/he/kfar.mp3";
    String bar =
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3";
    String foobar =
        "https://d39yykiboizsia.cloudfront.net/audio/$languageKey/$soundFile";

    print("languageKey $languageKey");
    print("soundFile $soundFile");

    print("foo $foo"); // https://d39yykiboizsia.cloudfront.net/audio/he/kfar.mp3
    print("bar $bar"); // https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3
    print("foobar $foobar"); // https://d39yykiboizsia.cloudfront.net/audio/he/kfar.mp3
   // thus foo == foobar, but it still only foo will actually play a sound on iOS

    await audioPlayer.setReleaseMode(ReleaseMode.STOP);

    audioPlayer.setUrl(foo); // will work perfectyl also on iOS
    audioPlayer.setUrl(bar); // will work perfectyl also on iOS (why i thought it's the duration)
    audioPlayer.setUrl(foobar); // will not work on iOS, although the value is the exact same as the one of foo

    await audioPlayer.release();
    await audioPlayer.seek(Duration(milliseconds: 0));
    await audioPlayer.resume();
  },
)
```

**Comment by mxmzb** [comment]
can be closed. my issue was that somehow `foobar` had a whitespace (i believe) at the end due to `soundFile`. fixed by adding a `.trim()`. sorry and thank you!

// note: i did not see the whitespace at any point of time. not sure what the proper debugging command in dart is to print objects / strings properly to the console, but `print()` doesn't seem to do a good job with this.
