### ISSUE TITLE
How to have media controls in lock screen and notification bar

### ISSUE THREAD

**Issue by krishnakirana** [luanpotter/audioplayers#254]

**Comment by luanpotter** [comment]
That's out of the scope for this lib, please look for a plugin specifically designed for notifications. This is about playing and controlling audio, not UI or notifications.

**Comment by Sun3** [comment]
@luanpotter I understand what you are saying that it is out of scope for this lib, but when a user is playing an audio and the device goes to the lock screen they are expecting the audio to continue to play and if they need to pause the audio without the audio media controls on the lock screen they would need to go back to the app and pause the audio.

You have a great plugin and I believe adding the ability to pause, play, skip audio media controls from the lock screen is a must for any audio app and it would make your plugin even greater.

Thank you.

**Comment by Sun3** [comment]
Any updates on the lock screen controls?
