### ISSUE TITLE
AudioCache once set loop, can't go back to normal playback

### ISSUE THREAD

**Issue by hasen6** [luanpotter/audioplayers#256]
I found with AudioCache, once I played once with loop and then stop it with `advancedPlayer.stop();` if I play it again but with the normal .play method it still loops the audio. Any way to reset it or cancel the looping?

I'm basically enabling and disabling looping mode with a button.

```
    if (loop) {
      print('loop');
      audioCache.loop('file.mp3');
    } else {
      print('play');
      audioCache.play('file.mp3');
    }
```

**Comment by erickzanardo** [comment]
That probably happened because you are using a fixed player, I would suggest using the instance returned by the play and/or loop method to control the audio instead of using a fixed player

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
