### ISSUE TITLE
Cache singleton within widget doesn't keep the same AudioPlayer

### ISSUE THREAD

**Issue by j-oswin** [luanpotter/audioplayers#258]
I wanted to create an AudioCache singleton as recommended in the docs using "fixedPlayer", but I'm not sure if I'm doing it right, because I'm still getting multiple player ID's when I access the singleton from within a component.

Creating the audio player and cache:

```dart
class MyAudioPlayer {

  static final AudioPlayer _player = new AudioPlayer();
  static final AudioCache _cache = new AudioCache(fixedPlayer: _player);

  MyAudioPlayer._privateConstructor();

  static final MyAudioPlayer _instance = MyAudioPlayer._privateConstructor();

  factory MyAudioPlayer(){
    return _instance;
  }

  static playAsset(String filename) async {

    await _cache.play(filename);
    print("playing with playerId: "+_player.playerId.toString());

  }

}
```

Then playing an asset file:
`MyAudioPlayer.playAsset('123.mp3');`

The log outputs the same `playerId` everywhere when I play from main screens, but it's different when I play from within a component/widget (i.e. a custom play button), even though it's the same line of code.  This means I can't manipulate a sound that's initiated from within the play button without passing the audioplayer around.

**Comment by luanpotter** [comment]
Hi, @j-oswin , thanks for your report.

I'm gonna go out on a limb here and ask you how are you importing MyAudioPlayer into each file? I suspect mixing relative and absolute imports might cause two instances of your 'singleton' being created. Very nasty behavior from dart.

If that's not the case I'd need to think it through, because everything you are doing there seems fine.

**Comment by j-oswin** [comment]
You're so right.  In one I imported the file and in one I imported the class, by difference of capitalization.  Didn't realize I could even do that.  Thank you!

**Comment by luanpotter** [comment]
Indeed, that's a very hard to find bug! In fact, I have made a plugin you can use if you want: https://github.com/luanpotter/vscode-dart-import
it changes all imports in the file to relative format! very handy!
