### ISSUE TITLE
ios AVPlayerItemStatus.failed file is aac

### ISSUE THREAD

**Issue by wapchief** [luanpotter/audioplayers#261]
I have configured 
```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```
But it's a pity that.
I try to use examples，the result is the same .

url:http://icxinli-im.unnue.com//im/audio/2019/8/21/wx2b07371a7f3ccd7a.o6zAJs-PQLyxJakso25UNHZPQhKQ.Yh1mtL29DxPla53c00a905435219820525da66fd062b.durationTime=2441.aac

**Comment by alejantab** [comment]
I have the same problem, Have you found a solution?

**Comment by wapchief** [comment]
> I have the same problem, Have you found a solution?

no

**Comment by erickzanardo** [comment]
Have you tried downloading that file on the device and testing from it? Both AAC and remote playback works fine, so my guess is that the server or the file has some issue

**Comment by olivoil** [comment]
I'm also having the same issue

```
path: satisfied (Path is satisfied), interface: en0
    "LocalDataTask <64F8D24C-68C0-4648-B231-05D5F64FAE06>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <64F8D24C-68C0-4648-B231-05D5F64FAE06>.<1>, NSLocalizedDescription=cancelled}
flutter: _platformCallHandler call audio.onError {playerId: 9f06e1ef-9a82-40d4-80a0-bd8c69d319b9, value: AVPlayerItemStatus.failed}
```

**Comment by chenft** [comment]
chang androidEncoder, such as AndroidEncoder.HE_AAC

**Comment by markst** [comment]
Also having trouble with the following URL:
https://cast-1.nucleusstreaming.com:4443/pbsfm_live_64.aacp

**Comment by erickzanardo** [comment]
This issue is outdated or uses a very old version of the project, could you please test if this happens on newer versions? And in case that this still happens, open a new issue?
