### ISSUE TITLE
Android remote play only (or always) works on android 6+

### ISSUE THREAD

**Issue by jkmpariab** [luanpotter/audioplayers#263]
i'v been using this plugin for a while. have this #249 before, but that works for android 9+ (that ignores http clear text stuffs), android below 6 still have the issue. this problem is the same for other plugins that using the same underlying android implementation (MediaPlayer library maybe?!). and your example app can expose this problem when running on android below 6. on remote page (first tab) audio 1 and 2 always have the problem but for other audios the problem is occasionally.

**Comment by erickzanardo** [comment]
This issue is outdated or uses a very old version of the project, could you please test if this happens on newer versions? And in case that this still happens, open a new issue?

**Comment by jkmpariab** [comment]
> This issue is outdated or uses a very old version of the project, could you please test if this happens on newer versions? And in case that this still happens, open a new issue?

I have not used Flutter for a long time sorry
