### ISSUE TITLE
AudioManager events support

### ISSUE THREAD

**Issue by nt4f04uNd** [luanpotter/audioplayers#264]
You should add some events handling. 

Firstly, it's support for handling media focus changes (`AUDIOFOCUS_GAIN`,`AUDIOFOCUS_LOSS` and others) and pause player automatically if focus changes, or give us an option to handle this as additional player property (this would be great!). E.g now if I start playing track, then go to Youtube app and try to watch video, the music will keep playing.

Seconly, `ACTION_AUDIO_BECOMING_NOISY` handling.

Though we can implement these ones manually, just write some native code, but it would be perfect to see these implementations in your library.

**Comment by erickzanardo** [comment]
Fixed by #291
