### ISSUE TITLE
Seek audio does not works in IOS

### ISSUE THREAD

**Issue by kaifiappsmaven** [luanpotter/audioplayers#265]
I am using audioplayer.seek(value) where value = Duration(minutes: seekvalue_min, seconds:  seekvalue_sec, hours: seekvalue_hour,milliseconds: 0);

When I call this function to play my audio where I left off, it works fine in android but audio starts from 0 position in IOS

**Comment by Adriano72** [comment]
Something probably related is happening to me as well. It seems the audio position remains stuck at 0.0 but just until the play function is called. After it seems to work correctly

**Comment by erickzanardo** [comment]
This issue is outdated or uses a very old version of the project, could you please test if this happens on newer versions? And in case that this still happens, open a new issue?
