### ISSUE TITLE
Issue while playing background in IOS

### ISSUE THREAD

**Issue by shikha1992** [luanpotter/audioplayers#267]
Hi, 
When I tries to play audio through - 
resume() method as in Example class, it does not play in background (in IOS)
while it works at background with play() function only. 
I want to use resume() function to play song from where its left off(I am locally saving minutes where it is paused) and want to resume from same position. 
Also I tried with adding same minutes in 
_position = Duration(minutes :1); in play() function, it always starts from beginning. In resume it works fine but is not working in background. 
Please help with solution. 
I want to keep song playing in background too
@luanpotter @erickzanardo

**Comment by subhash279** [comment]
I am working on fixing this bug. I will submit a PR in a few days!

**Comment by shikha1992** [comment]
okay thankyou

**Comment by subhash279** [comment]
@luanpotter  @erickzanardo  Submitted a PR for this - #270

**Comment by shadyshrif** [comment]
@subhash279 how are you. Any updates regarding supporting both android and ios

**Comment by shadyshrif** [comment]
@luanpotter @erickzanardo Does this PR #304 solve the issue for both android and IOS?

**Comment by luanpotter** [comment]
@shadyshrif this issue is about iOS only, it seems that @subhash279 PR's fixed it. Please test again on android and open a new issue if another problem arrises.
