### ISSUE TITLE
App crashes in release mode in android phones 

### ISSUE THREAD

**Issue by arefhosseini** [luanpotter/audioplayers#271]
In debug mode audio plays clearly but in release mode app crashes in playing.
Should I add any command in progaurd-rules or not? 
thank's.

**Comment by erickzanardo** [comment]
Does it crashs because this plugin? Is there any errors?

**Comment by arefhosseini** [comment]
app crashes in building **aab** file
but it works in making **apk** release. dont know why...

**Comment by erickzanardo** [comment]
but how can you identify that the app crashed because of Audioplayers? Which is the error of the crash?

**Comment by arefhosseini** [comment]
When player start playing, app crashes. Don't know why because its in release mode.
I mean should I add any code in my **progaurd-rules.pro**?

**Comment by yannick-bernaerts** [comment]
I seem to be having the same issue. My app crashes when trying to play a remote sound in low_latency mode, this only occurs in the release version (no issue in debug). When removing the mode, the app stops crashing but no sound is played at all.
```
AudioPlayer audioPlayer = AudioPlayer(mode: PlayerMode.LOW_LATENCY);
await audioPlayer.play(src);
```
Not sure but it looks like some sort of proguard/obfuscation issue. To be clear, I did not enable proguard for my release builds. This is the error I receive:
```
E/flutter (22818): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null)
E/flutter (22818): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569)
E/flutter (22818): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321)
E/flutter (22818): <asynchronous suspension>
E/flutter (22818): #2      AudioPlayer._invokeMethod (package:audioplayers/audioplayers.dart:211)
E/flutter (22818): #3      AudioPlayer.stop (package:audioplayers/audioplayers.dart:268)
E/flutter (22818): <asynchronous suspension>
```

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
