### ISSUE TITLE
Request feature: Stop playback when another app is playing song.

### ISSUE THREAD

**Issue by glennmichaelmejias** [luanpotter/audioplayers#275]
I want to request a feature that will automatically stops the playback when another app is playing in the background.

**Comment by luanpotter** [comment]
Isn't that what that respect silence flag is for?

**Comment by erickzanardo** [comment]
@luanpotter respectSilence is a different thing, it is about not playing anything when the cellphone is on a silent sound profile (like the silent button on iPhone).

What is requested on this issue already has a PR, but the PR is missing the iOS implementation: https://github.com/luanpotter/audioplayers/pull/232

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
