### ISSUE TITLE
getCurrentPosition is broken in ios

### ISSUE THREAD

**Issue by bardiarastin** [luanpotter/audioplayers#277]
I was getting this error 
flutter: error MissingPluginException(No implementation found for method getCurrentPosition on channel xyz.luan/audioplayers)
but audioplayer was working fine in previous versions, so I took a look at commits and found this https://github.com/luanpotter/audioplayers/commit/8ed42bc8598ca99975e5726ba0d158579c474fcc

**Comment by ProgrammingLife** [comment]
Maybe you just need to do: flutter clean && flutter run
