### ISSUE TITLE
[Android]Sound only playing through headphones

### ISSUE THREAD

**Issue by aitch-3** [luanpotter/audioplayers#278]
I know that iOS had a same issue on sound playing only through headphones.
(https://github.com/luanpotter/audioplayers/issues/33)
I am facing same problem with android.

```
static AudioCache player = AudioCache(prefix: 'sound/');
player.load('beap.mp3');
player.play('beap.mp3');
```

this works perfect on iOS. but for Android, sound only plays through headphone.
Is there a way to fix this? 
Thank you

**Comment by erickzanardo** [comment]
Does that happens with multiple devices? As far as I remember we don't have any code to select where to play the sound despite the respectSilence flag, which by your code, you don't use, so maybe the device you used to test has some config to play only on the headphones?

**Comment by aitch-3** [comment]
I am testing this on Samsung Galaxy S6.  I tested same code on Galaxy S10, and it worked fine.
I was thinking same, config to play only on the headphones, but i don't see any where to config sound properties.

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
