### ISSUE TITLE
Audioplayer doesn't start

### ISSUE THREAD

**Issue by klinki** [luanpotter/audioplayers#28]
Hello,

I have a problem with audioplayer. It doesn't start playing and calls `onComplete` callback right away.

Here is log, if it helps:

> Launching lib\main.dart on GT I9195 in debug mode...
> C:\Users\david\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\audioplayers-0.7.3\android\src\main\java\xyz\luan\audioplayers\WrappedMediaPlayer.java:204: warning: [deprecation] setAudioStreamType(int) in MediaPlayer has been deprecated
>             player.setAudioStreamType(AudioManager.STREAM_MUSIC);
>                   ^
> 1 warning
> Built build\app\outputs\apk\debug\app-debug.apk.
> I/FlutterActivityDelegate(25121): onResume setting current activity to this
> I/Choreographer(25121): Skipped 94 frames!  The application may be doing too much work on its main thread.
> E/dalvikvm(25121): Could not find class 'android.media.AudioAttributes$Builder', referenced from method xyz.luan.audioplayers.WrappedMediaPlayer.createPlayer
> W/dalvikvm(25121): VFY: unable to resolve new-instance 38 (Landroid/media/AudioAttributes$Builder;) in Lxyz/luan/audioplayers/WrappedMediaPlayer;
> D/dalvikvm(25121): VFY: replacing opcode 0x22 at 0x0012
> D/dalvikvm(25121): DexOpt: unable to opt direct call 0x004e at 0x14 in Lxyz/luan/audioplayers/WrappedMediaPlayer;.createPlayer
> V/MediaPlayer-JNI(25121): native_setup
> V/MediaPlayer(25121): constructor
> V/MediaPlayer(25121): setListener
> V/MediaPlayer-JNI(25121): setAudioStreamType: 3
> V/MediaPlayer(25121): MediaPlayer::setAudioStreamType
> V/MediaPlayer-JNI(25121): setVolume: left 1.000000  right 1.000000
> V/MediaPlayer(25121): MediaPlayer::setVolume(1.000000, 1.000000)
> V/MediaPlayer-JNI(25121): setLooping: 0
> V/MediaPlayer(25121): MediaPlayer::setLooping
> V/MediaPlayer(25121): message received msg=8, ext1=0, ext2=0
> V/MediaPlayer(25121): notify(8, 0, 0) callback on disconnected mediaplayer
> V/MediaPlayer-JNI(25121): setVolume: left 1.000000  right 1.000000
> V/MediaPlayer(25121): MediaPlayer::setVolume(1.000000, 1.000000)
> V/MediaPlayer-JNI(25121): setLooping: 0
> V/MediaPlayer(25121): MediaPlayer::setLooping
> V/MediaPlayer(25121): setVideoSurfaceTexture
> V/MediaPlayer(25121): prepareAsync
> V/MediaPlayer(25121): message received msg=100, ext1=1, ext2=-1004
> E/MediaPlayer(25121): error (1, -1004)
> V/MediaPlayer(25121): callback application
> V/MediaPlayer(25121): back from callback
> E/MediaPlayer(25121): Error (1,-1004)
> V/MediaPlayer-JNI(25121): stop
> V/MediaPlayer(25121): stop
> E/MediaPlayer(25121): stop called in state 0
> V/MediaPlayer(25121): message received msg=100, ext1=-38, ext2=0
> E/MediaPlayer(25121): error (-38, 0)
> V/MediaPlayer(25121): callback application
> V/MediaPlayer(25121): back from callback
> V/MediaPlayer-JNI(25121): reset
> V/MediaPlayer(25121): reset
> V/MediaPlayer(25121): message received msg=8, ext1=0, ext2=0
> V/MediaPlayer(25121): notify(8, 0, 0) callback on disconnected mediaplayer
> V/MediaPlayer-JNI(25121): release
> V/MediaPlayer(25121): setListener
> V/MediaPlayer(25121): disconnect
> V/MediaPlayer(25121): destructor
> V/MediaPlayer(25121): disconnect
> I/flutter (25121): _platformCallHandler call audio.onComplete {value: true, playerId: 4e53b7f9-5f74-4001-bce7-bb3e666b6332}
> V/MediaPlayer-JNI(25121): native_setup
> V/MediaPlayer(25121): constructor
> V/MediaPlayer(25121): setListener
> V/MediaPlayer-JNI(25121): setAudioStreamType: 3
> V/MediaPlayer(25121): MediaPlayer::setAudioStreamType
> V/MediaPlayer-JNI(25121): setVolume: left 1.000000  right 1.000000
> V/MediaPlayer(25121): MediaPlayer::setVolume(1.000000, 1.000000)
> V/MediaPlayer-JNI(25121): setLooping: 0
> V/MediaPlayer(25121): MediaPlayer::setLooping
> V/MediaPlayer(25121): message received msg=8, ext1=0, ext2=0
> V/MediaPlayer(25121): notify(8, 0, 0) callback on disconnected mediaplayer
> V/MediaPlayer(25121): setVideoSurfaceTexture
> V/MediaPlayer(25121): prepareAsync
> V/MediaPlayer(25121): message received msg=100, ext1=1, ext2=-1004
> E/MediaPlayer(25121): error (1, -1004)
> V/MediaPlayer(25121): callback application
> V/MediaPlayer(25121): back from callback
> E/MediaPlayer(25121): Error (1,-1004)
> V/MediaPlayer-JNI(25121): stop
> V/MediaPlayer(25121): stop
> E/MediaPlayer(25121): stop called in state 0
> V/MediaPlayer(25121): message received msg=100, ext1=-38, ext2=0
> E/MediaPlayer(25121): error (-38, 0)
> V/MediaPlayer(25121): callback application
> V/MediaPlayer(25121): back from callback
> V/MediaPlayer-JNI(25121): reset
> V/MediaPlayer(25121): reset
> V/MediaPlayer(25121): message received msg=8, ext1=0, ext2=0
> V/MediaPlayer(25121): notify(8, 0, 0) callback on disconnected mediaplayer
> V/MediaPlayer-JNI(25121): release
> V/MediaPlayer(25121): setListener
> V/MediaPlayer(25121): disconnect
> V/MediaPlayer(25121): destructor
> V/MediaPlayer(25121): disconnect
> I/flutter (25121): _platformCallHandler call audio.onComplete {value: true, playerId: 4e53b7f9-5f74-4001-bce7-bb3e666b6332}
>

**Comment by luanpotter** [comment]
This is on Android, correct? So not the iOS/headphone problem. Other audio sources work? Did you try with different files and options? Is it Local file mode?

**Comment by klinki** [comment]
Hello, yes, it is Android. I think I found out what was the problem - playing a remote file with disabled internet connectivity. But I think it should not call `onComplete` but rather throw some exception or call `onError`.

**Comment by luanpotter** [comment]
Agreed, maybe there is an exception being catch somewhere and then the player thinks it's completed, when in reality it should throw an error. If you'd like to take a look and contribute with a PR, it'll be very appreciated! Otherwise I might take a look at this soon-ish :)

**Comment by klinki** [comment]
Sure, I will have a look and try to come with some PR. Probably this or next weekend, I hope.

**Comment by thanglq1** [comment]
I'm facing the same issue. I have a list urls . When play 1 url completed, I'll play next url. But the error occur after play completed about 5 urls. Can't play next url.

V/MediaPlayer( 5527): MediaPlayer::setAudioStreamType
V/MediaPlayer-JNI( 5527): setVolume: left 1.000000  right 1.000000
V/MediaPlayer( 5527): MediaPlayer::setVolume(1.000000, 1.000000)
V/MediaPlayer-JNI( 5527): setLooping: 0
V/MediaPlayer( 5527): MediaPlayer::setLooping
V/MediaPlayer-JNI( 5527): setVolume: left 1.000000  right 1.000000
V/MediaPlayer( 5527): MediaPlayer::setVolume(1.000000, 1.000000)
V/MediaPlayer-JNI( 5527): setLooping: 0
V/MediaPlayer( 5527): MediaPlayer::setLooping
V/MediaPlayer( 5527): setVideoSurfaceTexture
V/MediaPlayer( 5527): prepareAsync
D/ViewRootImpl( 5527): ViewPostImeInputStage processPointer 1
D/MediaHTTPConnection( 5527): setReadTimeOut =  30000ms
D/MediaHTTPConnection( 5527): setReadTimeout with 30000ms
I/System.out( 5527): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out( 5527): (HTTPLog)-Static: isSBSettingEnabled false
V/MediaPlayer-JNI( 5527): stop
V/MediaPlayer( 5527): stop
E/MediaPlayer( 5527): stop called in state 4
V/MediaPlayer( 5527): message received msg=100, ext1=-38, ext2=0
E/MediaPlayer( 5527): error (-38, 0)
V/MediaPlayer( 5527): callback application
V/MediaPlayer( 5527): back from callback
V/MediaPlayer-JNI( 5527): reset
V/MediaPlayer( 5527): reset
V/MediaPlayer( 5527): message received msg=1, ext1=0, ext2=0
V/MediaPlayer-JNI( 5527): release
V/MediaPlayer( 5527): setListener
V/MediaPlayer( 5527): disconnect
V/MediaPlayer( 5527): notify(1, 0, 0) callback on disconnected mediaplayer
V/MediaPlayer( 5527): message received msg=8, ext1=0, ext2=0
V/MediaPlayer( 5527): notify(8, 0, 0) callback on disconnected mediaplayer
V/MediaPlayer( 5527): destructor
V/MediaPlayer( 5527): disconnect

**Comment by amenski** [comment]
Hi guys, did you have success patching this issue? In my case it happens even with working internet. printing " _platformCallHandler call audio.onComplete {value: true, playerId: ef1abaca-5980-4b65-8b3f-0c58a71985b2}" immediately. I don't know if it is the file type(wma), since it is not happening for mp3. I know that it is supported in android. Thank you.

**Comment by erickzanardo** [comment]
Closing due inactivity
