### ISSUE TITLE
Player stops when android kills activity

### ISSUE THREAD

**Issue by nt4f04uNd** [luanpotter/audioplayers#286]
I am building a music player with your plugin but here's an issue. 

Android manages memory for apps and kills them by its decision. For some reason when this happens your plugin stops playing music, but I wan't to preserve it until user re-opens an application again manually.

**Comment by DylanXie123** [comment]
I also want to keep playing music even activity is killed.

**Comment by DylanXie123** [comment]
I find a package that might be helpful
[audio_service](https://pub.dev/packages/audio_service)
