### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by aliyazdi75** [luanpotter/audioplayers#288]
Hello sir,
As many issues and what we need about notification I've been working on media style android notification and built this [package](https://pub.dev/packages/flutter_media_notification) in this repository https://github.com/aliyazdi75/flutter_media_notification
If you liked it you can share it on `README` , it would help other developers.

**Comment by luanpotter** [comment]
I think we already suggest `audio_service` for that, please check the Feature Parity Table file for reference.

**Comment by aliyazdi75** [comment]
Yea, sure, it was for a long time ago, and `audio_service` didn't exist, and I don't maintain that anymore.
