### ISSUE TITLE
Problem playing concurrent LOW_LATENCY sounds on Android

### ISSUE THREAD

**Issue by dsyrstad** [luanpotter/audioplayers#292]
I'm testing the example app on Android 10, audioplayers 0.13.2. There is a button "Play Local Asset In Low Latency 'audio.mp3'" in example/lib/main.dart, `localAsset()`  which has the code:
```
           Text('Play Local Asset In Low Latency \'audio.mp3\':'),
          _btn('Play', () => audioCache.play('audio.mp3', mode: PlayerMode.LOW_LATENCY)),
```
If I run the app and click the button rapidly, I can get it to play multiple streams concurrently.

If I change the button to:
```
      _btn('Play', () async {
        await audioCache.play('audio.mp3', mode: PlayerMode.LOW_LATENCY);
        await audioCache.play('audio2.mp3', mode: PlayerMode.LOW_LATENCY);
      }),
```
it only plays the last stream (audio2.mp3). I'm having exactly the same problem in my game when I try to play two sounds at the same time.

If I add a short sleep in between:
```
      _btn('Play', () async {
        await audioCache.play('audio.mp3', mode: PlayerMode.LOW_LATENCY);
        sleep(Duration(milliseconds: 50));
        await audioCache.play('audio2.mp3', mode: PlayerMode.LOW_LATENCY);
      }),
```
both will play nearly concurrently (offset by 50ms). It seems like there may be some kind of race condition.

Also, if I change the mode to MEDIA_PLAYER, I do not need the sleep. Apparently because this is using Android MediaPlayer rather than SoundPool. Of course, the lag in playing sounds this way is not acceptable for a game.

I'm on Flutter (Channel stable, v1.9.1+hotfix.4, on Linux, locale en_US.UTF-8)

**Comment by dsyrstad** [comment]
This is a loading race condition for WrappedSoundPool. I have a PR coming for it.

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
