### ISSUE TITLE
The getter '_positionController' was called on null.

### ISSUE THREAD

**Issue by ssbaval** [luanpotter/audioplayers#294]
Looking in **sentry**  -  am getting lots of these errors :- 

NoSuchMethodError
NoSuchMethodError: The getter '_positionController' was called on null.
Receiver: null
Tried calling: _positionController
audioplayers.dart in AudioPlayer._doHandlePlatformCall at line 358
Called from: <asynchronous suspension>
audioplayers.dart in AudioPlayer.platformCallHandler at line 335
Called from: <asynchronous suspension>
platform_channel.dart in MethodChannel._handleAsMethodCall at line 397
Called from: <asynchronous suspension>
platform_channel.dart in MethodChannel.setMethodCallHandler.<fn> at line 365
binary_messenger.dart in _DefaultBinaryMessenger.handlePlatformMessage at line 110
Called from: <asynchronous suspension>

**Comment by mtkgeek** [comment]
I'm getting this error too. Infact every getter method gives me this error so i'm thinking there was an error when the AudioPlayer instance was being created, pls is there a solution yet?

**Comment by leidig54** [comment]
@ssbaval did you find a solution?

**Comment by danielgrgly** [comment]
I seem to have the same error.

**Comment by iamdhrv** [comment]
I am also getting same Error.
`[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The getter '_positionController' was called on null.
Receiver: null
Tried calling: _positionController
[38;5;244m#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)[39;49m
[38;5;248m#1      AudioPlayer._doHandlePlatformCall[39;49m
<asynchronous suspension>
[38;5;248m#2      AudioPlayer.platformCallHandler[39;49m
<asynchronous suspension>
[38;5;244m#3      MethodChannel._handleAsMethodCall[39;49m
<asynchronous suspension>
[38;5;244m#4      MethodChannel.setMethodCallHandler.<anonymous closure>[39;49m
[38;5;244m#5      _DefaultBinaryMessenger.handlePlatformMessage[39;49m
<asynchronous suspension>
[38;5;244m#6      _invoke3.<anonymous closure>  (dart:ui/hooks.dart:296:15)[39;49m
[38;5;244m#7      _rootRun  (dart:async/zone.dart:1190:13)[39;49m
#8      _CustomZone.run (dart:async/zone.dart<…>
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The getter '_positionController' was called on null.
Receiver: null
Tried calling: _positionController
[38;5;244m#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)[39;49m
[38;5;248m#1      AudioPlayer._doHandlePlatformCall[39;49m
<asynchronous suspension>
[38;5;248m#2      AudioPlayer.platformCallHandler[39;49m
<asynchronous suspension>
[38;5;244m#3      MethodChannel._handleAsMethodCall[39;49m
<asynchronous suspension>
[38;5;244m#4      MethodChannel.setMethodCallHandler.<anonymous closure>[39;49m
[38;5;244m#5      _DefaultBinaryMessenger.handlePlatformMessage[39;49m
<asynchronous suspension>
[38;5;244m#6      _invoke3.<anonymous closure>  (dart:ui/hooks.dart:296:15)[39;49m
[38;5;244m#7      _rootRun  (dart:async/zone.dart:1190:13)[39;49m
#8      _CustomZone.run (dart:async/zone.dart<…>
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The getter '_positionController' was called on null.
Receiver: null
Tried calling: _positionController
[38;5;244m#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)[39;49m
[38;5;248m#1      AudioPlayer._doHandlePlatformCall[39;49m
<asynchronous suspension>
[38;5;248m#2      AudioPlayer.platformCallHandler[39;49m
<asynchronous suspension>
[38;5;244m#3      MethodChannel._handleAsMethodCall[39;49m
<asynchronous suspension>
[38;5;244m#4      MethodChannel.setMethodCallHandler.<anonymous closure>[39;49m
[38;5;244m#5      _DefaultBinaryMessenger.handlePlatformMessage[39;49m
<asynchronous suspension>
[38;5;244m#6      _invoke3.<anonymous closure>  (dart:ui/hooks.dart:296:15)[39;49m
[38;5;244m#7      _rootRun  (dart:async/zone.dart:1190:13)[39;49m
#8      _CustomZone.run (dart:async/zone.dart<…>
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The getter '_positionController' was called on null.
Receiver: null
Tried calling: _positionController
[38;5;244m#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)[39;49m
[38;5;248m#1      AudioPlayer._doHandlePlatformCall[39;49m
<asynchronous suspension>
[38;5;248m#2      AudioPlayer.platformCallHandler[39;49m
<asynchronous suspension>
[38;5;244m#3      MethodChannel._handleAsMethodCall[39;49m
<asynchronous suspension>
[38;5;244m#4      MethodChannel.setMethodCallHandler.<anonymous closure>[39;49m
[38;5;244m#5      _DefaultBinaryMessenger.handlePlatformMessage[39;49m
<asynchronous suspension>
[38;5;244m#6      _invoke3.<anonymous closure>  (dart:ui/hooks.dart:296:15)[39;49m
[38;5;244m#7      _rootRun  (dart:async/zone.dart:1190:13)[39;49m
#8      _CustomZone.run (dart:async/zone.dart<…>
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The getter '_positionController' was called on null.
Receiver: null
Tried calling: _positionController
[38;5;244m#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)[39;49m
[38;5;248m#1      AudioPlayer._doHandlePlatformCall[39;49m
<asynchronous suspension>
[38;5;248m#2      AudioPlayer.platformCallHandler[39;49m
<asynchronous suspension>
[38;5;244m#3      MethodChannel._handleAsMethodCall[39;49m
<asynchronous suspension>
[38;5;244m#4      MethodChannel.setMethodCallHandler.<anonymous closure>[39;49m
[38;5;244m#5      _DefaultBinaryMessenger.handlePlatformMessage[39;49m
<asynchronous suspension>
[38;5;244m#6      _invoke3.<anonymous closure>  (dart:ui/hooks.dart:296:15)[39;49m
[38;5;244m#7      _rootRun  (dart:async/zone.dart:1190:13)[39;49m
#8      _CustomZone.run (dart:async/zone.dart<…>
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The getter '_positionController' was called on null.
Receiver: null
Tried calling: _positionController
[38;5;244m#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)[39;49m
[38;5;248m#1      AudioPlayer._doHandlePlatformCall[39;49m
<asynchronous suspension>
[38;5;248m#2      AudioPlayer.platformCallHandler[39;49m
<asynchronous suspension>
[38;5;244m#3      MethodChannel._handleAsMethodCall[39;49m
<asynchronous suspension>
[38;5;244m#4      MethodChannel.setMethodCallHandler.<anonymous closure>[39;49m
[38;5;244m#5      _DefaultBinaryMessenger.handlePlatformMessage[39;49m
<asynchronous suspension>
[38;5;244m#6      _invoke3.<anonymous closure>  (dart:ui/hooks.dart:296:15)[39;49m
[38;5;244m#7      _rootRun  (dart:async/zone.dart:1190:13)[39;49m
#8      _CustomZone.run (dart:async/zone.dart<…>
Application finished.
Exited (sigterm)
`

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
