### ISSUE TITLE
Exception in E/Config:Grabber:GameModeImComponents when calling play

### ISSUE THREAD

**Issue by nbros** [luanpotter/audioplayers#295]
Each time I call AudioPlayer.play, the following error appears in the error log (but the audio plays anyway):

`E/Config:Grabber:GameModeImComponents(31855): Exception:Value 2dfb8af(...)f986538a7e of type java.lang.String cannot be converted to JSONArray`

**Comment by erickzanardo** [comment]
There isn't enough information on this issue for us to act on. Please edit this, or open a new one and please follow the issue template.

Feel free to comment here and we can re open this eventually.
