### ISSUE TITLE
no sound on mac

### ISSUE THREAD

**Issue by MeFelixWang** [luanpotter/audioplayers#296]
Hi there, thanks for this awesome plugin!

I got a weird bug which had confused me for several days.

The plugin works wellon windows, but on mac, there is no sound.

I have tried ios simulator and android simulator on mac, same result.

And the listeners didn't work:
```
audioPlayer
  ..onAudioPositionChanged.listen((p) {
    print(p);
  })
  ..onPlayerError.listen((String msg) {
    print(msg);
  })
  ..onDurationChanged.listen((d) {
    print(d);
  })
  ..onPlayerStateChanged.listen((state) {
    print(state);
  })
  ..onPlayerCompletion.listen((e) {
    print(e);
  });
```
Here are the plugins:

```
audioplayers: ^0.11.0
path_provider: ^0.5.0
```
Any help will be appreciated.

**Comment by luanpotter** [comment]
Are you able to play sounds on other apps inside your simulator in the mac?

**Comment by MeFelixWang** [comment]
Yeah, I tried youtube when debugging, the sound could be heard clearly.

And I tried headphones for the case of #278, but no sound neither.

Do I need to add any other config code except for the https config? I'm using remote urls.

**Comment by jingweno** [comment]
I just met this problem when using audioplayers as part of [Flame](https://github.com/flame-engine/flame/). There is no sound on Mac for my game: https://github.com/jingweno/heroic_haiku

**Comment by luanpotter** [comment]
I have since refactored all the macos code to swift, tested locally and it is working. Please test this on the current version (0.17.0) and if it's still a problem please open a new issue, following the template.
