### ISSUE TITLE
Crash when used with audio_service after upgrade to 0.13.0

### ISSUE THREAD

**Issue by secretwpn** [luanpotter/audioplayers#298]
I'm using `audio_service` flutter package to make my app support background audio playback (when the screen is off or the app is minimized) and it was all working fine up to `audioplayers 0.12.1` but the same code breaks after upgrading to `audioplayers 0.13.0` (Stacktrace below)

To see this for yourself you can get the example from `audio_service` plugin, which uses `audioplayer `package that `audioplayers` is based on. just replace the `audioplayer` package in the example pubspec.yaml with `audioplayers` package and see for yourself.

    E/AudioplayersPlugin(31218): Unexpected error!
    E/AudioplayersPlugin(31218): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
    E/AudioplayersPlugin(31218):    at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:60)
    E/AudioplayersPlugin(31218):    at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:41)
    E/AudioplayersPlugin(31218):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
    E/AudioplayersPlugin(31218):    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
    E/AudioplayersPlugin(31218):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:645)
    E/AudioplayersPlugin(31218):    at android.os.MessageQueue.nativePollOnce(Native Method)
    E/AudioplayersPlugin(31218):    at android.os.MessageQueue.next(MessageQueue.java:325)
    E/AudioplayersPlugin(31218):    at android.os.Looper.loop(Looper.java:142)
    E/AudioplayersPlugin(31218):    at android.app.ActivityThread.main(ActivityThread.java:6541)
    E/AudioplayersPlugin(31218):    at java.lang.reflect.Method.invoke(Native Method)
    E/AudioplayersPlugin(31218):    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    E/AudioplayersPlugin(31218):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
    E/MethodChannel#xyz.luan/audioplayers(31218): Failed to handle method call
    E/MethodChannel#xyz.luan/audioplayers(31218): java.lang.IllegalArgumentException: Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
    E/MethodChannel#xyz.luan/audioplayers(31218):   at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
    E/MethodChannel#xyz.luan/audioplayers(31218):   at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
    E/MethodChannel#xyz.luan/audioplayers(31218):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:230)
    E/MethodChannel#xyz.luan/audioplayers(31218):   at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:44)
    E/MethodChannel#xyz.luan/audioplayers(31218):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
    E/MethodChannel#xyz.luan/audioplayers(31218):   at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
    E/MethodChannel#xyz.luan/audioplayers(31218):   at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:645)
    E/MethodChannel#xyz.luan/audioplayers(31218):   at android.os.MessageQueue.nativePollOnce(Native Method)
    E/MethodChannel#xyz.luan/audioplayers(31218):   at android.os.MessageQueue.next(MessageQueue.java:325)
    E/MethodChannel#xyz.luan/audioplayers(31218):   at android.os.Looper.loop(Looper.java:142)
    E/MethodChannel#xyz.luan/audioplayers(31218):   at android.app.ActivityThread.main(ActivityThread.java:6541)
    E/MethodChannel#xyz.luan/audioplayers(31218):   at java.lang.reflect.Method.invoke(Native Method)
    E/MethodChannel#xyz.luan/audioplayers(31218):   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    E/MethodChannel#xyz.luan/audioplayers(31218):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
    E/flutter (31218): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference, null)
    E/flutter (31218): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
    E/flutter (31218): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
    E/flutter (31218): <asynchronous suspension>
    E/flutter (31218): #2      AudioPlayer._invokeMethod (package:audioplayers/audioplayers.dart:211:10)
    E/flutter (31218): #3      AudioPlayer.play (package:audioplayers/audioplayers.dart:233:30)
    E/flutter (31218): #4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
    E/flutter (31218): #5      AudioPlayer.play (package:audioplayers/audioplayers.dart:219:19)
    E/flutter (31218): #6      BackgroundAudioPlayer.onPlay (package:radiopostnauka/services/background_audio_player.dart:26:18)
    E/flutter (31218): #7      BackgroundAudioPlayer.onStart (package:radiopostnauka/services/background_audio_player.dart:72:5)
    E/flutter (31218): #8      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
    E/flutter (31218): #9      BackgroundAudioPlayer.onStart (package:radiopostnauka/services/background_audio_player.dart:41:23)
    E/flutter (31218): #10     AudioServiceBackground.run (package:audio_service/audio_service.dart:752:16)
    E/flutter (31218): #11     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
    E/flutter (31218): #12     _rootRunUnary (dart:async/zone.dart:1132:38)
    E/flutter (31218): #13     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    E/flutter (31218): #14     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
    E/flutter (31218): #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
    E/flutter (31218): #16     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
    E/flutter (31218): #17     Future._completeWithValue (dart:async/future_impl.dart:522:5)
    E/flutter (31218): #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
    E/flutter (31218): #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
    E/flutter (31218): #20     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart)
    E/flutter (31218): #21     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
    E/flutter (31218): #22     _rootRunUnary (dart:async/zone.dart:1132:38)
    E/flutter (31218): #23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    E/flutter (31218): #24     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
    E/flutter (31218): #25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
    E/flutter (31218): #26     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
    E/flutter (31218): #27     Future._completeWithValue (dart:async/future_impl.dart:522:5)
    E/flutter (31218): #28     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
    E/flutter (31218): #29     _rootRun (dart:async/zone.dart:1124:13)
    E/flutter (31218): #30     _CustomZone.run (dart:async/zone.dart:1021:19)
    E/flutter (31218): #31     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
    E/flutter (31218): #32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
    E/flutter (31218): #33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
    E/flutter (31218): #34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
    E/flutter (31218):

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
