### ISSUE TITLE
`AudioCache` audios should not be constrained to assets folder

### ISSUE THREAD

**Issue by hugocbpassos** [luanpotter/audioplayers#309]
`AudioCache` allows you to specify a `prefix`, which as per the docs:

> This is the path inside your assets folder where your files lie.

However, creating a directory called "assets" in the project's root to place your resources is a Flutter convention, not a rule, so I don't think the users should be constrained to that.

For instance, if I have a custom folder called "resources", I have to ascend one level, choose my folder, and then specify my actual `prefix`, which is a quite hacky solution:

```dart
AudioCache(prefix: '../resources/audios/').play('audio.mp3');
```

### Suggestions and considerations: 

* Add the attribute `root` to `AudioCache`, which defaults to "assets/". This would avoid a breaking change, but also make everything confusing, since it's not quite obvious when to use `root` or `prefix`.

* Change the default value of `prefix` from "" to "assets/". This would be a **runtime** breaking change, which is probably infeasible for such a popular package.

* Remove the attribute `prefix`, and add the attribute `root`, which defaults to "assets/". This would be a compile-time breaking change.

I like the last solution, but there may be better ones, so feel free to share any other ideas with us.

**Comment by luanpotter** [comment]
I'm ok with the last solution, can you put out a pr for that? We can release a new minor version for that. please add it to the changelog and mention it as a breaking issue.

Thanks for figuring it out!

**Comment by mockturtl** [comment]
This issue may duplicate #199.

**Comment by hugocbpassos** [comment]
@mockturtl Indeed. I'll keep this issue since it specifies a workaround (quite tricky, but works), suggestions and considerations.

Thanks for letting me know, though. I may close both issues if I decide to make a PR.

**Comment by luanpotter** [comment]
This was fixed! Now the default prefix is 'assets' and nothing is added if you override it.
