### ISSUE TITLE
audio.onError / AVPlayerItemStatus.failed on playback of local file

### ISSUE THREAD

**Issue by mdr** [luanpotter/audioplayers#310]
I get the following error trying to play audio from a local MP4 file on iOS, both on a real device and the simulator:
```flutter: _platformCallHandler call audio.onError {playerId: 8633185b-6dbd-4087-b475-daf152241119, value: AVPlayerItemStatus.failed}```

The audio file itself is well-formed (I can play it with `flutter_sound`, for example). The file is located in the `Documents` directory (e.g. `/Users/matt/Library/Developer/CoreSimulator/Devices/E25613DC-981D-4A38-BDC2-189A1123F938/data/Containers/Data/Application/DACE34F6-06C3-45A7-B15A-5D121F3FFEBE/Documents/recordings/3c406cbc-d092-4147-b303-bd9ea0a75ab8`).

Is there any way to get more information about the error?

**Comment by joeharper1000** [comment]
I'm having the same issue. Did you find a fix?

**Comment by CristianSavin** [comment]
Recently I also had a problem, but the problem was with local MP3. 
Solution is that: When you call method play you need to provide an option isLocal: true, that solved my problem.

**Comment by volgin** [comment]
I see this error every time when I call setURL() with a local file. But the player plays normally, so it's not clear what causes this error to be reported. But I don't see this error when I call play(). So it may be related to #404. I already submitted one PR to address that issue, but it appears that something else still needs to be fixed between play() and setUrl().

**Comment by erickzanardo** [comment]
This issue is outdated or uses a very old version of the project, could you please test if this happens on newer versions? And in case that this still happens, open a new issue?
