### ISSUE TITLE
Can not play audio on Web Flutter

### ISSUE THREAD

**Issue by hautran90** [luanpotter/audioplayers#312]
I used library audioplayers: ^0.13.2, it working on app flutter, but it can not play audio on web flutter. You can help me fix it?

My code :
GestureDetector(
onTap: (){
AudioPlayer().play(url, isLocal: true, stayAwake: true);
},
child: Icon(Icons.play_circle_outline)
)

**Comment by erickzanardo** [comment]
Flutter web is still as a tech preview, we don't support it. Maybe in the future.

**Comment by hautran90** [comment]
Okay! Thanks @erickzanardo

**Comment by tolstenko** [comment]
We are facing the same issue here.

**Comment by Xadovsk** [comment]
Same issue here. I really like Audioplayers library, hope it supports flutter web in the near future. It would help me a lot.

**Comment by erickzanardo** [comment]
We sure want to support Flutter Web, but we will wait at least until Flutter web leaves the tech preview state, so let’s hope this happens soon.

**Comment by saeed-golshan** [comment]
Hi @erickzanardo as flutter web on beta and dart:web_audio library is available do you have any plan to add support web audio?

**Comment by erickzanardo** [comment]
@luanpotter has started some initial work on web support, can you share your progress so far Luan?

**Comment by FieserKiller** [comment]
@luanpotter or anyone. Is there any progress on this topic?

**Comment by luanpotter** [comment]
I just merged in a branch where some features are available to web. We need to work to get to feature parity though
