### ISSUE TITLE
stayAwake does not work on ios Devices

### ISSUE THREAD

**Issue by Blackwolf-Iran** [luanpotter/audioplayers#314]
StayAwake does not work on ios Devices

`PlayerWidget.audioplayers.play(stayAwake: true)`

and :

`  Future<int> _play({bool stayAwake=true}) async {
    setState(() {
      loading = true;
    });
    final playPosition = (_position != null &&
        _duration != null &&
        _position.inMilliseconds > 0 &&
        _position.inMilliseconds < _duration.inMilliseconds)
        ? _position
        : null;
    final result = await PlayerWidget.audioPlayer
        .play(url, isLocal: isLocal, position: playPosition,stayAwake: true);
    if (result == 1)
      setState(() {
        PlayerWidget.playerState = PlayerState.playing;
      });
    return result;
  }
`
Works well in the Xcode and AndroidStudio simulator but does not work on iPhone devices
flutter doctor is good and i dont have any problem with other settings.

**Comment by volgin** [comment]
I just tried on my iPhone, and it works as expected. Maybe, it a specific device or iOs version?

**Comment by ryanrhodes** [comment]
Hi, had this issue and realized I needed to do this as well: https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/creating_a_basic_video_player_ios_and_tvos/enabling_background_audio

**Comment by TheBestMoshe** [comment]
> Hi, had this issue and realized I needed to do this as well: https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/creating_a_basic_video_player_ios_and_tvos/enabling_background_audio

This fixed it for me

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
