### ISSUE TITLE
Audio does not pause when different application begins to play

### ISSUE THREAD

**Issue by jonas-zebari** [luanpotter/audioplayers#317]
The only operating systems and version I can confirm this behavior on is Android 10.

If you play audio using this plugin + Flutter application, navigate to a different application (like Chrome) and begin to play video or audio, the background plugin audio does not pause. I would expect the default behavior to be pausing in this case, with the ability to change that if desired.

Is this expected behavior? Or is there a way to do this I have not yet seen? Whoever looks at this, thanks for your time!

**Comment by erickzanardo** [comment]
Pausing when app lose focus should be handled by your app, not the plugin. To pause it you should use flutters lyficicle methods to capture when your app lost focus, and pause the player.

**Comment by jonas-zebari** [comment]
Pausing when the app loses focus is not a problem. We do not want the audio to pause on app lost focus, instead we want the audio to continue in the background until a different app begins to play audio. Based on a recent PR to lower the audio volume in this case, it should be possible.

**Comment by jonas-zebari** [comment]
@erickzanardo Any additional thoughts on this?

**Comment by andrei-pavel** [comment]
There is #232 which fixes this for about five months. Don't throw stones, it's just an idea, I say it should get merged without iOS and through NotImplemented exceptions for this feature and maybe that will incentivize people to implement it. :man_shrugging:

**Comment by erickzanardo** [comment]
I don't like having features like these on only one platform, but since by the looks of it, the author will not be implementing the iOS support, I wouldn't mind merging it if we somehow have some warnings on README informing that this is only available on Android. #232 has some conflicts that need to be fixed as well.

But I would like to hear what @luanpotter has to say before merging it.

**Comment by luanpotter** [comment]
I'm ok with it if we add proper disclaimer on the readme, asking for help and linking to issues to the missing features on the other platforms

**Comment by erickzanardo** [comment]
Fair enough, if someone want to update #232 to fix the conflict problem, and add the READM disclaimer that we discussed, we can accept the PR.

I can do it myself, but I am quite overwhelmed at the moment, so it can take a while for me to able to work on this.

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening

**Comment by hathim92** [comment]
Is this issue fixed?? please let me know how to fix this issue?
