### ISSUE TITLE
How can audiocache join the listening event? I added it but it is invalid

### ISSUE THREAD

**Issue by du666du** [luanpotter/audioplayers#319]
How can audiocache join the listening event? I added it but it is invalid

**Comment by luanpotter** [comment]
what do you mean it's invalid? what did you try to do? can you share some code?

**Comment by andrewsdv** [comment]
I'm not sure what @du666du was asking about. But what I faced with is absence of onPlayerCompletion() or similar callback for AudioCache. And I haven't found a way to execute some code AFTER local audio asset is played. Can you help me with that @luanpotter?

**Comment by erickzanardo** [comment]
Closing due inactivity, if there is more info that you can add to the issue, comment here and we can re open the issue.
