### ISSUE TITLE
Could not resolve all artifacts for configuration ':audioplayers:classpath'

### ISSUE THREAD

**Issue by pbsajjad** [luanpotter/audioplayers#320]
Hi. I am using latest version of Flutter (1.9) and when I use audioplayers package, I could not run app and get the following error. I also add dependencies of package.

**pubspec.yaml**
`dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  audioplayers: ^0.13.2
  path_provider: ^1.1.0
  uuid: ^2.0.0
  test: ^1.3.0
  http: ^0.11.3+17`

**Flutter Version**
`Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (9 weeks ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0`

**Error**
`C:\flutter\tester>flutter run
Launching lib\main.dart on BLN L21 in debug mode...
Initializing gradle...                                             15.6s
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "C:\flutter\tester\android\gradlew.bat" exited abnormally:

> Configure project :audioplayers

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':audioplayers'.
> Could not resolve all artifacts for configuration ':audioplayers:classpath'.
   > Could not find gradle.jar (com.android.tools.build:gradle:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.0/gradle-3.3.0.jar
   > Could not find builder.jar (com.android.tools.build:builder:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.0/builder-3.3.0.jar
   > Could not find tracker.jar (com.android.tools.analytics-library:tracker:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/tracker/26.3.0/tracker-26.3.0.jar
   > Could not find shared.jar (com.android.tools.analytics-library:shared:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/shared/26.3.0/shared-26.3.0.jar
   > Could not find crash.jar (com.android.tools.analytics-library:crash:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/crash/26.3.0/crash-26.3.0.jar
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle-api/26.3.0/lint-gradle-api-26.3.0.jar
   > Could not find gradle-api.jar (com.android.tools.build:gradle-api:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle-api/3.3.0/gradle-api-3.3.0.jar
   > Could not find databinding-compiler-common.jar (androidx.databinding:databinding-compiler-common:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-compiler-common/3.3.0/databinding-compiler-common-3
         .3.0.jar
   > Could not find manifest-merger.jar (com.android.tools.build:manifest-merger:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/manifest-merger/26.3.0/manifest-merger-26.3.0.jar
   > Could not find sdk-common.jar (com.android.tools:sdk-common:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/26.3.0/sdk-common-26.3.0.jar
   > Could not find builder-test-api.jar (com.android.tools.build:builder-test-api:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-test-api/3.3.0/builder-test-api-3.3.0.jar
   > Could not find ddmlib.jar (com.android.tools.ddms:ddmlib:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/26.3.0/ddmlib-26.3.0.jar
   > Could not find sdklib.jar (com.android.tools:sdklib:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.3.0/sdklib-26.3.0.jar
   > Could not find layoutlib-api.jar (com.android.tools.layoutlib:layoutlib-api:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/layoutlib/layoutlib-api/26.3.0/layoutlib-api-26.3.0.jar
   > Could not find dvlib.jar (com.android.tools:dvlib:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/dvlib/26.3.0/dvlib-26.3.0.jar
   > Could not find repository.jar (com.android.tools:repository:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/repository/26.3.0/repository-26.3.0.jar
   > Could not find common.jar (com.android.tools:common:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/common/26.3.0/common-26.3.0.jar
   > Could not find jetifier-processor.jar (com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta02).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-processor/1.0.0-beta02/jetifier-processor-
         1.0.0-beta02.jar
   > Could not find bundletool.jar (com.android.tools.build:bundletool:0.6.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.6.0/bundletool-0.6.0.jar
   > Could not find jetifier-core.jar (com.android.tools.build.jetifier:jetifier-core:1.0.0-beta02).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-core/1.0.0-beta02/jetifier-core-1.0.0-beta
         02.jar
   > Could not find builder-model.jar (com.android.tools.build:builder-model:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-model/3.3.0/builder-model-3.3.0.jar
   > Could not find protos.jar (com.android.tools.analytics-library:protos:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/26.3.0/protos-26.3.0.jar
   > Could not find apkzlib.jar (com.android.tools.build:apkzlib:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apkzlib/3.3.0/apkzlib-3.3.0.jar
   > Could not find apksig.jar (com.android.tools.build:apksig:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/3.3.0/apksig-3.3.0.jar
   > Could not find annotations.jar (com.android.tools:annotations:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.3.0/annotations-26.3.0.jar
   > Could not find databinding-common.jar (androidx.databinding:databinding-common:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-common/3.3.0/databinding-common-3.3.0.jar
   > Could not find baseLibrary.jar (com.android.databinding:baseLibrary:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/databinding/baseLibrary/3.3.0/baseLibrary-3.3.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get
full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 34s
  Command: C:\flutter\tester\android\gradlew.bat app:properties

Please review your Gradle project setup in the android/ folder.`

Thanks a lot for helping.

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
