### ISSUE TITLE
[ERROR]MissingPluginException version 0.13.3 for android

### ISSUE THREAD

**Issue by tula-Intelads** [luanpotter/audioplayers#328]
`[ERROR]MissingPluginException(No implementation found for method startHeadlessService on channel xyz.luan/audioplayers)`

`MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314)
I/flutter (18991): <asynchronous suspension>
I/flutter (18991): #1      AudioPlayer._invokeMethod (package:audioplayers/audioplayers.dart:303)
I/flutter (18991): #2      new AudioPlayer. (package:audioplayers/audioplayers.dart:287)
`

**Comment by mhd-barikhan** [comment]
Same issue for me :(

**Comment by mhd-barikhan** [comment]
use V 12.1 working fine until fix the new one.

**Comment by mhd-barikhan** [comment]
this issue related to https://pub.dev/packages/flame version.

**Comment by dvorapa** [comment]
Dupe of #306

**Comment by dagrinchi** [comment]
Same ploblem, any solution ?

**Comment by dagrinchi** [comment]
Works fine in v0.13.2 but without iOS notifications, this commit https://github.com/luanpotter/audioplayers/commit/7ce1f21c7a230e92976c0e5159321aba16fbe380#diff-af2e7e77d80537390f02669683368ba2 doesn't has startHeadlessService method support for Android

**Comment by dagrinchi** [comment]
Hello @subhash279 any ideas ?

**Comment by sayhicoelho** [comment]
Switching to version 0.13.2 has fixed

**Comment by subhash279** [comment]
I submitted a new PR #332  which should fix this!

**Comment by erickzanardo** [comment]
Fixed on #332
