### ISSUE TITLE
[Question] Is there any way to get access to the player from android code

### ISSUE THREAD

**Issue by andrewpmoore** [luanpotter/audioplayers#329]
We've got the flutter part of the audio player working fine, but the app also has some android components to it. Is there a way to get a reference to the audio player directly in android so that we can call methods such as play/stop etc from android?

**Comment by erickzanardo** [comment]
I think the easiest way to do that on the native side atm, is to use platform channel api directly on the android code.

Closing as this is not an issue but a question. Feel free to add more comments here.
