### ISSUE TITLE
Play asset audio exception:  java.lang.RuntimeException: Unable to access resource

### ISSUE THREAD

**Issue by ryanhz** [luanpotter/audioplayers#330]
D/MediaPlayerNative( 9136): Action:start, CurrentState:MEDIA_PLAYER_STARTED
I/flutter ( 9136): Caught error: MissingPluginException(No implementation found for method startHeadlessService on channel xyz.luan/audioplayers)
I/flutter ( 9136): Reporting to Sentry.io...
D/MediaPlayerNative( 9136): MediaPlayer::setVolume(1.000000, 1.000000)
D/MediaPlayerNative( 9136): MediaPlayer::setVolume(1.000000, 1.000000)
I/PlayerBase( 9136): isRestricted: falseLeftvolume: 1.0 Rightvolume: 1.0mPanMultiplierL: 1.0mPanMultiplierR: 1.0
I/MediaPlayerNative( 9136): setDataSource(107, 0, 576460752303423487)
E/MediaPlayerNative( 9136): Unable to create media player
D/MediaPlayer( 9136): setDataSource failed:
D/MediaPlayer( 9136): java.io.IOException: setDataSourceFD failed.: status=0x80000000
D/MediaPlayer( 9136): 	at android.media.MediaPlayer._setDataSource(Native Method)
D/MediaPlayer( 9136): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1382)
D/MediaPlayer( 9136): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1365)
D/MediaPlayer( 9136): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1296)
D/MediaPlayer( 9136): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1233)
D/MediaPlayer( 9136): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1200)
D/MediaPlayer( 9136): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setSource(WrappedMediaPlayer.java:240)
D/MediaPlayer( 9136): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.java:52)
D/MediaPlayer( 9136): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:64)
D/MediaPlayer( 9136): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:43)
D/MediaPlayer( 9136): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
D/MediaPlayer( 9136): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
D/MediaPlayer( 9136): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:645)
D/MediaPlayer( 9136): 	at android.os.MessageQueue.nativePollOnce(Native Method)
D/MediaPlayer( 9136): 	at android.os.MessageQueue.next(MessageQueue.java:386)
D/MediaPlayer( 9136): 	at android.os.Looper.loop(Looper.java:175)
D/MediaPlayer( 9136): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
D/MediaPlayer( 9136): 	at java.lang.reflect.Method.invoke(Native Method)
D/MediaPlayer( 9136): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
D/MediaPlayer( 9136): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/AudioplayersPlugin( 9136): Unexpected error!
E/AudioplayersPlugin( 9136): java.lang.RuntimeException: Unable to access resource
E/AudioplayersPlugin( 9136): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setSource(WrappedMediaPlayer.java:242)
E/AudioplayersPlugin( 9136): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.java:52)
E/AudioplayersPlugin( 9136): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:64)
E/AudioplayersPlugin( 9136): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:43)
E/AudioplayersPlugin( 9136): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/AudioplayersPlugin( 9136): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/AudioplayersPlugin( 9136): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:645)
E/AudioplayersPlugin( 9136): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AudioplayersPlugin( 9136): 	at android.os.MessageQueue.next(MessageQueue.java:386)
E/AudioplayersPlugin( 9136): 	at android.os.Looper.loop(Looper.java:175)
E/AudioplayersPlugin( 9136): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/AudioplayersPlugin( 9136): 	at java.lang.reflect.Method.invoke(Native Method)
E/AudioplayersPlugin( 9136): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/AudioplayersPlugin( 9136): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/AudioplayersPlugin( 9136): Caused by: java.io.IOException: setDataSourceFD failed.: status=0x80000000
E/AudioplayersPlugin( 9136): 	at android.media.MediaPlayer._setDataSource(Native Method)
E/AudioplayersPlugin( 9136): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1382)
E/AudioplayersPlugin( 9136): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1365)
E/AudioplayersPlugin( 9136): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1296)
E/AudioplayersPlugin( 9136): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1233)
E/AudioplayersPlugin( 9136): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1200)
E/AudioplayersPlugin( 9136): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setSource(WrappedMediaPlayer.java:240)
E/AudioplayersPlugin( 9136): 	... 13 more
E/MethodChannel#xyz.luan/audioplayers( 9136): Failed to handle method call
E/MethodChannel#xyz.luan/audioplayers( 9136): java.lang.IllegalArgumentException: Unsupported value: java.lang.RuntimeException: Unable to access resource
E/MethodChannel#xyz.luan/audioplayers( 9136): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
E/MethodChannel#xyz.luan/audioplayers( 9136): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
E/MethodChannel#xyz.luan/audioplayers( 9136): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:239)
E/MethodChannel#xyz.luan/audioplayers( 9136): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:46)
E/MethodChannel#xyz.luan/audioplayers( 9136): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#xyz.luan/audioplayers( 9136): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#xyz.luan/audioplayers( 9136): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:645)
E/MethodChannel#xyz.luan/audioplayers( 9136): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#xyz.luan/audioplayers( 9136): 	at android.os.MessageQueue.next(MessageQueue.java:386)
E/MethodChannel#xyz.luan/audioplayers( 9136): 	at android.os.Looper.loop(Looper.java:175)
E/MethodChannel#xyz.luan/audioplayers( 9136): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/MethodChannel#xyz.luan/audioplayers( 9136): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#xyz.luan/audioplayers( 9136): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/MethodChannel#xyz.luan/audioplayers( 9136): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
I/flutter ( 9136): Caught error: MissingPluginException(No implementation found for method startHeadlessService on channel xyz.luan/audioplayers)
I/flutter ( 9136): Reporting to Sentry.io...

**Comment by ider0614** [comment]
+1

**Comment by erickzanardo** [comment]
There isn't enough information on this issue for us to act on. Please edit this, or open a new one and please follow the issue template.

Feel free to comment here and we can re open this eventually.
