### ISSUE TITLE
calling getDuration after calling the setUrl throw Exception

### ISSUE THREAD

**Issue by amirc901** [luanpotter/audioplayers#334]
Hi there is a bug in Android when you call the " await setUrl " and exactly after it you call " await getDuration " it throws the Exception wich says that you are calling getDuration on the wrong state and I think it is because in the setUrl method you are calling the prepareAsync you should use the prepare method which waits until player state changes to the prepare so when you are calling the await setUrl it waits until the player state changed to the prepare

**Comment by volgin** [comment]
Don't call getDuration() until you get AudioPlayerState.PLAYING status. I do it this way:

```
_audioPlayerStateSubscription =
        audioPlayer.onPlayerStateChanged.listen((s) {
      if (s == AudioPlayerState.PLAYING) {
        audioPlayer.getDuration().then((d) {
          /// This is called only once when the recording starts playing.
          _duration = d;
        });
      } else if (s == AudioPlayerState.STOPPED) {
      } else if (s == AudioPlayerState.COMPLETED) {
      }
    }, onError: (_msg) {
    });
```

**Comment by volgin** [comment]
The following code works for me on Android:

```
          Future.delayed(
              Duration(milliseconds: 500),
              () => foregroundAudio.getDuration().then((d) {
                    /// This is called only once when the recording starts playing.
                    _duration = d;
                  }));
```

**Comment by erickzanardo** [comment]
volgin suggestion is the correct way to do this, closing this.
