### ISSUE TITLE
Unhandled Exception: PlatformException(error, Unsupported value: java.lang.IllegalStateException, null)

### ISSUE THREAD

**Issue by jekorx** [luanpotter/audioplayers#336]
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.17763.737], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] VS Code (version 1.40.1)
[√] Connected device (1 available)

• No issues found!
```
```
audioplayers: ^0.13.3
```

```
Android virtual device
api 28
```

```
E/MediaPlayerNative( 6980): error (1, -2147483648)
E/MediaPlayer( 6980): Error (1,-2147483648)
E/MediaPlayerNative( 6980): pause called in state 0, mPlayer(0xcdefb600)
E/MediaPlayerNative( 6980): error (-38, 0)
E/MediaPlayerNative( 6980): Attempt to perform seekTo in wrong state: mPlayer=0xcdefb600, mCurrentState=0
E/MediaPlayerNative( 6980): error (-38, 0)
E/MediaPlayer( 6980): Error (-38,0)
E/MediaPlayer( 6980): Error (-38,0)
V/MediaHTTPService( 6980): MediaHTTPService(android.media.MediaHTTPService@ed3e754): Cookies: null
V/MediaHTTPService( 6980): makeHTTPConnection: CookieHandler (java.net.CookieManager@cdb2a1a) exists.
V/MediaHTTPService( 6980): makeHTTPConnection(android.media.MediaHTTPService@ed3e754): cookieHandler: java.net.CookieManager@cdb2a1a Cookies: null
V/MediaHTTPService( 6980): MediaHTTPService(android.media.MediaHTTPService@1fcdf52): Cookies: null
E/MediaPlayerNative( 6980): attachNewPlayer called in state 4
E/AudioplayersPlugin( 6980): Unexpected error!
E/AudioplayersPlugin( 6980): java.lang.IllegalStateException
E/AudioplayersPlugin( 6980): 	at android.media.MediaPlayer.nativeSetDataSource(Native Method)
E/AudioplayersPlugin( 6980): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1176)
E/AudioplayersPlugin( 6980): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1164)
E/AudioplayersPlugin( 6980): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1131)
E/AudioplayersPlugin( 6980): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setSource(WrappedMediaPlayer.java:240)
E/AudioplayersPlugin( 6980): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.java:52)
E/AudioplayersPlugin( 6980): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:64)
E/AudioplayersPlugin( 6980): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:43)
E/AudioplayersPlugin( 6980): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)

```

**Comment by jekorx** [comment]
It should be a compatibility issue with Android P and above.

**Comment by jekorx** [comment]
That's the problem.
```
android:usesCleartextTraffic="true"
```

**Comment by muhammadanas759** [comment]
please solve this issue...i am facing this 


E/MediaPlayerNative(32167): attachNewPlayer called in state 4
D/AudioPlayers(32167): Unexpected error!
D/AudioPlayers(32167): java.lang.IllegalStateException
D/AudioPlayers(32167): 	at android.media.MediaPlayer._setDataSource(Native Method)
D/AudioPlayers(32167): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1319)
D/AudioPlayers(32167): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setDataSource(WrappedMediaPlayer.kt:52)
D/AudioPlayers(32167): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:71)
D/AudioPlayers(32167): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:33)
D/AudioPlayers(32167): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
D/AudioPlayers(32167): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
D/AudioPlayers(32167): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
D/AudioPlayers(32167): 	at android.os.MessageQueue.nativePollOnce(Native Method)
D/AudioPlayers(32167): 	at android.os.MessageQueue.next(MessageQueue.java:326)
D/AudioPlayers(32167): 	at android.os.Looper.loop(Looper.java:165)
D/AudioPlayers(32167): 	at android.app.ActivityThread.main(ActivityThread.java:6864)
D/AudioPlayers(32167): 	at java.lang.reflect.Method.invoke(Native Method)
D/AudioPlayers(32167): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
D/AudioPlayers(32167): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/flutter (32167): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(Unexpected error!, null, java.lang.IllegalStateException
E/flutter (32167): 	at android.media.MediaPlayer._setDataSource(Native Method)
E/flutter (32167): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1319)
E/flutter (32167): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setDataSource(WrappedMediaPlayer.kt:52)
E/flutter (32167): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:71)
E/flutter (32167): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:33)
E/flutter (32167): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (32167): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (32167): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (32167): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (32167): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (32167): 	at android.os.Looper.loop(Looper.java:165)
E/flutter (32167): 	at android.app.ActivityThread.main(ActivityThread.java:6864)
E/flutter (32167): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (32167): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/flutter (32167): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/flutter (32167): , null)
