### ISSUE TITLE
Why doesn't AudioCache have a stop method?

### ISSUE THREAD

**Issue by ChristianKleineidam** [luanpotter/audioplayers#337]
I want to play a mp3 from my assets. It seems I have to use AudioCache for that. How do I stop the file from playing? Why isn't there a stop method?

**Comment by adindotdev** [comment]
You have to stop the `fixedPlayer` of the AudioCache object.

`AudioCache audioCache;
...
audioCache.fixedPlayer.stop()`

**Comment by luanpotter** [comment]
Exactly. Additionally the `play` method returns the instance of the AudioPlayers used, so you can use the full range of controls provided by AudioPlayers there (stop, pause, etc). Please take a look at the documentation.
