### ISSUE TITLE
App Crashes Abruptly

### ISSUE THREAD

**Issue by rv97** [luanpotter/audioplayers#338]
I just created an app with a small flatbutton and in the onpressed method created an instance of audio cache and played an audio, the app closes abruptly without any error. Then i changed to version 0.10.1 it is working fine.

Error:
iOS => call startHeadlessService, playerId b295134d-9204-436e-a91d-019e2141f81b

**Comment by mavbcn** [comment]
Hi have the same problem with iOS

**Comment by joshhaaronn** [comment]
I am also having the same issue on iOS

**Comment by batman-dev** [comment]
I am also having the same issue on iOS
When play assets mp3

Env iOS13  XCode11.2.1

**Comment by rv97** [comment]
> I am also having the same issue on iOS
> ![audiobug](https://user-images.githubusercontent.com/30924169/69821582-f5941a00-11b8-11ea-9e2b-1db5191aaa8f.gif)

This is the exact issue i am also facing!

**Comment by dvorapa** [comment]
@subhash279 !!!

**Comment by andrewsdv** [comment]
The same for me. Could anyone help and point out the reason?

**Comment by mavbcn** [comment]
Hi everyone,
I tried to use this version   audioplayers: ^0.12.1 .  and it works. 
Try to update pubspec.yaml with this version
best

**Comment by andrewsdv** [comment]
> Hi everyone,
> I tried to use this version audioplayers: ^0.12.1 . and it works.
> Try to update pubspec.yaml with this version
> best

Indeed it worked for me also. Looks like the 0.13.2 is broken.

**Comment by eggnstone** [comment]
See #306 
0.13.2 works for me though, only 0.13.3 doesn't work for me.

**Comment by eggnstone** [comment]
Duplicate of #306

**Comment by smocken78** [comment]
I had the same problem, in my case using AudioCache with fixed player and low latency mode helped:

var player = new AudioCache(
  fixedPlayer: new AudioPlayer(
    mode: PlayerMode.LOW_LATENCY,
  ),
);

**Comment by subhash279** [comment]
Created a new PR #332 which should also fix this.

**Comment by JonathanIvyCR** [comment]
I'm using 0.13.4 and it's still happening. It was working fine and now it's crashing every time it plays an audio.

**Comment by crizant** [comment]
I'm using 0.13.4 and it crashes every time when the playback comes to end.

On iPhone 11 Pro, iOS 13.2.3.

**Comment by JesseScott** [comment]
> I'm using 0.13.4 and it crashes every time when the playback comes to end.
> 
> On iPhone 11 Pro, iOS 13.2.3.

this is already tracked in https://github.com/luanpotter/audioplayers/issues/345

**Comment by luanpotter** [comment]
Closing as duplicate of #345
