### ISSUE TITLE
Error running Gradle

### ISSUE THREAD

**Issue by akel-alkubeh** [luanpotter/audioplayers#343]
I got this error and I can't start my project 

`
* Error running Gradle:
ProcessException: Process "D:\Flutter App\Xylophone\xylophone\android\gradlew.bat" exited abnormally:

> Configure project :audioplayers

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':audioplayers'.
> Could not resolve all artifacts for configuration ':audioplayers:classpath'.
   > Could not find builder.jar (com.android.tools.build:builder:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.0/builder-3.3.0.jar
   > Could not find bundletool.jar (com.android.tools.build:bundletool:0.6.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.6.0/bundletool-0.6.0.jar
   > Could not find protos.jar (com.android.tools.analytics-library:protos:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/26.3.0/protos-26.3.0.jar
   > Could not find apksig.jar (com.android.tools.build:apksig:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/3.3.0/apksig-3.3.0.jar
   > Could not find annotations.jar (com.android.tools:annotations:26.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.3.0/annotations-26.3.0.jar
   > Could not find databinding-common.jar (androidx.databinding:databinding-common:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-common/3.3.0/databinding-common-3.3.0.jar
   > Could not find baseLibrary.jar (com.android.databinding:baseLibrary:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/databinding/baseLibrary/3.3.0/baseLibrary-3.3.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command: D:\Flutter App\Xylophone\xylophone\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.
`

here is my import import 'package:audioplayers/audio_cache.dart';
and here is my depen.   audioplayers: ^0.13.3

**Comment by luanpotter** [comment]
This is a problem with your setup/env/config and not a bug with audioplayers.
