### ISSUE TITLE
don't play in background

### ISSUE THREAD

**Issue by dtdevpro** [luanpotter/audioplayers#348]
hello, i use audioplayers plugin. I play audio in background (screen off), i have set stayAwake = true. But play next music about 2-3 songs ( about 3 minute/song) was stop play until srceen on. Help me fix this issue. Sorry my english is bad

**Comment by saviourdog** [comment]
same

**Comment by Dotsung** [comment]
same

**Comment by Dotsung** [comment]
I wanted to take a log and check if the playerCompleteSubscription itself did not work or if the function I put in it did not work.
However, it works well while the device is connected to computer and running.

This issue occurs if i do not use debugging mode and only run it using the device.
Is the background function not perfect?
What's strange is that the app isn't completely turned off, but if I just turn the screen back on, it's going to call the next song.

**Comment by erickzanardo** [comment]
To properly play audio in the background, the audio_service plugin can be used alongside audioplayers: https://pub.dev/packages/audio_service
