### ISSUE TITLE
Need an options to use PlayAndRecord on IOS

### ISSUE THREAD

**Issue by hanabi1224** [luanpotter/audioplayers#350]
I have a scenario to do continuous recording, speech recognition, and play response audio. But this plugin always reset audio mode to playback which breaks the recording session, thanks!

**Comment by hanabi1224** [comment]
I fixed it by forcing audio session category to play and record.

**Comment by tuanbs** [comment]
> I fixed it by forcing audio session category to play and record.

Can you please tell me how to force audio session category to play and record? I have the same scenario as yours and got the same issue. Also, which plugin do you use for speech recognition and record voice? I'm using [speech_recognition](https://github.com/rxlabz/speech_recognition) and [flutter_sound](https://github.com/dooboolab/flutter_sound).

**Comment by hanabi1224** [comment]
@tuanbs The fix is in my [fork](https://github.com/hanabi1224/audioplayers/tree/workaround). Regarding continuous SR, I'm using a cloud service that does not provide SDK so I just send raw PCM to server and handle CSR there

**Comment by erickzanardo** [comment]
Closing due inactivity, if there is more info that you can add to the issue, comment here and we can re open the issue.
