### ISSUE TITLE
LOW_LATENCY can't play audio with volume bigger than 1.0

### ISSUE THREAD

**Issue by erickzanardo** [luanpotter/audioplayers#351]
More context here: https://github.com/flame-engine/flame/pull/195

**Comment by luanpotter** [comment]
This also implies figuring out what volume greater than 1 means, if it makes sense, if it's consistent between android and ios and then fix any inconsistencies and update the docs to reflect that.

**Comment by erickzanardo** [comment]
We can't play louder than 1.0, closing this.
