### ISSUE TITLE
Device silent or vibrate mode

### ISSUE THREAD

**Issue by quantosapplications** [luanpotter/audioplayers#352]
Hello, is there a way to detect if device is in silent mode?
I'm using this plugin to play sound when user click a button so I would like to not play if the device is silenced? 
Thank you!

**Comment by luanpotter** [comment]
I think there is a `respectSilence` flag, which I assume does exactly that :)

**Comment by quantosapplications** [comment]
Thank you @luanpotter , I didn't read documentation enough. I will try that thank you again!

**Comment by quantosapplications** [comment]
Thank you @luanpotter that's working perfectly :)

**Comment by Dooks123** [comment]
I have the following:

    import 'package:audioplayers/audioplayers.dart';
    
    class AudioPlay {
      static final AudioPlayer _fixedPlayer = AudioPlayer(
        mode: PlayerMode.LOW_LATENCY,
        playerId: 'fixedPlayer',
      );
      static final AudioCache _player = AudioCache(
        prefix: 'lib/assets/sounds/',
        fixedPlayer: _fixedPlayer,
        duckAudio: true,
        respectSilence: true,
      );
    
      static Future<void> error() async {
        await _player.play('error.mp3', mode: PlayerMode.LOW_LATENCY);
      }
    
      static Future<void> success() async {
        await _player.play('success.mp3', mode: PlayerMode.LOW_LATENCY);
      }
    }

As you can see I have the `respectSilence: true,` there, but on the REDMI device, it doesn't respect silence.

Any ideas?

**Comment by vatsaltanna** [comment]
After using respectSilence: true, volume controller is used of system sound(call volume controller). Is there any way in which there will be volume controller of media player and it also respects silent mode?

**Comment by Dooks123** [comment]
@vatsaltanna I have removed this library. Now playing sounds which I have added natively to Android and iOS.
Calling play via a method channel I have setup.

**Comment by Dooks123** [comment]
@vatsaltanna This is what I used to play sounds from Flutter natively:

**iOS** method channel and play sound (`AppDelegate.swift`):

    import UIKit
    import Flutter
    import AVFoundation
    
    @UIApplicationMain
    @objc class AppDelegate: FlutterAppDelegate {
        
        var player: AVAudioPlayer?
        
        override func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
            let controller = (window?.rootViewController as! FlutterViewController)
            let methodChannel = FlutterMethodChannel(name: "MainApp", binaryMessenger: controller.binaryMessenger)
            methodChannel.setMethodCallHandler(self.handle)
            
            GeneratedPluginRegistrant.register(with: self)
            return super.application(application, didFinishLaunchingWithOptions: launchOptions)
        }
        
        public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) -> Void {
            switch call.method {
            case "getPlatformVersion":
                result("iOS " + UIDevice.current.systemVersion)
            case "playSoundSuccess":
                playSound(success: true)
                result(nil)
            case "playSoundError":
                playSound(success: false)
                result(nil)
            default:
                result(nil)
            }
        }
        
        private func playSound(success: Bool) -> Void {
            guard let url = Bundle.main.url(forResource: success ? "success" : "error", withExtension: "mp3") else { return }
            do {
                try AVAudioSession.sharedInstance().setCategory(.ambient, mode: .default)
                try AVAudioSession.sharedInstance().setActive(true)
                player = try AVAudioPlayer(contentsOf: url, fileTypeHint: AVFileType.mp3.rawValue)
                guard let player = player else { return }
                player.play()
            } catch let error {
                print(error.localizedDescription)
            }
        }
    }

**Android** method channel and play sound (`MainActivity.java`):

    import android.content.Context;
    import android.content.Intent;
    import android.media.AudioManager;
    import android.media.MediaPlayer;
    import android.os.Build;
    import android.os.Bundle;
    
    import androidx.annotation.NonNull;
    import androidx.annotation.Nullable;
    
    import io.flutter.embedding.android.FlutterActivity;
    import io.flutter.embedding.engine.FlutterEngine;
    import io.flutter.plugin.common.MethodCall;
    import io.flutter.plugin.common.MethodChannel;
    
    public class MainActivity extends FlutterActivity implements MethodChannel.MethodCallHandler {
        private MethodChannel channel;
        private AudioPlayer audioPlayer;
    
        @Override
        protected void onCreate(@Nullable Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
        }
    
        @Override
        protected void onResume() {
            super.onResume();
    
            initializeMethodChannel();
            initializeAudioPlayer();
        }
    
        private void initializeMethodChannel() {
            if (channel == null) {
                FlutterEngine engine = getFlutterEngine();
                if (engine != null) {
                    channel = new MethodChannel(engine.getDartExecutor().getBinaryMessenger(), "MainApp");
                    channel.setMethodCallHandler(this);
                }
            }
        }
    
        private void initializeAudioPlayer() {
            if (audioPlayer == null) {
                audioPlayer = new AudioPlayer();
            }
        }
    
        @Override
        public void onMethodCall(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
            switch (call.method) {
                case "getPlatformVersion":
                    result.success("Android " + Build.VERSION.RELEASE);
                    break;
                case "playSoundSuccess":
                    if (audioPlayer != null) {
                        audioPlayer.play(this, true);
                    }
                    result.success(null);
                    break;
                case "playSoundError":
                    if (audioPlayer != null) {
                        audioPlayer.play(this, false);
                    }
                    result.success(null);
                    break;
                default:
                    result.notImplemented();
                    break;
            }
        }
    
        @Override
        protected void onDestroy() {
            channel.setMethodCallHandler(null);
            channel = null;
            if (audioPlayer != null) {
                audioPlayer.destroy();
                audioPlayer = null;
            }
            super.onDestroy();
        }
    
        class AudioPlayer {
            private AudioManager audioManager;
            private MediaPlayer mediaPlayer;
    
            public void play(Context context, boolean success) {
                if (allowSounds()) {
                    try {
                        destroyPlayer();
                        mediaPlayer = MediaPlayer.create(context, success ? R.raw.success : R.raw.error);
                        mediaPlayer.start();
                    } catch (Exception ignored) {
                    }
                }
            }
    
            public void destroy() {
                destroyPlayer();
                mediaPlayer = null;
                audioManager = null;
            }
    
            private boolean allowSounds() {
                AudioManager audioManager = getAudioManager();
                return audioManager.getRingerMode() == AudioManager.RINGER_MODE_NORMAL
                        && audioManager.getMode() == AudioManager.MODE_NORMAL;
            }
    
            private AudioManager getAudioManager() {
                if (audioManager == null) {
                    audioManager = (AudioManager) getSystemService(Context.AUDIO_SERVICE);
                }
                return audioManager;
            }
    
            private void destroyPlayer() {
                try {
                    if (mediaPlayer != null) {
                        if (mediaPlayer.isPlaying()) {
                            mediaPlayer.stop();
                        }
                        mediaPlayer.release();
                    }
                } catch (Exception ignored) {
                }
            }
        }
    }

**Flutter/Dart** create a class (`main_app.dart`):

    import 'package:flutter/services.dart';
    
    class MainApp {
      static const MethodChannel _channel = MethodChannel('MainApp');
    
      static Future<String?> get platformVersion async {
        final String? version = await _channel.invokeMethod('getPlatformVersion');
        return version;
      }

      static Future<void> playSoundSuccess() async {
        await _channel.invokeMethod('playSoundSuccess');
      }
    
      static Future<void> playSoundError() async {
        await _channel.invokeMethod('playSoundError');
      }
    }

So you setup a method channel, create the players natively and then play those sounds by using the method channel.
