### ISSUE TITLE
Module 'audioplayers' not found on XCODE on Product archive

### ISSUE THREAD

**Issue by armanhadifatah** [luanpotter/audioplayers#359]
Hello 

Hello
I tested the app on ios it works fine but when i try to archive on xcode it give me this error and build will fail Module 'audioplayers' not found

my pubspec.yaml : 
`name: mohammad
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  intro_slider: ^2.2.2
  shared_preferences: ^0.5.3+1
  url_launcher: ^5.4.1
  device_info: ^0.4.1+1
  scoped_model: ^1.0.1
  wifi_info_plugin: ^1.0.6
  # connectivity: ^0.4.5+3
  flutter_udid: ^1.0.1
  http: ^0.12.0+2
  webview_flutter: ^0.3.18+1
  audioplayers: ^0.13.5
  flutter_launcher_icons: ^0.7.4
  flutter_svg: ^0.15.0

flutter_icons:
  image_path: "assets/icon/icon.jpeg"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/mohammad.png
    - assets/new-word.png
    - assets/open-book.png
    - assets/icon/icon.jpeg
    - assets/elearning.png
    - assets/messenger.png
    - assets/icon/facebook.svg
    - assets/icon/instagram.svg
    - assets/icon/snapchat.svg
    - assets/icon/youtube.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: bahij
      fonts:
       - asset: assets/bahij.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

flutter doctor
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.0)
[✓] Connected device (1 available)`

**Comment by rseibane** [comment]
Facing the same issue. It only happens trying to archive in XCode.

![image](https://user-images.githubusercontent.com/25082216/71421314-645e7900-267a-11ea-8df0-5f0a5277c91f.png)

- Flutter doctor:
![image](https://user-images.githubusercontent.com/25082216/71421377-bc957b00-267a-11ea-86b6-995d3532465a.png)
- Using `audioplayers: ^0.13.5`

**Comment by egv** [comment]
form me it archives ok in xcode, but fails in xcodebuild on CI

**Comment by shinayser** [comment]
Same problem here :'(

**Comment by Gadda27** [comment]
Same problem here, using audioplayers: ^0.14.0

**Comment by Gadda27** [comment]
This maybe occurs because you didn't open the workspace file: [See this issue](https://github.com/flutter/flutter/issues/41033`)

We got this error when running flutter build ios.

We solved it by using the latest stable Flutter version (1.12.13) and setting the minimum ios version to 11, which excludes all phones with an armv7 architecture (which doesn't seem to be supported by this plugin)

**Comment by luanpotter** [comment]
@Gadda27 does that require any changes to our committed config files? If so, could you please provide a PR to fix the issue?

**Comment by dark-chocolate** [comment]
@Gadda27 Didn't work for me. 

@luanpotter `flutter build ios` works just fine but when archiving the problem occurs, is there any solution, we aren't able to update the app on the AppStore.

**Comment by WxxShirley** [comment]
@dark-chocolate  have you solved this problem?
I've met the same problem, so desperate to find a solution....

**Comment by WxxShirley** [comment]
fix it，sorry

**Comment by armanhadifatah** [comment]
After a lot of search i found the solution which it was a very annoying.

For me the problem was when i opened the ios folder i was on Visual Studio Code and like you will do right click on it and choose open with Xcode but that is a problem because it will open wrong file you will think it is correct because at first there will be no error .

So the correct way to do it Go to ios folder and open .xcworkspace file.

Hope this will help others :)
