### ISSUE TITLE
Android: Should reconnect to platform audioplayer on app resume.

### ISSUE THREAD

**Issue by jeffmikels** [luanpotter/audioplayers#36]
On iOS, the audioplayer class can correctly reconnect to the platform audio player, but on Android, it does not.

To reproduce this issue:

- Launch an app with an audioplayer instance and start the playback.
- Use the "back" button to exit out of the app (background audio continues)
- Start the app again.

RESULT: A second audioplayer instance will be created and a second audio stream will begin. The only way to stop the previous audio player is to us the Android System methods to kill or fully dismiss the app.

**Comment by luanpotter** [comment]
This is a problem I also noticed when you do a Full restart in debug mode. I tried for a bit to listen to this events on android, exploring a lot of documentation for the Registrar object, but could not find a proper method to hook. Do you have any idea on how to fix this? We'd be glad if you could help us with a PR. :)

**Comment by jeffmikels** [comment]
I don't know Android development well enough to have a suggestion here. My workaround was to hook into the willPop method of the root navigator route and to stop playback whenever the app fully exits.

**Comment by pranavkapoorr** [comment]
Hey guy I have a similar issue that when I press the home button to send app in background(without terminating it) or lock screen, audio stops. On unlocking screen or on bring it to the front makes it play again. Any suggestions?

Thanks in advance :)

**Comment by erickzanardo** [comment]
Closing due inactivity
