### ISSUE TITLE
Not working on high end devices

### ISSUE THREAD

**Issue by amangautam1** [luanpotter/audioplayers#360]
I am facing a weird issue, the plugin is not working on some devices but working fine on low spec devices. Has anyone else faced such issue or am I doing something wrong?
P.S. : I have only tested on Android devices.

**Comment by amirpacolli03** [comment]
same!

**Comment by volgin** [comment]
I tested on both iPhone 6s and iPhone 11 - works fine on both.

**Comment by amirpacolli03** [comment]
It didn't work on Samsung galaxy a20 did you tested on samsung devices?

**Comment by KingIthumeleng** [comment]
I use a galaxy A20 to do my testing and it works fine, as well as on a simulator for an iPhone 11 Pro.

**Comment by luanpotter** [comment]
Closing this as it does not follow the issue template; if the issue still persists please open a new one following the guidelines.
