### ISSUE TITLE
SDK location not found.

### ISSUE THREAD

**Issue by tvqphong001** [luanpotter/audioplayers#363]
`A problem occurred configuring root project 'audioplayers'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.`

**Comment by babulpatel1309** [comment]
I'm facing a same issue.

**Comment by babulpatel1309** [comment]
Detailed error

> * What went wrong:
> A problem occurred configuring root project 'audioplayers'.
> > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Comment by babulpatel1309** [comment]
Hi @tvqphong001  in my case clipboard libarary was causing an issue. I just removed it and it worked.

**Comment by tvqphong001** [comment]
@babulpatel1309 tell me and show me some code the way to solved it, where you removed it?

**Comment by tvqphong001** [comment]
@babulpatel1309 but i need this libarary, have any way to fix it?

**Comment by FadiChaalab** [comment]
Just add ANDROID_HOME to your environment variables with the path to your SDK. For more information check YouTube.

**Comment by cyberpwnn** [comment]
It's defined in my local properties and in my path. Other plugins requiring this have no problems, and without audioplayers, it builds fine.

**Comment by tvqphong001** [comment]
Sorry it not your issue @luanpotter , because in my project have some lugins in compileSdkVersion below 28
