### ISSUE TITLE
Remove isLocal property

### ISSUE THREAD

**Issue by saeed-golshan** [luanpotter/audioplayers#364]
Please remove isLocal form play function and make analyze from address to found is local or remote address like if contain(http, ftp and vice versa). This make an easier api to use.

Best regards

**Comment by luanpotter** [comment]
That would be a good thing, would you be interesting in sending a PR? I think the field is only used in iOS btw, android is able to do that automatically.

**Comment by saeed-golshan** [comment]
I can't understand what you want
> would you be interesting in sending a PR?
but i think it can be easy to found that, just replace `isLocal ??= false;` at line 348 with `isLocal ??= url.startsWith('/');` because all the local url in Android and iOS start with `/`.

**Comment by luanpotter** [comment]
That makes sense, what I meant is, can you open a Pull Request with that change? I'll gladly merge it :)

**Comment by luanpotter** [comment]
One concern would be something like: `file://xxx` and also making sure it works with audiocache

**Comment by saeed-golshan** [comment]
ok got it!

**Comment by saeed-golshan** [comment]
I do some edit in library and example and check every section of app and work properly. I opened a pull request 👍
