### ISSUE TITLE
How to write the path of local audio playing? Is the audiolayers library really effective for local audio playback monitoring?

### ISSUE THREAD

**Issue by du666du** [luanpotter/audioplayers#366]
How to write the path of local audio playing? Is the audiolayers library really effective for local audio playback monitoring?

  void play(String path) async {
    audioPlayer = await audioCache.play(path);
  }
 audioPlayer.onPlayerStateChanged.listen((state) {
      print('onPlayerStateChanged');//invalid
 
    });

**Comment by erickzanardo** [comment]
There isn't enough information on this issue for us to act on. Please edit this, or open a new one and please follow the issue template.

Feel free to comment here and we can re open this eventually.
