### ISSUE TITLE
can't play multiple audios one by one with 2 seconds pause with text_to_speech_api plugin

### ISSUE THREAD

**Issue by div3791** [luanpotter/audioplayers#368]
I am trying to play multiple mp3 files with for loop. I need to pause player for 2 seconds after each audio files played. and when I stops player with player.stop(), player start playing next audio file after 2 seconds of wait. some times in android, it doesn't play but in console, 200 printed.

I am using text_to_speech_api for converting text to audio mp3 file. here is my code

```
Audio player = AudioPlayer();
TextToSpeechService service = TextToSpeechService();

for (int i = 0; i < textsList.length; i++) {
      File mp3;
      try {
        mp3 = await service.textToSpeech(
          text: textsList[i],
          languageCode: 'en-US',
          audioEncoding: 'MP3',
          voiceName: 'en-US-Wavenet-D',
        );
        await player.play(
          mp3.path,
          isLocal: true,
        );
        int duration = await player.getDuration();
        await Future.delayed(Duration(milliseconds: duration));
      } catch (e) {
        debugPrint(e);
        break;
      }
      await Future.delayed(Duration(milliseconds: 2000));
}
```

**Comment by luanpotter** [comment]
`await Future.delayed(Duration(milliseconds: duration));` is not a good way of waiting, use the onComplete handler isntead.
