### ISSUE TITLE
Audio player should stop sending messages to the flutter view when view is detached.

### ISSUE THREAD

**Issue by jeffmikels** [luanpotter/audioplayers#37]
Create an app

Instantiate an audioplayer.

Play a file.

Hit the back button on Android.

Audio continues to play, but the log gets spammed with messages that FlutterView.send cannot send messages to the detached view.

**Comment by luanpotter** [comment]
You are absolutely correct, thanks for your feedback. Would you like to help contributing with a PR? :)

**Comment by jeffmikels** [comment]
This looks doable to me. I might have time to look into it.

**Comment by erickzanardo** [comment]
Closing due inactivity
