### ISSUE TITLE
androidQ  Unsupported

### ISSUE THREAD

**Issue by Moyout** [luanpotter/audioplayers#371]
androidQ  Unsupported.
This is a very serious problem.
This is a very serious problem

**Comment by luanpotter** [comment]
If you think it's a serious problem (2x), please submit a PR to address it ;)

**Comment by Moyout** [comment]
> 如果您认为这是一个严重的问题（2x），请提交PR来解决;）

How to operate

**Comment by luanpotter** [comment]
Please open a properly described and comprehensible issue if you'd like.

**Comment by Moyout** [comment]
> Please open a properly described and comprehensible issue if you'd like.
In Android Q's mobile phone, if you use the audiolayers plug-in to play network audio, that prompt error : “E/MediaPlayerNative( 5165): error (1, -2147483648)
E/MediaPlayer( 5165): Error (1,-2147483648)”，
I hope you can solve the problem，thanks.
