### ISSUE TITLE
onAudioPositionChanged called every 1 second in IOS!

### ISSUE THREAD

**Issue by nawaf11** [luanpotter/audioplayers#373]
I read in the Docs that onAudioPositionChanged "Roughly fires every 200 milliseconds" which is true in android device it was good, But when I tried it in IOS Emulator it get called every 1 second (From the logs I check the timing), Which is slow for my need.

I hope that someone help me.

And Thanks the lib if really very good.

**Comment by Dotsung** [comment]
Is it a problem that onAudioPositionChanged is called every second?
In my case, iOS calls it in 200ms, but I get it only in one second and it don't recognize 'ms'.

In your case, I think it's an emulator problem.
Have you ever tested using a physical device? I think it's probably going to work.

**Comment by nawaf11** [comment]
I tried in real device but same ...

I found another solution ... using timer :

```
      Timer timer = Timer.periodic(Duration(milliseconds: 200), 
              (Timer t) => () async {
                var val = await audioPlayer.getCurrentPosition();
                onDurationChange(val);
              });
```

but i have to stop it when play is finish to save battery..

**Comment by volgin** [comment]
I just confirmed that iOs calls onAudioPositionChanged ~200ms, both in emulator and on a physical device.

**Comment by monnguyen2512** [comment]
@volgin I am testing with a virtual machine, it is only called once and the time is 2 times bigger.

**Comment by monnguyen2512** [comment]
@volgin - duration 1117715 - 18:37, The actual time is 09:18
https://www.youtube.com/watch?v=6PVMHrpVSrs

**Comment by volgin** [comment]
My app is using this plugin. We test every day on different emulators and physical devices. It returns correct duration and position, and our users can change position manually, if they want. It all works as expected.

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-12-06 at 11 35 14](https://user-images.githubusercontent.com/297748/72668994-825d9600-39fa-11ea-87cb-5ba8b988611f.png)

**Comment by volgin** [comment]
I think I know what's going on: onAudioPositionChanged is fired every 200ms, _but_ it returns the position in milliseconds rounded to a second. Thus, if you are using some kind of ChangeNotifier, this notifier will be fired only once per second - when the value of position actually changes.

**Comment by Kalzeroth** [comment]
Yes this is very much the problem, why is the event called every 200ms and returns a Duration, which clearly supports up to milliseconds but doesn't contain this level of precision ?

I wouldn't even expect that 200ms limitation out of the box, why such a limitation ?

**Comment by volgin** [comment]
This has been fixed in one of the PR a few days ago.

**Comment by luanpotter** [comment]
Thanks, @volgin !
