### ISSUE TITLE
E/AudioplayersPlugin( 5831): java.lang.NullPointerException

### ISSUE THREAD

**Issue by zhstar** [luanpotter/audioplayers#378]
E/AudioplayersPlugin( 5831): Unexpected error!
E/AudioplayersPlugin( 5831): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AudioplayersPlugin( 5831): 	at xyz.luan.audioplayers.WrappedSoundPool.start(WrappedSoundPool.java:255)
E/AudioplayersPlugin( 5831): 	at xyz.luan.audioplayers.WrappedSoundPool.play(WrappedSoundPool.java:99)
E/AudioplayersPlugin( 5831): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:69)
E/AudioplayersPlugin( 5831): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:44)
E/AudioplayersPlugin( 5831): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/AudioplayersPlugin( 5831): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/AudioplayersPlugin( 5831): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/AudioplayersPlugin( 5831): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AudioplayersPlugin( 5831): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/AudioplayersPlugin( 5831): 	at android.os.Looper.loop(Looper.java:136)
E/AudioplayersPlugin( 5831): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
E/AudioplayersPlugin( 5831): 	at java.lang.reflect.Method.invoke(Native Method)
E/AudioplayersPlugin( 5831): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
E/AudioplayersPlugin( 5831): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
E/MethodChannel#xyz.luan/audioplayers( 5831): Failed to handle method call

**Comment by luanpotter** [comment]
I believe this has been since fixed (just saw a similar issue). If it still occurs please open a new issue and make sure to use code blocks and follow the template.

**Comment by cavanlee** [comment]
If you play a remote audio source, can't init the player with this way: `AudioPlayer(mode: PlayerMode.LOW_LATENCY);`, the right is `AudioPlayer();`.
