### ISSUE TITLE
http stream url not working

### ISSUE THREAD

**Issue by Andrewngabriel** [luanpotter/audioplayers#383]
First of all, thanks for creating a great plugin with detailed docs!!

I am building an app which plays audio streams of different radio stations. The problem I ran into was that I noticed the plugin doesn't work when the stream URL is `http`. Is there an alternative approach to playing `http`? Should I download the stream into a local file then play it locally instead? If not, where in the plugin code would need to be modified in order to accommodate `http` URL streams. I can try to see if I can work on it and make a PR.

Thanks!

**Comment by Andrewngabriel** [comment]
After doing a bit of research, it seems like the issue happens due to a default restriction on Android not allowing traffic from http resources. The solution to this is adding `android:usesCleartextTraffic="true"` within your AndroidManifest.xml file located inside the main folder in Android. Path for it is `android/app/src/main/AndroidManifest.xml`

Here is an example of how how it should be added.
```
<?xml version="1.0" encoding="utf-8"?>
<manifest ...>
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        ...
        android:usesCleartextTraffic="true"
        ...>
        ...
    </application>
</manifest>
```

You can read more about the cause of this issue on [this stackoverflow question](https://stackoverflow.com/questions/37866619/cleartext-http-traffic-to-myserver-com-not-permitted-on-android-n-preview)

I think this should be added in the docs to better explain the issue and fix for it because I initially thought it was the plugin. I will create a PR shortly to update the docs as there are a few issues here about this problem.

**Comment by luanpotter** [comment]
Hi @Andrewngabriel , we actually have a section about this on iOS. On android, it was allowed but now the default changed. Can you please submit a PR updating our readme or FAQ file with that information? I'd be happy to merge it in :)
