### ISSUE TITLE
0.13.5 crash when I pop  from flutterVC quickly on ios.

### ISSUE THREAD

**Issue by XummerLilyDream** [luanpotter/audioplayers#387]
Sending a message before the FlutterEngine has been run.

**Comment by XummerLilyDream** [comment]
I try to post notification of name is AudioplayersPluginStop when flutter call native pop, the issue is solved.

**Comment by luoei** [comment]
I also encountered the same problem on 0.13.7

**Comment by luanpotter** [comment]
Since I just released 0.17.0, I believe this is a relic of the past. If the issue persists, please open a new issue following the issue template.
