### ISSUE TITLE
Proper way to parallelize AudioCache playbacks

### ISSUE THREAD

**Issue by emvaized** [luanpotter/audioplayers#388]
Hi, dear community!

In my Flutter game there is a grid of elements, every one of which plays a sound when being tapped. My issue is that when too many taps in a queue are being recognized, the whole app just freezes for a few seconds. 
When I disable playing sound on tap, this problem seems to doesn't occur.

So what is the proper way to parallelize AudioCache playbacks in such a cases?
Thanks.

**Comment by luanpotter** [comment]
Hi @emvaized , please take a look at my last comment [here](https://github.com/luanpotter/audioplayers/issues/398). You should be able to use a similar solution with audio_pool

**Comment by emvaized** [comment]
> Hi @emvaized , please take a look at my last comment [here](https://github.com/luanpotter/audioplayers/issues/398). You should be able to use a similar solution with audio_pool

Thank you so much! It seems like a perfect solution to the problem, which I puzzled over for a week -- no freezes yet.

I also will take a closer look to this Flame thing -- seems to be pretty useful for game development.
Thank you again!
