### ISSUE TITLE
There are multiple audio objects playing. If you control one of them, all the others are paused

### ISSUE THREAD

**Issue by tianshangwuyun** [luanpotter/audioplayers#395]
There are multiple audio objects playing. If you control one of them, all the others are paused

Is this the case that only one audioplayer object can be created by calling seturl

**Comment by tianshangwuyun** [comment]
I use eventbus to control whether other players pause in the right way

**Comment by luanpotter** [comment]
Please provide some code demonstrating the unexpected behaviour.

**Comment by erickzanardo** [comment]
Closing due inactivity.
