### ISSUE TITLE
`setPluginRegistrantCallback` is not implemented, so a conflict is happening on iOS devices when using with some other plugins (e.g. flutter_downloader)

### ISSUE THREAD

**Issue by AnasMasri** [luanpotter/audioplayers#397]
There is some conflict in my plugin registry, as I'm using

**flutter_downloader dependency: https://pub.dev/packages/flutter_downloader**

When I comment out the flutter downloader init method, everything works great.

The point is, in order to use Flutter downloader plugin, you have to register the registrant callback like this:
`FlutterDownloaderPlugin.setPluginRegistrantCallback(registerPlugins)`
and as mentioned in the documentation:

> In Flutter, in order to work in background isolate, plugins need to register with
> a special instance of FlutterEngine that serves for background execution only.
> Hence, all (and only) plugins that require background execution feature need to
> call registerWithRegistrar in this function.

But the method: `optional static func setPluginRegistrantCallback(_ callback: @escaping FlutterPluginRegistrantCallback) ` in protocol **FlutterPlugin : FlutterApplicationLifeCycleDelegate** _IS NOT_ overriden which is causing an exception on app opening if I tried to register set the registrant callback on **AudioplayerPlugin**.

Any ideas to fix?

**Comment by mucahitnezir** [comment]
Hello, I had the same problem. If you update the contents of ios / Runner / AppDelegete.swift as below, the problem will be fixed.

```
import UIKit
import Flutter
import flutter_downloader

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    FlutterDownloaderPlugin.setPluginRegistrantCallback(registerPlugins)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

private func registerPlugins(registry: FlutterPluginRegistry) {
    if (!registry.hasPlugin("FlutterDownloaderPlugin")) {
      FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin"))
    }
}
```

**Comment by AnasMasri** [comment]
I was really close to this solution, but moved to try setting registrants for Audioplayers lib! Thank you man it's working perfectly!
