### ISSUE TITLE
[Android] Stream not playing in the background

### ISSUE THREAD

**Issue by Andrewngabriel** [luanpotter/audioplayers#400]
I am currently using this plugin to play stream URLs and I noticed after locking the screen, the audio will play for about 5 - 10 minutes before it shuts off and the only way to get it to play again is to go to the app and restart the stream. I am experiencing this issue on Android but haven't tested it on iOS to see if it's happening there as well.

I am curious to know if there is a certain permission I need to add in the `AndroidManifest.xml` file in order to fix this issue or if something needs to be done on the native code level. I do have some basic knowledge about Android development so I can try to look into opening a PR with a possible fix but I am personally not even sure about what needs to be modified in order to fix this issue. Would appreciate any pointers or help on this.

Thanks!

**Comment by RinaldoNani** [comment]
Same problem here! 

The amazing thing: background music with audioplayers worked perfectly on older versions of Android.
But with version>=9 something extra should be done :| (other important apps play music in background without problems).

Help would be really appreciated!

**Comment by Andrewngabriel** [comment]
@RinaldoNani After doing a bit of research, it seems like there has to be a service registered on Android's side in order to allow for background activity to continue happening while the phone is locked or application not active. I am currently testing a plugin called [audio_service](https://pub.dev/packages/audio_service) which is built specifically to fix this issue and it can be wrapped around this plugin.

**Comment by RinaldoNani** [comment]
@Andrewngabriel thanks for your suggestion. 

It looks like the audio_service plugin is quite complex and may impact on the app we are developing, but if nothing else can be done, I'll give it a try.

In the docs of the audio_service plugin there is the iOS counterpart/section: but I never had any similar issues with iOS devices. Should I implement the services for iOS as well?

Thanks again!

**Comment by Andrewngabriel** [comment]
@RinaldoNani It shouldn't hurt to have it run on iOS as well. The setup on iOS is fairly simple. Worst case scenario if it causes issues, you can make it run only on Android.

**Comment by RinaldoNani** [comment]
@Andrewngabriel : we noticed that the problem is not necessarily related to screen locking! 
This is what happens: 
1) audio is started in our app normally, using audioplayers, in foreground;
2) we leave the device on the desk, without touching anything, with the audio still playing;
2a) (after a certain amount of time, the screen becomes black, but audio is still playing);
3) after 3 min and 30 seconds, the audio stops playing.

Do you think that the audio_service plugin will prevent this unwanted stopping occurrence? 

Thanks for your patience. :)

**Comment by Andrewngabriel** [comment]
@RinaldoNani Yes, this is exactly the same behavior I am experiencing. I am currently still testing it and having some trouble getting it correctly set up because you have to have a service & receiver set up on Android directory in order to keep a background service playing. Checkout my project where I used it here: https://github.com/Andrewngabriel/radio-player/tree/v0.1
Hope that helps. Let me know if you have other questions.

**Comment by thachnb85** [comment]
I got the same error, but we can reproduce easy by these steps:
I tested on iOS 13.3

1. create play list with 2 songs ( I used 2 URLs, play song remotely)
2. play the first song, seek to nearby the end of file
3. press lock to lock screen
4. now it will call play() in the state that device is locked -> not playing anything.
5. if I unlock the phone, now we have to call play() again to play that second file.

**Comment by arodriguezgb** [comment]
I am having the same issue, I play a stream and after lets say 8-14 minutes the audio stops.

Has anyone been able to resolve this ?

**Comment by alainseys** [comment]
the only solution i have found for the moment is by adding:

`Screen.keepOn(true);` this prevents the screen by going into locked state

**Comment by dev01mrrocco** [comment]
I believe that I was able to correct this problem by adding the permission below in `AndroidManifest.xml`" file. In my tests, this problem was present only on Android OS 8 or later and was not identified on iOS. So I decided to investigate the permissions and then, in my tests on android 10 and 11, this permission fixed the problem. Also check and let us know.

`<uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>`

**Comment by erickzanardo** [comment]
Like mentioned, to correctly play things in the backgorund, the audio_service package needs to be used.

**Comment by guilhermeagostinelli** [comment]
Would it be possible to user `audio_service` just for handling this specific situation of playing files in the background? Let's say, before audioplayer's `play` is called (e.g. a new song of a playlist needs to be started), detect if the app is running on background and, if so, trigger a function to allow calling audioplayer's `play` again?

Do you have any example @erickzanardo ?

**Comment by erickzanardo** [comment]
> Would it be possible to user `audio_service` just for handling this specific situation of playing files in the background? Let's say, before audioplayer's `play` is called (e.g. a new song of a playlist needs to be started), detect if the app is running on background and, if so, trigger a function to allow calling audioplayer's `play` again?
> 
> Do you have any example @erickzanardo ?

We have an article listed on our readme: https://github.com/bluefireteam/audioplayers#background-playing
