### ISSUE TITLE
An exception error in master channel

### ISSUE THREAD

**Issue by somaria** [luanpotter/audioplayers#402]
Anyone encountered this exception error related to Audioplayers in the master channel?

E/flutter ( 6228): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null)
E/flutter ( 6228): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 6228): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 6228): <asynchronous suspension>
E/flutter ( 6228): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 6228): #3      AudioPlayer._invokeMethod (package:audioplayers/audioplayers.dart:297:10)
E/flutter ( 6228): #4      AudioPlayer.play (package:audioplayers/audioplayers.dart:360:30)
E/flutter ( 6228): #5      _HomeState._remotePlay (package:alsospeak/home.dart:200:36)
E/flutter ( 6228): #6      _HomeState._playButtonIsPressed (package:alsospeak/home.dart:226:7)
E/flutter ( 6228): <asynchronous suspension>

**Comment by luanpotter** [comment]
I think https://github.com/luanpotter/audioplayers/pull/406 fixes this, could you please try again against master (not released)?

**Comment by somaria** [comment]
Updated with the commits in #406 but exception error remains.  Looks like it is an issue with flutter itself.
[https://github.com/flutter/flutter/issues/44774](url)

**Comment by luanpotter** [comment]
I assume this has been fixed in the later versions, as it works fine for me on all platforms. Please open a new issue if the problem still occurs.
