### ISSUE TITLE
The plugin is built using an older version of the Android plugin API

### ISSUE THREAD

**Issue by praveenb** [luanpotter/audioplayers#407]
Hi,
Im getting below message

The plugin `audioplayers` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.

Thank you

**Comment by luanpotter** [comment]
Thanks for the comment, @praveenb . Would you like to help by submitting a pr to update it?

**Comment by luanpotter** [comment]
I believe I migrated this.
