### ISSUE TITLE
File Buffering callback

### ISSUE THREAD

**Issue by ReaganRealones** [luanpotter/audioplayers#408]
How do I get a callback or listen to audio file buffering while playing a remote file such that I can customize and show the user a preloader if it's buffering more while playing already

**Comment by pobrejuanito** [comment]
Maybe show the preloader until you get a duration info? Maybe listen to AudioPlayerState value?

**Comment by ReaganRealones** [comment]
@pobrejuanito I get what you're saying and that's what I do but while it's playing and starts buffering again, the audio suddenly stops playing, however the audio player state is still PLAYING. In such a scenario, I want to display a preloaded to indicate to the user the audio is buffering.

**Comment by volgin** [comment]
just_audio plugin has two more player states: "connecting" and "buffering". "buffering" state is very valuable. Playback can stop at any moment if a player cannot load the file, but there is no way to alert the user if a player remains in the "playing" state. It is also very useful at the beginning of the playback: "paused -> buffering -> playing" sequence leads to a better UX.

**Comment by ReaganRealones** [comment]
@volgin ,that's another plugin right?

**Comment by ReaganRealones** [comment]
@volgin , Do you think it's better than Audioplayers plugin?

**Comment by pobrejuanito** [comment]
At quick glance, it appears an equivalent of "buffering" implementation in audioplayers compared to just_audio is implementing seekCompleteHandler and indicate buffering is done inside handler? I'm going to try that when I get a chance.

**Comment by erickzanardo** [comment]
Closing in favor of #361
