### ISSUE TITLE
[iOS] several methods and callbacks are returning inaccurate milliseconds

### ISSUE THREAD

**Issue by om-ha** [luanpotter/audioplayers#414]
### PR
This [PR](https://github.com/luanpotter/audioplayers/pull/421) fixes this issue.

### Issue
Several methods and callbacks are returning milliseconds rounded up to seconds, losing fraction of second.
- `updateDuration` callback (`audio.onDuration`, `onDurationChanged`)
- `getDuration` method
- `getCurrentPosition` method
- `onTimeInterval` callback (i.e. `audio.onCurrentPosition`,  `onAudioPositionChanged`)

### Example
For example if the real current position is `4200` milliseconds, then the reported position is `4000`.

**Comment by volgin** [comment]
This fix makes no difference.

**Comment by om-ha** [comment]
Right. `duration` parameter from the callback is still incorrect. but `getCurrentPosition` inside the callback's block is achieving a somehow correct value. Which I think is good enough as a temporary fix until PR is merged.

Essentially we're using `onAudioPositionChanged ` as a timer without using its inaccurate `duration parameter. With this timer we're fetching accurate position with `getCurrentPosition`

**Comment by volgin** [comment]
getCurrentPosition still returns a value rounded to seconds. I think you might have tried this fix _with_ your changes to the plugin's code.

**Comment by om-ha** [comment]
Rightly so, you're correct! Thanks for pointing this out.

**Comment by om-ha** [comment]
Closing since [PR](https://github.com/luanpotter/audioplayers/pull/421) is merged. Thanks for your participation volgin.
