### ISSUE TITLE
For iOS, can you play a file that is not in the asset folder?

### ISSUE THREAD

**Issue by somaria** [luanpotter/audioplayers#417]
For iOS, can you play a file that is not in the asset folder?

I tested it, and it seems that it can't be done for iOS.  For android, it is ok.

**Comment by volgin** [comment]
I play local files (not assets) all the time - even now, as I type this comment :)

**Comment by somaria** [comment]
I tested downloading the file to the device using [Flutter Cache Manager](https://pub.dev/packages/flutter_cache_manager) and played the file using a file path returned by Flutter Cache Manager and it works well for Android but for iOS, I just could not get it to work.  

I prefer playing a file cached rather than playing it remotely as there is a significant delay for iOS when playing a file remotely.  Sometimes I think flutter is more native in Android than in iOS.

There are only that few lines but yet I could not figure out what was needed for iOS and so I thought for iOS, you would have to use AudioCache to play a file downloaded to the device.  But I believe this should not be the case.

Here is the link for the test code and if you have any suggestions for me, please let me know.

[Flutter cache try](https://github.com/somaria/flutter_cache_try)

**Comment by volgin** [comment]
I am not familiar with AudioCache. I download files directly to the device, which gives me more control over what to do with these files: when to delete them, how much space they take, etc.

I know that Android and iOs players treat the local file paths differently.  If you don't pass "isLocal" parameter to audioplayers, it may still work on Android but not on iOs.

This is the relevant part from the plugin:

```
isLocal ??= url.startsWith("/") ||
        url.startsWith("file://") ||
        url.substring(1).startsWith(':\\');
```

Check what path you pass to the player.

**Comment by 0xDefalt** [comment]
Hello,
When i try to play a file that has been stored internally in IOS, and after investigating, it looks like the setUrl method does not work properly. I did not dig into objective-C code since i don't have skills for that. 
The path where my file is stored is like /var/mobile/Containers/Data/Application/992AF912-9085-497B-A916-422FE9E9D135/...

However it works like a charm when remote. Of course isLocal variable have been set to true.

Device : Iphone XR
IOS version : tested on 12.4 and 13

**Comment by 0xDefalt** [comment]
Ok guys,
After investigating i found why it doesn't worked : Looks like AVPlayer class in IOS don't like files without extension. Ensure also that the file codec is supported by AVPlayer too.

**Comment by luanpotter** [comment]
Seems this has been fixed.
