### ISSUE TITLE
await does not wait on audioCache.play()

### ISSUE THREAD

**Issue by Troto** [luanpotter/audioplayers#418]
Hi,
I have two sounds playing one after the other on audioplayers: ^0.14.0
```
await playWhistle();
await playWhistle(); 
```

```
Future<void> playWhistle() async {
    await audioCache.play(whistlePath, volume: 1);
  }
```

But I never hear both sounds I only ever hear one. And when I use some print statements I can see that the second line is being run immediately showing that await definitely doesn't wait for the sound to be completed. 

Is this a bug or am I doing something wrong here?

**Comment by volgin** [comment]
"await" simply waits for a call to be made to the OS side. It does not wait for a recording to finish playing.

You need to listen to a stream of state changes, and then play the second recording when the state changes to AudioPlayerState.COMPLETED.

Something like;

```
 _audioPlayerStateSubscription = _audioPlayer.onPlayerStateChanged
        .listen((_s) => _handleStateChange(_s), onError: (_msg) {
      print(_msg);
    });

void _handleStateChange(AudioPlayerState _s) {
      if (_s == AudioPlayerState.COMPLETED) {
         // previous recording finished playing.
      }
  }
```

**Comment by Troto** [comment]
OK that's not obvious. Thanks @volgin for your example code. 

There should probably be some explanation somewhere that the await isn't waiting for the sound to complete as that would be a fair assumption I think.

Could even be worth having a function like PlayCompletely that you could await with the state changes nicely tucked away.

**Comment by officer47p** [comment]
> OK that's not obvious. Thanks @volgin for your example code.
> 
> There should probably be some explanation somewhere that the await isn't waiting for the sound to complete as that would be a fair assumption I think.
> 
> Could even be worth having a function like PlayCompletely that you could await with the state changes nicely tucked away.

Exactly, that would be awesome if our future would resolve when the audio is finished playing.
