### ISSUE TITLE
Error in iOs code

### ISSUE THREAD

**Issue by volgin** [luanpotter/audioplayers#420]
`520: isLocal: (int) isLocal`

must be

`520: isLocal: (bool) isLocal`

I am waiting for a previous PR to be merged before I can submit a new one.

**Comment by luanpotter** [comment]
Hi @volgin ! What files is this in? IIRC I merged your PR about this? Or is this another thing still underway?

Thanks for all the help!

**Comment by volgin** [comment]
It's in AudioplayersPlugin.m.

This particular instance is fixed, but there are several more places where isLocal is an integer value, and then passed to the other methods as a boolean.

For example, isLocal is defined as intValue:

`211: int isLocal = [call.arguments[@"isLocal"]intValue];`

then passed to setUrl, where it is cast into a bool:

`432: isLocal: (bool) isLocal`

It's actually working, but it may not work as we want it. Any idea why it was originally an int value? Do you expect any side effects from making it consistently bool everywhere?

**Comment by luanpotter** [comment]
I have since converted the code to Swift and every instance of isLocal on iOS is now correctly typed as bool.
