### ISSUE TITLE
Unable to play remote file url in android

### ISSUE THREAD

**Issue by unlovedmilds** [luanpotter/audioplayers#423]
My main problem is I cannot figure out why is not playing even if I already have a url value of song.

 Future<int> _play() async {
    String url = "https://luan.xyz/files/audio/ambient_c_motion.mp3"; 
    final result = await _audioPlayer.play('$url'); 
    if (result == 1) setState(() => _audioPlayerState = AudioPlayerState.PLAYING);
    return result;
  }
The result return true and why is not playing ? :((
I tried your example, same problem. But local asset is work fine.

I already edit the manifest file.

 android:networkSecurityConfig="@xml/network_security_config"
 android:usesCleartextTraffic="true">

P.S : No error found in console

**Comment by luanpotter** [comment]
Does the example app work for you? It showcases examples of doing what you want.

**Comment by erickzanardo** [comment]
Closing due inactivity.
Remote files are working on the example app.
