### ISSUE TITLE
MacOS: No such module 'audioplayers'

### ISSUE THREAD

**Issue by 11ib** [luanpotter/audioplayers#426]
Hi all,

I'm unable to build for MacOS, but iOS and Android builds are successful.

I get the following error:
![Screen Shot 2020-02-13 at 3 59 19 PM](https://user-images.githubusercontent.com/10055660/74477765-e8aeca80-4e79-11ea-9822-89dae28b6cf4.png)

My pubspec.yaml file contains audioplayers: ^0.14.0, and I've verified that I'm opening/building the project in Xcode using the Runner.xcodeproj file generated from `flutter build macos`.

Any leads/tips?

Thanks!

**Comment by bhan** [comment]
Similar issue, can't build Android.

**Comment by VigneshPasupathy** [comment]
Do check if this answer helps you
https://stackoverflow.com/questions/29500227/getting-error-no-such-module-using-xcode-but-the-framework-is-there

The issue in my case was that i was running xcodeproj instead of xcworkspace

**Comment by luanpotter** [comment]
This is a configuration issue with your env/config/flutter and has nothing to do with audioplayers. I just tested the example app on macos and it worked.
