### ISSUE TITLE
[iOS] switch between speakers and earpiece

### ISSUE THREAD

**Issue by beerline** [luanpotter/audioplayers#429]
It will be great, if some one could help with implementation of Stream routing for iOS, as it implements for Android https://github.com/luanpotter/audioplayers/pull/424

**Comment by DoubleTime** [comment]
looking forward for this~

**Comment by RedHappyLlama** [comment]
Hello, 

Is there anyway to get an update on this? I've just started developing an app and this function is critical for my app. 

(I'm new to this world of app development so apologise for any naivety.)

Cheers!

**Comment by nmazidi** [comment]
Have implemented this in #515 and awaiting review.

**Comment by luanpotter** [comment]
#515 is merged.
