### ISSUE TITLE
Plugin dosen't resolve dependancies with flutter version higher than 0.5.x

### ISSUE THREAD

**Issue by NickoftheSouth** [luanpotter/audioplayers#43]
Looks like flutter has shifted their included version of dart to 2.1.0 which prevents the dependency for this plugin from begin resolved.  
  
I've reverted my flutter to 0.5.1 by running this call in the flutter directory;  
`git checkout v0.5.1`   
then running `flutter packages pub get`  
  
I can get the actual error message if it helps but you can reproduce this by calling `flutter upgrade` and then trying to build a project which depends on audioplayers.  
  
The flutter team also have an issue open here;
https://github.com/flutter/flutter/issues/20885
which describes the issue and a solution

**Comment by luanpotter** [comment]
Hi, @NickoftheSouth, thanks for your feedbac, and sorry for the delay! I took a look at the thread and it does seem that I need to perform some change in the pubspec, but I couldn't extract from the thread what exactly needs to be done.

So I updated my flutter and tried to build the example with success; flame seems to be working as well. What exactly is the version of flutter you are using that doesn't work? I'm on the dev channel:

```bash
[luan@ariel example]$ flutter --version
Flutter 0.9.1-pre.1 • channel dev • https://github.com/flutter/flutter.git
Framework • revision bf7c27095c (26 hours ago) • 2018-09-18 13:39:21 -0700
Engine • revision 9e315e6465
Tools • Dart 2.1.0-dev.4.0.flutter-050561fd82
[luan@ariel example]$ flutter pub get
Running "flutter packages get" in example...                 2.9s
[luan@ariel example]$ flutter build apk
Initializing gradle...                                       9.1s
Resolving dependencies...                                   63.1s
Running 'gradlew assembleRelease'...                        36.2s
Built build/app/outputs/apk/release/app-release.apk (8.3MB).
[luan@ariel example]$ 
```

Also, if you'd like to contribute with a PR, we will be glad to have it! ;)

**Comment by erickzanardo** [comment]
0.5.x is kind old at this point with flutter 1.0 released, and audioplayers seems to be working with the latests releases, I will be closing this issue, but if you get other problems @NickoftheSouth , feel free to open a new issue.
