### ISSUE TITLE
Getting null duration even after checking state

### ISSUE THREAD

**Issue by JSBmanD** [luanpotter/audioplayers#431]
I have code:
```
if(value.state == AudioPlayerState.PLAYING) {
					return value?.getDuration();
				} else {
					return 0;
				}
```

And it should work without exceptions but somehow it throws NullPointerException. How about adding null check on the paltform side to avoid such error?

Error:
```
PlatformException(error, Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.MediaPlayer.getDuration()' on a null object reference, null)
```

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
