### ISSUE TITLE
Seek in IOS makes some weird jumps when sliding while playing

### ISSUE THREAD

**Issue by noraibrahimi** [luanpotter/audioplayers#432]

**Comment by luanpotter** [comment]
Please add more details, your code, audio file, what exactly you are doing and the outcomes (expected and actual)

**Comment by Mamong** [comment]
when you slide, you should not sync the slider‘s value with the player's progress. when you release, you seek the audio to the aiming progress. But before your seeking is complete, you should not sync the slider with the  player's progress.🙂

**Comment by noraibrahimi** [comment]
> Please add more details, your code, audio file, what exactly you are doing and the outcomes (expected and actual)

@luanpotter It also happens when you run the example code from the package. I tried other variants but all have that jumping outcome. 

On IOS when u start to slide, it firstly goes to the desired place, then it jumps 2-5 seconds back and then again to the place it was. To see it better you have to slide faster.

**Comment by obnil** [comment]
![image](https://user-images.githubusercontent.com/30790621/76137617-23231600-607a-11ea-97de-b7fbd39eb443.png)
So do i, it jumps

**Comment by Mamong** [comment]
If you want to perform better seeking, you should do like below:

`Listener(
                    onPointerUp: (e){
                      _audioPlayer.seek(_position);
                    },
                    child: Slider(
                      onChangeStart: (v) {
                        print("onChangeStart");
                        _isSeeking = true;
                      },
                      onChanged: (v) {
                        print("onChanged");
                        if (_duration != null) {
                          final Position = v * _duration.inMilliseconds;
                          _position = Duration(milliseconds: Position.round());
                          setState(() {});
                        }
                      },
                      onChangeEnd: (v) {
                        print("onChangeEnd");
                        final Position = v * _duration.inMilliseconds;
                        _position = Duration(milliseconds: Position.round());
                      },
                      value: (_position != null &&
                          _duration != null &&
                          _position.inMilliseconds > 0 &&
                          _position.inMilliseconds < _duration.inMilliseconds)
                          ? _position.inMilliseconds / _duration.inMilliseconds
                          : 0.0,
                    ),
                  )`

and
`_playerSeekSubscription = _audioPlayer.onSeekComplete.listen((finished) {
      _isSeeking = !finished;
    });`

These codes make the player seek stably.

**Comment by obnil** [comment]
thank you, my problem is solved, i add `_isSeeking` to decide whether update ` _position` 

>         _positionSubscription =
>             _audioPlayer.onAudioPositionChanged.listen((position) {
>           if (!mounted) return;
>           if (_isSeeking) return;
>           setState(() {
>               _position = position;
