### ISSUE TITLE
android shoutcast stream delay

### ISSUE THREAD

**Issue by taekungkub** [luanpotter/audioplayers#433]
Shoutcast it delay on platform android
have to wait for 20 seconds for the song to play.
how to fix it

>  
      void playHomeFirst() async {
    if (playerStateHome == null) {
      await audioPlayerHome.play("http://##############");
      playerStateHome = _PlayerStateHome.playing;
      notifyListeners();
    }}
  
but ios is working
 
version audioplays ^0.14.0

**Comment by spy-reality** [comment]
Icecast also delay

**Comment by erickzanardo** [comment]
There isn't enough information on this issue for us to act on. Please edit this, or open a new one and please follow the issue template.

Feel free to comment here and we can re open this eventually.
