### ISSUE TITLE
Lockscreen audio controls and controls on bluetooth headphones not working

### ISSUE THREAD

**Issue by ozz-rjq** [luanpotter/audioplayers#434]
Plugin should support lockscreen controls and wireless (bluetooth) controls

**Comment by luanpotter** [comment]
Please describe why they are not working, what code you are using, what is the expected result and what you see instead.

**Comment by trt14** [comment]
> Please describe why they are not working, what code you are using, what is the expected result and what you see instead.

I'm also , I don't see any controls in lock screen ,it's working in background but i don't see any controls 

I'm using this plugin also

**Comment by ozz-rjq** [comment]
@luanpotter latest version is working great, thanks!
