### ISSUE TITLE
Supports AAC format

### ISSUE THREAD

**Issue by spy-reality** [luanpotter/audioplayers#441]
I want to configure the stream from Icecast (AAC format) but not play

**Comment by erickzanardo** [comment]
Right now we only support the files and streams with the formats supported by the native platforms, to see the list of the supported files, AAC is supported on both platforms, check our README https://github.com/luanpotter/audioplayers#supported-formats

**Comment by valerauko** [comment]
Hey @erickzanardo, that information no longer seems to be in the README.

Could you point me to the new location of those docs?

**Comment by Gustl22** [comment]
https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md#supported-formats--encodings
