### ISSUE TITLE
iOS 13, In background, loop is not working

### ISSUE THREAD

**Issue by UnCheon** [luanpotter/audioplayers#443]
in ios 13 and background,  setReleaseMode(ReleaseMode.LOOP).

When the app is in the background, the music plays only once.

**Comment by yudataguy** [comment]
Same problem, any suggestion on fix?

**Comment by dev01mrrocco** [comment]
I have the same problem. The setReleaseMode(ReleaseMode.LOOP) works very well on Android, but not on iOS, regardless of whether in the background or not. Any solution?

**Comment by erickzanardo** [comment]
Have you tried the advice we have on our traobleshooting?

https://github.com/luanpotter/audioplayers/blob/master/troubleshooting.md#ios

**Comment by erickzanardo** [comment]
Closing due inactivity, if there is more info that you can add to the issue, comment here and we can re open the issue.
