### ISSUE TITLE
Audio Not Playing From Remote URL

### ISSUE THREAD

**Issue by BashisthaSudeep** [luanpotter/audioplayers#450]
Hi, I'm developing an app for streaming online radios URLs. This plugin is very suitable for my requirements but I'm having problems playing the remote audio URLs.

This is my code: 
`playStation(url) async {`
`    AudioPlayer audioPlayer = new AudioPlayer(mode: PlayerMode.MEDIA_PLAYER);`
`    int result = await audioPlayer.play(url);`
`   print(result);`
`}`

This is my Debug Console: 
`V/MediaHTTPService(23782): MediaHTTPService(android.media.MediaHTTPService@2d1d92d): Cookies: null`
`V/MediaHTTPService(23782): makeHTTPConnection: CookieHandler (java.net.CookieManager@35c64b2) exists.`
`V/MediaHTTPService(23782): makeHTTPConnection(android.media.MediaHTTPService@2d1d92d): cookieHandler: java.net.CookieManager@35c64b2 Cookies: null`
`I/flutter (23782): 1`

The above output appears and after around 15 seconds, this error is thrown: 
`E/MediaPlayerNative(23782): error (1, -2147483648)`
`E/MediaPlayer(23782): Error (1,-2147483648)`
`E/MediaPlayerNative(23782): stop called in state 0, mPlayer(0xc830f620)`
`E/MediaPlayerNative(23782): error (-38, 0)`
`V/MediaPlayer(23782): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false`
`V/MediaPlayer(23782): cleanDrmObj: mDrmObj=null mDrmSessionId=null`
`V/MediaPlayer(23782): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false`
`V/MediaPlayer(23782): cleanDrmObj: mDrmObj=null mDrmSessionId=null`

Can't figure out what's going on!!
I'm using Android Emulator.

**Comment by BashisthaSudeep** [comment]
I managed to solve the issue by adding
`<application`
`        ...              `
`        android:usesCleartextTraffic="true"`
`        ...`
`    </application>`
on my AndroidManifest.xml

**Comment by jwhijazi** [comment]
I have the same problem as you mentioned.
I tried your solution but did'nt work for me.
I got a message:

 No Network Security Config specified, using platform default

I also tried to use my own security network xml file but not luck

any other solutions please.

**Comment by BashisthaSudeep** [comment]
Can you post the snippet from your manifest file where you have added your network XML file?

**Comment by jwhijazi** [comment]
@BashisthaSudeep 
Here is the code:

`<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">com.example.radio_player</domain>
    </domain-config>
</network-security-config>`


and here is the manifest.xml file:

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.radio_player">
    

         <uses-permission android:name="android.permission.WAKE_LOCK" />
         <uses-permission android:name="android.permission.INTERNET" />
         
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="radio_player"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>`

**Comment by BashisthaSudeep** [comment]
Is this issue exists with all the URLs or some specific ones? Are the URLs Http?

**Comment by jwhijazi** [comment]
@BashisthaSudeep 
The problem exists for http only.
After I run (flutter clean) command and run the app the again (http) urls worked for me.


Thanks for your help

**Comment by mapleyuan** [comment]
i just run flutter clean and it work fine.thx

**Comment by sandrhymend** [comment]
Hi, I'm having same issue playing the remote audio URLs on android 9.0 . I got same error but with https url :(

V/MediaHTTPService( 7231): MediaHTTPService(android.media.MediaHTTPService@3913297): Cookies: null
V/MediaHTTPService( 7231): makeHTTPConnection: CookieHandler (java.net.CookieManager@5ef5871) exists.
V/MediaHTTPService( 7231): makeHTTPConnection(android.media.MediaHTTPService@3913297): cookieHandler: java.net.CookieManager@5ef5871 Cookies: null
E/MediaPlayerNative( 7231): error (1, -2147483648)
E/MediaPlayer( 7231): Error (1,-2147483648)
E/MediaPlayerNative( 7231): stop called in state 0, mPlayer(0xd0d0dcc0)
E/MediaPlayerNative( 7231): error (-38, 0)

I tried this solution:
<application
...
android:usesCleartextTraffic="true"
...
</application>
on my AndroidManifest.xml
but neither work :(


Flutter version 1.19.0-2.0.pre.142 

My dependencies:
  http: ^0.12.1
  path_provider: ^1.6.9
  audioplayers: any
  provider: ^3.0.0+1

I'll appreciate any help. I am frustrating :(

**Comment by vikassaini075** [comment]
I am facing the same issue, found any solution?

**Comment by hamzeh1999** [comment]
I am facing the same issue, found any solution?

**Comment by deepanshi0** [comment]
tried xml solution and flutter clean too still facing same issue
