### ISSUE TITLE
Target of URI doesn't exist.

### ISSUE THREAD

**Issue by Nucl3arSn3k** [luanpotter/audioplayers#452]
Hello.
When I attempt to run the example app,I get a error from vscode.

`Target of URI doesn't exist: 'package:audioplayers/audioplayers_web.dart'.`

Are there any extra configuration steps that I need to take?

**Comment by nikhilmufc7** [comment]
Try this 
`Target of URI doesn't exist: 'package:audioplayers/audioplayers_web.dart.tmp'`

**Comment by nemoryoliver** [comment]
> tmp

doesn't work for me

**Comment by luanpotter** [comment]
That file clearly exists: https://github.com/luanpotter/audioplayers/blob/master/lib/audioplayers_web.dart
If this is still a problem please open a new issue following the mandatory issue template.
