### ISSUE TITLE
Android Can't play in background

### ISSUE THREAD

**Issue by JustMyLive** [luanpotter/audioplayers#453]
Do I need to setting anything else?
I use audioplayers ^0.14.1, android version 9, Not a problem with http.
Thank you very much

**Comment by trt14** [comment]
add this in android/app/src/main/AndroidManifest.xml.

<manifest ...>
    <uses-permission android:name="android.permission.INTERNET" /> // this line
    <application
        ...
        android:usesCleartextTraffic="true" // this line
        ...>
        ...
    </application>
</manifest>

**Comment by JustMyLive** [comment]
> add this in android/app/src/main/AndroidManifest.xml.
> 
> ```
> 
> <manifest ...>
>     <uses-permission android:name="android.permission.INTERNET" /> // this line
>     <application
>         ...
>          android:usesCleartextTraffic="true" // this line
>         ...>
>         ...
>     </application>
> </manifest>
> ```

Thanks, I have added it but still not working

**Comment by scullabyte** [comment]
@JustMyLive it is working for me in iOS on `0.13.5`, but not in `0.14` and above

**Comment by erickzanardo** [comment]
To correctly play in the background, you need to use [audio_service](https://pub.dev/packages/audio_service) package alongside audioplayers
