### ISSUE TITLE
How to deal with pause and resume while playing multiple audio files

### ISSUE THREAD

**Issue by esperaking81** [luanpotter/audioplayers#454]
Hello
In my app, am playing lot of letters with the help of the AudioCache file.
The way I do it is by creating a future delayed inside an iteration. The iteration loops through the list of strings a play at each position. I was wondering how I could deal with pausing and resuming in this use case. 

Thanks for any help.

**Comment by luanpotter** [comment]
You need to use multiple instances of AudioPlayer to play multiple audios at the same time. Then, you can control pause/resume/stop from each instance individually.
