### ISSUE TITLE
Audio playing background service

### ISSUE THREAD

**Issue by SivaGiga** [luanpotter/audioplayers#455]
I'm using audioplayers plugin to play local asset file. It's working fine with play, pause and stop. But when audio is playing if I get a call, it's not stopping, or if I move to another app without closing audio playing app, like YouTube and play video. Simultaneously it's also playing..how to handle this??

**Comment by trt14** [comment]
I'm Also I have this issue !

+1

**Comment by coder-Aayush** [comment]
Same issue

**Comment by scullabyte** [comment]
Background audio works in ios `0.13.5` for me. I think it stopped working in `.14.0`.

**Comment by alakhsingh** [comment]
@SivaGiga Are you testing your app in an Android smartphone?

**Comment by surpriso1997** [comment]
> Background audio works in ios `0.13.5` for me. I think it stopped working in `.14.0`.

I am going to use this library in upcoming project. Does this library support background audio play and show player in notifications and lock screen?

**Comment by alakhsingh** [comment]
@surpriso1997 Notification at the moment is only implemented for IOS. IOS stops the audio the moment you move out of the app although, in Android, the audio keeps playing but you do not have notifications to control the player.

**Comment by surpriso1997** [comment]
@alakhsingh do you know if those features are going to be implemented in the near future?

**Comment by alakhsingh** [comment]
@surpriso1997 Not sure. If you need it right now then you can  audio_service plugin which also supports audio playing in the background and android lock screen audio control too.

**Comment by rizerzero** [comment]
Same issue. This plugin is the most simple and stable I have tested, The only missing feature is the background service which is, unfortunately, a key feature.
Good luck.

**Comment by surpriso1997** [comment]
@alakhsingh There is issue in audio service plugin that there is compatibility issue between audio service and audioplayers.

**Comment by alakhsingh** [comment]
@surpriso1997 , I don't think compatibility is an issue. I did implement audioplayers plugin with audioservice plugin. It works perfectly fine. There are some audio player states which might be different but yeah, it does work.

**Comment by MasjZam** [comment]
Background audio in iOS works, you just need to enable the "Audio, AirPlay and Picture in Picture" background mode capability for your specified target - https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/creating_a_basic_video_player_ios_and_tvos/enabling_background_audio

**Comment by luanpotter** [comment]
We should probably add that link to our troubleshooting guide! Thanks @MasjZam for figuring it out

**Comment by luanpotter** [comment]
Closed by #709
