### ISSUE TITLE
android.os.NetworkOnMainThreadException 

### ISSUE THREAD

**Issue by NovytskaKateryna** [luanpotter/audioplayers#456]
In my project I use only one instance of audioplayer and user can switch between different audios. Audios are played from remote urls. When I try to play remote audio on Android I get this error very often, but audio will still be played. What could be the reason of this error and how can it influence audio player performance ? 

`I/MediaPlayer(11048): [HSM] stayAwake false uid: 10455, pid: 11048
W/System.err(11048): android.os.NetworkOnMainThreadException
W/System.err(11048): at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1315)
W/System.err(11048): at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:300)
W/System.err(11048): at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:741)
W/System.err(11048): at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
W/System.err(11048): at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
W/System.err(11048): at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
W/System.err(11048): at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:418)
W/System.err(11048): at com.android.okhttp.internal.Util.skipAll(Util.java:159)
W/System.err(11048): at com.android.okhttp.internal.Util.discard(Util.java:141)
W/System.err(11048): at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close(HttpConnection.java:435)
W/System.err(11048): at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:396)
W/System.err(11048): at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:384)
W/System.err(11048): at java.io.BufferedInputStream.close(BufferedInputStream.java:472)
W/System.err(11048): at android.media.MediaHTTPConnection.teardownConnection(MediaHTTPConnection.java:153)
W/System.err(11048): at android.media.MediaHTTPConnection.disconnect(MediaHTTPConnection.java:144)
W/System.err(11048): at android.media.IMediaHTTPConnection$Stub.onTransact(IMediaHTTPConnection.java:61)
W/System.err(11048): at android.os.Binder.execTransact(Binder.java:565)
W/System.err(11048): at android.media.MediaPlayer._reset(Native Method)
W/System.err(11048): at android.media.MediaPlayer.reset(MediaPlayer.java:1772)
W/System.err(11048): at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.java:49)
W/System.err(11048): at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:101)
W/System.err(11048): at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:44)
W/System.err(11048): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
W/System.err(11048): at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
W/System.err(11048): at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
W/System.err(11048): at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(11048): at android.os.MessageQueue.next(MessageQueue.java:356)
W/System.err(11048): at android.os.Looper.loop(Looper.java:138)
W/System.err(11048): at android.app.ActivityThread.main(ActivityThread.java:6523)
W/System.err(11048): at java.lang.reflect.Method.invoke(Native Method)
W/System.err(11048): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
W/System.err(11048): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)`

Android version: 7.0
Flutter version: 1.12.13+hotfix.8, stable

**Comment by erickzanardo** [comment]
There isn't enough information on this issue for us to act on. Please edit this, or open a new one and please follow the issue template.

Feel free to comment here and we can re open this eventually.

**Comment by josephmangmang** [comment]
Same issue here:

E/AudioplayersPlugin( 5215): Unexpected error!
E/AudioplayersPlugin( 5215): android.os.NetworkOnMainThreadException
E/AudioplayersPlugin( 5215): 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1605)
E/AudioplayersPlugin( 5215): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
E/AudioplayersPlugin( 5215): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
E/AudioplayersPlugin( 5215): 	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
E/AudioplayersPlugin( 5215): 	at com.android.okhttp.Dns$1.lookup(Dns.java:41)
E/AudioplayersPlugin( 5215): 	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
E/AudioplayersPlugin( 5215): 	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
E/AudioplayersPlugin( 5215): 	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
E/AudioplayersPlugin( 5215): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:192)
E/AudioplayersPlugin( 5215): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:144)
E/AudioplayersPlugin( 5215): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:106)
E/AudioplayersPlugin( 5215): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:400)
E/AudioplayersPlugin( 5215): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:333)
E/AudioplayersPlugin( 5215): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
E/AudioplayersPlugin( 5215): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
E/AudioplayersPlugin( 5215): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
E/AudioplayersPlugin( 5215): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
E/AudioplayersPlugin( 5215): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
E/AudioplayersPlugin( 5215): 	at java.net.URL.openStream(URL.java:1072)
E/AudioplayersPlugin( 5215): 	at xyz.luan.audioplayers.WrappedSoundPool.downloadUrl(WrappedSoundPool.kt:229)
E/AudioplayersPlugin( 5215): 	at xyz.luan.audioplayers.WrappedSoundPool.loadTempFileFromNetwork(WrappedSoundPool.kt:218)
E/AudioplayersPlugin( 5215): 	at xyz.luan.audioplayers.WrappedSoundPool.getAudioPath(WrappedSoundPool.kt:214)
E/AudioplayersPlugin( 5215): 	at xyz.luan.audioplayers.WrappedSoundPool.setUrl(WrappedSoundPool.kt:142)
E/AudioplayersPlugin( 5215): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:98)
E/AudioplayersPlugin( 5215): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:37)
E/AudioplayersPlugin( 5215): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AudioplayersPlugin( 5215): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AudioplayersPlugin( 5215): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AudioplayersPlugin( 5215): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AudioplayersPlugin( 5215): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AudioplayersPlugin( 5215): 	at android.os.Looper.loop(Looper.java:206)
E/AudioplayersPlugin( 5215): 	at android.app.ActivityThread.main(ActivityThread.java:8512)
E/AudioplayersPlugin( 5215): 	at java.lang.reflect.Method.invoke(Native Method)
E/AudioplayersPlugin( 5215): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AudioplayersPlugin( 5215): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)

**Comment by 28harishkumar** [comment]
+1

**Comment by pishguy** [comment]
@28harishkumar 
@NovytskaKateryna 

i have the same error, but after change and using this line code, my problem solved

```dart
_audioPlayer = AudioPlayer(mode: PlayerMode.MEDIA_PLAYER);
```

**Comment by alfawzaan** [comment]
This actually fixed my issue
