### ISSUE TITLE
Stop song when playing another one

### ISSUE THREAD

**Issue by kebsont** [luanpotter/audioplayers#458]
Hi, Thanks for this great plugin. It helps me a lot for my usage.

However, I know its purpose is for playing multiple songs simultaneously, but for my usage I want to stop the one playing before playing  another one.

When I look in the doc, I see there is **fixedPlayer** but is only available in **AudioCache**.

But I don't use AudioCache, I use **AudioPlayer** instead.

How could I do that please  with AudioPlayer?

**Comment by luanpotter** [comment]
If you are using a single instance of `AudioPlayer` it will behave as you expect. The way to play more than one at the same time is to create multiple instances of `AudioPlayer`. that is what audiocache does by default if you don't provide a `fixedPlayer`.

**Comment by kebsont** [comment]
I’m using a single instance of AudioPlayer but when I click on another song it doesn’t stop the first one. Both are playing akd it’s not what I want.

**Comment by kebsont** [comment]
Up @luanpotter 
Did you understand my question ?

**Comment by nikhilmufc7** [comment]
Hey @luanpotter , I am facing the same issue, any tips on how to stop the audio when another one plays? Thanks for this great plugin!

**Comment by alakhsingh** [comment]
Hi,
I think the issue here is that you are creating a new instance of AudioPlayer which will play the new audio irrespective of what was playing before. 
To solve this issue, I would suggest you re-use the same object to stop and or release the audio using the respective functions and play the next audio. 

It would help if you add a code snippet here.

Thanks,
Alakh

**Comment by kebsont** [comment]
Thanks @alakhsingh 

My play() function is:
`_play(String url) async {
    final playPosition = (_position != null &&
            _duration != null &&
            _position.inMilliseconds > 0 &&
            _position.inMilliseconds < _duration.inMilliseconds)
        ? _position
        : null;
    final result = await _audioPlayer.play(url,
        position: playPosition, volume: _sliderVolume);
    if (result == 1) setState(() => _playerState = PlayerState.playing);
    _audioPlayer.setPlaybackRate(playbackRate: 1.0);

    return result;
  }`

and here my stop() function

`Future<int> _stop() async {
    final result = await _audioPlayer.stop();

    if (result == 1) {
      setState(() {
        _playerState = PlayerState.paused;
        _position = Duration();
        // play_pause_icon = Icon(Icons.pause);
      });
    }
    return result;
  }`

As you can see, I use the same instance of _audioPlayer in the play and stop function.
So when I call play() again for another audio track, it should be stopped.

**Comment by alakhsingh** [comment]
As @luanpotter said, when you invoke play() method, it behaves as it should for me too. I was under the impression that I should probably stop the audio currently playing and start playing new audio. 

I did try your code and found it running perfectly alright. Although in your case, I do suspect that maybe you are creating the AudioPlayer object and the reference of the older object is lost which might also cause the issue. 

May I also see the way you are initializing and or reusing the object?

Thanks,
Alakh

**Comment by kk-boss** [comment]
I am too facing the same problem. When I create different instances. All audios play simultaneously. When I use a single Audioplayer then while playing one song, its affects other songs' wigets too, all the progress bar shows the progres of same song. How can solve this?

**Comment by kebsont** [comment]
@kk-boss 
I resolved it by not generating everytime a new PlayerId.
I fixed it in a unique string, so everytime I play an audio, it overwrites the last one played.

**Comment by luanpotter** [comment]
If you use AudioPlayer directly, a single instance will only play one sound at a time.
If you are using AudioCache, set the fixedPlayer to get that behavior (otherwise a new AudioPlayer will be generated each time).
This is working as intended.
