### ISSUE TITLE
loading progress when play(url) 

### ISSUE THREAD

**Issue by yase-hesham** [luanpotter/audioplayers#460]
Hello 
 thanks for this package , it's really helpful, however i want to be able to see loading file progress when playing a url , is there anyway to do it ?

**Comment by alakhsingh** [comment]
Hi,
Do you mean a slider or a seek bar? 
If so, there is a way to fo that. Flutter natively provides Slider class which can be used. 
```
Slider(
                  max: totalDuration, //total duration of the audio which you can get it from AudioPlayer class
                  min: 0,
                  value: position, //current position also which you can get it from AudioPlayer class
                  activeColor: Colors.teal[400],
                  inactiveColor: Colors.grey,
                  onChanged: (value) {
                    seek(value.toInt());
                  },
                )
```
You can listen to these events by `onAudioPositionChanged` and `onDurationChanged` for max and value respectively.
Thanks,
Alakh

**Comment by alakhsingh** [comment]
In case you meant that you wanted to display a loading bar to the user until the song has started to play (as it takes few seconds to load from the URL), then you can use `AudioPlayerState` and subscribe to it by `onPlayerStateChanged` function and check if the state has changed to` AudioPlayerState.Playing`.

**Comment by yase-hesham** [comment]
thanks , but there is no way to know the progress of loading right ?

**Comment by alakhsingh** [comment]
Yeah, I guess so, I don't see any code related to that in the plugin.

**Comment by yase-hesham** [comment]
aha thanks so much @alakhsingh  ^^

**Comment by kepuza** [comment]
you can do it like that for loading 

`_isPlaying && _position == null ? CircularProgressIndicator() : SizedBox()`
