### ISSUE TITLE
I can't play .pcm file

### ISSUE THREAD

**Issue by SimonsLeung** [luanpotter/audioplayers#461]
I can't play .pcm file, 

format
SAMPLE_RATE = 16000;
CHANNEL = AudioFormat.CHANNEL_OUT_MONO;
AUDIO_FORMAT = AudioFormat.ENCODING_PCM_16BIT

support like this?

**Comment by luanpotter** [comment]
Please check [our readme](https://github.com/luanpotter/audioplayers#supported-formats) for a comprehensive list of all supported formats per platform.
