### ISSUE TITLE
flutter packages get on version 0.14.0 or 0.14.1 creates invalid entry in generated_plugin_registrant.dart

### ISSUE THREAD

**Issue by nohli** [luanpotter/audioplayers#462]
```
import 'package:audioplayers/audioplayers_web.dart';

AudioplayersPlugin.registerWith(registry.registrarFor(AudioplayersPlugin));
```

Because of commit https://github.com/luanpotter/audioplayers/commit/22c4121d31d26efc166a30de22d1a14bcbf0dda5 the import needs to be:

```
import 'package:audioplayers/audioplayers_web.dart.tmp';
```

but `flutter anaylze` or `flutter packages get` always brings back the invalid import

**Comment by abegehr** [comment]
I'm experiencing this aswell. Might be related to this: https://github.com/dart-lang/pub-dev/issues/3277
Also, this commit: https://github.com/luanpotter/audioplayers/commit/22c4121d31d26efc166a30de22d1a14bcbf0dda5

**Comment by luanpotter** [comment]
Sorry, my bad. Web support is not supported by pub so I temporarily removed it.

I thought by changing the file name to something not dart pub would not complain.

I will take a deeper look. (curiously it worked for me though)

**Comment by luanpotter** [comment]
This should fix it, I believe https://github.com/luanpotter/audioplayers/pull/464

**Comment by nohli** [comment]
Thanks!

Can I help (I can't review the PR I guess)?

**Comment by luanpotter** [comment]
you sure can :) (I can bypass github rules for merges, I was just waiting for the tests)

**Comment by luanpotter** [comment]
@nohli I released 0.14.2, can you please confirm it's working?

**Comment by nohli** [comment]
@luanpotter yes, it removes everything regarding audioplayers from generated_plugin_registrant.dart

thanks!!

**Comment by luanpotter** [comment]
(replied to you on #425)
