### ISSUE TITLE
go-flutter-desktop example not working

### ISSUE THREAD

**Issue by Nailik** [luanpotter/audioplayers#463]
Hello,
i wanted to try the go-flutter-desktop branch. However when i make `hover run` it's not working because it says:
`
go: github.com/go-flutter-desktop/plugins/audioplayers@v0.1.0: parsing Users\erick\projects\go-flutter-desktop\plugins\audioplayers\go.mod: open C:\Users\username\Documents\Projects\flutter_audioplayers\example\go\Users\erick\projects\go-flutter-desktop\plugins\audioplayers\go.mod: Das System kann den angegebenen Pfad nicht finden.
`
(System cannot find path).

This is probably because in `go.mod` there is:
`replace github.com/go-flutter-desktop/plugins/audioplayers => /Users/erick/projects/go-flutter-desktop/plugins/audioplayers`

Where do i find the plugin directory withing this github repository?
Can you maybe help me @erickzanardo as you commited the branch?

**Comment by luanpotter** [comment]
I think this was a WIP from @erickzanardo and @raonifn. Not sure what is the current status.

(btw macOS is supported natively on master for a few versions now, but we are very open to other implementations to support all desktop platforms).

**Comment by Nailik** [comment]
Ahh too bad ... since there's no plugin to play audio files on windows desktop. My c++ knowledge is not good enought to do this (i'm still stuck in trying to send data to a usb device).
Maybe when they bring C# as a second option to flutter desktop i will have a look into it.

**Comment by luanpotter** [comment]
@erickzanardo @raonifn any updates in this? should we :axe: the project in favour of the new official flutter desktop embeddings?

**Comment by erickzanardo** [comment]
@luanpotter yes, we never finished that example and I don't think we plan on continuing, I will remove the branch.
