### ISSUE TITLE
Can't play audio/accp URL

### ISSUE THREAD

**Issue by jwhijazi** [luanpotter/audioplayers#466]
I used to play audio url of type (audio/accp) like this [http://yayin.netradyom.com:8050/PARKFM] using version 13.7 on android 8.

Now when upgrade my emulator to android 9 and using version 14.1 the App stopped playing this type of audio.
Can anyone help me in this issue.

**Comment by erickzanardo** [comment]
Android 9 does not accepts http by default, it must be https url, or you must enable http on your app.

**Comment by jwhijazi** [comment]
it's not about http, coz i solved this issue and all non secure http urls are working.
The problem with the audio type (format) audio/accp.

**Comment by erickzanardo** [comment]
Have you checked if that format is supported by Android?

Here we have links that list the supported file formats on which platforms https://github.com/luanpotter/audioplayers#supported-formats

All the files supported are provided by the native platforms, as audioplayers uses directly the native platform features and don't implement any file support itself.

**Comment by jwhijazi** [comment]
@erickzanardo 
I can see the type acc is supported by android.
The type I'm talking about is audio/accp.

I'm confused because in older version of my app (Android 8 with AudioPlayers 13.7) this type of audio used to work without any problem.
Just when I upgraded the emulator to (Android 9) with AudioPlayers 14.1 this type stopped working.

Can you try a small App using the same url suggested above to check.

**Comment by erickzanardo** [comment]
it is weird that it worked on older Android version and AP version, I looked on the table of supported files by Android, and I could not find that format you are trying to use.

I can't test right now, but I suggest you try change the file to use one that is on that list.

@luanpotter I will re open this issue, and leave it up to you to decide if we should support this file format or not.

**Comment by jwhijazi** [comment]
@erickzanardo 
Thanks for your help... Waiting your test results.

Regarding changing the file, actually the url is a radio station so it's hard to change it.

**Comment by HetalGohil** [comment]
are u able to solve the issue?..because i m facing same issue my url is also this type and it is not playing

**Comment by jwhijazi** [comment]
@HetalGohil 
I tried the latest version 15.1 but the problem is not solved.

@erickzanardo 
Did you test it to find any problem?

**Comment by HetalGohil** [comment]
no not playing with accp url ..i m unable to get duration and not playing..sound not coming but player state is playing

**Comment by jwhijazi** [comment]
@HetalGohil 
Yeah, it returns 1 with status (playing), but the duration is not changed.

I have a radio stations app and not all stations are working due to this problem :(

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
