### ISSUE TITLE
can someone help me get code for audio play from local assets only? 

### ISSUE THREAD

**Issue by TenzinProgrammer** [luanpotter/audioplayers#469]
hello programmers,
can anyone please help me play audio from local assets only? i am confused with this giant code. i am a beginner. can anyone help me? i will be grateful. my email is (tenzinprogrammer@gmail.com)
thanks
Tenzin

**Comment by faizanmohiuddin482** [comment]
> hello programmers,
> can anyone please help me play audio from local assets only? i am confused with this giant code. i am a beginner. can anyone help me? i will be grateful. my email is ([tenzinprogrammer@gmail.com](mailto:tenzinprogrammer@gmail.com))
> thanks
> Tenzin

// import in the begining of the file
    import 'package:audioplayers/audio_cache.dart';

//Add the dependencies in pubspec.yaml file
dependencies:
  audioplayers: ^0.14.2

// create a directory in flutter project as **assets** and drop the audio file in that folder
//add the files to the pubspec.yaml file
flutter:
  assets:
   - assets/example.mp3

**Comment by TenzinProgrammer** [comment]
Thank you for your time. I think i managed to do it myself. I added play, pause and stop button by invoking methods in the same class. Because of the plugin. Seems working without any problem. Thank you.

**Comment by rmtmckenzie** [comment]
@TenzinProgrammer If you have it working, why don't you close this issue.

**Comment by luanpotter** [comment]
I shall.
