### ISSUE TITLE
MissingPluginException(No implementation found for method setNotification...)

### ISSUE THREAD

**Issue by Veerse** [luanpotter/audioplayers#473]
Hello,
Thanks for the great package. 

I'm facing a very tedious issue. I'm getting a MissingPluginException with this very simple code 

```
void play() async {
    await audioPlayer.play("https://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_1MG.mp3", isLocal: false).then((v){
      print('Playing $v');
    }).catchError((e){
      print('error $e');
    });
    audioPlayer.setNotification(
      title: 'Test audio',
      artist: 'The artist',
      albumTitle: 'The album',
      imageUrl: 'https://i.picsum.photos/id/59/200/200.jpg'
    ).then((v){
      print('Notification ok');
    }).catchError((e){
      print('error with setNotification $e');
    });
  }
```

`I/flutter ( 3921): error with setNotification MissingPluginException(No implementation found for method setNotification on channel xyz.luan/audioplayers)`

I've tried to flutter clean & flutter pub get and I've also tried older version of the plugin, unsuccessfully

I've had a similar issue with the method Play(), uninstalling and reinstalling the application fixed the problem, but not in this case..

**Comment by alakhsingh** [comment]
Which emulator are you using? because from the code in audioplayers.dart
`  /// Sets the notification bar for lock screen and notification area in iOS for now.
  ///
  /// Specify atleast title
  Future<dynamic> setNotification(
      {String title,
      String albumTitle,
      String artist,
      String imageUrl,
      Duration forwardSkipInterval,
      Duration backwardSkipInterval,
      Duration duration,
      Duration elapsedTime}) {
    return _invokeMethod('setNotification', {
      'title': title ?? '',
      'albumTitle': albumTitle ?? '',
      'artist': artist ?? '',
      'imageUrl': imageUrl ?? '',
      'forwardSkipInterval': forwardSkipInterval?.inSeconds ?? 30,
      'backwardSkipInterval': backwardSkipInterval?.inSeconds ?? 30,
      'duration': duration?.inSeconds ?? 0,
      'elapsedTime': elapsedTime?.inSeconds ?? 0
    });
  }` 
It says that, it has only been implemented for IOS for now. So, if you are using an Android emulator, you might probably get this issue. I could not verify if this works in IOS as emulator doesn't show full control center.

**Comment by Veerse** [comment]
Yes you are write, I didn't read the comment until the end sorry.

I've tested on iOS, it's works fine. So is there any way to have multimedia control on the Android Notification Center ?

**Comment by alakhsingh** [comment]
You can probably create a custom notification with flutter_local_notifications for now

**Comment by Veerse** [comment]
Yep. That's what I tried to do. But an other issue came up, when you make a sticky notification (as it's usually done with audio players like Spotify, Deezer...) and you kill your application, the sticky notification doesn't go. It stays forever

It seems that there is no way in Flutter to detect when the application is killed by user. Anyway, it is out of the scope of this plugin.

**Comment by darwin-morocho** [comment]
After check the dart code and the native code  `startHeadlessService` and `setNotification`  for now is only supported for iOS.  Please add support to Android for this amazing plugin.

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
