### ISSUE TITLE
don't add 'assets/' to the front of paths

### ISSUE THREAD

**Issue by lukepighetti** [luanpotter/audioplayers#480]
Most packages in Flutter do not automatically add the "assets" folder to the beginning of paths. We have to filter this out from our code because `audioplayers` does this automatically. It also means that `audioplayers` files MUST be in a folder named `assets` which is not guaranteed.

**Comment by lukepighetti** [comment]
This is how I have to use audio players and have it interchange with other sound services

```dart
class SoundService {
  SoundService() {
    player.loadAll(AppConfig.toneOptions.values.withoutAssetOnFront);
  }

  static final player = AudioCache();

  void play(String path) async {
    player.play(path.withoutAssetOnFront, mode: PlayerMode.LOW_LATENCY);
  }
}

extension on Iterable<String> {
  List<String> get withoutAssetOnFront =>
      this.map((e) => e.withoutAssetOnFront).toList();
}

extension on String {
  String get withoutAssetOnFront => this.replaceFirst("assets/", "");
}

```

**Comment by lukepighetti** [comment]
This is especially problematic when you are creating a package with sounds to be consumed by a flutter web project and `audioplayers` insists on adding an extra `assets/` path to the front. It ends up being `assets/assets/foo.wav` if you provide `audioplayers` with `foo.wav`

**Comment by erickzanardo** [comment]
This is fixed on newer versions.
