### ISSUE TITLE
100ms cold start delay even with cache

### ISSUE THREAD

**Issue by lukepighetti** [luanpotter/audioplayers#481]
On iOS I am seeing about a 100ms first play delay even if we cache the sounds. The solution here is to play all of our sounds with no volume before we need them. There must be a better way to improve this first play delay without the developer who is consuming `audioplayers` from performing this workaround.

```dart
class SoundService {
  SoundService() {
    final sounds = AppConfig.toneOptions.values;

    /// Cache them
    _player.loadAll(sounds);

    /// Play them each once with no volume to get them on deck
    /// this improves first time play latency by about 100ms.
    sounds.forEach((e) {
      _player.play(e, volume: 0.0);
    });
  }

  /// Our player instance
  static final _player = AudioCache();

  /// Play a sound path
  void play(String path) async {
    _player.play(path, mode: PlayerMode.LOW_LATENCY);
  }
}
```

**Comment by Skuallpa** [comment]
I'm experimenting same behaviour on an iPad Air 1rst generation. First play often takes around 100ms.

I also tried to use the AudioPlayer interface instead of the AudioCache, but same behaviour.

**Comment by ddonze** [comment]
Ive definitely had this issue. It almost disappears in newer hardware but not entirely (my iPhone 11 has a nearly unnoticeable delay on the first cold play but my older iPhone SE has a really bad delay)

I have a branch that addresses this problem by changing the underlying iOS implementation. However it’s still partially incomplete. Play, stop, loop, and change volume all work for local files, but that’s all that I’ve really tested. I haven’t tested remote files and a lot of the callbacks (like checking the progress) Check it out here: [iOS Branch](https://github.com/ddonze/audioplayers/tree/ios-low-latency)

**Comment by Skuallpa** [comment]
@ddonze I have tested the "ios-low-latency" branch, but the sound is not always playing, kind of randomly. I don't have any error message in the console.
Below is the code I'm using. 
(I load first the audio files with audio cache and then play them with the player as I experimented a better performance this way compare to playing the audio with the AudioCache interface directly).

Here is the code I was using:

``` dart
const String AUDIO_FILE_SOUND_BTN_TAPPED = 'audio/btn.mp3';

class AudioCachePlayer {
  AudioCache _audioCache;
  AudioPlayer _audioPlayer;

  String _audioFileBtnTappedFilePath;

  static final _instance = AudioCachePlayer._internal();

  factory AudioCachePlayer() => _instance;

  AudioCachePlayer._internal() {
    _audioCache = AudioCache();

    _audioPlayer = AudioPlayer(mode: PlayerMode.LOW_LATENCY);

    // Stops audio playback but keep all resources intact. Use this if you intend to play again later.
    _audioPlayer.setReleaseMode(ReleaseMode.STOP);

    // Load the file in cache
    _audioCache.load(AUDIO_FILE_SOUND_BTN_TAPPED).then((f) {
      _audioFileBtnTappedFilePath = f.path;
    });
  }

  playSoundBtnTapped() async {
    if (_audioFileBtnTappedFilePath.isNotEmpty) {
      await _audioPlayer.play(_audioFileBtnTappedFilePath,
          isLocal: true, stayAwake: true);
    }
  }
}
```

So for now I'm back to master branch and used the trick proposed by @lukepighetti (to play once the file with volume set to 0 once loaded).

```dart
// We play the sounds once loaded as it help to reduce a 100ms cold start delay
_audioCache.load(AUDIO_FILE_SOUND_BTN_TAPPED).then((f) {
  _audioFileBtnTappedFilePath = f.path;
  _audioPlayer.play(_audioFileBtnTappedFilePath,
      volume: 0.0, stayAwake: true);
});
```

**Comment by BaranMichal25** [comment]
on Android there is this intriguing [delay](https://github.com/luanpotter/audioplayers/blob/master/android/src/main/java/xyz/luan/audioplayers/AudioplayersPlugin.java#L258) in library:
```dart
if (nonePlaying) {
    audioplayersPlugin.stopPositionUpdates();
} else {
    handler.postDelayed(this, 200);
}
```

**Comment by jamie1192** [comment]
I've had (and still have) this issue also.

No matter I try, there's always an initial delay playing from cache and some plays don't even trigger if fired in quick succession to the previous, with no errors being logged to the console.

Is there any update on this?

**Comment by erickzanardo** [comment]
This issue is outdated or uses a very old version of the project, could you please test if this happens on newer versions? And in case that this still happens, open a new issue?

**Comment by cto-leaps** [comment]
Hey, sorry to reopen this, but I do have the issue myself on recent (12 Pro Max iPhone) and using the latest version of the library.
I preload all the sounds, I even check if they are preloaded before playing (which they are), but at app start, the very first sound ALWAYS has a 100-200ms delay that is very noticeable...

**Comment by lukepighetti** [comment]
I had an issue the other day where playing the same sound over and over eventually it was getting a 10 second (!!!!) delay

**Comment by Erhannis** [comment]
I've been having a ~10 second delay on first play of an audio file, even with player.setSource before .resume.  Yeah, just tested it; called .setSource, waited 10 seconds, then .resume, and 12 seconds elapsed before it started playing.  seek(0) and resume then only incurred a ~40ms delay.
