### ISSUE TITLE
Audio Stream STOPPED without finishing in some devices, like MI Note 6, Samung A10, A30, without any error

### ISSUE THREAD

**Issue by jangidakhilesh** [luanpotter/audioplayers#484]
Audio Stream STOPPED without finishing in some devices, like MI Note 6, Samung A10, A30, without any error

**Comment by jangidakhilesh** [comment]
got this info error: 

### MediaPlayer: info/warning (703, 22304)

**Comment by handofthecode** [comment]
Same issue here.

**Comment by arodriguezgb** [comment]
I am also having this issue. Pixel 4 XL,  Galaxy S9. 

When the app is in the background on Android the stream stops at about 10-14 minutes.

**Comment by jangidakhilesh** [comment]
Is there anyone who can help out from this issue ?

**Comment by MardariG** [comment]
I thought the problem was with this library, but actually it was caused by other package whitch listened for network change, and when device entered sleep mode it triggers offline (it's a bug). Just try to comment player stop() function, and see if it will actually stop then.

**Comment by DenisPushkarev** [comment]
@jangidakhilesh is it happening when app in background mode?

**Comment by peleteiro-dev** [comment]
Same issue on Galaxy S7/8/10, Huawei P20 Pro and LG G6 at least ...
Streaming stops randomly, sometimes in minutes, sometimes takes hours to happen

**Comment by peleteiro-dev** [comment]
does anybody have a solution for this, please ?

**Comment by timoknapp** [comment]
I also the exact same problem, when playing streams longer than 40 minutes. Basically right after 40 minutes it stops playing with a similar error like @peleteiro-dev described:

```
W/MediaHTTPConnection( 3979): readAt 36823797 / 7435 => java.net.ProtocolException: unexpected end of stream
E/MediaPlayerNative( 3979): error (1, -1010)
E/MediaPlayer( 3979): Error (1,-1010)
E/MediaPlayerNative( 3979): stop called in state 0, mPlayer(0xd0464980)
E/MediaPlayerNative( 3979): error (-38, 0)
V/MediaPlayer( 3979): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3979): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 3979): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3979): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaHTTPService( 3979): MediaHTTPService(android.media.MediaHTTPService@b2d3644): Cookies: null
V/MediaHTTPService( 3979): makeHTTPConnection: CookieHandler (java.net.CookieManager@bd7a014) exists.
V/MediaHTTPService( 3979): makeHTTPConnection(android.media.MediaHTTPService@b2d3644): cookieHandler: java.net.CookieManager@bd7a014 Cookies: null
V/MediaPlayer( 3979): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3979): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaHTTPService( 3979): MediaHTTPService(android.media.MediaHTTPService@b144062): Cookies: null
V/MediaHTTPService( 3979): makeHTTPConnection: CookieHandler (java.net.CookieManager@bd7a014) exists.
V/MediaHTTPService( 3979): makeHTTPConnection(android.media.MediaHTTPService@b144062): cookieHandler: java.net.CookieManager@bd7a014 Cookies: null
```

**Comment by rvachev** [comment]
guys, help me please. Audio stream stops when I scroll down and audio player is over screen height. Do you have any solutions?

**Comment by erickzanardo** [comment]
There isn't enough information on this issue for us to act on. Please edit this, or open a new one and please follow the issue template.

Feel free to comment here and we can re open this eventually.
