### ISSUE TITLE
flutter: Fatal Error: Callback lookup failed! - It is still happening on iOS when using PlayerMode.LOW_LATENCY

### ISSUE THREAD

**Issue by animeshjain** [luanpotter/audioplayers#490]
I think this line is to blame.

https://github.com/luanpotter/audioplayers/blob/fc9a66c6664eebf60101049d02ea23af6918965c/lib/audioplayers.dart#L295

I feel it should be 

```
if (defaultTargetPlatform == TargetPlatform.iOS && mode == PlayerMode.MEDIA_PLAYER) {
```

This fixes the error for me.

**Comment by alectogeek** [comment]
@animeshjain  Is this fix works well after some time?

**Comment by animeshjain** [comment]
> @animeshjain Is this fix working well after some time?

It seems to be working OK. Are you experiencing a crash/app not responding after some time?

**Comment by alectogeek** [comment]
@animeshjain Can't say definitely. Sometimes my app crashes, but sometimes it works well despite many errors in console

**Comment by alectogeek** [comment]
Moreover, I tried your workaround and I still can see errors in the console

**Comment by animeshjain** [comment]
@alectogeek can you publish a small repo which can reproduce what you are seeing? Hard to say for me otherwise, I haven't delved too deep into this.

**Comment by xuwankang** [comment]
i have the same issue

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
