### ISSUE TITLE
Hide Notification on ios

### ISSUE THREAD

**Issue by quangquy87** [luanpotter/audioplayers#492]
How to hide Notification on ios call from flutter?

**Comment by luanpotter** [comment]
What do you mean hide Notification? no notifications will be shown unless you ask for.

**Comment by erickzanardo** [comment]
Closing due inactivity, if there is more info that you can add to the issue, comment here and we can re open the issue.

**Comment by jamie1192** [comment]
@erickzanardo not OP but I was subbed to this issue as I was looking for a solution to this myself.

I think OP was referring to clearing the notification center media player notification programmatically, as it is retained there long after it is actually used within your app (eg. if you only use the audio player on a specific page).

**Comment by searchy2** [comment]
@luanpotter Can this issue be reopened? Currently, none of audioplayers' `notificationService` methods dismiss the iOS headless service and `setNotification` notification.

The only way to dismiss the notification is to write native code. 
There should be a way to dismiss the notification from the player itself.

**Comment by erickzanardo** [comment]
@searchy2 this is issue don't have much info on it, I think it would be better if a new issue were open, would you mind opening a new one so we can track this more easily?

**Comment by searchy2** [comment]
Sure, I'll open a new issue.

**Comment by searchy2** [comment]
Create a new issue https://github.com/luanpotter/audioplayers/issues/897
