### ISSUE TITLE
Issues playing sounds on Android

### ISSUE THREAD

**Issue by VicHofs** [luanpotter/audioplayers#496]
Hi all,
Whenever I activate a sound through `AudioCache()`, No audio is actually played and I get the following on the console: 
```
V/MediaPlayer( 8838): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 8838): cleanDrmObj: mDrmObj=null mDrmSessionId=null
```
Don't really know what could be going wrong.

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
