### ISSUE TITLE
Stop audio when AppLifecycleState changes 

### ISSUE THREAD

**Issue by gupta-shrinath** [luanpotter/audioplayers#497]
Hello,
First, of all, I would like to congratulate you guys on this plugin.
Here is my issue I want to stop the audio played by the audiocache class when the applifecycle state changes so
I created a function that can give me the instance of audioplayer class for my audiocache play method.

```
 Future<void> playAnimalSound() async {
    mAudioPlayer = await mAudioCache.play('$sound.wav');
  }
```

Note I have audiocache and audioplayer instance in the class

```
  static AudioCache mAudioCache = AudioCache();
  static AudioPlayer mAudioPlayer;
  AppLifecycleState mAppLifecycleState;
```

So I check if my applifecyclestate has changed then I call the stop method of my audioplayer class
but it doesn't work

```
 @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    setState(() {
      mAppLifecycleState = state;
      print(mAppLifecycleState);
      if (mAppLifecycleState == AppLifecycleState.paused ||
          mAppLifecycleState == AppLifecycleState.detached) {
        print('Trying to stop');
        mAudioPlayer.stop();
      }
    });
  }
```

Note : i have WidgetBindingObserver added to my initiState method as well as the dipose method too.

```
 @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
```

PS: I don't know whether this is silly issue or not its my first time creating an issue so if i have made any mistake i apologize

**Comment by luanpotter** [comment]
> but it doesn't work

what happens? does it print `Trying to stop` or not? Also please follow the template and put code inside code blocks, otherwise they are completely unreadable

**Comment by gupta-shrinath** [comment]
Thanks for the reply and I'll make to use of the issue template
The following gets printed in the logs
**I/flutter (16770): AppLifecycleState.inactive
I/flutter (16770): AppLifecycleState.paused
I/flutter (16770): Trying to stop**
E/ExtMediaPlayer-JNI(16770): env->IsInstanceOf fails
I think that the last log statement is something but I can't understand it

**Comment by luanpotter** [comment]
So it logs `Trying to stop` but doesn't stop? The audio keeps playing?

I believe your `playAnimalSound` always replace the previous player. So I think the issue might be it being called multiple times, which gets you many players, and you are only stopping the last one. You should add this to that method:

```
  if (playAnimalSound != null) {
    playAnimalSound.release();
  }
```

Before re-assigning. Also please use code blocks in the future, otherwise we can't read the issue properly. Lmk if that works.

**Comment by erickzanardo** [comment]
Closing due inactivity, if there is more info that you can add to the issue, comment here and we can re open the issue.
