### ISSUE TITLE
Player does not work as expected players confusion

### ISSUE THREAD

**Issue by kepuza** [luanpotter/audioplayers#498]
Hi,

Im using firestore and firestorege i have 5 player in chat page. I'm waiting for someone to finish playing after I play and pause someone and after i will record one more players mix up The last 2 players I initialized are at the bottom ?

Thank you

**Comment by kepuza** [comment]
now I realized that if there are 2 players in a row If new player data comes from firestore, it gets confused i dont understand why ?

**Comment by erickzanardo** [comment]
There isn't enough information on this issue for us to act on. Please edit this, or open a new one and please follow the issue template.

Feel free to comment here and we can re open this eventually.
