### ISSUE TITLE
Android player not playing MP3 that is <1sec

### ISSUE THREAD

**Issue by awilliams684** [luanpotter/audioplayers#502]
Having trouble  playing a sub 1 second MP3 file on android. The file is from a zip containing iOS system sounds and is called Tink.mp3 (zip file linked below)

This file will play fine in iOS however does not play in Android. I opened the file in Audacity and extended the length to 1 second by adding silence to the end and then it plays as expected on Android. This makes me think it has to do with the length. 

Link to iOS sounds zip file (link is in first post attachment)
https://forum.xda-developers.com/showthread.php?t=1165751

**Comment by yeelone** [comment]
me too

**Comment by NotThatBowser** [comment]
Same.

**Comment by luanpotter** [comment]
Have you tried using LOW_LATENCY mode? Please provide some code so I can see the exact configurations you are using. Also a link directly to the exact mp3 file you are talking about is helpful.

**Comment by awilliams684** [comment]
> Have you tried using LOW_LATENCY mode? Please provide some code so I can see the exact configurations you are using. Also a link directly to the exact mp3 file you are talking about is helpful.

[Orginal - Tink.mp3](https://srv-store4.gofile.io/download/p9ujdq/Tink.mp3)
[Modified - Tink.mp3](https://gofile.io/d/9OiBRb)

`playMp3('assets/sounds/Tink.mp3').whenComplete(() {});`

`Future playMp3(String asset) async {
  AudioPlayer _audioPlayer = AudioPlayer();
  AudioPlayer.logEnabled = logEnabled;
  final file = new File('${(await getTemporaryDirectory()).path}/temp.mp3');
  await file.writeAsBytes((await loadAsset(asset)).buffer.asUint8List());
  await _audioPlayer.play(file.path, isLocal: true);
  _audioPlayer.onPlayerCompletion.listen((event) {
    print('audio complete');
    _audioPlayer.release();
  });
}`

**Comment by erickzanardo** [comment]
This issue is outdated or uses a very old version of the project, could you please test if this happens on newer versions? And in case that this still happens, open a new issue?

**Comment by BadReese** [comment]
same issue on 0.19.1, use LOW_LATENCY mode cause double sound .
