### ISSUE TITLE
Audio not resuming and playing from start

### ISSUE THREAD

**Issue by narayan8291** [luanpotter/audioplayers#508]
I have the following code. Audio plays but starts from start instead of resuming. Docs: https://pub.dev/packages/audioplayers

Widget build(BuildContext context) {
    final double _width = MediaQuery.of(context).size.width;
    var url = "";
..
...
IconButton(
                                    icon: isPlaying
                                        ? Icon(
                                      Icons.pause_circle_outline,
                                      size: 60.0,
                                    ): Icon(Icons.play_circle_outline, size: 60.0),
                                    onPressed: () {
                                      setState(() {
                                        isPlaying = !isPlaying;
                                        play(audioPlayer, isPlaying, url);
                                      });
                                    }
                                    ),

void play(player, flag, url) async {
  if (flag == true) {
    await player.play(url);
  }
  else {
    await player.pause();
  }
}

How do I resume from where a user left when a user pauses and clicks on the play button again.

**Comment by narayan8291** [comment]
Made it workl

**Comment by MardariG** [comment]
> Made it workl

how?
