### ISSUE TITLE
AudioCache not working 

### ISSUE THREAD

**Issue by danju4rizzl** [luanpotter/audioplayers#509]
For some strange reason whenever after adding the audioplayers package to my pubspec.yaml file and importing it into my code, the application doesn't run anymore. 

Anyone else with this issue or anyone with a working file?

I have used "flutter clean" and "flutter run -v" still same error

However, since I am **new to flutter** I tried using assets_audio_player and it worked

**Comment by debugerer** [comment]
me too, no sound heart on iOS simultor, but log show success.

**Comment by HugoHeneault** [comment]
Have you tried restarting your simulator/device?

**Comment by yaraju** [comment]
@HugoHeneault Thank you. I was running into the same problem on Android, and restarting my Android emulator fixed it.

**Comment by M1Joe** [comment]
@danju4rizzl I might be running into the same issue.  Any chance your logs look like this: https://github.com/luanpotter/audioplayers/issues/576
