### ISSUE TITLE
Trying to play AudioStream

### ISSUE THREAD

**Issue by ckildgypmk** [luanpotter/audioplayers#52]
I'm trying to play audiostream with audioplayers, and everything is ok in android emulator, but when Im trying to test it on device i get those errors:
`E/ExtMediaPlayer-JNI(11346): env->IsInstanceOf fails
E/MediaPlayer-JNI(11346): JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
E/ExtMediaPlayer-JNI(11346): env->IsInstanceOf fails
E/MediaPlayer-JNI(11346): JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
D/MediaHTTPConnection(11346): filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 6.0.1)
D/MediaHTTPConnection(11346): proxy null port 0`
BUT after about 10-20 seconds my stream starts playing. 
How to fix it?

**Comment by erickzanardo** [comment]
Closing this due inactivity, if you still got problems, please open a new issue.
