### ISSUE TITLE
ios audio player not starting to play

### ISSUE THREAD

**Issue by pacifio** [luanpotter/audioplayers#520]
Device logs is showing that some audio is being played but not playing actually on the screen itself . It works on android but fails to work on IOS

```bash
Runner[33261]: (audioplayers) setUrl "SOME_VALID_URL"
[+4997 ms] [DEVICE LOG] 2020-05-03 00:28:01.558682+0600  localhost
Runner[33261]: (audioplayers) iOS => call stop, playerId
643fb71a-8ee1-485b-a3c9-b0e247c4a761
[        ] [DEVICE LOG] 2020-05-03 00:28:01.558810+0600  localhost
Runner[33261]: (audioplayers) stop
```

```dart
String audioUrl = "some_valid_url";
audioPlayer.play(audioUrl);
```

**Comment by HugoHeneault** [comment]
Is your file local (from assets, temp files) or remote?

**Comment by Mohamed50** [comment]
anything on that i have the same issue on ios but it's working fine in android
i stream mp3 file from network

**Comment by nivla360** [comment]
I also have the same issue on iOS when I try to play audio from the internet but Android works fine.

**Comment by erickzanardo** [comment]
There isn't enough information on this issue for us to act on. Please edit this, or open a new one and please follow the issue template.

Feel free to comment here and we can re open this eventually.
