### ISSUE TITLE
Implement Notification on android?

### ISSUE THREAD

**Issue by quangquy87** [luanpotter/audioplayers#521]
How to implement Notification on android?

**Comment by DenisPushkarev** [comment]
You can use audioplayers with another plugin - https://pub.dev/packages/audio_service

**Comment by jffiorillo** [comment]
@DenisPushkarev How do audioplayers interact with audio_service? Do you have an example? Thank you

**Comment by DenisPushkarev** [comment]
@jffiorillo audioplayers has on `onPlayerStateChanged`, `onAudioPositionChanged`, `onPlayerCompletion`, etc events which you can use to interact with the audio service. 
And audio service also has `AudioService.runningStream` for displaying the state and `BackgroundAudioTask` class for controlling the player state.

Simple example you can find on https://github.com/DenisPushkarev/audioplayers_service

**Comment by jffiorillo** [comment]
Great, thank you for the info 🙏

**Comment by luanpotter** [comment]
Closing in favor of https://github.com/luanpotter/audioplayers/issues/561
