### ISSUE TITLE
Play remote file by https failed.

### ISSUE THREAD

**Issue by heibor** [luanpotter/audioplayers#523]
The pem file for my https server is generated by ssh. When I play the mp3 file from remote, it seems that the file can not be played. The logs are:

An Observatory debugger and profiler on A0001 is available at: http://127.0.0.1:49909/Ze2u5lkAXjE=/
I/flutter ( 6344): https://192.168.1.66/staff/textsound/13/bb31ba67.mp3
V/MediaHTTPService( 6344): MediaHTTPService(android.media.MediaHTTPService@ecfaf3f): Cookies: null
V/MediaHTTPService( 6344): makeHTTPConnection: CookieManager created: java.net.CookieManager@f8d000c
V/MediaHTTPService( 6344): makeHTTPConnection(android.media.MediaHTTPService@ecfaf3f): cookieHandler: java.net.CookieManager@f8d000c Cookies: null
D/NetworkSecurityConfig( 6344): No Network Security Config specified, using platform default
I/flutter ( 6344): ok
E/MediaPlayerNative( 6344): error (1, -2147483648)
E/MediaPlayer( 6344): Error (1,-2147483648)
E/MediaPlayerNative( 6344): stop called in state 0, mPlayer(0x95ca9e80)
E/MediaPlayerNative( 6344): error (-38, 0)
V/MediaPlayer( 6344): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 6344): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 6344): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 6344): cleanDrmObj: mDrmObj=null mDrmSessionId=null

Is there any solution?

**Comment by heibor** [comment]
My https sever is self-signed. I have modify the `AndroidManifest.xml` file by adding `android:usesCleartextTraffic="true"` to connect to the non-https port to avoid the `transport security` problem.

I am wondering whether it's possible to use some `dart` code as an optional solution to the https trusted connection problem.

For example, here is a [dio solution](https://stackoverflow.com/questions/54285172/how-to-solve-flutter-certificate-verify-failed-error-while-performing-a-post-req). By using dart code, we don't need to modify the `AndroidManifest.xml` file, maybe the dart code can be used to extend resilience.

**Comment by pacifio** [comment]
I am facing the same issue as well
my server is configured
my app has all the internet permissions and I have added ```android:usesCleartextTraffic="true"``` as well

Seems to be failing for those which are using android 8 to (lesser) versions

**Comment by sandrhymend** [comment]
Same issue as well. It works pretty well on ios but on android get me a headache :(

**Comment by BringTheChill** [comment]
someone with a solution :( ?

**Comment by erickzanardo** [comment]
This issue is outdated or uses a very old version of the project, could you please test if this happens on newer versions? And in case that this still happens, open a new issue?
