### ISSUE TITLE
License warning

### ISSUE THREAD

**Issue by dhalloop7** [luanpotter/audioplayers#525]
[!] A license was specified in podspec `audioplayers` but the file does not exist - /Users/webwerks/Documents/D/DHAVAL/FLUTTER_WORKSPACE/amer/ios/.symlinks/plugins/audioplayers/LICENSE.md

[!] Unable to read the license file `../LICENSE.md` for the spec `audioplayers (0.0.1)`

[!] Unable to read the license file `../LICENSE.md` for the spec `audioplayers (0.0.1)`

**Comment by peleteiro-dev** [comment]
I´ve seen same warning, it works but it's a warning anyway. Should I be concerned about this ?

**Comment by renancaraujo** [comment]
There is not much to worry, also, updated the license file on #534

**Comment by luanpotter** [comment]
Fixed by #534
