### ISSUE TITLE
A problem occurred configuring root project 'audioplayers'. > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

### ISSUE THREAD

**Issue by Bidhanrai** [luanpotter/audioplayers#537]
In debug mode it works fine. But when i try to build in release mode it shows the above error. Please can anyone help me?

This error might be with AndroidX incompatibilities with this plugin.

**Comment by liemvo** [comment]
Just update the gradle version to 3.3.x or above

**Comment by Bidhanrai** [comment]
ok done thank you. Problem solved.:-)

**Comment by liemvo** [comment]
@Bidhanrai  That is fantastic! Can you close this issue?

**Comment by luanpotter** [comment]
I can :)

**Comment by Bidhanrai** [comment]
thank you :-)

**Comment by bytelyus** [comment]
Hi there .. I am facing this issue ... :( 

my gradle is set to 3.5.0 at android level ... like so:

`classpath 'com.android.tools.build:gradle:3.5.0' `

I am on Mac &  channel Stable 1.22.2 ...  and also with sdk.dir location defined at local.properties ... 

ERROR TRACE:

What went wrong:
```
A problem occurred configuring root project 'audioplayers'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
```



Also did try to downgrade to gradle 3.3.0 with same resultsss... :(

**Comment by bytelyus** [comment]
only happens when trying to build for --release

**Comment by lucaszeroxit** [comment]
Same here. Only happens when release...

Any help guys?

**Comment by lgozalvez** [comment]
Same issue here:

Only when: flutter run --release

`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'audioplayers'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.`

**Comment by MATTYGILO** [comment]
how did you fix this I've had this error for a week now

**Comment by WallachiaAcademy** [comment]
Hey guys. I have no idea what caused this and frankly I don't care much at this stage.
But in my case this error showed up when I tried to add some ads to my app.
I was using "firebase_admob: ^0.11.0+1" and once I've downgraded to "firebase_admob: ^0.10.3" everything worked as a charm.
I've been using 0.10.3 because this is what I've been using in one of my previously made apps and it worked XD

Hope it helps.

**Comment by bhanuka96** [comment]
same issue

**Comment by najib-mrh** [comment]
same problem ... 
my gradle version is com.android.tools.build:gradle:3.5.0 
audioplayers 0.10.0  ,  firebase_admob 0.9.3   ,

Thanks !

**Comment by bahcem** [comment]
I get the same error need help

**Comment by najib-mrh** [comment]
> same problem ...
> my gradle version is com.android.tools.build:gradle:3.5.0
> audioplayers 0.10.0 , firebase_admob 0.9.3 ,
> 
> Need help, Thanks !

Solved !! 
i update the gradle to 4.0.1 
https://android-developers.googleblog.com/2020/07/preparing-your-build-for-package-visibility-in-android-11.html

**Comment by dhruvdani** [comment]
> Hi there .. I am facing this issue ... :(
> 
> my gradle is set to 3.5.0 at android level ... like so:
> 
> `classpath 'com.android.tools.build:gradle:3.5.0' `
> 
> I am on Mac & channel Stable 1.22.2 ... and also with sdk.dir location defined at local.properties ...
> 
> ERROR TRACE:
> 
> What went wrong:
> 
> ```
> A problem occurred configuring root project 'audioplayers'.
> > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
> ```
> 
> Also did try to downgrade to gradle 3.3.0 with same resultsss... :(

i am facing same issue any help please?

**Comment by chaochaox1990** [comment]
* What went wrong:
A problem occurred configuring root project 'audioplayers'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
this same issue

**Comment by Aryankaushik2312** [comment]
I'm using classpath 'com.android.tools.build:gradle:3.5.0'
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'audioplayers'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
