### ISSUE TITLE
Imports not working

### ISSUE THREAD

**Issue by SSolheim2000** [luanpotter/audioplayers#538]
I haven't been able to get this to work, so I tried loading up the Example program and ran into errors right away.

The first three errors have to do with import locations that don't exist:
import 'package:http/http.dart';
import 'package:provider/provider.dart';
import 'player_widget.dart';

"The error message is: Target of URI doesn't exist: 'package:http/http.dart'."

**Comment by fartem** [comment]
@SSolheim2000 It looks you do not import [http](https://pub.dev/packages/http) package correctly. Try import from instruction from https://pub.dev/packages/http

**Comment by SSolheim2000** [comment]
I was able to get two of them resolved by adding to the `dependencies` section in pubspec.yaml:
```
  http: ^0.12.1
  provider: ^4.1.2
```
I couldn't fine the 'player_widget' page to figure out what line to add there.

**Comment by fartem** [comment]
@SSolheim2000 What about player_widget? It is a local file?

**Comment by SSolheim2000** [comment]
It is one of the imports you referenced in your example.

**Comment by fartem** [comment]
@SSolheim2000 If you haven't this file, don't import it.

**Comment by SSolheim2000** [comment]
Then the example doesn't work.

**Comment by fartem** [comment]
@SSolheim2000 your imports looks like:
```dart
import 'package:http/http.dart';
import 'package:provider/provider.dart';
```

?

Do you get dependencies with `flutter packages get` or something else?

**Comment by SSolheim2000** [comment]
Here's the example I'm working with: https://pub.dev/packages/audioplayers#-example-tab-
On about the 11th line, there is a call to `import 'player_widget.dart';` That import doesn't work.

As for the other two, http and provider, I was able to get them working. I did it in Android Studio, after modifying the `dependencies` section to include the them, I did the get 'Pub Get' function and now they work fine.

So, I just need to know where to find the dependency information for the 'player_widget'.

**Comment by fartem** [comment]
@SSolheim2000 See in this folder https://www.github.com/luanpotter/audioplayers/tree/master/example%2Flib

**Comment by luanpotter** [comment]
You have to run `flutter pub get` in the example folder.

**Comment by SSolheim2000** [comment]
I was able to find another project that actually worked and moved on from there. I documented my findings and the code needed here: [https://github.com/SSolheim2000/AudioPlayer_Basic/]

I would take a good look at your documentation and make sure all the steps are included and that someone can actually follow it.

**Comment by zah-alin** [comment]
I have the same problem, couldn't find audio widget package.
audio Palyer basic just works for local files and I need audio player for remoteUrl.

**Comment by alainseys** [comment]
> I haven't been able to get this to work, so I tried loading up the Example program and ran into errors right away.
> 
> The first three errors have to do with import locations that don't exist:
> import 'package:http/http.dart';
> import 'package:provider/provider.dart';
> import 'player_widget.dart';
> 
> "The error message is: Target of URI doesn't exist: 'package:http/http.dart'."

Hy you can fix this by doing  import 'package:http/http.dart' as http;

**Comment by SSolheim2000** [comment]
As I mentioned earlier, I was able to get the HTTP and provider imports to work. 
As I advised Launpotter, I would double-check and make sure the documentation is correct.

**Comment by luanpotter** [comment]
If you want those libs, you have to explicitly add them as deps. They are not transitive from this package.
This is clearly a flutter issue and has nothing to do with audioplayers.

**Comment by zjaweds** [comment]
I couldn't use this plugin and the hardest thing that I encountered was that I am missing the nuances in documentation of this plugin.

**Comment by SSolheim2000** [comment]
Yep. I let them know their documentation was incomplete and they did nothing.
