### ISSUE TITLE
Exception thrown when calling audioPlayer.dispose

### ISSUE THREAD

**Issue by namchuai** [luanpotter/audioplayers#543]
The exception is thrown when user was playing audio, then immediately pop the screen. Exception is thrown at audioPlayer.dispose.

Device: iOS simulator

> [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add  (dart:async/broadcast_stream_controller.dart:251:24)
#1      AudioPlayer._doHandlePlatformCall 
package:audioplayers/audioplayers.dart:575
#2      AudioPlayer.platformCallHandler 
package:audioplayers/audioplayers.dart:538
#3      MethodChannel._handleAsMethodCall 
package:flutter/…/services/platform_channel.dart:409
#4      MethodChannel.setMethodCallHandler.<anonymous closure> 
package:flutter/…/services/platform_channel.dart:377
#5      _DefaultBinaryMessenger.handlePlatformMessage 
package:flutter/…/services/binding.dart:199
#6      _invoke3.<anonymous closure>  (dart:ui/hooks.dart:290:15)
#7      _rootRun  (dart:async/zone.dart:1184:13)
#8      _CustomZone.run  (dart:async/zone.dart:1077:19)
#9      _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
#10     _invoke3  (dart:ui/hooks.dart:289:10)
#11     _dispatchPlatformMessage (d<…>

**Comment by sauzy34** [comment]
I made a change at https://github.com/luanpotter/audioplayers/blob/45a79be4167e0a1f010995f35eafe0eedda6f092/example/lib/player_widget.dart#L59
```
    _audioPlayer.stop();
```
and it worked for me ✅ ❤️
