### ISSUE TITLE
Android - Play remote url with m3u8 format failed.

### ISSUE THREAD

**Issue by sandrhymend** [luanpotter/audioplayers#545]
I recently discovered that my remote url failed when I pressed play on emulator Nexus 6 API 28.
The only difference is m3u8 format.

Anyone has similar situation or anyone knows how can I handle this streaming audio url ?
Thanks :)

**Comment by dfdgsdfg** [comment]
Seems to same here. Any workaround? iOS just works fine.

```
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:18
#EXT-X-DISCONTINUITY
#EXTINF:15.019000
http://records/x95XRjP9yeGYkJAs4pjk/355870f3e64842b850ff7fba4fe07859_BqNdzJRLTmdPmEMwNXPnM3SVWWN2_20200723070500484.ts
```

**Comment by sandrhymend** [comment]
In my case It works but I use this packages: m3u, just_audio and audio_service, but the package m3u allows me to handle.
Hope this help you

**Comment by dfdgsdfg** [comment]
Here are some error messages.

``
V/MediaHTTPService( 9900): MediaHTTPService(android.media.MediaHTTPService@2bf52cd): Cookies: null
V/MediaHTTPService( 9900): makeHTTPConnection: CookieManager created: java.net.CookieManager@e3ee782
V/MediaHTTPService( 9900): makeHTTPConnection(android.media.MediaHTTPService@2bf52cd): cookieHandler: java.net.CookieManager@e3ee782 Cookies: null
E/MediaPlayerNative( 9900): Attempt to call getDuration in wrong state: mPlayer=0x7c5567b300, mCurrentState=4
E/MediaPlayerNative( 9900): error (-38, 0)
E/MediaPlayer( 9900): Error (-38,0)
E/MediaPlayerNative( 9900): error (1, -2147483648)
E/MediaPlayer( 9900): Error (1,-2147483648)
E/MediaPlayerNative( 9900): pause called in state 0, mPlayer(0x7c5567b300)
E/MediaPlayerNative( 9900): error (-38, 0)
E/MediaPlayerNative( 9900): Attempt to perform seekTo in wrong state: mPlayer=0x7c5567b300, mCurrentState=0
E/MediaPlayerNative( 9900): error (-38, 0)
E/MediaPlayer( 9900): Error (-38,0)
E/MediaPlayer( 9900): Error (-38,0)
``

**Comment by dfdgsdfg** [comment]
Seems to Android `mediaplayer` does not support m3u.

If I want to use this plugin I have to parse m3u and get each of the media files from it. 

https://stackoverflow.com/questions/6688758/streaming-m3u-audio

**Comment by sandrhymend** [comment]
Sample parse from package https://pub.dev/packages/m3u
import 'package:m3u/m3u.dart';

main() async {
  String playlistContent = <load_playlist>;
  final playlist = await M3uParser.parse(file);
  
  // Organized categories
  final categories =
      sortedCategories(entries: listOfTracks, attributeName: 'group-title');
  print(categories);
}

**Comment by erickzanardo** [comment]
m3u8 is not supported by Android MediaPlayer, so audioplayers don't support it either. Here you can check the supported formats: https://github.com/luanpotter/audioplayers#supported-formats
