### ISSUE TITLE
No sound in the player and its not running also

### ISSUE THREAD

**Issue by rishabhshukla7** [luanpotter/audioplayers#547]
E/ExtMediaPlayer-JNI( 3273): env->IsInstanceOf fails
E/MediaPlayer-JNI( 3273): JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
E/ExtMediaPlayer-JNI( 3273): env->IsInstanceOf fails
E/MediaPlayer-JNI( 3273): JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
E/MediaPlayer( 3273): error (1, -22)
E/MediaPlayer( 3273): Error (1,-22)
E/MediaPlayer( 3273): stop called in state 0, mPlayer(0x7f71396580)
E/MediaPlayer( 3273): error (-38, 0)

**Comment by rishabhshukla7** [comment]
It was working first but now what happened I don't know can anybody help me

**Comment by luanpotter** [comment]
What did you change since it was working? New version, code change...

**Comment by erickzanardo** [comment]
There isn't enough information on this issue for us to act on. Please edit this, or open a new one and please follow the issue template.

Feel free to comment here and we can re open this eventually.
