### ISSUE TITLE
short gap between the end and the beginning of the music when using AudioCache().loop()

### ISSUE THREAD

**Issue by RaphaelRevivor** [luanpotter/audioplayers#548]
Hi,

I am using audioplayers in my app. My requirement is to play continuous (looping) background music, without any gap in between, using a local media file.
However, when I used AudioCache().loop("my_local_media"), it did loop, but there is a gap between the end and the beginning of the music. The gap is short, but noticeable, like around 0.5 seconds. Later I tried another audio player, this situation did not happen.
There is no error or warning during running, so I am not sure whether this is a design choice or a bug.
The environment I'm running audioplayers with is:
ubuntu 18.04
vscode 1.45.1
android studio 3.5.3
flutter 1.17.1
Dart 2.8.2
audioplayers 0.15.1
on an emulator for Pixel 2 API 28 running Android 9.0 x86.

It would be nice if you could help me with this.

Best Regards,
Raphael

**Comment by leidig54** [comment]
Hello. From having a similar problem and looking around it looks like this is the only workable solution at present https://github.com/fireslime/flutter_gapless_audio_loop

**Comment by RaphaelRevivor** [comment]
> Hello. From having a similar problem and looking around it looks like this is the only workable solution at present https://github.com/fireslime/flutter_gapless_audio_loop
Thanks! I also find a closed issue: #77 , so in the end, the solution goes to the audio player Ocarina.
