### ISSUE TITLE
Unable to load asset

### ISSUE THREAD

**Issue by FilipeOS** [luanpotter/audioplayers#549]
Hi there,

I've having issues trying to play audio files from `getExternalStorageDirectory`, I get `Unable to load asset: assets//storage/emulated/0/Android/data/com.xxxx.myapp/files/xxxx.m4a`

``` 
static AudioCache _player = AudioCache();
AudioPlayer _audioPlayer = AudioPlayer();


Future<AudioPlayer> _playAudio(String path) async {
    return _player.play(path);
  }
```

Can someone advise?

I tried with .m4a and .aac and .wav... App have the write and read permissions.

**Comment by luanpotter** [comment]
did you add it to your pubspec file? please send the contents of that file and your directory structure.

**Comment by FilipeOS** [comment]
Yes, I added on pubspec or it would not work.

I'm using the app folder I wrote on last post, I basically just record (in a Uint8list) and save a .acc file (more compatible?). After that I go to the list screen and list all files in that folder and use the audioplayers plugin to play it.

I even added a .m4a file that works (to test if was saving issues) and even that file is not playable.

pubspec `audioplayers: ^0.15.1`

```
static AudioCache _player = AudioCache();
  AudioPlayer _audioPlayer = AudioPlayer();
```

```
Future<AudioPlayer> _playAudio(String path) async {
    return _player.play(path);
  }

  void _stopAudio() {
    if (_audioPlayer != null) {
      _audioPlayer.stop();
    }
  }
```

```
if (_isPlaying) {
            _isPlaying = false;
            _stopAudio();
          } else {
            _stopAudio();
            _isPlaying = true;
            try {
              await _playAudio(file.path);
            } catch (e) {
              print(e);
              Fluttertoast.showToast(toastLength: Toast.LENGTH_SHORT, msg: "Error occurred");
              _isPlaying = false;
            }
          }
```

This helps?

**Comment by FilipeOS** [comment]
Oh, if you look the path it's wrong, it's forcing assets folder? who to fix this to remote path? `assets//storage/emulated/0/Android/data/com.xxxx.myapp/files/xxxx.m4a`

**Comment by FilipeOS** [comment]
Fixed by placing only this declaration:
`AudioPlayer _audioPlayer = AudioPlayer(mode: PlayerMode.LOW_LATENCY);`

and

```
void _playAudio(String path) async {
    _audioPlayer.play(path, isLocal: true);
  }

  void _stopAudio() {
    if (_audioPlayer != null) {
      _audioPlayer.stop();
    }
  }
```
