### ISSUE TITLE
project:path_provider_macos error

### ISSUE THREAD

**Issue by weview777** [luanpotter/audioplayers#550]
my app couldnt run because of the macos_path provider but i have after some snooping around i could finally fix it by deleting the path_provider_macos.dart ,
soo please i would advise creatung two seperate plugins for audioplayers

**Comment by luanpotter** [comment]
I don't know what you are talking about, there is no `path_provider_macos.dart` file on this project. That was probably some misconfiguration on your part regarding your multiple plugins. We do depend on path provider as as dependency. That seems to be working fine for me.

**Comment by jinfagang** [comment]
I suppose he might runs on macOS? Does this repo supports macOS or not?

**Comment by weview777** [comment]
It supports both platforms and I just deleted the path_provuder_macos in my
pub_cache folder and it was all fine .

**Comment by luanpotter** [comment]
We do, with limited features. Not sure about this issue though, seems like a flutter / flutter clean issue. I am closing, please open another issue if this persists.
