### ISSUE TITLE
Android: isNotification / respectSilence have no effect with PlayerMode.LOW_LATENCY

### ISSUE THREAD

**Issue by tuarrep** [luanpotter/audioplayers#553]
When using `LOW_LATENCY` player mode, a `SoundPool` is created with static audio attributes.
https://github.com/luanpotter/audioplayers/blob/master/android/src/main/java/xyz/luan/audioplayers/WrappedSoundPool.java#L239

So when a player is created with `respectSilence: true` or `play(isNotification: true)` is called the sound is sent through media channel

**Comment by tadeubas** [comment]
What is supposed to `respectSilence: true` do?
Tested with version `audioplayers: ^0.18.2` on Android 6.0 phone in debug mode with or without **respectSilence** and **isNotification**, with media down and all other volumes up and nothing happens.

**Comment by tuarrep** [comment]
Sorry, don't remember on which project I've used your lib neither the reason for opening this issue.
