### ISSUE TITLE
iOS remote files immediately stopping for "longer" audio files

### ISSUE THREAD

**Issue by kbanta11** [luanpotter/audioplayers#556]
So I'm running into a weird issue on iOS only where when I try to play a remote file, it will "start" but then immediately stop before playing any audio (I can tell this by printing out the player state when it changes). But here's what's kind of weird:  This will only happen when trying to listen to an audiofile that's longer than about 30 seconds that was recorded on android (recorded with flutter sound).  Files will play just fine in any other combo (ie. remote files longer than 30 seconds recorded on iPhone play just fine, remote files shorter than 30 seconds recorded on android play fine).

Not sure what else to try and troubleshoot since it seems like the player is working fine in all cases but this one. I'm not getting any errors from the player, its just changing state to playing for a couple seconds without actually starting audio and then stopped.

Edit:
I was able to get this output for the failing posts:
`	path: satisfied (Path is satisfied), interface: en0
    "LocalDataTask <49AD6E54-D0D8-49C9-8356-29C760B8397D>.<25>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <49AD6E54-D0D8-49C9-8356-29C760B8397D>.<25>, NSLocalizedDescription=cancelled}
player status: 2
flutter: _platformCallHandler call audio.onError {playerId: 0c9be397-e6ca-4f2c-87cd-ab0682f1ca2c, value: AVPlayerItemStatus.failed}`

**Comment by erickzanardo** [comment]
There isn't enough information on this issue for us to act on. Please edit this, or open a new one and please follow the issue template.

Feel free to comment here and we can re open this eventually.
