### ISSUE TITLE
Support changing speed of audio when playing?

### ISSUE THREAD

**Issue by fzyzcjy** [luanpotter/audioplayers#557]
Hi thanks for the library! I wonder whether we can change the speed of audio?

**Comment by nimisis** [comment]
This feature is already available. See _audioPlayer.setPlaybackRate(playbackRate: newRate);

**Comment by fzyzcjy** [comment]
Thanks!

**Comment by Wyctus** [comment]
Seems like it's not implemented on the web yet, I got the following error:
`Error: PlatformException(Unimplemented, null, The audioplayers plugin for web doesn't implement the method 'setPlaybackRate')`

Is there any way I can change the speed?

Thanks!

**Comment by advayanand** [comment]
Hello,

When I tried to change the audio playback rate while it was playing, the changes were not reflected in the audio. Do I need to pause the audio, change the playback rate, and then play? Or is it another issue?
