### ISSUE TITLE
Resource leak?

### ISSUE THREAD

**Issue by Eneum** [luanpotter/audioplayers#56]
Using AudioCache player to repeatedly play a sound effect in a game-like app.  on iOS, after a large number of plays, the sound disappears, and the whole app comes to a screeching halt, and then crashes.  Looks like some sort of resource leak that gets accumulated over time.

**Comment by luanpotter** [comment]
Hi, @Eneum 

Each time the cache plays a new audio, if using the default configurations, it will create a new AudioPlayer and load the resource, but on RELEASE mode, meaning that as soon as it finishes playing, the player is released. That is, however, just on Android. On iOS, the release function does nothing, as I believed there was no need to release the media player for iOS. Maybe that's a problem with that?

To test this theory, you could set the fixedPlayer property on the audiocache and now every call to play will use the same player (you won't be able to play simultaneously, though).

The best way to handle this if you have possible overlapping sound is to use the AudioPool class provided by Flame. In fact, if you are building a game-like app, I'd suggest taking a look at [Flame](https://github.com/luanpotter/flame) to help you out, it provides lots of goodies to help with games.

The AudioPool class can be found [here](https://github.com/luanpotter/flame/blob/master/lib/audio_pool.dart); it creates a pool of pre-loaded audioplayers (you control min and max) to have one always ready for quick firing sounds but also don't overload the heap with tons of players.

The parameters are:

* min : the minimal amount of players, upon creating it will leave this amount ready. if more than min happen to be created, they are kept (up to max)
* max : the max to be kept, if more than max are created, they are released and discarded.
* prefix : audiocache's prefix
* repeating : probably false to you, but allows to play on repeat mode

Please let me know if this helps you out!

**Comment by erickzanardo** [comment]
Closing this due inactivity, if you still have problems, feel free to open a new issue.
