### ISSUE TITLE
Extreme latency on Safari

### ISSUE THREAD

**Issue by lukepighetti** [luanpotter/audioplayers#562]
We are seeing about 1 second latency on Safari trying to play sounds. This issue is not present on Chrome.

**Comment by luanpotter** [comment]
In general, Safari sucks haha. But please see https://github.com/luanpotter/audioplayers/issues/591, I presented a workaround.

Unless it takes 1 second the second time you play as well, then it's something else (not pre-loading).

**Comment by lukepighetti** [comment]
> In general, Safari sucks haha.

Our personal opinions about Safari are irrelevant when it is within the 98% of browsers in use.

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
