### ISSUE TITLE
I want to add pause or stop button using Audio Cache

### ISSUE THREAD

**Issue by Osama7869** [luanpotter/audioplayers#565]
I want to add pause or stop button using Audio Cache. 
There is no properties in Audio cache
How i play, pause and Stop using assets and audio cache??

**Comment by shalllman** [comment]
I suppose that you are in your 
class _homeState extends State<home>
{

// you can like this

  AudioCache audioCache = AudioCache();
  AudioPlayer advancedPlayer = AudioPlayer();



  Future play() async {
    advancedPlayer=await audioCache.play('song.mp3');
  }

  Future stopplay() async {
    await  advancedPlayer.stop();
  }

  Future stopplay() async {
    await  advancedPlayer.pause();
  }


//and call theses functions in your Scaffold

**Comment by luanpotter** [comment]
Please read the docs before asking questions, this is clearly explained in details.

**Comment by luanpotter** [comment]
There is even a [FAQ](https://github.com/luanpotter/audioplayers/blob/master/troubleshooting.md) section about it -.-
