### ISSUE TITLE
Catch one issue from iOS 13.5

### ISSUE THREAD

**Issue by orliu** [luanpotter/audioplayers#567]
_NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <E973B5F8-2CC4-4645-B0B3-271064D97D02>.<1>

_platformCallHandler call audio.onError {playerId: b8ba6871-92b2-4310-bd41-95a7bc7cc2e7, value: AVPlayerItemStatus.failed}

**Comment by erickzanardo** [comment]
There isn't enough information on this issue for us to act on. Please edit this, or open a new one and please follow the issue template.

Feel free to comment here and we can re open this eventually.
