### ISSUE TITLE
unable to play android 9 and above 

### ISSUE THREAD

**Issue by prssvraju** [luanpotter/audioplayers#568]
url_playing  is working in ios/android but not playing in android 9 and above

**Comment by muarachmann** [comment]
Can anyone else confirm this? mine seems to be working fine both emulator and physical device.

**Comment by erickzanardo** [comment]
Probably because of secure traffic, which was introduced on Android 9.

**Comment by muarachmann** [comment]
> Probably because of secure traffic, which was introduced on Android 9.

Definitely... was about asking that. @prssvraju try seeing - https://github.com/luanpotter/audioplayers#warning-ios--macos-app-transport-security

**Comment by luanpotter** [comment]
Please follow the issue template carefully, otherwise I will just close the issue.

**Comment by erickzanardo** [comment]
Closing due inactivity
