### ISSUE TITLE
youtube url problem

### ISSUE THREAD

**Issue by gulmensedat** [luanpotter/audioplayers#569]
does not open youtube link?

example

 https://r2---sn-nv47ln7z.googlevideo.com/videoplayback?expire=1593996731&ei=WyECX_zFCZnygAee3qX4Dw&ip=178.233.152.104&id=o-AGtzxmMxooZsOPrFh7_9nbzx6D9qeQefJgxAyoYlhMWz&itag=251&source=youtube&requiressl=yes&hcs=yes&mh=3F&mm=31%2C29&mn=sn-nv47ln7z%2Csn-nv47ln7z&ms=au%2Crdu&mv=m&mvi=1&pl=24&shardbypass=yes&initcwndbps=797500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=3503481&dur=212.581&lmt=1593252407033282&mt=1593975029&fvip=5&keepalive=yes&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=hcs%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cshardbypass%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKAk--pTpys5ziR0wafVTTpgCZVPONbl0nqnyGY0aksqAiEA0Axl4r2oBvcv810_r9jigzrn25_o5GPpwh6wH070uW4%3D&sig=AOq0QJ8wRAIgKLrVnv9GoW89qV2x0c3_zh_pwQmM-e8CiFDSezMPbEkCIH6xmxTZcbYSiOsYM3Mw0ARAPjgmtKrLGvSZsw6su_Tv

**Comment by luanpotter** [comment]
That URL is not accessible. Clearly it won't work.
