### ISSUE TITLE
Audio URL is not play on android as well as IOS

### ISSUE THREAD

**Issue by aTeamSolace** [luanpotter/audioplayers#570]
Im trying to play this url :  http://testing.janmakundali.com/storage/audios/v_i_s_h_n_u_s_a_h_a_s_r_a_n_a_m_a_s_t_h_o_t_r_a_m.mp3

then below error occured how to solve this

E/MediaPlayerNative(10887): error (1, -2147483648)
E/MediaPlayer(10887): Error (1,-2147483648)
E/MediaPlayerNative(10887): stop called in state 0, mPlayer(0x8d43cc00)
E/MediaPlayerNative(10887): error (-38, 0)
V/MediaPlayer(10887): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(10887): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(10887): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(10887): cleanDrmObj: mDrmObj=null mDrmSessionId=null

**Comment by muarachmann** [comment]
Try to load  a secure url i.e from `https` or if you want to test locally or http consider adding         `android:usesCleartextTraffic="true"` to your manifest file. I think this is in the ReadME
