### ISSUE TITLE
Recording state as method

### ISSUE THREAD

**Issue by madhu131313** [luanpotter/audioplayers#574]
Currently I am running 
`      await audioPlayer.pause();
`
And separately setting the state after that mode as "paused". In an ideal scenario following single source of truth principle, I want the player to provide the recording state as method

**Comment by luanpotter** [comment]
It's not a recording state, because it's an audio *player* that thus *plays* audio.
But you can get its state simply by doing `audioPlayer.state` or using one of streams to listen for updates.
