### ISSUE TITLE
When using navigation, music cannot be paused, and other applications that play music or videos will not be paused.

### ISSUE THREAD

**Issue by chongx117** [luanpotter/audioplayers#575]

**Comment by luanpotter** [comment]
Please follow the issue template carefully, otherwise I will just close the issue.

**Comment by zzSleepyCoderzz** [comment]
Hello @luanpotter, have you found any solutions to this issue? I have read many threads and tried many solutions but my code still doesnt work.

**Comment by luanpotter** [comment]
No because it is not following the issue template. Please open a proper issue if you want me to investigate.
