### ISSUE TITLE
Pod install cannot read audio players licence file

### ISSUE THREAD

**Issue by michael-ottink** [luanpotter/audioplayers#578]
When I run pod install in my flutter iOS folder it generates the following error

```
[!] A license was specified in podspec `audioplayers` but the file does not exist - /Users/michaelottink/Desktop/Michael/flutterapp/ios/.symlinks/plugins/audioplayers/LICENSE.md

[!] Unable to read the license file `../LICENSE.md` for the spec `audioplayers (0.0.1)`

[!] Unable to read the license file `../LICENSE.md` for the spec `audioplayers (0.0.1)`
```

I run

audioplayers: ^0.15.1
flutter: 1.17.4

**Comment by thenexus00** [comment]
I have the same error

**Comment by whatthemehek** [comment]
me too

**Comment by MATTYGILO** [comment]
Same

**Comment by zhuyongbo100** [comment]
me too

**Comment by ventr1x** [comment]
Great, another broken and abandoned plugin. Business as usual I guess

**Comment by erickzanardo** [comment]
I have just tested our example app on the 0.15.1 tag on iOS and everything working fine. It only asked me delete the Podfile, so Flutter would recreate it on the next run (probably because the new flutter stable.

Have you tried running on the last Flutter stable.

**Comment by aavinashj** [comment]
> I have just tested our example app on the 0.15.1 tag on iOS and everything working fine. It only asked me delete the Podfile, so Flutter would recreate it on the next run (probably because the new flutter stable.
> 
> Have you tried running on the last Flutter stable.

It worked for me as well but once I removed the podfile it app does not build

**Comment by erickzanardo** [comment]
How are you building @aavinashj ? When I run `flutter run` on the terminal, the podfile is recreated.

**Comment by luanpotter** [comment]
This was fixed by https://github.com/luanpotter/audioplayers/pull/534
