### ISSUE TITLE
Duration Streams not working on Web.

### ISSUE THREAD

**Issue by NikhilSingh-NS** [luanpotter/audioplayers#579]
onDurationChanged and onAudioPositionChanged not working on web when used with Audio Cache.

**Comment by akshayru** [comment]
I guess its not supported, even i am having same issue.

**Comment by erickzanardo** [comment]
This is not supported on web yet as you can see on the readme https://github.com/luanpotter/audioplayers#streams

**Comment by erickzanardo** [comment]
Closing due inactivity
