### ISSUE TITLE
Extreme Latency on iOS when playing audio in rapid succession

### ISSUE THREAD

**Issue by zanesc** [luanpotter/audioplayers#580]
I am playing a local short sound when spinning a bonus wheel for every tick of the wheel and it is unusable on iOS. It works perfectly on Android, even on my 2013 Nexus 7 (which is very laggy for just about everything else other than this).

I have tested on an iPhone 7 and a iPhone X both with the same result. The wheel freezes while spinning due to the latency and the audio does not play fluently, like it does on Android.

**Comment by erickzanardo** [comment]
Audioplayers is not focused for this kind of use, I suggest you take a look on this package: https://pub.dev/packages/ocarina, which is focused on perfomance. Or implementing an AudioPool like the one that exists on flame_audio: https://github.com/flame-engine/flame_audio
