### ISSUE TITLE
No Support For Lock Screen Controls

### ISSUE THREAD

**Issue by amitojsingh366** [luanpotter/audioplayers#581]
No Support For Lock Screen Controls. Would love if it had lock screen controls - android

**Comment by muarachmann** [comment]
See #542 I think it tries to solve this

**Comment by erickzanardo** [comment]
Closing this as we don't plan on expanding this feature as mentioned here: https://github.com/luanpotter/audioplayers/pull/542#issuecomment-796361859

You can use audio_service to achieve this: https://pub.dev/packages/audio_service
