### ISSUE TITLE
Bug: iOS14 Simulator

### ISSUE THREAD

**Issue by cliffordh** [luanpotter/audioplayers#584]
This command:

await audioPlayer.play("sounds/CLICK12A.mp3");

causes the simulator lock up for a few seconds and doesn't play the audio. Worked fine in iOS 13 and also works on Android.

**Comment by erickzanardo** [comment]
Is iOs 14 out already? 🤔

**Comment by cliffordh** [comment]
Just an early heads up, that's why they give developers access to the iOS 14 betas :)

**Comment by erickzanardo** [comment]
> Just an early heads up, that's why they give developers access to the iOS 14 betas :)

Phew, I freaked out for a moment hahaahaha

**Comment by cliffordh** [comment]
Good news. XCode 12 beta 2 seems to have fixed the issue. Must have been a problem with the simulator?
