### ISSUE TITLE
Found a problem，It will automatically play on ios

### ISSUE THREAD

**Issue by hrongyong** [luanpotter/audioplayers#585]
Steps to reproduce
1.Play your audio（AudioPlayerState.PLAYING）
2.Then pause it(AudioPlayerState.PAUSED)
3.Switch audio app to background(AudioPlayerState.PAUSED)
4.Wait about 5 minutes(AudioPlayerState.PAUSED)
5.Switch the audio app to the foreground(PAUSED is displayed, but it is actually PLAYING)

Audio apps are likely to play directly，But the state has not changed。And I think it should not be played after switching。

This is found on the iphone, and did not find this situation on the android

**Comment by muarachmann** [comment]
This is weird, I haven't experienced this neither on physical device nor simulator. Maybe adding more info about your iOS device might help here.

**Comment by hrongyong** [comment]
Maybe it's my own problem，I added the handling of audio interruption events
code show as below：
  [[NSNotificationCenter defaultCenter] addObserver:self
                                                   selector:@selector(audioSessionWasInterrupted:)
                                                       name:AVAudioSessionInterruptionNotification
                                                     object:[AVAudioSession sharedInstance]];
- (void)audioSessionWasInterrupted:(NSNotification *)notification
{
    NSLog(@"the notification is %@",notification);
    if (AVAudioSessionInterruptionTypeBegan == [notification.userInfo[AVAudioSessionInterruptionTypeKey] intValue])
    {
        NSLog(@"begin");
        [self pause:_currentPlayerId];
    }
    else if (AVAudioSessionInterruptionTypeEnded == [notification.userInfo[AVAudioSessionInterruptionTypeKey] intValue])
    {
        NSLog(@"begin - end");
        [self resume:_currentPlayerId];
    }
}
---------------------------------------------------------
I found that the problem comes from "begin - end"，So I added this code：
       if([UIApplication sharedApplication].applicationState != UIApplicationStateBackground)
        {

            return;
        }
----------------------------------------------------------
The final code is as follows：
- (void)audioSessionWasInterrupted:(NSNotification *)notification
{
    NSLog(@"the notification is %@",notification);
    if (AVAudioSessionInterruptionTypeBegan == [notification.userInfo[AVAudioSessionInterruptionTypeKey] intValue])
    {
        NSLog(@"begin");
        [self pause:_currentPlayerId];
    }
    else if (AVAudioSessionInterruptionTypeEnded == [notification.userInfo[AVAudioSessionInterruptionTypeKey] intValue])
    {
        NSLog(@"begin - end");
        if([UIApplication sharedApplication].applicationState != UIApplicationStateBackground)
        {

            return;
        }
        [self resume:_currentPlayerId];
    }
}
----------------------------------------------------------
Although I don't know why it will "begin-end", but can prevent it from continuing to execute
My problem is temporarily resolved, so I will close issue
