### ISSUE TITLE
Attempt to call getDuration in wrong state: mPlayer=0x7a0c862fc0, mCurrentState=0

### ISSUE THREAD

**Issue by heqingbao** [luanpotter/audioplayers#588]
Multiple Loop BGM switching, occasionally unable to play error

```
E/MediaPlayerNative(25407): Attempt to call getDuration in wrong state: mPlayer=0x7a0c862fc0, mCurrentState=0
D/MediaPlayerNative(25407): Message: MEDIA_ERROR(100), ext1=Unknown MediaErrorType(-38), ext2=0x0
E/MediaPlayerNative(25407): error (-38, 0)
E/MediaPlayer(25407): Error (-38,0)
V/PlayerBase(25407): baseStop() piid=4879
I/MediaPlayer(25407): [HSM] stayAwake false uid: 11336, pid: 25407
```

**Comment by Lix-ai** [comment]
me to

**Comment by frostextreme11** [comment]
I have the same problem, no solutions yet?

**Comment by dannycortesv** [comment]
I'm also having this issue....

**Comment by ton-An** [comment]
Adding a 50ms delay between `audioPlayer.play` and `audioPlayer.getDuration` semms to have 'fixed' it for me. 
Not a pretty fix but better than nothing

**Comment by erickzanardo** [comment]
You must have called called getDuration before the player be ready, You need to use the events listener for when the player is ready, and then call the duration.

**Comment by erickzanardo** [comment]
Closing due inactivity, if there is more info that you can add to the issue, comment here and we can re open the issue.

**Comment by saquelain** [comment]
AudioPlayer audioPlayer = AudioPlayer(mode: PlayerMode.LOW_LATENCY);
