### ISSUE TITLE
Ability to recording sound

### ISSUE THREAD

**Issue by smbody** [luanpotter/audioplayers#59]
For full featured need this...

**Comment by luanpotter** [comment]
Hi, @smbody !

There seems to be already a plugin to do that: https://pub.dartlang.org/packages/audio_recorder

I have never used it though. Does it serve your need?

I think recording and playing are two separate features, many apps might need only one of those. A few need both. So I think it makes sense to have different plugins. But, if that plugin does not satisfy your needs, for some reason, and you'd like to contribute with a PR, or even create your own separate plugin, please feel free to do so.

**Comment by smbody** [comment]
Maybe you right... sorry!

**Comment by erickzanardo** [comment]
Closing this in flavor of using the `audio_recorder` lib
