### ISSUE TITLE
Preloading files with AudioCache not working in Flutter Web

### ISSUE THREAD

**Issue by etiennelenhart** [luanpotter/audioplayers#591]
Flutter Version: Beta 1.20.0-7.2.pre

When using the `loadAll()` function from `AudioCache` I get the following error in Flutter Web:

_Overflow on channel: plugins.flutter.io/path_provider.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel._

The page then also doesn't finish initializing and shows a blank screen.
Since _path_provider_ is currently not supported in Flutter Web, is preloading also simply not supported in Web builds?

**Comment by luanpotter** [comment]
It is not, yet. What we are doing for now is basically doing a request to fetch the audio file. The browser caches requests so later when the plugin tries to play it has the audio file handy. But definitely something we can improve in the future.

**Comment by etiennelenhart** [comment]
So I'd have to make manual requests for the audio files, even when they're local assets?

Thanks for the info though. Totally understandable since working with files is currently quite difficult in Flutter Web.

**Comment by luanpotter** [comment]
Yes, that is correct, and sad. Hopefully we can figure out a better way...

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
