### ISSUE TITLE
A problem occurred configuring root project 'audioplayers'.

### ISSUE THREAD

**Issue by intradept** [luanpotter/audioplayers#595]
When building the release I get an error

flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi

`A problem occurred configuring root project 'audioplayers'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
`

**Comment by muarachmann** [comment]
Are you trying to build the sample app? or another. From the error, it shows your android sdk installation is not done properly you can try to fix it by running the following `flutter config --android-sdk <path-to-your-android-sdk-path>`

Also `flutter doctor -v` will let you know if you have everything setup properly.

**Comment by luanpotter** [comment]
This seems to be a flutter configuration issue, not related to audioplayers at all...

**Comment by MikeDaniel18** [comment]
I seem to be having this issue too, what is the recommended fix?
