### ISSUE TITLE
Detect current song played in background

### ISSUE THREAD

**Issue by kadaluarsa** [luanpotter/audioplayers#599]
- is there any internal API or some method provide information on currently played music? because I have some cases and need to detect songId, song Url, and duration when music playing in the background.

**Comment by muarachmann** [comment]
None of which I know, What I use is [Flutter provider](https://pub.dev/packages/provider) which I track when a song is playing, stopped etc and I can use anywhere, anytime

**Comment by luanpotter** [comment]
No, no metadata can be extracted using audioplayers. But you can keep track of it yourself as @muarachmann suggested.
