### ISSUE TITLE
how to stop an audio playing when you press back and stop it playing in background by using flutter audio player.

### ISSUE THREAD

**Issue by pravinjyoti** [luanpotter/audioplayers#600]

**Comment by rt16** [comment]
Hey u got any solution?

**Comment by muarachmann** [comment]
> Hey u got any solution?

You can wrap your widget on a `WillPopScope` and use the `onWillPop: _onBackPressed,` to determine if the user pressed the back button and stop the player manually. Hope that helps. If you haven't heard about WillPopScope here is a nice tutorial that should give you some clue - https://medium.com/@iamatul_k/flutter-handle-back-button-in-a-flutter-application-override-back-arrow-button-in-app-bar-d17e0a3d41f or course you can see its implemenation class here - https://api.flutter.dev/flutter/widgets/WillPopScope-class.html

**Comment by luanpotter** [comment]
Thanks @muarachmann .
