### ISSUE TITLE
android 10 can't play audio

### ISSUE THREAD

**Issue by tingyuyinlu** [luanpotter/audioplayers#602]
added android:usesCleartextTraffic="true" within AndroidManifest.xml already.

export:
V/MediaHTTPService(31703): MediaHTTPService(android.media.MediaHTTPService@4b5d6f9): Cookies: null
V/MediaHTTPService(31703): makeHTTPConnection: CookieHandler (java.net.CookieManager@643c56) exists.
V/MediaHTTPService(31703): makeHTTPConnection(android.media.MediaHTTPService@4b5d6f9): cookieHandler: java.net.CookieManager@643c56 Cookies: null
D/MediaPlayerNative(31703): Message: Unknown MediaEventType(8), ext1=0, ext2=0x0
D/MediaPlayerNative(31703): Action:reset_l, CurrentState:MEDIA_PLAYER_IDLE
V/MediaPlayer(31703): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(31703): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/PlayerBase(31703): baseRelease() piid=1815 state=4
I/MediaPlayer(31703): [HSM] stayAwake false uid: 10317, pid: 31703
V/MediaPlayer(31703): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(31703): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/MediaPlayerNative(31703): Pid:31703 MediaPlayer destructor MediaPlayer(0x7b2580df00)
I/MediaPlayer(31703): [HSM] stayAwake false uid: 10317, pid: 31703
I/AudioTrack(31703): recheck for pg, sessionid : 1953
I/AudioTrack(31703): recheck for pg, sessionid : 1961
V/PlayerBase(31703): baseRelease() piid=1815 state=0
V/PlayerBase(31703): baseRelease() piid=1807 state=0
I/AudioTrack(31703): recheck for pg, sessionid : 1953
I/AudioTrack(31703): recheck for pg, sessionid : 1961
I/AudioTrack(31703): recheck for pg, sessionid : 1953
I/AudioTrack(31703): recheck for pg, sessionid : 1961
I/AudioTrack(31703): recheck for pg, sessionid : 1953
I/AudioTrack(31703): recheck for pg, sessionid : 1961

**Comment by stonekase** [comment]
Having the same issue

**Comment by erickzanardo** [comment]
Have you checked if Android supports that file? What is the url in question, need more info

**Comment by luanpotter** [comment]
Closing for lack of response, please open a new issue with more details if this still occurs in the latest version.
