### ISSUE TITLE
how to custom notification?

### ISSUE THREAD

**Issue by JimmyKent** [luanpotter/audioplayers#603]
In iOS notification，There is two button: forwardSkipInterval and backwardSkipInterval，Is it any method to custom those two button? for example, I want to change to prev and next audio.

**Comment by muarachmann** [comment]
@JimmyKent you can see #598

**Comment by JimmyKent** [comment]
> @JimmyKent you can see #598

I test #598 , It work well in Sample, can this commit merge and update a new version?

**Comment by luanpotter** [comment]
It is already merged.
