### ISSUE TITLE
sample in setNotification imageUrl

### ISSUE THREAD

**Issue by JimmyKent** [luanpotter/audioplayers#604]
have any sample in setNotification imageUrl?
imageUrl use http type is ok. but I wanna use local image, like: 'assets/image/avatar.png'.
How can I do?

here is my code to save image to phone, and imageUrl: imageUrl, but it doesn't work.

`  
Future<void> test () async {
    imageUrl = '${(await getApplicationSupportDirectory()).path}/avatar.png';
    print('copy image imageUrl $imageUrl');
    final File file = File(imageUrl);
    // ignore: avoid_slow_async_io
    final bool exists = await file.exists();
    if (!exists) {
      file.writeAsBytes((await AssetsUtils.fetchAsset('iamges/avatar.png')).buffer.asUint8List());
    }
  }
`

**Comment by muarachmann** [comment]
@JimmyKent pass the `isLocal` in your player by default it is `false`, you just need to tell it to be `true` or you can do a
`audioPlayer.setUrl(url, isLocal: true);`

**Comment by JimmyKent** [comment]
I wanna set imageUrl, not the url.
setNotifacation(imageUrl: 'assets/image/avatar.png');

_audioPlayer.setNotification(
  title: 'App Name',
  artist: 'Artist or blank',
  albumTitle: 'Name or blank',
  imageUrl: 'https://img2.woyaogexing.com/2020/08/14/b2963eacf87a4d3aa1f9850bcf70a477!400x400.jpeg', // work
 **// imageUrl: 'assets/images/avatar.png', // didn't work.**
  duration: duration,
  elapsedTime: Duration(seconds: 0),
  hasNextTrack: true,
  hasPreviousTrack: true,
);

**Comment by muarachmann** [comment]
Hi @JimmyKent I have never tried this, Will check...

**Comment by luanpotter** [comment]
you will probably need to send a PR to support this

**Comment by muarachmann** [comment]
@luanpotter I would love to begin a PR on this just some thoughts, can we have a flag to know if we are loading remotely or locally same like with the audio file?

**Comment by luanpotter** [comment]
yes that makes sense. I just extracted this code into a NotificationsHandler file so should be easy to jump in @muarachmann (see my current PR that I shall merge soon)

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
