### ISSUE TITLE
can't find interrupt callback

### ISSUE THREAD

**Issue by JimmyKent** [luanpotter/audioplayers#606]
in iOS, I play audio in background, open another player and play song, I can't find any callback, but it's pause.
I have ever try 
onPlayerStateChanged 
onDurationChanged 
onPlayerCompletion
onPlayerError
onNotificationPlayerStateChanged
onAudioPositionChanged

all of them didn't callback.

**Comment by geedevelopers** [comment]
Same here

**Comment by luanpotter** [comment]
sorry, I don't quite understand what you are talking about. please provide:

* some code reproducing the problem
* what you expect to see vs what happens
* what platforms you tested it in, in detail

**Comment by luanpotter** [comment]
Please follow the issue template carefully, otherwise I will just close the issue.

**Comment by JimmyKent** [comment]
in Android, we have a callback as onAudioFocusChange, when audio player is interrupt by other application. then we can change play button in player's view.
in this player, I can't find some callbacks like this.

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening

**Comment by fullflash** [comment]
onPlayerStateChanged is not triggered when user receives incoming call. and there is no other callbacks as issue owner mentioned. why issue is closed ?
