### ISSUE TITLE
Playing a sound mutes microphone when recording a video

### ISSUE THREAD

**Issue by jpiabrantes** [luanpotter/audioplayers#610]
When I play a local sound:
`_audioCache.play(sound, mode: PlayerMode.LOW_LATENCY);`

while recording a video, the video stops capturing sound from the microphone.

**Comment by jacksonw765** [comment]
I had this issue also so I investigated it more. I think this is just the way iOS handles recording and playing a sound effect at the same time. Would love to have a workaround. Works fine in Android.

**Comment by jpiabrantes** [comment]
I ended up using Soundpool, works for iOs and Android.

**Comment by luanpotter** [comment]
The work around has arrived: use the new `recordingActive` param (on master, will deploy later this week).

**Comment by jacksonw765** [comment]
Haven't tested yet but thanks so much!
