### ISSUE TITLE
play audio with http header

### ISSUE THREAD

**Issue by hesham91fci** [luanpotter/audioplayers#611]
Does anyone knows how to play a remote http file along with sending http headers, since the remote file requires "Authorization" header

Best regards

**Comment by alainseys** [comment]
remote like as in webradio ?

**Comment by qianciling** [comment]
> remote like as in webradio ?

I need this
for android, call `MediaPlayer.setDataSource(Context context, Uri uri,Map<String, String> headers, List<HttpCookie> cookies)`

**Comment by bert1100** [comment]
i haved the same question～

**Comment by fdietze** [comment]
I'm trying to implement this right now: https://github.com/luanpotter/audioplayers/pull/806
But I'm a bit stuck with the details. Any help is appreciated.

**Comment by luanpotter** [comment]
Closing in lieu of https://github.com/luanpotter/audioplayers/issues/129
