### ISSUE TITLE
Upgrading to 0.16.0 crashes on iOS

### ISSUE THREAD

**Issue by m-j-g** [luanpotter/audioplayers#613]
AudioCache cache = AudioCache();
cache.play(filePath());

Crashes on iOS.  Works on 0.15.1

both work on Android.

**Comment by ParsaRbn** [comment]
having the same issue

**Comment by wednesday** [comment]
try ```flutter build ios --release```

**Comment by ParsaRbn** [comment]
> try `flutter build ios --release`

Thanks
i tried it, but it dosent work.

**Comment by neonfink** [comment]
+1, adding the basic code from readme causes the app to crash on iOS simulator and physical device, same code snippet works after rolling back to 0.15.1

**Comment by luanpotter** [comment]
Looking at this rn, thanks for the feedback

**Comment by tnaseem** [comment]
Having the same issue here on iOS (tested on iPhone 7, iOS 13.6 and iPhone SE, iOS 13.6). Running a debug, it just drops out with a  'Lost connection to device', when I call `_audioCache.play()`.

I have stepped through the code and I think it's somewhere inside the `_invokeMethod()` call in `platform_channel.dart`, but I could be wrong! I just did a quick run through to see if I could spot anything.

Works fine on Android.

**Comment by luanpotter** [comment]
it is, you are right. it was because of a param being null. I fixed on master. I will release a new version later today. please lmk if it works.

**Comment by molundb** [comment]
happening to me too

**Comment by beersheba** [comment]
> it is, you are right. it was because of a param being null. I fixed on master. I will release a new version later today. please lmk if it works.

^0.16.1 cannot be resolved

```
/Users/andrey/flutter/bin/flutter --no-color pub get
Running "flutter pub get" in xylophone-flutter...               
Because xylophone depends on audioplayers ^0.16.1 which doesn't match any versions, version solving failed.
pub get failed (1; Because xylophone depends on audioplayers ^0.16.1 which doesn't match any versions, version solving failed.)
Process finished with exit code 1
```

**Comment by tnaseem** [comment]
> ^0.16.1 cannot be resolved

That's because it hasn't been released to pubdev yet. You need to grab the `master` branch instead. I will try this tomorrow, myself.

**Comment by tnaseem** [comment]
If you want to try out the latest 0.16.1 with the fix, you can load the package directly from the `master` branch, by updating:

`
audioplayers: ^0.16.0
`

to:

```
  # Loading from master branch to get around iOS crash in 0.16.0
  audioplayers:
    git:
      url: git://github.com/luanpotter/audioplayers.git
```

Give that a go and see if it helps. Obviously, once 0.16.1 has been published, revert back to `audioplayers: ^0.16.1`!

**Comment by tnaseem** [comment]
> it is, you are right. it was because of a param being null. I fixed on master. I will release a new version later today. please lmk if it works.

It works on iOS  now, thanks! However, I'm getting a 

```
flutter: Fatal Error: Callback lookup failed!
```

when it finishes playing each file.

**Comment by ivan-pavliuk** [comment]
Any updates on it?

**Comment by RizanPSTU** [comment]
I am also getting flutter: Fatal Error: Callback lookup failed!

**Comment by qipingwu** [comment]
> > it is, you are right. it was because of a param being null. I fixed on master. I will release a new version later today. please lmk if it works.
> 
> ^0.16.1 cannot be resolved
> 
> ```
> /Users/andrey/flutter/bin/flutter --no-color pub get
> Running "flutter pub get" in xylophone-flutter...               
> Because xylophone depends on audioplayers ^0.16.1 which doesn't match any versions, version solving failed.
> pub get failed (1; Because xylophone depends on audioplayers ^0.16.1 which doesn't match any versions, version solving failed.)
> Process finished with exit code 1
> ```

Are you talking Angela's class?
I am having problem playing sound.

**Comment by qipingwu** [comment]
> it is, you are right. it was because of a param being null. I fixed on master. I will release a new version later today. please lmk if it works.

Hello!
I think in the dart package website, the newest version is still audioplayers: ^0.16.0.
If I put audioplayers: ^0.16.1 in pubspec.yaml, I get this error: 

Running "flutter pub get" in getitdone...                       
Because getitdone depends on audioplayers ^0.16.1 which doesn't match any versions, version solving failed.
pub get failed (1; Because getitdone depends on audioplayers ^0.16.1 which doesn't match any versions, version solving failed.)
Process finished with exit code 1

**Comment by muarachmann** [comment]
@qipingwu it hasn't been published to pubdev, use git versioning in your yalm file to point to master, time for it to get up.

I will quote this previously said
> If you want to try out the latest 0.16.1 (with the fix), before it's published, you can load the package directly from the `master` branch, by updating:
> 
> `audioplayers: ^0.16.0`
> 
> to:
> 
> ```
>   audioplayers:
>     git:
>       url: git://github.com/luanpotter/audioplayers.git
> ```
> 
> Give that a go and see if it helps. Obviously, once 0.16.1 has been published, revert back to `audioplayers: ^0.16.1`!

**Comment by MrDEV0** [comment]
> it is, you are right. it was because of a param being null. I fixed on master. I will release a new version later today. please lmk if it works.

Thanks a lot, it works, looking forward to have this fix published on pub.dev.

**Comment by MrDEV0** [comment]
> it is, you are right. it was because of a param being null. I fixed on master. I will release a new version later today. please lmk if it works.

Thanks a lot, it works for me, looking forward to have this fix published on pub.dev.

**Comment by Naranmandakh** [comment]
version ^0.16.1 and iPhoneX simulator

```
2020-09-08 11:10:17.063101+0800 Runner[50170:1232328] iOS => call startHeadlessService, playerId 88360b42-8e2a-4224-afec-47632ee9b8d4
2020-09-08 11:10:17.089744+0800 Runner[50170:1232328] iOS => call play, playerId 88360b42-8e2a-4224-afec-47632ee9b8d4
2020-09-08 11:10:17.089863+0800 Runner[50170:1232328] play!
2020-09-08 11:10:17.090013+0800 Runner[50170:1232328] -[NSNull boolValue]: unrecognized selector sent to instance 0x10e023ef0
2020-09-08 11:10:17.131248+0800 Runner[50170:1232328] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull boolValue]: unrecognized selector sent to instance 0x10e023ef0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010dd5a12b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010cd0df41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010dddb024 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010dcdcf78 ___forwarding___ + 1432
	4   CoreFoundation                      0x000000010dcdc958 _CF_forwarding_prep_0 + 120
	5   audioplayers                        0x000000010c58bf23 __46-[AudioplayersPlugin handleMethodCall:result:]_block_invoke.83 + 1827
	6   audioplayers                        0x000000010c58ae87 -[AudioplayersPlugin handleMethodCall:result:] + 4583
	7   Flutter                             0x000000010a1b4976 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	8   Flutter                             0x00000001099c012a _ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 166
	9   Flutter                             0x00000001099c4bc8 _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 38
	10  Flutter                             0x0000000109cfe847 _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_33NS_9allocatorIS8_EEFvvEEclEv + 83
	11  Flutter                             0x00000001099ccba7 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 117
	12  Flutter                             0x00000001099d1636 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	13  CoreFoundation                      0x000000010dcea174 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	14  CoreFoundation                      0x000000010dce9e32 __CFRunLoopDoTimer + 1026
	15  CoreFoundation                      0x000000010dce99ea __CFRunLoopDoTimers + 266
	16  CoreFoundation                      0x000000010dce1404 __CFRunLoopRun + 2308
	17  CoreFoundation                      0x000000010dce0889 CFRunLoopRunSpecific + 409
	18  GraphicsServices                    0x00000001158009c6 GSEventRunModal + 62
	19  UIKit                               0x000000010e2e75d6 UIApplicationMain + 159
	20  Runner                              0x0000000107623f7b main + 75
	21  libdyld.dylib                       0x0000000111fd1d81 start + 1
	22  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by joaowd** [comment]
I still get the error 'Fatal Error: Callback lookup failed!' after each play.

**Comment by beersheba** [comment]
> > > it is, you are right. it was because of a param being null. I fixed on master. I will release a new version later today. please lmk if it works.
> > 
> > 
> > ^0.16.1 cannot be resolved
> > ```
> > /Users/andrey/flutter/bin/flutter --no-color pub get
> > Running "flutter pub get" in xylophone-flutter...               
> > Because xylophone depends on audioplayers ^0.16.1 which doesn't match any versions, version solving failed.
> > pub get failed (1; Because xylophone depends on audioplayers ^0.16.1 which doesn't match any versions, version solving failed.)
> > Process finished with exit code 1
> > ```
> 
> Are you talking Angela's class?
> I am having problem playing sound.

yes. this version works
`audioplayers: ^0.15.1`

**Comment by luanpotter** [comment]
This has been fixed, please open a new issue for the `Fatal Error: Callback lookup failed!` thing with details, definitely it seems like an unrelated issue. If the original issue (param being null) still persists please lmk and I can re-open this.

**Comment by mustafabhatkar** [comment]
Hey @luanpotter `Fatal Error: Callback lookup failed!` is already open at #344

**Comment by erickisos** [comment]
Hey guys, I'm having this issue with the version 0.20.1
