### ISSUE TITLE
 After playing the music with the same audioCache in a loop, if you play a non-loop, it will be played in a loop.

### ISSUE THREAD

**Issue by HirokiIshimori** [luanpotter/audioplayers#618]
In my research, I suspect that the cause is probably that I haven't set `player.setReleaseMode(ReleaseMode.STOP);` before processing `player.play` in this `play` method.
I've confirmed that when I do this, it plays in a non-loop without any problems.

https://github.com/luanpotter/audioplayers/blob/c20b07fc5d90f25d26a2c5b318d600f5f4986d7d/lib/audio_cache.dart#L104-L121

Here is the response I tried.

```
Future<AudioPlayer> play(String fileName,
      {double volume = 1.0,
      bool isNotification,
      PlayerMode mode = PlayerMode.MEDIA_PLAYER,
      bool stayAwake}) async {
    String url = await getAbsoluteUrl(fileName);
    AudioPlayer player = _player(mode);
    player.setReleaseMode(ReleaseMode.STOP);    // added.
    await player.play(
      url,
      volume: volume,
      respectSilence: isNotification ?? respectSilence,
      stayAwake: stayAwake,
    );
    return player;
  }
```

**Comment by HirokiIshimori** [comment]
This is a bug of the case where `fixedPlayer` is set in `AudioCache`

**Comment by luanpotter** [comment]
yup that is a bug, though I consider if we should make it STOP or RELEASE (maybe a new optional param?)

for now I think STOP is fine. maybe an if its release => change to stop or something. would you like to submit a PR adding this fix? thank you so much for reporting!

**Comment by HirokiIshimori** [comment]
Merged.
https://github.com/luanpotter/audioplayers/pull/632
