### ISSUE TITLE
Playing a large amount of sound obviously delays the sound playing.

### ISSUE THREAD

**Issue by HirokiIshimori** [luanpotter/audioplayers#619]
If you play a lot of sounds without using fixedPlayer, the queue will overflow.

Specifically, the sound playback is clearly delayed.

I suspect that the cause is that, unless `fixedPlayer` is used, an `AudioPlayer` is generated each time it sounds.

https://github.com/luanpotter/audioplayers/blob/c20b07fc5d90f25d26a2c5b318d600f5f4986d7d/lib/audio_cache.dart#L93-L96

I'm not sure if this is correct, but using map to manage resources and using fixedplayer solved the problem.
```
class MyAudio {
  static Map _audioMap = Map();

  static void perpare() {
    _audioMap.addAll({
      'sound/se/a.wav' : new AudioCache(fixedPlayer: new AudioPlayer()),
      'sound/se/b.wav' : new AudioCache(fixedPlayer: new AudioPlayer()),
      'sound/se/c.wav' : new AudioCache(fixedPlayer: new AudioPlayer()),
    });

    _audioMap.forEach((key, value) {
      value.load(key);
    });
  }

  static void play(String soundPath, {double volume = 1.0}) {
    _audioMap[soundPath].play(soundPath, volume: volume);
  }
}
```

**Comment by luanpotter** [comment]
Your solution makes sense to me, that is exactly why fixedPlayer exists. They have different behaviors. By using fixedPlayer as you did, it will not play the same sound over itself. It will stop the previous playing sound when you call play again. So it's up to you. Also please check Flame's AudioPool class if you want to quick fire a lot of short audios w/o stopping the previous one.
