### ISSUE TITLE
【Bug】Failed on iOS simulator when trying remote audio url

### ISSUE THREAD

**Issue by SmallStoneSK** [luanpotter/audioplayers#62]
I've tried successfully local file using AudioCache but failed when trying remote audio url. And when I enable the log function, I got this 【error info】:

_platformCallHandler call audio.onError {playerId: 6d0cadd3-8420-4f8a-a05b-14e0c0d8af54, value: AVPlayerItemStatus.failed}

**Comment by luanpotter** [comment]
Hi, @SmallStoneSK!

For remote urls, use the AudioPlayer class, not AudioCache. AudioCache is for storing local assets to the cache memory only.

Something like this (I can't test right now, but apart from minor syntax issues this should work):

```dart
    AudioPlayer p = new AudioPlayer();
    p.play('http://my.remote.host', remote: true);
```

**Comment by SmallStoneSK** [comment]
Hi, @luanpotter 

Yeah, I use AudioPlayer for trying remote audio url.

My code is just like following:

`
AudioPlayer player = AudioPlayer();
player.play('http://www.rxlabz.com/labz/audio.mp3', isLocal: false);
`

but it does not work.

**Comment by SmallStoneSK** [comment]
Hi, @luanpotter 

I'm not sure whether I use this lib wrongly. Sadly, I failed again when trying on android simulator.

My code is following:

```dart
AudioPlayer.logEnabled = true;
AudioPlayer player = new AudioPlayer();
player.play('http://www.rxlabz.com/labz/audio.mp3', isLocal: false);
```

And I get these error information this time:

V/MediaHTTPService(31308): MediaHTTPService(android.media.MediaHTTPService@8853614): Cookies: null
V/MediaHTTPService(31308): makeHTTPConnection: CookieHandler (java.net.CookieManager@2ea5e8b) exists.
V/MediaHTTPService(31308): makeHTTPConnection(android.media.MediaHTTPService@8853614): cookieHandler: java.net.CookieManager@2ea5e8b Cookies: null
E/MediaPlayerNative(31308): error (1, -2147483648)
E/MediaPlayer(31308): Error (1,-2147483648)
E/MediaPlayerNative(31308): stop called in state 0, mPlayer(0xcdb23320)
E/MediaPlayerNative(31308): error (-38, 0)
V/MediaPlayer(31308): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(31308): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(31308): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(31308): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/flutter (31308): _platformCallHandler call audio.onComplete {value: true, playerId: 6aee94d8-a572-4ced-8062-72247823d30a}

**Comment by yshahak** [comment]
Hi, first thanks for the package. I'm newbie to Flutter, and my background is limited to `Android`, so in my code, when I run my remote url on Android, it's works just fine, but on IPhone simulator, when I'm doing the following:
`audioPlayer.play("http://www.remote.domain/1a.mp3", isLocal: false);`
I'm getting this:
`setUrl http://www.remote.domain/1a.mp31a.mp3
    "LocalDataTask <915FC3B9-F0B6-4C70-A616-A93055BA78D8>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <915FC3B9-F0B6-4C70-A616-A93055BA78D8>.<1>, NSUnderlyingError=0x600001fea3a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1022 "(null)"}} [-1022]
player status: 2`

**Comment by erickzanardo** [comment]
Closing this due inactivity, if the problem still persist, please open a new issue
