### ISSUE TITLE
Crash on iOS when trying to play sound from cache

### ISSUE THREAD

**Issue by molundb** [luanpotter/audioplayers#620]
flutter -v

[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.5 19F101, locale en-DE)
    • Flutter version 1.20.2 at /Users/marg/Dev/flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/marg/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2019.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 8 (mobile)                  • 4DCC5893-6F30-417E-AEC3-5A8D0E705B99 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

! Doctor found issues in 2 categories.

Hi everyone. I am trying to play an mp3 sound. It is working on Android devices/emulators, but whenever I try to play the sound on an iOS device/simulator my app crashes. 

Crash output from XCode:

2020-09-01 13:24:53.973493+0200 Runner[70875:2723017] flutter: Observatory listening on http://127.0.0.1:49301/ApuP6znXsHQ=/
2020-09-01 13:24:54.646524+0200 Runner[70875:2722427] iOS => call startHeadlessService, playerId 30707baf-dad0-46db-8eda-73b93283e37e
2020-09-01 13:24:56.589596+0200 Runner[70875:2722427] iOS => call play, playerId 30707baf-dad0-46db-8eda-73b93283e37e
2020-09-01 13:24:56.589754+0200 Runner[70875:2722427] play!
2020-09-01 13:24:56.589878+0200 Runner[70875:2722427] -[NSNull boolValue]: unrecognized selector sent to instance 0x7fff8062db10
2020-09-01 13:24:56.630109+0200 Runner[70875:2722427] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull boolValue]: unrecognized selector sent to instance 0x7fff8062db10'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3de6e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff512539b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e5eb94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23e4286c ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23e44b58 _CF_forwarding_prep_0 + 120
	5   audioplayers                        0x000000010f201f33 __46-[AudioplayersPlugin handleMethodCall:result:]_block_invoke.83 + 1827
	6   audioplayers                        0x000000010f200e97 -[AudioplayersPlugin handleMethodCall:result:] + 4583
	7   Flutter                             0x000000010d817976 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	8   Flutter                             0x000000010d02312a _ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 166
	9   Flutter                             0x000000010d027bc8 _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 38
	10  Flutter                             0x000000010d361847 _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_33NS_9allocatorIS8_EEFvvEEclEv + 83
	11  Flutter                             0x000000010d02fba7 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 117
	12  Flutter                             0x000000010d034636 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	13  CoreFoundation                      0x00007fff23da2414 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	14  CoreFoundation                      0x00007fff23da20ae __CFRunLoopDoTimer + 1038
	15  CoreFoundation                      0x00007fff23da170a __CFRunLoopDoTimers + 282
	16  CoreFoundation                      0x00007fff23d9c35e __CFRunLoopRun + 1950
	17  CoreFoundation                      0x00007fff23d9b8a4 CFRunLoopRunSpecific + 404
	18  GraphicsServices                    0x00007fff38c39bbe GSEventRunModal + 139
	19  UIKitCore                           0x00007fff49325968 UIApplicationMain + 1605
	20  Runner                              0x000000010cd8e06b main + 75
	21  libdyld.dylib                       0x00007fff520ce1fd start + 1
	22  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

My code:

main.dart
```
import 'package:audioplayers/audio_cache.dart';
import 'package:audioplayers/audioplayers.dart';
import 'package:my_app/sounds.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Title,
      theme: ThemeData(
        primarySwatch: Colors.green,
      ),
      home: MyHomePage(title: 'Title'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<String> _headshots = [
    'assets/images/image.jpeg',
  ];

  AudioCache audioCache;
  AudioPlayer audioPlayer;

  final List _sounds = Sounds().sounds;

  @override
  void initState() {
    super.initState();
    initSounds();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: GridView.builder(
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
          crossAxisCount: 3,
          mainAxisSpacing: 15,
          crossAxisSpacing: 15,
        ),
        itemBuilder: (BuildContext context, int index) => GestureDetector(
          child: Container(
            decoration: BoxDecoration(
              image: DecorationImage(
                image: AssetImage(_headshots[0]),
                fit: BoxFit.contain,
              ),
            ),
            child: Container(),
          ),
          onTap: () {
            if (mounted) {
              setState(() {
                playSound(_sounds[0]);
              });
            }
          },
        ),
        primary: false,
        padding: const EdgeInsets.all(30),
      ),
    );
  }

  void initSounds() async {
    audioPlayer = AudioPlayer();
    audioCache = AudioCache(fixedPlayer: audioPlayer);
    audioCache.loadAll(_sounds);
  }

  void playSound(sound) async {
    var fileName = sound;
    if (audioPlayer.state == AudioPlayerState.PLAYING) {
      audioPlayer.stop();
    }
    audioPlayer = await audioCache.play(fileName);
  }
}
```

sounds.dart
```
class Sounds {
  List<String> _sounds = [
    'sounds/sound.mp3',
  ];
  get sounds => _sounds;
}
```

I have been unable at finding an answer to this problem. Does anyone have an idea how this could be fixed? I am using audioplayers 0.16.0.

**Comment by dishcheng** [comment]
ipad pro2020 alse!!!!

**Comment by jacksonw765** [comment]
This is an issue for me as well.

**Comment by tnaseem** [comment]
This has already been reported here: https://github.com/luanpotter/audioplayers/issues/613.

The fix is currently on the master branch.

**Comment by luanpotter** [comment]
Closing this in favor of #613.
