### ISSUE TITLE
How to loop two songs one after the another

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [luanpotter/audioplayers#624]
How to loop two songs one after the another. I have two audio files in my local assets folder. How to loop playing these two files one after the another continuously.

**Comment by muarachmann** [comment]
Hi, you can have a `List<Songs>` to hold  the songs and just listen on the `_audioPlayer.onPlayerCompletion` . In general, I usually do this to play musics in a List.  the `next()` just iterates and plays the next song 
```
_audioPlayer.onPlayerCompletion.listen((event) {
      if (isRepeat) {
        play(currentSong);
      } else {
        next();
      }
    });
``

**Comment by kpradeepkumarreddy** [comment]
> Hi, you can have a `List<Song>` to hold the songs and just listen on the `_audioPlayer.onPlayerCompletion` . In general, I usually do this to play musics in a List. the `next()` just iterates and plays the next song
> 
> ```
> _audioPlayer.onPlayerCompletion.listen((event) {
>       if (isRepeat) {
>         play(currentSong);
>       } else {
>         next();
>       }
>     });
> ``
> ```

Thanks. I will try this.  Can we also know if audio player is currently playing any song or not, like isPlaying() ??

**Comment by luanpotter** [comment]
@kpradeepkumarreddy you can use `audioPlayer.state` directly or listen to `onPlayerStateChanged`.

@muarachmann thanks you so much for helping with the issues, sometimes it's very hard for me to keep up!

**Comment by kpradeepkumarreddy** [comment]
> @kpradeepkumarreddy you can use `audioPlayer.state` directly or listen to `onPlayerStateChanged`.
> 
> @muarachmann thanks you so much for helping with the issues, sometimes it's very hard for me to keep up!

Thanks
