### ISSUE TITLE
AudioCache stop the background music player

### ISSUE THREAD

**Issue by JmyW** [luanpotter/audioplayers#625]
My app uses AudioCache to play simple click sound when user clicks any action. The click.wav is a 100ms WAV file in assets. It's running well. But if the device is using a music player whatever native or download from store and play music in background. When my app play the click sound, the music is stop. It will resume playback once I leave my app. It's supposed to resume playback as soon as the click sound play finished.  Could you check? thanks.

**Comment by JmyW** [comment]
This phenomenon is only happened in iOS, fine in Android.

**Comment by JmyW** [comment]
Any comment?

**Comment by wonpyohong** [comment]
I have same problem

**Comment by luanpotter** [comment]
this will probably be fixed by merging the duck audio PR

**Comment by JmyW** [comment]
> this will probably be fixed by merging the duck audio PR

Thanks for reply. Yes, that should be audio ducking on such scenario. But how?

On my Android(java) and Swift experience, that is not a work on player. I do have an app publishing in both iOS and Android store which can play youtube music. I can keep playing after another app play a short notified sound without any additional code design or settings. So, I believe that should be effort in system side or what audio play command the app is using for play the short audio.

**Comment by luanpotter** [comment]
Take a look at: https://github.com/luanpotter/audioplayers/pull/559

it will add a new bool param duckAudio. I have a few comments but should be merged in a timely manner.

please lmk if that is what you wanted or if your use case doesn't fit.

**Comment by JmyW** [comment]
@luanpotter Yes!!! it works. Thank you so much!
