### ISSUE TITLE
 Unable to load asset (prefix: "sounds/" -> prefix: "assets/sounds/")

### ISSUE THREAD

**Issue by adrianvintu** [luanpotter/audioplayers#627]
I believe `audioplayers: ^0.16.1` introduced a breaking change from `audioplayers: ^0.15.1`

I used to have `static final instance = AudioCache(prefix: "sounds/")`

When playing `instance.play(...)` I would now (0.16.1) get an exception `Unhandled Exception: Unable to load asset: sounds/...`

I changed initialization to `AudioCache(prefix: "assets/sounds/")`  and now it works as expected.

I got the idea from https://github.com/luanpotter/audioplayers/pull/597

**Comment by laurensdewaele** [comment]
Thank you for the fix ;)

**Comment by luanpotter** [comment]
It did. You got it exactly right. Please check the changelog :)

The reason was to allow for people to use different folders if they wanted

**Comment by mikeesouth** [comment]
Hmm, is this breaking change documented in the changelog? I cannot see it in this changelog but maybe it's documented in some other changelog? https://github.com/luanpotter/audioplayers/blob/master/CHANGELOG.md
