### ISSUE TITLE
How to get state playing,  pause , stop on current Player

### ISSUE THREAD

**Issue by phuongphally** [luanpotter/audioplayers#63]
Thanks for your nice package! 

I would like to ask you a question , 

I use video_player package then can get state well . But it don't work on background when device locked screen. 

In video_player package
#VideoPlayerController _controller

-_controller.value.initialized
-_controller.value.isPlaying
-_controller.value.current 

How about your package? Because I'm can not see in the document. 

Thanks

**Comment by localpcguy** [comment]
In the example and in my code, you have to keep track of the current state in your own stateful widget that wraps the audioplayers widget. I'd also like to see the player maintain it's own state and expose it as a public property.

**Comment by erickzanardo** [comment]
A PR for handling the player was just merged, I think this is what you need?

https://github.com/luanpotter/audioplayers/pull/68

**Comment by erickzanardo** [comment]
Closing this, in case the merged PR does not provide what you need, please open a new issue
