### ISSUE TITLE
No implementation found for method setNotification on channel xyz.luan/audioplayers

### ISSUE THREAD

**Issue by zekkontro** [luanpotter/audioplayers#635]
I have a problem. No implementation found for method setNotification on channel xyz.luan/audioplayers. 

My setNotification code: ```
setNotification() async {
    await advancedPlayer.setNotification(
        albumTitle: "Beatifun Music",
        artist: video.snippet.channelTitle,
        duration: _duration,
        elapsedTime: _position,
        backwardSkipInterval: Duration(seconds: 10),
        forwardSkipInterval: Duration(seconds: 10),
        imageUrl: video.snippet.thumbnails.high.url,
        title: video.snippet.title);
  }
```
How can I solve this problem? Help me please!

**Comment by kaina404** [comment]
pod install

**Comment by zekkontro** [comment]
how so

**Comment by luanpotter** [comment]
I'm pretty sure the "setNotification" method is not impl on android. can you please make sure it works on ios?

Also, please format your code properly next time and follow our issue template.

**Comment by luanpotter** [comment]
Closing due to lack of response.
