### ISSUE TITLE
Stop Fucking Music

### ISSUE THREAD

**Issue by thatsenam** [luanpotter/audioplayers#636]
// import in the begining of the file
    import 'package:audioplayers/audio_cache.dart';

    // add it to your class as a static member
    static AudioCache player = AudioCache();
    // or as a local variable
    final player = AudioCache();

    // call this method when desired
    player.play('explosion.mp3');

how to stop the audio??

**Comment by erickzanardo** [comment]
player returns an AudioPlayer instance and you can use it to stop

```
final player = await audioCache.play('bla.mp3');
player.stop();
```

Please be respectful on your issues titles and description!

**Comment by unrealsmart** [comment]
暴躁老哥，在线嘶吼。
非常感谢 @erickzanardo ，这同时也解决了我的问题

**Comment by erickzanardo** [comment]
> 暴躁老哥，在线嘶吼。
> 
> 非常感谢 @erickzanardo ，这同时也解决了我的问题

Sorry but I don't understand, use English please
