### ISSUE TITLE
ios can not get the event

### ISSUE THREAD

**Issue by caipeng-hrv** [luanpotter/audioplayers#637]
AudioPlayer _audioPlayer = AudioPlayer();

_audioPlayer.onAudioPositionChanged.listen((Duration p) async {
     print(p)
 });

_audioPlayer.play(path, isLocal: true);

ios 10.0, flutter version 1.20.3

**Comment by luanpotter** [comment]
Please follow the issue template carefully, otherwise I will just close the issue.

**Comment by erickzanardo** [comment]
Closing due inactivity, if there is more info that you can add to the issue, comment here and we can re open the issue.
