### ISSUE TITLE
Support for metadata

### ISSUE THREAD

**Issue by pspatel602** [luanpotter/audioplayers#638]
Requested feature : Fetching metadata from audio files.

**Full Description**

Metadata of an audio file is most important things in audio related apps. With the help of meta data we can use title, author name, artist name, album name, cover image and other details so we can use those details in our app to list the music items and able to create different groups or partition accordingly. For example if we create the music app so if the 6 songs is from imagine dragon and other 6 song from one republic and also some if some songs of imagine dragon but from different album so we can categories them based on certain criteria of metadata. 

In [assets_audio_player ](https://pub.dev/packages/assets_audio_player) we can add metadata manually but could not fetch existing metadata from the files. And as far as i know through exploring the other audio packages in pub.dev most of other packages does not support that.

**Example Code**
```
_audioPlayer.fetchMetadata(String dir){
   // That can able to return meta data from selected files
   // And if possible for all files based on selected directory
}
```

**Platforms**

feature needed most in this platform right now => Android, IOS

**Comment by luanpotter** [comment]
Please check: https://github.com/luanpotter/audioplayers/blob/master/feature_parity_table.md#other-features

Metadata from files is out of scope for `audioplayers`. It can be implemented on a new package, could even be called `audioplayers_metadata`. But it has nothing to do with playing audio and sound effects.

I will close this issue but if you are willing to contribute with a sibling package feel free to join the AP channel on discord to gather other people to help, gauge interest, etc.
