### ISSUE TITLE
audioplayers v0.16.x

### ISSUE THREAD

**Issue by MrR1pp3r** [luanpotter/audioplayers#644]
I setup android studio recently.. and try to learn flutter via online tutorial...

I see, they use audioplayers v0.10.0, but i use v0.16.0.. 'cause of latest branch

but i face some problem in Android version.

1. I run flutter build apk & it's finished his task.
2. I add audioplayers ^0.16.1 & it's give me error 'path-provider:compileReleaseAidl'
Failed to find build-tools : 28.0.3

I use build-tools : 30.0.2

I think.. i see 'cause of Buildtool version.. & I reInstall Android Studio.. and again same problem..

Then I remove package audioplayers ^0.16.1 and install ^0.16.0(same problem)

3. I remove audioplayers package from my app.. & again flutter build my package easily.. using build tool v30 .. 

Config
Android Studio : v4.0
Api level : 30
build-tools : 30.0.2
Platform : Android
OS : Windows

**Comment by vancegillies** [comment]
Have you tried lowering you api level?? both path provider and audio players show 28 as the compiled level?

**Comment by MrR1pp3r** [comment]
Path Provider use API 29 & Audioplayers use 28.. 

I readthe code on Github.. tomorrow i make audioplayers for API 30

**Comment by luanpotter** [comment]
You need to install build-tools 28.0.3. Run `~/Android/Sdk/tools/bin/sdkmanager` or use the visual interface on your android studio to install any missing packages. You also need to accept the licenses. This is a flutter question, nothing to do with AudioPlayers.

**Comment by MrR1pp3r** [comment]
This isn't a Flutter issue.. I read the code.. You're using Build-tools 28.. Why should I use API 28. If i hv API level 30 phone.. 
Also if i install build tools 28, so platforms version 28 is compulsory.. So upgrade your build tools.. not me.

**Comment by MrR1pp3r** [comment]
If you use API level 30 in your code.. then everyone use it.. your pub.
