### ISSUE TITLE
lag streaming AACP source

### ISSUE THREAD

**Issue by incafox** [luanpotter/audioplayers#65]
Hi, i was trying this plugins with some .mp3 streaming sources ... everything i ok, but i have a litle problem with AACP streaming sources, every time I play this type of sources i need to wait like 1 minut and it start the stream, how to solve this? (sorry my english)

**Comment by luanpotter** [comment]
You are streaming from the internet? Maybe it's your connection? Or the server has a delay?

**Comment by incafox** [comment]
> You are streaming from the internet? Maybe it's your connection? Or the server has a delay?
Yes, is streaming from aac sources.
My internet connection is very good, server has no delay, i proved it with a simple implementation of java service, this is a problem from MediaPlayer itself so i maked my own implementation with Exoplayer and the problem is gone.

**Comment by incafox** [comment]
Yes, is streaming from aac sources.
My internet connection is very good, server has no delay, i proved it with a simple implementation of java service, this is a problem from MediaPlayer itself so i maked my own implementation with Exoplayer and the problem is gone.
