### ISSUE TITLE
_audioPlayer.seek not working in the init and build method on iOS 

### ISSUE THREAD

**Issue by MiroLiebschner** [luanpotter/audioplayers#651]
_audioPlayer.seek not working on iOS when called in the init  or build method

Usecase: 
I try to skip to the position the user was on when he closed the audioPage. 

So I save the timestamp and try to _audioPlayer.seek to the position. I have tried it in the Widget build method and in the init method and it is working fine both times for Android. On iOS it skips to that timestamp but instantly goes back to 0:00. 

You can reproduce that bug by writing: 
`_audioPlayer.seek(Duration(seconds: 10)); `
in the `init method` of` _PlayerWidgetState(this.url, this.mode);` in the example app. 

Maybe there was a step of iOS configuration I missed?

**Comment by luanpotter** [comment]
@MiroLiebschner did you test the example app? there is a seek feature on the last tab. Does that work?

**Comment by MiroLiebschner** [comment]
@luanpotter  Just tested it and the seek Buttons work fine. In the app im building seek Buttons such as "Skip 10 seconds" also work fine. The problem is skipping when the Widget is build. For that task I only see 2 options: In the init or in the build method. Both are not working for me. Maybe Im doing smt wrong?

**Comment by ismailslmnv** [comment]
> @luanpotter Just tested it and the seek Buttons work fine. In the app im building seek Buttons such as "Skip 10 seconds" also work fine. The problem is skipping when the Widget is build. For that task I only see 2 options: In the init or in the build method. Both are not working for me. Maybe Im doing smt wrong?

Could you find a solution for this?

**Comment by erickzanardo** [comment]
Closing due inactivity, if there is more info that you can add to the issue, comment here and we can re open the issue.
