### ISSUE TITLE
lock screen for audio payers 

### ISSUE THREAD

**Issue by Zeehshan** [luanpotter/audioplayers#654]
Hi, i hope you will well.
   Kindly can you let me know how can i get proper code for showing lock screen in flutter using audioplayres plugin, thanks.

**Comment by luanpotter** [comment]
We already have this feature for ios, just not for android.

**Comment by luanpotter** [comment]
Closing in favour of https://github.com/luanpotter/audioplayers/issues/561

**Comment by hossam-zaki** [comment]
> We already have this feature for ios, just not for android.

Where is this? They do not seem to work for me
