### ISSUE TITLE
Conflict with other Packages

### ISSUE THREAD

**Issue by daniwaxman** [luanpotter/audioplayers#655]
There is a conflict between the Flutter audioplayers package (using version 0.16.1) and youtube_player_flutter  starting at version7.0.0+1 . 

**Full Description**
I have been using audioplayers and recently added youtube_player_flutter. On build an error is thrown nd being attributed to the audiopolayers package:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'audioplayers'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

The SDK is installed and working correctly and if I remove either package the build succeeds. 

**Code to Reproduce**
Add both of these to your package.json:
audioplayers: ^0.16.1
 youtube_player_flutter: ^7.0.0+7

**Log Errors**

**Files/URLs/Sources**

**Screenshots**
![image](https://user-images.githubusercontent.com/10358119/96841750-d4818b00-1454-11eb-9f61-84ebf17498d8.png)

**Platforms**
List in detail here **all** the platforms that you have tested, indicating which platforms the error occurs on. Please try to test on as many different platforms as possible to make our lives easier (this is optional). You must add at least one platform in which the problem occurs (evidently). For each platform listed, you must specify:

* Device: Trying to run on Android emulator but fails at build before trying to run on device
* flutter version: Flutter Stable 1.20.2
* audioplayers version: 0.16.1
* release or not release: debug mode

**Comment by luanpotter** [comment]
The first error seems to indicate it's an issue with youtube_player_flutter? some sort of incompatible versions there.

**Comment by erickzanardo** [comment]
Closing due inactivity
