### ISSUE TITLE
Ability to play sounds (local/remote) together with background music playing in Spotify/YouTube etc

### ISSUE THREAD

**Issue by chris-rutkowski** [luanpotter/audioplayers#656]
Hello,

When I play sound using your package when the background music is being played

either from local assets:

```
constructor:
final _audioCache = AudioCache();
await _audioCache.loadAll(['sounds/correct.wav']);

play function:
_audioCache.play('sounds/correct.wav', mode: PlayerMode.LOW_LATENCY, volume: 0.6)
```

or from internet: 

```
final audioPlayer = AudioPlayer();
audioPlayer.play('https://example.com/sound.wav');
```

I experience the following ambiguity:
- on Android, it mixes with background music (without lowering the volume of background music)
- on iOS it stops background music and the music doesn't return when it stops

I wish this wasn't ambiguous and I also wish it dims the background music and returns to full volume after sound completes.

If this is already implemented my apologies, the README could include it :)
Thank you in advance.

**Comment by luanpotter** [comment]
Isn't this what the `duckAudio` flag does?

**Comment by luanpotter** [comment]
Closing as we already support this with duckAudio.
