### ISSUE TITLE
run demo under the web, reported an error

### ISSUE THREAD

**Issue by stoneLee81** [luanpotter/audioplayers#659]
![image](https://user-images.githubusercontent.com/18001708/97519982-330ab400-19d5-11eb-8aea-c6c7ca569c16.png)

I ran the demo under the web and reported an error; audioCache is no longer provided to the website. What should I do if I want to play the audio files in the website asset directory? Before it was audioCache ('raw/audio file')

**Comment by erickzanardo** [comment]
Like the message says AudioCache is not available on web. To play on web you can just use the AudioPlayer class, and just set the url of the asset as a relative url.
