### ISSUE TITLE
E/MediaPlayerNative( 9032): error (1, -19)

### ISSUE THREAD

**Issue by oSamDavis** [luanpotter/audioplayers#661]
I am using AudioCache to play sounds in my assets in my Flutter project. Initially plays sounds  perfectly for me but stops along the way, I have no idea why.
![Screenshot (339)](https://user-images.githubusercontent.com/59079555/97667882-dea41a80-1a4e-11eb-8f8d-9de24c088fb1.png)

**Comment by Jolium** [comment]
I have the same problem. I think it happened to me when I upgraded a few dependencies, but I have already downgraded the dependencies and the problem persists.

![print_problem](https://user-images.githubusercontent.com/41831414/98155435-851c6f80-1ed6-11eb-8641-bea70c79bb6f.png)

**Comment by oSamDavis** [comment]
okay yes, Try using version 0.10. it works fine for me

**Comment by minikupa** [comment]
same error

**Comment by vietdungkma** [comment]
I get the same issue when using:
audioplayers: ^0.17.2
I have an app that have 7 button equivalent to 7 audio files in the assets folder to be play.
The problem it, when I spam clicking into those buttons, to a certain time, the issues happens and can't play any audio file any more, the error logs shown like the one of @Jolium 

I switch back to:
audioplayers: '0.16.0'

and everything works fine :)

Here are some of mine error logs:
E/MediaPlayerNative( 8470): error (1, -19)
E/MediaPlayer( 8470): Error (1,-19)
E/MediaPlayerNative( 8470): pause called in state 0, mPlayer(0xb8c3c310)
E/MediaPlayerNative( 8470): error (-38, 0)
E/MediaPlayerNative( 8470): Attempt to perform seekTo in wrong state: mPlayer=0xb8c3c310, mCurrentState=0
E/MediaPlayerNative( 8470): error (-38, 0)
E/MediaPlayer( 8470): Error (-38,0)
E/MediaPlayer( 8470): Error (-38,0)
E/MediaPlayerNative( 8470): error (1, -19)
E/MediaPlayer( 8470): Error (1,-19)
E/MediaPlayerNative( 8470): pause called in state 0, mPlayer(0xb8c2ba20)
E/MediaPlayerNative( 8470): error (-38, 0)
E/MediaPlayerNative( 8470): Attempt to perform seekTo in wrong state: mPlayer=0xb8c2ba20, mCurrentState=0
E/MediaPlayerNative( 8470): error (-38, 0)
E/MediaPlayer( 8470): Error (-38,0)
E/MediaPlayer( 8470): Error (-38,0)
E/MediaPlayerNative( 8470): error (1, -19)
E/MediaPlayer( 8470): Error (1,-19)
E/MediaPlayerNative( 8470): pause called in state 0, mPlayer(0xb8c39940)
E/MediaPlayerNative( 8470): error (-38, 0)
E/MediaPlayerNative( 8470): Attempt to perform seekTo in wrong state: mPlayer=0xb8c39940, mCurrentState=0
E/MediaPlayerNative( 8470): error (-38, 0)
E/MediaPlayer( 8470): Error (-38,0)
E/MediaPlayer( 8470): Error (-38,0)
E/MediaPlayerNative( 8470): error (1, -19)
E/MediaPlayer( 8470): Error (1,-19)
E/MediaPlayerNative( 8470): pause called in state 0, mPlayer(0xb8c278e0)
E/MediaPlayerNative( 8470): error (-38, 0)
E/MediaPlayerNative( 8470): Attempt to perform seekTo in wrong state: mPlayer=0xb8c278e0, mCurrentState=0
E/MediaPlayerNative( 8470): error (-38, 0)
E/MediaPlayer( 8470): Error (-38,0)
E/MediaPlayer( 8470): Error (-38,0)
E/MediaPlayerNative( 8470): error (1, -19)
E/MediaPlayer( 8470): Error (1,-19)
E/MediaPlayerNative( 8470): pause called in state 0, mPlayer(0xb8c30760)
E/MediaPlayerNative( 8470): error (-38, 0)
E/MediaPlayerNative( 8470): Attempt to perform seekTo in wrong state: mPlayer=0xb8c30760, mCurrentState=0
E/MediaPlayerNative( 8470): error (-38, 0)
E/MediaPlayer( 8470): Error (-38,0)

<img width="909" alt="Screen Shot 2021-01-12 at 00 22 41" src="https://user-images.githubusercontent.com/19856468/104216229-5b4e6e80-546c-11eb-9f08-483149cdb73f.png">
