### ISSUE TITLE
ios build fails " module 'audioplayers' not found"

### ISSUE THREAD

**Issue by Nader2004** [luanpotter/audioplayers#662]
Hi everyone. Whenever I build for ios it always give me this error :
 
`Xcode's output:
↳
    /Users/builder/clone/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'audioplayers' not found
    @import audioplayers;
     ~~~~~~~^~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description`

Al though I already have the plugin installed in the pubspec.yaml file.

Here is my flutter doctor : 
`[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc1)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.50.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.`

**Comment by zanesc** [comment]
Same.

**Comment by zanesc** [comment]
@Nader2004 have you found a solution?

**Comment by mmcib** [comment]
Same.
I was compiling an app many times for last 3h.
The error came from nowhere.
The app was working. I've stopped debugging and then I've started compiling and the error occurred (I didn't change the code!) :/

**Comment by mmcib** [comment]
@Nader2004 @zanesc 

I've just found the solution.
Y'all can try it too.

1. For example: If you are on master, change to different branch or make a new one.
2. Delete local master branch and let's checkout remote master.
3. Run "flutter clean" in root folder of project, run "pod install" in ios folder, go back to the root folder and run "flutter run".

Maybe it will help you :)

**Comment by VigneshPasupathy** [comment]
Do check if this answer helps you
https://stackoverflow.com/questions/29500227/getting-error-no-such-module-using-xcode-but-the-framework-is-there

The issue in my case was that i was running xcodeproj instead of xcworkspace

**Comment by luanpotter** [comment]
This is a configuration issue with your project/flutter and is not a bug in audioplayers.

**Comment by gferrazdev** [comment]
luan, can you give us an example of configuration issue that can cause this problem?

**Comment by jsanz1209** [comment]
Any could resolve this issue?
