### ISSUE TITLE
can not get playing status and duration when running it under web platform

### ISSUE THREAD

**Issue by stoneLee81** [luanpotter/audioplayers#665]
Flutter 1.22.0-12.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8b3760638a (7 weeks ago) • 2020-09-15 17:47:13 -0700
Engine • revision 4654fc6cf6
Tools • Dart 2.10.0 (build 2.10.0-110.3.beta)
audioplayers 1.6.2

When executing play action, audio plays, but listener can't get playing status and duration

**Comment by unger1984** [comment]
[streams are not available on web yet](https://pub.dev/packages/audioplayers#streams)

**Comment by luanpotter** [comment]
also: https://github.com/luanpotter/audioplayers/blob/master/feature_parity_table.md
