### ISSUE TITLE
Deprecated in the new Beta.

### ISSUE THREAD

**Issue by meghead** [luanpotter/audioplayers#667]
Seems audio player is deprecated when using in Flutter's latest Beta. I'm using the following in Android Studio;

Flutter 1.23.0-18.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 198df796aa (3 weeks ago) • 2020-10-15 12:04:33 -0700
Engine • revision 1d12d82d9c
Tools • Dart 2.11.0 (build 2.11.0-213.1.beta) 

Here's what I'm getting in the console;

C:\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.16.2\android\src\main\java\xyz\luan\audioplayers\AudioplayersPlugin.java:18: warning: [deprecation] PluginRegistry in io.flutter.plugin.common has been deprecated
import io.flutter.plugin.common.PluginRegistry.Registrar;
                               ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.16.2\android\src\main\java\xyz\luan\audioplayers\AudioplayersPlugin.java:18: warning: [deprecation] PluginRegistry in io.flutter.plugin.common has been deprecated
import io.flutter.plugin.common.PluginRegistry.Registrar;
                               ^
2 warnings
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_audio_recorder-0.5.5\android\src\main\java\com\zeno\flutter_audio_recorder\FlutterAudioRecorderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by kennaruk** [comment]
I'm getting the same issue

**Comment by L0p3zV4rg4s** [comment]
Yeah, same issue here

**Comment by Korrigierer** [comment]
Same

**Comment by markleavitt** [comment]
Same issue, identical environment

**Comment by WinKyawt** [comment]
same issue

**Comment by eebeeDEV** [comment]
same here, version 1.24.0-10.2.pre
Dec 15

**Comment by mps01** [comment]
same issue
version: Flutter 1.25.0-8.1.pre

**Comment by DenisTis** [comment]
Yes, apart from being deprecated, it already does not play sounds on real device :(

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
