### ISSUE TITLE
Not playing m4a in ios

### ISSUE THREAD

**Issue by deepak-gehlot** [luanpotter/audioplayers#67]
not playing M4a file from url only in ios recorded in adroid, working fine in android

**Comment by jonasholtkamp** [comment]
Can't replicate. Just began using this (awesome) package and it works well playing m4a files from remote.

**Comment by erickzanardo** [comment]
@deepak-gehlot can you provide the error or a reproducible example with the error?

**Comment by erickzanardo** [comment]
Closing due inactivity.
