### ISSUE TITLE
Cannot play on android kitkat

### ISSUE THREAD

**Issue by nizigama** [luanpotter/audioplayers#670]
It runs on all versions above 4.4 but when run on kitkat  the `onPlayerError` event is triggered with this error `MediaPlayer error with what:MEDIA_ERROR_UNKNOWN {what:1} extra:MEDIA_ERROR_IO`

**Comment by luanpotter** [comment]
That's because of the colon symbol, see https://github.com/luanpotter/audioplayers/issues/705
