### ISSUE TITLE
Live Streaming Link can't play on Android 9 or above

### ISSUE THREAD

**Issue by DavidG4869** [luanpotter/audioplayers#673]
**Link Tested:** 
LIVE STREAMING LINK: http://mediaserv30.live-streams.nl:8086/live
WEB LINK: https://luan.xyz/files/audio/nasa_on_a_mission.mp3

On **android 9 or above**, audio player can only play normal web link _but not streaming link._  
No problem in playing both live streaming link and normal web link in **android 8 or below** and **IOS**.

**Comment by erickzanardo** [comment]
You can't play links without https without adding configuration to your manifest.

Please look on the troubleshooting.md file for instructions.

**Comment by lsao2000** [comment]
Im using live video in youtube and it gives me this error when I try play it ``` VideoUnavailableException: Video "peUyxPmlA7Y" does not contain any playable streams.``` and I don't know is the problem in the library or in live stream url , I search a lot for this didn't get answear

**Comment by luanpotter** [comment]
The library is for playing audio only, I don't think it will work with video streams, specially youtube which is so finicky against such things
