### ISSUE TITLE
Add MPNowPlayingInfoCenter and MPRemoteCommandCenter capabilities

### ISSUE THREAD

**Issue by real1900** [luanpotter/audioplayers#674]
Please add support for MPNowPlayingInfoCenter on iOS and MPRemoteCommandCenter on Android

**Comment by luanpotter** [comment]
We already offer support for MPNowPlayingInfoCenter on iOS.

**Comment by luanpotter** [comment]
Closing in favor of https://github.com/luanpotter/audioplayers/issues/654

**Comment by real1900** [comment]
So how can I set that information for my player using audio player @luanpotter ?
