### ISSUE TITLE
The plugin audioplayers could not be built due to the issue above.

### ISSUE THREAD

**Issue by shamsher400** [luanpotter/audioplayers#677]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'audioplayers'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

The plugin audioplayers could not be built due to the issue above.

**Comment by domkoder** [comment]
i am having the same problem too.

**Comment by luanpotter** [comment]
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

Clearly you have an incorrect setup for your flutter environment, as it's lacking the android sdk/home env vars. Please configure it correctly, this has nothing to do with audioplayers whatsoever.
