### ISSUE TITLE
ios build: module 'audioplayers' not found

### ISSUE THREAD

**Issue by gferrazdev** [luanpotter/audioplayers#681]
Hello, when i run the command "flutter build ios" or try to "Archive", i get the same error that some of you guys has been faced of: "module audio players not found". 

I know there is already four closed issues about that error, but none of the solutions has worked for me. Luan, you've said that it could be relationed with project's configurations. Can you give me a example or more informations about that? . I'm truly desperate.

* OS: ios.
* OS version: Big Sur.
* flutter version: 1.22.4.
* audioplayers version: 17.

**Comment by luanpotter** [comment]
Try:

```
flutter clean
rm -rf build
rm -rf ~/.pub-cache

flutter pub get
```

And try running again. That seems like an env issue. Take a look at our new github action, it builds the example app correctly on ios. Can you build the example app?

**Comment by luanpotter** [comment]
Added a section on our FAQ for this since it's a very common issue people have: https://github.com/luanpotter/audioplayers/pull/834

**Comment by erickzanardo** [comment]
Closing due inactivity, if there is more info that you can add to the issue, comment here and we can re open the issue.

**Comment by ghyzx** [comment]
there are still problems on audioplayers: ^0.18.3

**Comment by gferrazdev** [comment]
I've figured out what was going on. When you run the pod install command, the dependencies are not added on podfile. You need to delete the podfile previously generetated, open the project on vscode, run the flutter pub get command, and then run the app. When you run the app, the podfile is created with the dependencies and you will be able to build the project on xcode. basically, if you use Windows to developer your app, you need tu run the app on the Mac before you build it on xcode.
