### ISSUE TITLE
Error when rapidly clicking on play button.

### ISSUE THREAD

**Issue by manojmula** [luanpotter/audioplayers#682]
**Main.dart**
import 'package:flutter/material.dart';
import 'package:audioplayers/audio_cache.dart';

void main() => runApp(XylophoneApp());

class XylophoneApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: Center(
              child: FlatButton(
            onPressed: () {
              final player = AudioCache();
              player.play('note1.wav');
            },
            child: Text('Click me'),
          )),
        ),
      ),
    );
  }
}
![Screenshot from 2020-11-25 10-00-12](https://user-images.githubusercontent.com/59415326/100183480-0f1f8d00-2f05-11eb-8601-8a3f9abd0bff.png)

**Error Message**
E/MediaPlayerNative( 4392): error (1, -19)
E/MediaPlayer( 4392): Error (1,-19)
E/MediaPlayerNative( 4392): pause called in state 0, mPlayer(0xb832a5e0)
E/MediaPlayerNative( 4392): error (-38, 0)
E/MediaPlayerNative( 4392): Attempt to perform seekTo in wrong state: mPlayer=0xb832a5e0, mCurrentState=0
E/MediaPlayerNative( 4392): error (-38, 0)
E/MediaPlayer( 4392): Error (-38,0)
E/MediaPlayer( 4392): Error (-38,0)

**Comment by manojmula** [comment]
Its not about rapid play but when the button is pressed like nearly 20 times, this error appears.

**Comment by YeasinKabirJoy** [comment]
I am having the same problem

**Comment by ArchangelAmin** [comment]
I used it in the Xylophone app and got the same issue. after about 31 key presses the app stops working.

**Comment by madz** [comment]
Same issue. So far it's only happening in Android phones.

**Comment by erickzanardo** [comment]
For multiple plays on a small timeframe you need to use low latency, you can see it on the README https://github.com/luanpotter/audioplayers#usage

Also, you are creating a AudioCache instance on every click. That invalidates the usage of the AudioCache, you should create a single instance and use only that instance.

**Comment by madz** [comment]
I just want to mention that making a single instance of the AudioCache does not solve the error for me.
Downgrading to audioplayers: ^0.12.0 solve it for me.

**Comment by keymistress** [comment]
[This](https://github.com/londonappbrewery/xylophone-flutter/issues/20#issuecomment-735051197) works with ^0.17.4 for me.

**Comment by Eduar2TC** [comment]
I had to change version from 5.2.0 to 0.20.1
