### ISSUE TITLE
Unable to stop playback of looped audio from AudioCache

### ISSUE THREAD

**Issue by lucasjbyoung** [luanpotter/audioplayers#686]
When using AudioCache to play a looped mp3 file, the stop() or pause() methods do not work.

**Full Description**
I have loaded an mp3 file from the local assets folder and looped it using AudioCache and AudioPlayer, however, even calling stop() or pause() immediately after it starts paying doesn't stop it.

**Code to Reproduce**
audioplayers version: 0.17.0
Import the files:
`import 'package:audioplayers/audio_cache.dart';
import 'package:audioplayers/audioplayers.dart';`

Declare variables in class:
`final AudioCache player = AudioCache();
  AudioPlayer mainAudioPlayer = AudioPlayer();`

Instantiate: 
`@override
  void initState() {
    // TODO: implement initState
    super.initState();
    _startup = startup();
  }

  Future<void> startup() async {
    player.load('background.mp3');
    mainAudioPlayer = await player.loop(
      'background.mp3',
      volume: 1,
    );
    await mainAudioPlayer.stop();
}`

**Log Errors**
There are no error messages

**Platforms**
* OS: iOS 14.1 and 14.3 beta
* Device: Emulator (iPhone 12 Pro Max iOS 14.1), physical device iPhone 12 Pro Max iOS 14.3 beta
* flutter version:  Flutter version 1.22.4 
* audioplayers version: 0.17.0
* release or not release: release and debug

**Comment by Theunodb** [comment]
Im getting this on Android only

```
D/WSP     ( 4707): time to call load() for /data/user/0/co.za.response24.responderApp/cache/sound1.mp3: 0 player=xyz.luan.audioplayers.WrappedSoundPool@5ae2754
E/AudioplayersPlugin( 4707): Unexpected error!
E/AudioplayersPlugin( 4707): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AudioplayersPlugin( 4707): 	at xyz.luan.audioplayers.WrappedSoundPool.setReleaseMode(WrappedSoundPool.java:214)
E/AudioplayersPlugin( 4707): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:158)
E/AudioplayersPlugin( 4707): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:60)
E/AudioplayersPlugin( 4707): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AudioplayersPlugin( 4707): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AudioplayersPlugin( 4707): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:738)
E/AudioplayersPlugin( 4707): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AudioplayersPlugin( 4707): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AudioplayersPlugin( 4707): 	at android.os.Looper.loop(Looper.java:174)
E/AudioplayersPlugin( 4707): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AudioplayersPlugin( 4707): 	at java.lang.reflect.Method.invoke(Native Method)
E/AudioplayersPlugin( 4707): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AudioplayersPlugin( 4707): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by vivekdhameliya2** [comment]
the same issue with me, I also want to stop music from assets, but I cannot, if you found any solution then please let me know

**Comment by luanpotter** [comment]
Since I converted the java code to kotlin there should now be no more `java.lang.NullPointerException`. please reopen if the issue persists on the latest version (with the updated trace)
