### ISSUE TITLE
How do I play a specified interval of audio?

### ISSUE THREAD

**Issue by Blues9527** [luanpotter/audioplayers#687]
For example, The audio is 10 seconds long, but I want to play 2nd to 5th seconds of audio. How do I resolve it ?

**Comment by muarachmann** [comment]
Hi @Blues9527 I don't there is a way to do it directly with this plugin. Rather, you can have a callback when listening to **onDurationChanged** to achieve the endgoal. This returns the duration/or how far you've played the song. Also play with the seek position to skip to a particular position. That should help you jump to the 2nd second. For example

```
_audioPlayer.seek(Duration(second: 2));
```

and you can stop the audio player at the fifth

 ```
 _audioPlayer.onDurationChanged.listen((duration) {
      if (duration.inseconds == 5) { 
          // Stop the player here....
    }
}
```

Hope this helps.

**Comment by Blues9527** [comment]
> Hi @Blues9527 I don't there is a way to do it directly with this plugin. Rather, you can have a callback when listening to **onDurationChanged** to achieve the endgoal. This returns the duration/or how far you've played the song. Also play with the seek position to skip to a particular position. That should help you jump to the 2nd second. For example
> 
> ```
> _audioPlayer.seek(Duration(second: 2));
> ```
> 
> and you can stop the audio player at the fifth
> 
> ```
> _audioPlayer.onDurationChanged.listen((duration) {
>      if (duration.inseconds == 5) { 
>          // Stop the player here....
>    }
> }
> ```
> 
> Hope this helps.

thanks bro!
