### ISSUE TITLE
iOS playrate 0.5  distortion of sound

### ISSUE THREAD

**Issue by dansunhappy** [luanpotter/audioplayers#688]
**Code to solve**
self.playerItem = [[AVPlayerItem alloc] initWithAsset:_asset];
self.playerItem.audioTimePitchAlgorithm = AVAudioTimePitchAlgorithmTimeDomain;

**Comment by luanpotter** [comment]
Does that need to be done only when using a playrate != 1 or can we do it for all player items? I am glad to review a PR with that line.

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
