### ISSUE TITLE
iOS lock screen PreviousTrack and NextTrack button disabled

### ISSUE THREAD

**Issue by WeeStar** [luanpotter/audioplayers#690]
Hello,glad to meet U in here.

Device:iOS

Description:
I use the "setNotification" function to make a Control in iOS lock screen.But the PreviousTrack and NextTrack button are disabled in lock screen.**I Have already set the params "hasNextTrack" "hasPreviousTrack" to true.**

Code:
    audioPlayer.setNotification(
        title: curMusic?.title ?? "未知歌曲",
        artist: curMusic?.artist ?? "未知歌手",
        albumTitle: curMusic?.album ?? "未知专辑",
        imageUrl: curMusic?.img_url ?? '',
        duration: duration,
        hasNextTrack: true,
        hasPreviousTrack: true);

Screenshot:
![WechatIMG18](https://user-images.githubusercontent.com/22439356/100581126-2655e480-3322-11eb-865e-118ab0f6935d.jpeg)

Trouble you.I’m not sure if this is a bug or I’m using the wrong way to set the control.
Looking forward to your reply,thx!

**Comment by WeeStar** [comment]
I know the problem.

**Comment by WeeStar** [comment]
I know the problem.
In file lib/audioplayers.dart,the method "setNotification" use params named **"hasPreviousTrack" and "hasNextTrack"**.
As follows.
<img width="623" alt="image" src="https://user-images.githubusercontent.com/22439356/102585651-b8902200-4143-11eb-9102-edbdc3e6a321.png">

But in file "ios/SwiftAudioplayersPlugin.swift",u use a wrong keys **"enablePreviousTrackButton" and "enableNextTrackButton"** to get the param values.
As follows.
<img width="708" alt="image" src="https://user-images.githubusercontent.com/22439356/102586148-8fbc5c80-4144-11eb-80c8-ea627c397640.png">

I think you just need to change the keys to **"hasPreviousTrack" and "hasNextTrack"** in file "ios/SwiftAudioplayersPlugin.swift" line  284 285.
BTW,file "macOS/SwiftAudioplayersPlugin.swift"  and file "darwin/SwiftAudioplayersPlugin.swift" has same problem.

That's all.

**Comment by luanpotter** [comment]
Nice catch, @WeeStar

**Comment by luanpotter** [comment]
Fixed: https://github.com/luanpotter/audioplayers/pull/835
