### ISSUE TITLE
i have a problem playing audios from url

### ISSUE THREAD

**Issue by leviis-dot** [luanpotter/audioplayers#692]
I use your plugin with audio service and I want to let the user know that the audio is loading when buffering. If anyone could help me that would be cool. Thank you otherwise your plugin is good.

**Comment by alainseys** [comment]
You can use the symbol for how much of the track is played just keep it running in a loop until the audio is fully buffered 

[see here ](https://streamable.com/rx9luk)

**Comment by leviis-dot** [comment]
> You can use the symbol for how much of the track is played just keep it running in a loop until the audio is fully buffered 
> 
> [see here ](https://streamable.com/rx9luk)

i can have sample code because i can't see what you're talking about. I am a beginner in dart

**Comment by alainseys** [comment]
> > You can use the symbol for how much of the track is played just keep it running in a loop until the audio is fully buffered 
> > 
> > [see here ](https://streamable.com/rx9luk)
> 
> i can have sample code because i can't see what you're talking about. I am a beginner in dart

Did you watched the video? I can send your a sample but you can find a sample in the dart page

**Comment by alainseys** [comment]
`Widget _buildAudioButton(PlayerProvider model, _isSelectedSong) {


    if (_isSelectedSong) {
      if (model.isLoading()) {
        return Center(
          child: CircularProgressIndicator(strokeWidth: 2.0),
        );
      }

      if (!model.isStopped()) {
        return Icon(Icons.stop);
      }

      if (model.isStopped()) {
        return Icon(Icons.play_circle_filled);
      }

    } else {
      return Icon(Icons.play_circle_filled);

    }

    return new Container();
  }`

**Comment by leviis-dot** [comment]
> Here you have a sample of widget , you see within the widget i call a child with the CirculaProcessIndicator so the icon will build some circles until the stream is fully processed, you can modify the stroke with a other value 2 was the best fit for my application.
> 
> hope this helps you 
> `
> Widget _buildAudioButton(PlayerProvider model, _isSelectedSong) {
> 
> 
>     if (_isSelectedSong) {
>       if (model.isLoading()) {
>         return Center(
>           child: CircularProgressIndicator(strokeWidth: 2.0),
>         );
>       }
> 
>       if (!model.isStopped()) {
>         return Icon(Icons.stop);
>       }
> 
>       if (model.isStopped()) {
>         return Icon(Icons.play_circle_filled);
>       }
> 
>     } else {
>       return Icon(Icons.play_circle_filled);
> 
>     }
> 
>     return new Container();
>   }
> `

thank you so much
