### ISSUE TITLE
build apk -release faild with android x

### ISSUE THREAD

**Issue by lmr520** [luanpotter/audioplayers#695]
run flutter build apk is failed  but run debug is working 
log:A problem occurred configuring root project 'audioplayers'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
buid-tools: com.android.tools.build:gradle:3.5.4

**Comment by muarachmann** [comment]
@lmr520 how did you install AS, also check `flutter doctor` to see if everything is correct. This has to do with your Android installation not this package.

**Comment by JhamereWilson** [comment]
@muarachmann I've experienced this same issue. I've been using the package for some time but when I updated flutter, I got this error. Flutter doctor shows that everything is correct. 

Where do you suggest one should start in regards to fixing the AS issue?

**Comment by lmr520** [comment]
@JhamereWilson @muarachmann my problem is solved  I find one of the depend plugins as vibrate,the plugin build sdk version different  with my build sdk version,but the log not point to vibrate。 your problem maybe  like so ,you can check your build sdk version is different  with plugin s support build sdk vision ,
