### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by md84419** [luanpotter/audioplayers#701]
```
The library 'package:audioplayers/audio_cache.dart' is legacy, and should not be imported into a null safe library.
Try migrating the imported library.
```

```
Error: This project cannot run with sound null safety, because one or more project dependencies do not
support null safety:

- audioplayers
```

```
dependencies:
  audioplayers: ^0.17.0
```

**Comment by alainseys** [comment]
@md84419  

you can fix this by removing the ^ from ^0.17.0 then you will be able to run you app

**Comment by md84419** [comment]
The issue is not resolved by using 0.17.0 nor by changing the Kotlin version.  The audioplayers library is not currently compatible with the Flutter nullsafety feature.  The audioplayers developers need to produce a nullsafety-aware version of audioplayers.

More info is available here: https://dart.dev/null-safety/migration-guide

**Comment by jj-hoeksema** [comment]
This issue is really important for the use of this plugin in the future.

**Comment by luanpotter** [comment]
Done thanks to @wolfenrain and a lot of help from the community! 🎉
