### ISSUE TITLE
The play function results error if the file name contains colon on Android.

### ISSUE THREAD

**Issue by noobar** [luanpotter/audioplayers#705]
`AudioPlayer#play` results error with `MediaPlayer error with what:MEDIA_ERROR_UNKNOWN {what:1} extra:MEDIA_ERROR_SYSTEM` if the file name contains colon (`:`).

**Environment**

* Android 10.0 (API 29) Emulator x86
* Flutter 1.22.0
* audioplayers 1.17.0

**Comment by luanpotter** [comment]
by the looks of it that seems to be a limitation of the platform...

**Comment by erickzanardo** [comment]
Like Luan mentioned, colon in the name is not a valid name apparently.
