### ISSUE TITLE
Big Sur V11.1 deploy to iOS cannot launch simulator or physical device

### ISSUE THREAD

**Issue by imbradyboy** [luanpotter/audioplayers#711]
Here is a snippet of the error I get when trying to debug on iOS using version 0.17.0. It works correctly when rolled back to version 0.16.2.

Xcode's output:
    ld: warning: Could not find or use auto-linked library 'swiftCore'
    ld: warning: Could not find or use auto-linked library 'swiftQuartzCore'
    ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics'
    ld: warning: Could not find or use auto-linked library 'swiftFoundation'
    ld: warning: Could not find or use auto-linked library 'swiftsimd'
    ld: warning: Could not find or use auto-linked library 'swiftCompatibility51'
    ld: warning: Could not find or use auto-linked library 'swiftMetal'
    ld: warning: Could not find or use auto-linked library 'swiftDarwin'
    ld: warning: Could not find or use auto-linked library 'swiftMediaPlayer'
    ld: warning: Could not find or use auto-linked library 'swiftUIKit'
    ld: warning: Could not find or use auto-linked library 'swiftObjectiveC'
    ld: warning: Could not find or use auto-linked library 'swiftDispatch'
    ld: warning: Could not find or use auto-linked library 'swiftCoreMedia'
    ld: warning: Could not find or use auto-linked library 'swiftAVFoundation'
    ld: warning: Could not find or use auto-linked library 'swiftCoreImage'
    ld: warning: Could not find or use auto-linked library 'swiftCompatibilityDynamicReplacements'
    ld: warning: Could not find or use auto-linked library 'swiftUniformTypeIdentifiers'
    ld: warning: Could not find or use auto-linked library 'swiftCoreMIDI'
    ld: warning: Could not find or use auto-linked library 'swiftCoreFoundation'
    ld: warning: Could not find or use auto-linked library 'swiftCompatibility50'
    ld: warning: Could not find or use auto-linked library 'swiftCoreAudio'
    ld: warning: Could not find or use auto-linked library 'swiftSwiftOnoneSupport'
    Undefined symbols for architecture x86_64:
...

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.

**Comment by erickzanardo** [comment]
Given this message on your log `Undefined symbols for architecture x86_64:`, this seems to be an issue related to your environment. We have tested on Big Sur and everything is working fine.

If you uncover more info about that, let us know and we can reopen this.
