### ISSUE TITLE
compileSdkVersion is not specified. Please add it to build.gradle

### ISSUE THREAD

**Issue by pradeepsthapa** [luanpotter/audioplayers#715]
A problem occurred configuring project ':audioplayers'.
> compileSdkVersion is not specified. Please add it to build.gradle

**My build.gradle file is**

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 30

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.ccbc.quizapp_final"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

**Comment by arunlakhera** [comment]
I faced the same issue and after struggling for 2 complete days with this. I was able to solve it by removing ^ that we give in pubspec.yaml file. Just used it like below and did pub get.. It started working now. 
audioplayers: 0.17.0

**Comment by pradeepsthapa** [comment]
Thank you for your answer.
**I solved this issue by adding following lines in project level build.gradle.**
buildscript {
    ext.kotlin_version = "1.4.10"
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.1'
        classpath 'com.google.gms:google-services:4.3.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

**and adding this line in AndroidManifest.xml file**
<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="30" tools:overrideLibrary="xyz.luan.audioplayers"/>

**Comment by MauroDiamantino** [comment]
> Thank you for your answer.
> **I solved this issue by adding following lines in project level build.gradle.**
> buildscript {
> ext.kotlin_version = "1.4.10"
> repositories {
> google()
> jcenter()
> }
> 
> ```
> dependencies {
>     classpath 'com.android.tools.build:gradle:4.1.1'
>     classpath 'com.google.gms:google-services:4.3.4'
>     classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
> }
> ```
> 
> }
> 
> **and adding this line in AndroidManifest.xml file**
> `<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="30" tools:overrideLibrary="xyz.luan.audioplayers"/>`

I followed your steps and I got an error related with the prefix `tools` which wasn't recognized. So, I investigated about this and I found it was necessary to modify file AndroidManifest.xml add this line `xmlns:tools="http://schemas.android.com/tools"` after `<manifest xmlns:android="http://schemas.android.com/apk/res/android"`. You can find this fix in this [link](https://stackoverflow.com/questions/45516305/error-the-prefix-tools-for-attribute-toolsoverridelibrary-associated-with).

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
