### ISSUE TITLE
AudioCache not work on apk release

### ISSUE THREAD

**Issue by huantd0111** [luanpotter/audioplayers#716]
[AudioCache not work on apk release]

I used AudioCache to play audio from Local Assets. It works properly with the debug build, but no sound is played or error messages against the release version.

`
final player = AudioCache();
`

`
player.play('/sound/click_sound.wav');
`

**Log Errors**
No log error

**Platforms**
Android 10, 
Device : Samsung A11,
audioplayers version: 0.17.0
Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-VN)

**Comment by pradeepsthapa** [comment]
You need to load first before playing
 `player.load('/sound/click_sound.wav');`

mp3 files worked for me in release mode.

**Comment by itssidhere** [comment]
Some of my users are facing this issue. Is it fixed for you? @huantd0111

**Comment by erickzanardo** [comment]
There isn't enough information on this issue for us to act on. Please edit this, or open a new one and please follow the issue template.

Feel free to comment here and we can re open this eventually.
