### ISSUE TITLE
path_provider Installed, error still reported

### ISSUE THREAD

**Issue by cnqiuxue** [luanpotter/audioplayers#72]
E/flutter (18314): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (18314): MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
E/flutter (18314): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:291:7)
E/flutter (18314): <asynchronous suspension>
E/flutter (18314): #1      getTemporaryDirectory (package:path_provider/path_provider.dart:24:38)
E/flutter (18314): <asynchronous suspension>
E/flutter (18314): #2      AudioCache.fetchToMemory (package:audioplayers/audio_cache.dart:54:37)
E/flutter (18314): <asynchronous suspension>
E/flutter (18314): #3      AudioCache.load (package:audioplayers/audio_cache.dart:72:37)
E/flutter (18314): <asynchronous suspension>
E/flutter (18314): #4      AudioCache.play (package:audioplayers/audio_cache.dart:87:23)
E/flutter (18314): <asynchronous suspension>
E/flutter (18314): #5      _MyHomePageState.initState (package:flutter_view/main.dart:75:16)
E/flutter (18314): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3830:58)
E/flutter (18314): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (18314): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (18314): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (18314): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (18314): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (18314): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (18314): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (18314): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (18314): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (18314): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (18314): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (18314): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (18314): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (18314): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (18314): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (18314): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (18314): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (18314): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (18314): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (18314): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (18314): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (18314): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (18314): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (18314): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (18314): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (18314): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (18314): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (18314): #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
E/flutter (18314): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (18314): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (18314): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (18314): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (18314): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (18314): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (18314): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (18314): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (18314): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (18314): #44     ComponentEl

**Comment by cnqiuxue** [comment]
![image](https://user-images.githubusercontent.com/26665435/50479148-146db780-0a10-11e9-921f-12ccdb273252.png)
![image](https://user-images.githubusercontent.com/26665435/50479150-19326b80-0a10-11e9-8d12-ff4725dd9ac9.png)
```
AudioCache audioCache = new AudioCache();
```
![image](https://user-images.githubusercontent.com/26665435/50479171-3109ef80-0a10-11e9-91ea-0f9b3e789c34.png)
![image](https://user-images.githubusercontent.com/26665435/50479180-36673a00-0a10-11e9-9272-76ad20ddca3b.png)
![image](https://user-images.githubusercontent.com/26665435/50479188-3c5d1b00-0a10-11e9-8a36-77f8a34ceac3.png)

**Comment by luanpotter** [comment]
You don't even need to import path_provided yourself on your app, it's already a dep. of audioplayers. Have you tried runnign flutter clean && flutter pub get again? Normally this solves these kinds of issues.

**Comment by erickzanardo** [comment]
Closing due inactivity

**Comment by gurmukhp** [comment]
I'm having the exact same issue. Tried to clean and pub get but the same problem occurs.

The screenshots whilst are somewhat useful, don't actually provide any insight on what to do.

The code I've got is copied from the AudioCache docs:

```
static AudioCache player = AudioCache();
player.play('journey1.mp3');
```

**Comment by mingsai** [comment]
In my case this happens on Macos/Linux but is fine on iOS and Android. 

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)

**Comment by AgboVincent** [comment]
In my case I just comment
package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;

import io.flutter.embedding.engine.FlutterEngine;
//import io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry;


in GeneratedPluginRegistrant.java and it started working
