### ISSUE TITLE
uses-sdk:minSdkVersion 23 declared in library

### ISSUE THREAD

**Issue by Faiizii** [luanpotter/audioplayers#720]
Recent update of lib, increase the min sdk version 23 which is blocking me from compiling/running my app. As I have a large audience so I can't update the min SDK to 23. Android 21 still have very large audience, so please decrease the min SDK version to 19 

**Log Errors**
Error: uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [:audioplayers]

**Platforms**
I am trying to run the app on android platform.
I am using audioplayers: ^0.17.1 version of library.

**Comment by erickzanardo** [comment]
Supporting bellow API 23 was turning the maintenance of the package quite complicated, we looked on many sources before increasing the min version, this [source](https://gs.statcounter.com/android-version-market-share/mobile-tablet/worldwide) for example shows that usage bellow API 23 barely reaches 5%

Sorry for the trouble, but we don't plan on decreasing the min version less than 23.
