### ISSUE TITLE
Duck other not working on iOS

### ISSUE THREAD

**Issue by smocken78** [luanpotter/audioplayers#722]
Since version 0.17.0 the in 0.16.2 added option for ducking other audio does not work anymore.

Tested on a real device (iPhone 11 / iOS 14.3)

Sorry that i can not add more information for now.

**Comment by smocken78** [comment]
It seems that when migrating the iOS code to swift, the duck other option got lost

**Comment by luanpotter** [comment]
Closing in lieu of https://github.com/luanpotter/audioplayers/issues/789
