### ISSUE TITLE
Stop playing automatically in the background

### ISSUE THREAD

**Issue by caoquanyong** [luanpotter/audioplayers#729]
hello, I play audio in background ,but play next music about 2-3 songs, it stop automatically, however,when the screen on, it played.A very strange strange phenomenon.My English is pool,I'm not sure if you understand what I mean，Could you please help me fix this issue.Thanks

**Comment by luanpotter** [comment]
Closing in lieu of https://github.com/luanpotter/audioplayers/issues/788
