### ISSUE TITLE
setVolume only accepts multiples of 0.5 on iOS

### ISSUE THREAD

**Issue by BringTheChill** [luanpotter/audioplayers#730]
I don't know if you really need extra info. Let me know. But the problem is literally that on iOS I can't change volume (only with 0.0, 0.5 and 1.0) with setVolume(), and on Android is working. 

I use AudioPlayer type of object.

**Comment by BringTheChill** [comment]
I fixed the problem using this kind of code: 

`playerBackground.setVolume(double.parse(value.toInt().toString()))`

**Comment by cyberpwnn** [comment]
> I fixed the problem using this kind of code:
> 
> `playerBackground.setVolume(double.parse(value.toInt().toString()))`

So we can only have volume or no volume? Wish this could be fixed.

**Comment by BringTheChill** [comment]
> > I fixed the problem using this kind of code:
> > `playerBackground.setVolume(double.parse(value.toInt().toString()))`
> 
> So we can only have volume or no volume? Wish this could be fixed.

Until they fix u can use this workaround that I posted.

**Comment by popeveryday** [comment]
I tested on iOS and found that setVolume work but the volume value is null but when if you setVolume(1.0) and setVolume(0.5) it works.

So I fixed the problems using these cheat code:
.../flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.17.4/lib/audioplayers.dart (line 527)

`Future<int> setVolume(double volume) {
    return _invokeMethod('setVolume', {'volume': volume});
  }`

to this code

`Future<int> setVolume(double volume) {
    if (Platform.isAndroid) {
      return _invokeMethod('setVolume', {'volume': volume});
    } else {
      return _invokeMethod('setVolume$volume', {'volume': volume});
    }
  }`

.../flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.17.4/ios/Classes/SwiftAudioplayersPlugin.swift (line 186)

`} else if method == "setVolume" {
            guard let volume = args["volume"] as? Float else {
                log("Error calling setVolume, volume cannot be null")
                result(0)
                return
            }
            
            player.setVolume(volume: volume)
        }`

to this code

`} else if method.starts(with: "setVolume"){
            guard let volume = Float(method.replacingOccurrences(of: "setVolume", with: "")) else {
                log("Error calling setVolume, volume cannot be null")
                result(0)
                return
            }
            
            player.setVolume(volume: volume)
        }`

**Comment by deimantasa** [comment]
Would love to hear if there is any other solution besides having iOS stuck with 0/0.5/1 values. As I'm facing exactly same issue.

**Comment by BringTheChill** [comment]
> I tested on iOS and found that setVolume work but the volume value is null but when if you setVolume(1.0) and setVolume(0.5) it works.
> 
> So I fixed the problems using these cheat code:
> 
> **.../flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.17.4/lib/audioplayers.dart (line 527)**
> 
> Future setVolume(double volume) {
> return _invokeMethod('setVolume', {'volume': volume});
> }
> 
> **to this code**
> 
> Future setVolume(double volume) {
> if (Platform.isAndroid) {
> return _invokeMethod('setVolume', {'volume': volume});
> } else {
> return _invokeMethod('setVolume$volume', {'volume': volume});
> }
> }
> 
> **.../flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.17.4/ios/Classes/SwiftAudioplayersPlugin.swift (line 186)**
> 
> } else if method == "setVolume" {
> guard let volume = args["volume"] as? Float else {
> log("Error calling setVolume, volume cannot be null")
> result(0)
> return
> }
> player.setVolume(volume: volume)
> }
> 
> **to this code**
> 
> } else if method.starts(with: "setVolume"){
> guard let volume = Float(method.replacingOccurrences(of: "setVolume", with: "")) else {
> log("Error calling setVolume, volume cannot be null")
> result(0)
> return
> }
> player.setVolume(volume: volume)
> }

Can you make a PR with your solution please?

**Comment by luanpotter** [comment]
I tested setVolume on the example app on ios and it seems to be working well, maybe this was already fixed?

**Comment by BringTheChill** [comment]
@luanpotter try to put volume at 0.0 and then change it on 0.1, 0.2, 0.4 ... it's not working, just after 0.5. why?

**Comment by luanpotter** [comment]
I see what you mean, and indeed the test app doesn't have other options that would allow me to see the problem. However I can't see why this bug would be other than some iOS limitation, as the code just grabs the double and passes it to the AVPlayer...

**Comment by luanpotter** [comment]
Possibly related to https://github.com/luanpotter/audioplayers/issues/778 ?

**Comment by BringTheChill** [comment]
> Possibly related to #778 ?

Yes, it is.

**Comment by luanpotter** [comment]
Fixed by #826
