### ISSUE TITLE
minSdkVersion 23 since 0.17.1

### ISSUE THREAD

**Issue by bdremynoel** [luanpotter/audioplayers#731]
Since version v0.17.1, minSdkVersion for Android is set to 23 which is quite high compared to previous 16 in v0.17.0 and below.

Don't know if this a bug or mandatory configuration due to changes in this release.
Anyway, any chance to lower this?

**Comment by erickzanardo** [comment]
Supporting bellow API 23 was turning the maintenance of the package quite complicated, we looked on many sources before increasing the min version, this [source](https://gs.statcounter.com/android-version-market-share/mobile-tablet/worldwide) for example shows that usage bellow API 23 barely reaches 5%

Sorry for the trouble, but we don't plan on decreasing the min version less than 23.
