### ISSUE TITLE
Build failing on Android

### ISSUE THREAD

**Issue by Samson11** [luanpotter/audioplayers#733]
In my build.gradle my min sdk is 23 and i added this tag to my android manifest 
<uses-sdk tools:overrideLibrary="xyz.luan.audioplayers"/>

but i get this error
C:\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.17.2\android\src\main\kotlin\xyz\luan\audioplayers\AudioplayersPlugin.kt: (181, 52): Expecting a parameter declaration7

C:\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.17.2\android\src\main\kotlin\xyz\luan\audioplayers\WrappedSoundPool.kt: (46, 77): Type inference failed. Expected type mismatch: inferred type is List<???> but MutableList<WrappedSoundPool> was expected

**Comment by yamen-redwan** [comment]
I am having the same problem, did you manage to solve that?

**Comment by yamen-redwan** [comment]
Alright I solved it, try downgrading the version of audioplayers to 0.17.0. Make sure not to add the ^ sign before the version. It worked for me

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
