### ISSUE TITLE
Crash and sound doesn't play since 0.17.1

### ISSUE THREAD

**Issue by Grorock** [luanpotter/audioplayers#734]
Since version 0.17.1, my app crashes on android when playing sound with audiocache.

I use a singleton for audio and I have duckAudio enabled.
In my code, the crash happens at :
player.play(sound, mode: PlayerMode.LOW_LATENCY);

In audio_cache.dart, the crash happens at :
 await player.play(
      url,
      volume: volume,
      respectSilence: isNotification ?? respectSilence,
      stayAwake: stayAwake,
      recordingActive: recordingActive,
      duckAudio: duckAudio ?? this.duckAudio,
    );

E/AudioplayersPlugin(10602): Unexpected error!
E/AudioplayersPlugin(10602): java.lang.UnsupportedOperationException: Operation is not supported for read-only collection
E/AudioplayersPlugin(10602): 	at kotlin.collections.EmptyMap.put(Unknown Source:4)
E/AudioplayersPlugin(10602): 	at java.util.Collections$SynchronizedMap.put(Collections.java:2632)
E/AudioplayersPlugin(10602): 	at xyz.luan.audioplayers.WrappedSoundPool.setUrl(WrappedSoundPool.kt:247)
E/AudioplayersPlugin(10602): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:62)
E/AudioplayersPlugin(10602): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:37)
E/AudioplayersPlugin(10602): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AudioplayersPlugin(10602): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AudioplayersPlugin(10602): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/AudioplayersPlugin(10602): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AudioplayersPlugin(10602): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/AudioplayersPlugin(10602): 	at android.os.Looper.loop(Looper.java:142)
E/AudioplayersPlugin(10602): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
E/AudioplayersPlugin(10602): 	at java.lang.reflect.Method.invoke(Native Method)
E/AudioplayersPlugin(10602): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/AudioplayersPlugin(10602): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

With 0.17.0, I have no problem.

Regards,

**Comment by itssidhere** [comment]
Facing the same issue. Any progress?

**Comment by md84419** [comment]
I'm seeing the same in 0.17.1 and 0.17.2.  Several other similar reports on sites like StackOverflow when searching the error message and audioplayers in Google.

See also #717 and #721

**Comment by itssidhere** [comment]
Try setting the fixed player argument of audiocache to an AudioPlayer instance.

**Comment by numen31337** [comment]
Same here, here is a bit longer log output.

```
E/AudioAttributes(10407): Invalid stream type -2147483648 for AudioAttributes
W/SoundPool::StreamManager(10407): StreamMap: requested 100 streams, clamping to 32
E/AudioplayersPlugin(10407): Unexpected error!
E/AudioplayersPlugin(10407): java.lang.UnsupportedOperationException: Operation is not supported for read-only collection
E/AudioplayersPlugin(10407): 	at kotlin.collections.EmptyMap.put(Unknown Source:4)
E/AudioplayersPlugin(10407): 	at java.util.Collections$SynchronizedMap.put(Collections.java:2639)
E/AudioplayersPlugin(10407): 	at xyz.luan.audioplayers.WrappedSoundPool.setUrl(WrappedSoundPool.kt:247)
E/AudioplayersPlugin(10407): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:62)
E/AudioplayersPlugin(10407): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:37)
E/AudioplayersPlugin(10407): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AudioplayersPlugin(10407): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AudioplayersPlugin(10407): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:738)
E/AudioplayersPlugin(10407): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AudioplayersPlugin(10407): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AudioplayersPlugin(10407): 	at android.os.Looper.loop(Looper.java:183)
E/AudioplayersPlugin(10407): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AudioplayersPlugin(10407): 	at java.lang.reflect.Method.invoke(Native Method)
E/AudioplayersPlugin(10407): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AudioplayersPlugin(10407): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (10407): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(Unexpected error!, Operation is not supported for read-only collection, java.lang.UnsupportedOperationException: Operation is not supported for read-only collection
E/flutter (10407): 	at kotlin.collections.EmptyMap.put(Unknown Source:4)
E/flutter (10407): 	at java.util.Collections$SynchronizedMap.put(Collections.java:2639)
E/flutter (10407): 	at xyz.luan.audioplayers.WrappedSoundPool.setUrl(WrappedSoundPool.kt:247)
E/flutter (10407): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:62)
E/flutter (10407): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:37)
E/flutter (10407): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (10407): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (10407): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:738)
E/flutter (10407): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (10407): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (10407): 	at android.os.Looper.loop(Looper.java:183)
E/flutter (10407): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter (10407): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (10407): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (10407): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (10407): , null)
[38;5;244mE/flutter (10407): #0      StandardMethodCodec.decodeEnvelope[39;49m
 package:flutter/…/services/message_codecs.dart
[38;5;244mE/flutter (10407): #1      MethodChannel._invokeMethod[39;49m
 package:flutter/…/services/platform_channel.dart
E/flutter (10407): <asynchronous suspension>
[38;5;244mE/flutter (10407): #2      AudioPlayer._invokeMethod.<anonymous closure> (package:audioplayers/audioplayers.dart)[39;49m
 package:audioplayers/audioplayers.dart
E/flutter (10407): <asynchronous suspension>
E/flutter (10407):
```

**Comment by minhtrids** [comment]
"mode: PlayerMode.LOW_LATENCY" => error
"mode: PlayerMode.MEDIA_PLAYER" => none error

**Comment by numen31337** [comment]
> "mode: PlayerMode.LOW_LATENCY" => error
> "mode: PlayerMode.MEDIA_PLAYER" => none error

@minhtrids Thank you for the suggestion. I tried to switch to `PlayerMode.MEDIA_PLAYER`, the aforementioned crash has disappeared but another one popped up. The sound is still not working whilst everything works fine on iOS and even macOS builds.

```
E/MediaPlayerNative(11964): error (1, -2147483648)
E/MediaPlayer(11964): Error (1,-2147483648)
```

**Comment by jeffiles** [comment]
(0.17.0 + mode: PlayerMode.LOW_LATENCY) => no more errors with AudioCache on Android
I can't try it on another plataform, but I hope it helps someone else.
Without low latency, I get an error after play an audio file 32 times.

```
E/MediaPlayerNative(17357): error (1, -19)
E/MediaPlayer(17357): Error (1,-19)
E/MediaPlayerNative(17357): pause called in state 0, mPlayer(0xb95e2390)
E/MediaPlayerNative(17357): error (-38, 0)
E/MediaPlayerNative(17357): Attempt to perform seekTo in wrong state: mPlayer=0xb95e2390, mCurrentState=0
E/MediaPlayerNative(17357): error (-38, 0)
E/MediaPlayer(17357): Error (-38,0)
E/MediaPlayer(17357): Error (-38,0)
```

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
