### ISSUE TITLE
.resume() throws Unexpected Error!

### ISSUE THREAD

**Issue by MathiasSolling** [luanpotter/audioplayers#736]
When calling audioPlayer.resume() it throws an exception on android. This happens now and then but mostly works.

At first i initialize the audioPlayer and set the source:
`
    AudioPlayer audioPlayer = new AudioPlayer(playerId: trackId);
    File file = await _getAudioFile(trackId);
    await audioPlayer.setUrl(file.path, isLocal: true);`

Then when it is time to play the audio, I get the audioPlayer and call resume

    AudioPlayer audioPlayerToResume = AudioPlayer.players[trackId];

    if (audioPlayerToResume == null) {
      logger.e('Cant find audioPlayerToResume');
      return Future.value(-1);
    }
    try {
      return await audioPlayerToResume.resume();
    } on Exception catch (error, stacktrace) {
      logger.e(error.toString());
      logger.e(stacktrace);
      return Future.value(-1);
    }

It prints the following error:

E/AudioplayersPlugin(26121): Unexpected error!
E/AudioplayersPlugin(26121): java.lang.NullPointerException: uriString
E/AudioplayersPlugin(26121): 	at android.net.Uri$StringUri.<init>(Uri.java:496)
E/AudioplayersPlugin(26121): 	at android.net.Uri$StringUri.<init>(Uri.java:486)
E/AudioplayersPlugin(26121): 	at android.net.Uri.parse(Uri.java:458)
E/AudioplayersPlugin(26121): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1167)
E/AudioplayersPlugin(26121): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1160)
E/AudioplayersPlugin(26121): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1125)
E/AudioplayersPlugin(26121): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setSource(WrappedMediaPlayer.java:422)
E/AudioplayersPlugin(26121): 	at xyz.luan.audioplayers.WrappedMediaPlayer.actuallyPlay(WrappedMediaPlayer.java:265)
E/AudioplayersPlugin(26121): 	at xyz.luan.audioplayers.WrappedMediaPlayer.play(WrappedMediaPlayer.java:252)
E/AudioplayersPlugin(26121): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:111)
E/AudioplayersPlugin(26121): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:60)
E/AudioplayersPlugin(26121): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AudioplayersPlugin(26121): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AudioplayersPlugin(26121): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/AudioplayersPlugin(26121): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AudioplayersPlugin(26121): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AudioplayersPlugin(26121): 	at android.os.Looper.loop(Looper.java:174)
E/AudioplayersPlugin(26121): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AudioplayersPlugin(26121): 	at java.lang.reflect.Method.invoke(Native Method)
E/AudioplayersPlugin(26121): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AudioplayersPlugin(26121): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by luanpotter** [comment]
That just means you provided either an invalid URL or a null one. I since added a check for the null URL.
