### ISSUE TITLE
whats wrong there??

### ISSUE THREAD

**Issue by AtifGujjar313** [luanpotter/audioplayers#740]
Launching lib\main.dart on CPH1729 in debug mode...
Running Gradle task 'assembleDebug'...
Parameter format not correct -
e: C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.17.2\android\src\main\kotlin\xyz\luan\audioplayers\AudioplayersPlugin.kt: (181, 52): Expecting a parameter declaration
e: C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.17.2\android\src\main\kotlin\xyz\luan\audioplayers\AudioplayersPlugin.kt: (231, 38): Expecting an argument
e: C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.17.2\android\src\main\kotlin\xyz\luan\audioplayers\ByteDataSource.kt: (8, 37): Expecting a parameter declaration
e: C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.17.2\android\src\main\kotlin\xyz\luan\audioplayers\WrappedMediaPlayer.kt: (10, 39): Expecting a parameter declaration
e: C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.17.2\android\src\main\kotlin\xyz\luan\audioplayers\WrappedSoundPool.kt: (168, 32): Expecting a parameter declaration
e: C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.17.2\android\src\main\kotlin\xyz\luan\audioplayers\WrappedSoundPool.kt: (205, 26): Expecting an argument
e: C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.17.2\android\src\main\kotlin\xyz\luan\audioplayers\WrappedSoundPool.kt: (46, 77): Type inference failed. Expected type mismatch: inferred type is List<???> but MutableList<WrappedSoundPool> was expected

**Comment by BringTheChill** [comment]
the errors are pretty clear ... if you want help add the code

**Comment by luanpotter** [comment]
See https://github.com/luanpotter/audioplayers/issues/742
