### ISSUE TITLE
Bug fixes for 0.17.1 version and further

### ISSUE THREAD

**Issue by Yowims** [luanpotter/audioplayers#742]
Hi everyone,

I can see a lot of people has the same problem as I have : audioplayers 0.17.1 and further does not work.
To solve the problem:

Solution n°1 : 
 You should upgrade your Kotlin version in "android/build.gradle" from 1.3.50 to 1.4.21 :
```
buildscript {
    ext.kotlin_version = '1.4.21'
    repositories {
        google()
        jcenter()
    }
...
```

Soution n°1 : 
 If you wanna keep using your old version of Kotlin, you should use precisely the version 0.17.0 of the plugin, like this :

```
dependencies:
  flutter:
    sdk: flutter
  audioplayers: 0.17.0
...
```

Don't use the "^" : If you do so, Flutter will download the latest version of the plugin, and the bug will remain.

**Comment by AssisBernardo** [comment]
it worked for me, thx very much

**Comment by jymden** [comment]
Solved my problem too, on 0.17.2.

**Comment by EducatedDeer** [comment]
My app uses java, I am also getting this errors
Why does the plugin not work with java?
Can I switch to kotlin somehow?

**Comment by luanpotter** [comment]
Since we downgraded kt I will close this issue.

**Comment by luanpotter** [comment]
Thanks for the investigation & compilation,  @Yowims
