### ISSUE TITLE
Error while making APK file

### ISSUE THREAD

**Issue by ghulamrasuldev** [luanpotter/audioplayers#743]
* What went wrong:
A problem occurred configuring root project 'audioplayers'.
> Failed to notify project evaluation listener.
   > org.gradle.api.tasks.compile.CompileOptions.setBootClasspath(Ljava/lang/String;)V

> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed                                    
     /home/gama/.gradle/caches/transforms-2/files-2.1/a528b13ac93e64cafa3d0480e2c93207/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.
                                                                        
     /home/gama/.gradle/caches/transforms-2/files-2.1/a528b13ac93e64cafa3d0480e2c93207/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.

**Comment by erickzanardo** [comment]
Apparently a value related to fonts wasn't found on the values.xml of your project. This don't seems to be related to audioplayers as there isn't any UI on this project.
