### ISSUE TITLE
onPlayerCompletion and onPlayerStateChanged not working for web (0.17.2)

### ISSUE THREAD

**Issue by xl-hacker** [luanpotter/audioplayers#744]
* I'm using audioplayers plugin version 0.17.2 on web
* The player plays audio fine, but onPlayerCompletion and onPlayerStateChanged isn't called when audio finishes playing. onPlayerStateChanged call back only happens when player starts playing but doesn't trigger for player complete events.
* To check my code and setup, I tried running the same code on iOS simulator, and state changes are received correctly, so it doesn't seem to be an issue with my code.

`
@override
  void initState() {
    _advancedPlayer.setReleaseMode(ReleaseMode.STOP);
    _advancedPlayer.onSeekComplete.listen((_) {
      print('Got seek complete');
    });

    _advancedPlayer.onPlayerCompletion.listen((event) {
      print('Got player complete');
    });

    _advancedPlayer.onAudioPositionChanged.listen((duration) {
      print('on position changed duration is: $duration');
    });

    _advancedPlayer.onPlayerStateChanged.listen((ondata) {
      print('Got player state change $ondata');
   });
   super.initState();
 }
`
**Platforms**
* Works on iOS simulator
* Fails on web, chrome Version 87.0.4280.141

* flutter version:
Flutter 1.26.0-1.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 63062a6443 (6 weeks ago) • 2020-12-13 23:19:13 +0800
Engine • revision 4797b06652
Tools • Dart 2.12.0 (build 2.12.0-141.0.dev)

**Comment by xl-hacker** [comment]
One thing I tried was polling the player state to see if it's just the listener that isn't called but even the player state remains 'PLAYING' even after the audio finishes playing.

**Comment by joranmulderij** [comment]
`onAudioPositionChanged` also fails on web.
Is this going to be resolved?

**Comment by erickzanardo** [comment]
As stated on the [README](https://github.com/luanpotter/audioplayers#streams), those are not available on web yet.

**Comment by michael-ottink** [comment]
Any eta on this?

**Comment by leo8545** [comment]
its not even working on android.. 

PlayerState remains PLAYING even after end playing
