### ISSUE TITLE
AudioPlayer hangs when running in Apple Silicon M1 Android Emulator

### ISSUE THREAD

**Issue by cliffordh** [luanpotter/audioplayers#747]
**Full Description**
When using the preview version of the Android emulator for Apple Silicon M1 processor the application hangs when the "play" method is called. This same version works on iOS and a physical Android device.

https://androidstudio.googleblog.com/2020/12/android-emulator-apple-silicon-preview.html

**Code to Reproduce**
 playAudioFromLocalStorage() async {
    await audioPlayer.play("sounds/partnersinrhyme_CLICK12A.mp3");
  }

**Log Errors**
No errors logged

**Files/URLs/Sources**
n/a

**Screenshots**
n/a

**Platforms**
iOS - works
Android physical device - works
Android Emulator for Apple Silicon M1 - hangs

[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-arm, locale en-US)
    • Flutter version 1.22.5 at /Users/cliff/Work/flutter
    • Framework revision 7891006299 (7 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/cliff/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/cliff/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • XT1064 (mobile) • ZX1D527BB6 • android-arm • Android 6.0 (API 23)

**Comment by erickzanardo** [comment]
Android emulator was still in preview, this is more a problem of stability of the emulator than audioplayers itself
