### ISSUE TITLE
AudioPlayer gives error when trying to play on device audio file on iOS : AVPlayerItemStatus.failed 

### ISSUE THREAD

**Issue by Ajay19990** [luanpotter/audioplayers#753]
AudioPlayer gives error when trying to play on device audio file on iOS : AVPlayerItemStatus.failed. Audio doesn't even start playing. On android it's working fine.
Code to reproduce : 
```import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/material.dart';
import 'dart:io' as io;

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  AudioPlayer _player = AudioPlayer();
  final url =
      '/Users/ajay/Library/Developer/CoreSimulator/Devices/C394D1D9-1355-46C4-9FED-B6F0728B963C/data/Containers/Data/Application/FAD80AED-2F99-4B46-9F71-02ADC2710FFF/Documents/xF58xz9cz43BgxmjVTyqlbuKUHN1dgbcRqwabg4p.mpga';

  @override
  void initState() {
    super.initState();
    AudioPlayer.logEnabled = true;
    _player.onPlayerError.listen((msg) {
      print('audioPlayer error : $msg');
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.black12,
        body: Center(
            child: Container(
          child: FlatButton(
            child: Text('Play'),
            color: Colors.greenAccent,
            onPressed: () async {
              _player.play(url, isLocal: true);
              print(await io.File(url).exists()); // returns true
            },
          ),
        )),
      ),
    );
  }
}

**Comment by nebarkay** [comment]
I have the same bug.
SomeTimes it play but on certain audio file it won't.
Android is OK.

**Comment by MerryOscar** [comment]
I am seeing the same issue. Would be great to get an update on this!

**Comment by luanpotter** [comment]
Could it be this `mpga` audio format is not supported? Have you checked the documentation on supported codecs? Do you have a sample file of that format so I can test myself?

**Comment by erickzanardo** [comment]
> Could it be this `mpga` audio format is not supported? Have you checked the documentation on supported codecs? Do you have a sample file of that format so I can test myself?

By the looks of it, that indeed seems to be the problem

https://www.techotopia.com/index.php/Playing_Audio_on_an_iPhone_using_AVAudioPlayer#Supported_Audio_Formats

**Comment by erickzanardo** [comment]
This specific issues to be because iOS don't support `mpga`, so I am closing this. If anyone is facing the same issue with a supported file by iOS, please, open a new issue.

**Comment by MerryOscar** [comment]
> I am seeing the same issue. Would be great to get an update on this!

My issue was that the file extension on device didn't match the extension of the download url. `.m4a` vs `.mp3`. Just need to check the extension of the audio url before downloading and works fine 👍 

```dart
http.Client _client = http.Client();
var req = await _client.get(Uri.parse(audioURL));
var bytes = req.bodyBytes;
String dir = (await getApplicationDocumentsDirectory()).path;
File audioFile = new File('$dir/audio.mp3'); // Audio File Extension Must Match
await audioFile.writeAsBytes(bytes);
```
