### ISSUE TITLE
Flutter: Android: Using audioplayers: ^0.17.3 package generats error, Execution failed for task ':app:processDebugManifest', Build failed

### ISSUE THREAD

**Issue by daxosorg** [luanpotter/audioplayers#754]
Making app in which pressing a button plays assets audio file, earlier it was working without any problem but now i don't know what happend to my app, whenever i run app on my phisical android device, it generates error, then i update package's version number from ^0.17.0 to ^0.17.3 in pubspec.yaml but even then problem is same, but if i remove audioplayer package line from pubspec.yaml then app runs well, what happen to app please check, also check my AndroidManifest.xml file code given blow after error. thanks

Following error comes whenever i run:

Launching lib\main.dart on SM M307F in debug mode...
 lib\main.dart
C:\Users\Anil\AndroidStudioProjects\newlightbulb\android\app\src\debug\AndroidManifest.xml Error:
    uses-sdk:minSdkVersion 16 cannot be smaller than version 23 declared in library [:audioplayers] C:\Users\Anil\AndroidStudioProjects\newlightbulb\build\audioplayers\intermediates\library_manifest\debug\AndroidManifest.xml as the library might be using APIs not available in 16
    Suggestion: use a compatible library with a minSdk of at most 16,
        or increase this project's minSdk version to at least 23,
        or use tools:overrideLibrary="xyz.luan.audioplayers" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 23 declared in library [:audioplayers] C:\Users\Anil\AndroidStudioProjects\newlightbulb\build\audioplayers\intermediates\library_manifest\debug\AndroidManifest.xml as the library might be using APIs not available in 16
    Suggestion: use a compatible library with a minSdk of at most 16,
        or increase this project's minSdk version to at least 23,
        or use tools:overrideLibrary="xyz.luan.audioplayers" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

Code in AndroidManifes.xml file:

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.newflash">
    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="newflash"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

**Comment by erickzanardo** [comment]
Like we mention on our [troubleshooting](https://github.com/luanpotter/audioplayers/blob/master/troubleshooting.md#android), AudioPlayers require min sdk 23 on Android.

You can follow the suggestion which is mentioned on your stacktrace to fix this issue on your project.
