### ISSUE TITLE
AudioCache.playBytes() dosn't works on iOs

### ISSUE THREAD

**Issue by adriancsbna** [luanpotter/audioplayers#759]
Hi all.

I have a little problem with Audioplayers and iOs 14.4. When I try to do a playBytes () from AudioCache, it doesn't work. On Android it works fine, but on iOS it doesn't work for me.
Does it happen to someone too?
Does anyone know the solution?

I am using Flutter 1.22.6 and Audioplayers 0.17.3

Thank you very much in advance.
A greeting

**Comment by sharpred** [comment]
See readme, playBytes is android only
"To play a file in the form of a data buffer (Uint8List), use the method playBytes. This currently only works for Android (requiring API >= 23)."

**Comment by luanpotter** [comment]
Also check the feature parity table

**Comment by Mouradif** [comment]
Sorry to bump but I was curious, is this feature ever going to be made available for iOS? Seeing that this issue was closed, it seems that it won't.

**Comment by erickzanardo** [comment]
> Sorry to bump but I was curious, is this feature ever going to be made available for iOS? Seeing that this issue was closed, it seems that it won't.

There isn't anything planned, playBytes was a feature added on Android by the community.

Although we don't have it planned for implementing this on iOS, we would happily accept PRs.
