### ISSUE TITLE
Playback speed?

### ISSUE THREAD

**Issue by IrosTheBeggar** [luanpotter/audioplayers#76]
Is there any plan to add a feature to control playback speed?  (Like you see in audio book apps)

**Comment by erickzanardo** [comment]
We are focusing right now on finishing some problems and bugs, but this would be a great addition, I will keep this open so we don't forget about this feature, but in meantime if anyone want to contribute with a PR, would be very helpful.

**Comment by catoldcui** [comment]
@erickzanardo I tried to implement speed control in Android. Following this [link](https://stackoverflow.com/questions/33072799/android-6-0-set-video-speed-with-playbackparams), the minSdk requires 23. Is that ok to change all this minSdk to API 23?

**Comment by catoldcui** [comment]
@erickzanardo  make sense. 20%+ can not be neglected. 

For this feature, if want to support android 23- versions, should use soundpool instead of mediaplayer, that might be a great change.

For my usecase, I will use my fork repo directly. Thanks

**Comment by erickzanardo** [comment]
Yes, that is quite a lot of the Android market share, we have plans on refactoring the android implementation to use SoundPool because we are having some perfomance issues when using audioplayers to play sound effects. But right now we are a bit overwhelmed and this may take a while to be implemented.

Thanks for your contribution anyway.

Will keep this open so we can get back to this after we refactor to use SoundPool.

**Comment by catoldcui** [comment]
No problem.

**Comment by feroult** [comment]
Hi @catoldcui 

Now you can use the `low latency` player mode to use `SoundPool` backend on Android.

Just change your code to `AudioPlayer audioPlayer = new AudioPlayer(mode: PlayerMode.LOW_LATENCY)`

Please let us know if you still have problems.

**Comment by catoldcui** [comment]
@feroult Thanks, great refactor of adding SoundPool. That makes it possible to implement rate control for android.

Previously, I implemented speed control for MediaPlayer, but not for SoundPool. Maybe could expand for SoundPool. 

There is one complex logic in player status when setting rate for me. There will be 3 cases:
* if rate == 0, the status will be paused.
* if the url is not loaded, the player should cache the rate data, and the status will be stopped/nil.
* if the url is loaded or the player is paused/playing, when setting rate and rate != 0, the player will auto play the audio source, and the status will be playing.

So for my implementation ([Android](https://github.com/luanpotter/audioplayers/pull/94/commits/87400e8f5075610f28665789dc378411bb9c5d9b#diff-0d38bc893a1941a63feb39dff03dc4aaR79) , [iOS](https://github.com/luanpotter/audioplayers/pull/94/commits/87400e8f5075610f28665789dc378411bb9c5d9b#diff-c5e5f437abe74dbf4e1ba771ce7344b5R140)), the results of settting rate call are ```0, 1, 2, 3```. I know, hard to understand... So is there any advice to simply this logic?

One fragile thought, is that possible not to control player status in dart side, instead, get it directly from native palyer?

**Comment by dvorapa** [comment]
Discussed further in #224: for iOS already fixed, for Android there is a patch coming: #304

**Comment by erickzanardo** [comment]
Closing due inactivity

**Comment by dvorapa** [comment]
I think this is solved already
