### ISSUE TITLE
Unable to play audio assets from the websites with cloud flare protection

### ISSUE THREAD

**Issue by mirkancal** [luanpotter/audioplayers#761]
Unable to play audio assets from the websites with cloud flare protection.

**Full Description**
I'm building a podcast app for a radio station and currently they added cloudflare. I'm sure it's relate to the cloudflare because I also had problem with the images in the app. I fix the image problem with CachedNetworkImage plugin but not sure how to resolve that ddos protection problem with the audioplayers plugin. There's no logs or errors, it just won't start playing.

**Files/URLs/Sources**
Link I'm trying to play is: https://www.shannonside.ie/wp-content/uploads/sites/11/Charlie-McConalague.mp3

**Platforms**
iOS and Android

**Comment by luanpotter** [comment]
The link doesn't seem to exist...

**Comment by erickzanardo** [comment]
Closing this as the link don't seems to exists. Feel free to comment here if you disagree and we can re open this.
