### ISSUE TITLE
Seamless looping

### ISSUE THREAD

**Issue by hexrcs** [luanpotter/audioplayers#77]
Hi, first of all thanks a lot for this great library and happy new year!

While building a demo app, I've noticed that there's always a small "gap" between loops if I set the `ReleaseMode` to "loop". Is it possible to fix this?

(I used AudioCache to playback audio from the assets)

**Comment by erickzanardo** [comment]
Hello @hexrcs can you confirm on which Platform is the problem? Is it android? Android has a problem history with gapless audio looping, and util today there not really a good solution.

[The recommendation from google](https://developer.android.com/about/versions/android-4.1#Gapless) to achieve this is using two audio players and to start the second when the first has ended. We could try to implement this on audioplayers, but right now we don't have time to make that change. So if you need this right now, you could try doing this directly on flutter, having two instances of the audioplayers and playing the second right after the first finished, and repeating this process.

**Comment by erickzanardo** [comment]
Great to hear that you get the workaround, looking forward to your PR, will keep this open for people who happen to have this same problem.

**Comment by xiaolongwuhpu** [comment]
> @erickzanardo Yes it was indeed on Android. Thanks for the tip, that's exactly what I did as a temporary workaround! When I have time I'll try to polish things up and create a PR for audioplayers.


Can you contribute your code?

**Comment by falxcerebri** [comment]
Hi guys, 
I have somewhat similar problem, totally related to this one. I'm implementing a feature in my playground application that mimics loud horn: when user taps a button I start to play a sound (_start_), while user holds it I loop another sample (_middle_) and when tap is finished/cancelled an ending sound is played (_end_).

And yeah, there's this gap between _start_ and _middle_, _middle_ and _middle_ during loops and finally between _middle_ and _end_. So far, I've attempted to:

* use 3 players - one for each sample
* cache with fixed player
* cache starting new players

I use `onPlayerCompletion.listen` to find out when _start_ finishes to play _middle_ in a loop and store the reference to player. When tap finishes/cancels I stop the _middle_ player and play single _end_.

So far without luck. The gap persists in every attempt...

**Comment by hexrcs** [comment]
Hey guys, sorry for the delay. I tried to add my workaround to the library a while ago, but realized that the library API needs to be extended and was a bit hesitant how I should proceed. 

---

@erickzanardo @luanpotter 

Is it OK to add a new API (eg. a new `SeamlessLoopPlayer` class) to the library? My specific workaround was to alternate 2 players with the same source, overlapping and cross-fade a few milliseconds. I would like to default that overlap to 10ms but make it adjustable.

---

@falxcerebri The idea is to start the second clip *right before* the first one ends. You need to cross-fade the contact surfaces to avoid the gap, try automating the volume. :)

**Comment by falxcerebri** [comment]
Yeah, SoundPool solves the issue. I've used `PlayerMode.LOW_LATENCY` . To avoid gap between Sound 1 and Sound 2, use fixed player and do not stop Sound 1, just straight away play Sound 2 after a timer or something. Also while using `PlayerMode.LOW_LATENCY` you don't receive playback events.

**Comment by MeteC** [comment]
This `LOW_LATENCY` is awesome! However it took me a day of mangling code and trying to roll my own audio player to realise that this works perfectly for looping audio tightly in Android - perhaps adding that to the README would be really helpful (i.e. `LOW_LATENCY` mode is not just "better for gaming sounds" :-) )

**Comment by TheKashe** [comment]
I'm trying this on iOS and despite LOW_LATENCY mode I have a gap between repetitions playing "endless" wav file.

**Comment by erickzanardo** [comment]
Seamless looping does not works on this package.

We have created a "sister" library, which is way simpler, but is specialized on that, please it here: https://github.com/fireslime/flutter_gapless_audio_loop

We are still evolving it and there is any feature on audioplayers that you need, that is not present there, feel free to open a feature request there.

**Comment by orestesgaolin** [comment]
Hi there, seeing that both https://github.com/bluefireteam/flutter_gapless_audio_loop and ocarina haven't been updated in a while I was wondering if the seamless playback would be possible with just_audio? In my experience neither using compressed (aac, mp3) or uncompressed audio files (wav) on iOS works to achieve gapless playback.

Sorry for restoring super old topic, but didn't want to create a new one if the answer is still the same.

**Comment by luanpotter** [comment]
Sadly it is an inherent issue of the underlying platforms. The best you can try with audioplayers is to use low_latency and an audiopool to preload the same audio in two audio players and control the transition yourself. But there seem to have been recent community effort to fix this kind of issue with [flutter_soloud](https://github.com/alnitak/flutter_soloud)
