### ISSUE TITLE
AudioPlayer - Add tutorials

### ISSUE THREAD

**Issue by yigtkaya** [luanpotter/audioplayers#772]
hi, Im looking for total tutorial for Audiplayer plugin flutter but ı couldn't find any. There are all speed codes or just typing code :( Is there any informative tutorial you could share.

**Comment by luanpotter** [comment]
The readme explain the basics of mostly everything you need to know, also you can check the example app or the code itself for deeper insights. We don't have any specific tutorials as of writing.

**Comment by erickzanardo** [comment]
@luanpotter do we want to maintain tutorials? If not we should close this

Giving the size of this packaged we should improve docs rather than having tutorials IMO

**Comment by luanpotter** [comment]
Agreed
