### ISSUE TITLE
play the song several times, an error appears.

### ISSUE THREAD

**Issue by minikupa** [luanpotter/audioplayers#773]
https://github.com/luanpotter/audioplayers/issues/682
same issue.

If you play the song several times, an error appears.
Error Message
E/MediaPlayerNative( 4392): error (1, -19)
E/MediaPlayer( 4392): Error (1,-19)
E/MediaPlayerNative( 4392): pause called in state 0, mPlayer(0xb832a5e0)
E/MediaPlayerNative( 4392): error (-38, 0)
E/MediaPlayerNative( 4392): Attempt to perform seekTo in wrong state: mPlayer=0xb832a5e0, mCurrentState=0
E/MediaPlayerNative( 4392): error (-38, 0)
E/MediaPlayer( 4392): Error (-38,0)
E/MediaPlayer( 4392): Error (-38,0)

**Comment by karloscode** [comment]
same issue here , if you use audiocache , you can try this code: 

`player.play('gong.mp3',
      mode: PlayerMode.LOW_LATENCY, 
      stayAwake: false);`

works for me

**Comment by StanislavBond** [comment]
Same error here, after several times it just stop playing and start with same error messages. Sadly, no response here nor discord/stackoverflow.

**Comment by najib-mrh** [comment]
> #682
> same issue.
> 
> If you play the song several times, an error appears.
> Error Message
> E/MediaPlayerNative( 4392): error (1, -19)
> E/MediaPlayer( 4392): Error (1,-19)
> E/MediaPlayerNative( 4392): pause called in state 0, mPlayer(0xb832a5e0)
> E/MediaPlayerNative( 4392): error (-38, 0)
> E/MediaPlayerNative( 4392): Attempt to perform seekTo in wrong state: mPlayer=0xb832a5e0, mCurrentState=0
> E/MediaPlayerNative( 4392): error (-38, 0)
> E/MediaPlayer( 4392): Error (-38,0)
> E/MediaPlayer( 4392): Error (-38,0)

what version do you use ?

**Comment by minikupa** [comment]
0.17.3

**Comment by neoacevedo** [comment]
Same, But I can't upgrade due for minsdk version.

**Comment by uugurbas** [comment]
> same issue here , if you use audiocache , you can try this code:
> 
> `player.play('gong.mp3', mode: PlayerMode.LOW_LATENCY, stayAwake: false);`
> 
> works for me
> 
> NOTE: you must import audioplayers to make it work not only audioCache:
> 
> `import 'package:audioplayers/audioplayers.dart';`

also worked for me. You are great :)

**Comment by neoacevedo** [comment]
Taht not worked for me.

**Comment by leviticus777** [comment]
I was experiencing the same problem as well. I made a very minor modification which seems to _mostly_ resolve the issue, as in I no longer receive the error messages as above and do not have to completely restart the application to get sounds to play again. 

Here's my temporary workaround:
(in audio_cache.dart):
Future<AudioPlayer> play(
..
..
..
player.setReleaseMode(ReleaseMode.STOP) <--- Change this to ReleaseMode.RELEASE

Let me know if this works for anyone else. Note: Running on Android, using audioplayers v0.18.1.

**Comment by hhfa1990** [comment]
> Same error here, after several times it just stop playing and start with same error messages. Sadly, no response here nor discord/stackoverflow.

Works for me

**Comment by erickzanardo** [comment]
Closing in favor of #843
