### ISSUE TITLE
API documentation for the last version is broken

### ISSUE THREAD

**Issue by dvorapa** [luanpotter/audioplayers#774]
When you look at https://pub.dev/packages/audioplayers there is no API documentation link. On page https://pub.dev/packages/audioplayers/versions you can see the docs for the last version could not be generated due to some error (there is also a logfile available to examine, what went wrong).

**Comment by luanpotter** [comment]
I think this was actually an issue with pub, I looked at the logs back then and didn't find any hints to why. But now I looked again and it seems all the docs are up and running. Thanks for reporting @dvorapa
