### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by atreeon** [luanpotter/audioplayers#776]
I've just been experimenting with null safety as it is in beta now.  This would be the only project that I depend on that doesn't have null safety enabled.  Any thoughts about releasing a null safety version?

**Comment by jinfagang** [comment]
Yes:

```
Thus, audioplayers >=0.16.2 is incompatible with archive >=3.0.0-nullsafety.0.
```
Doesn't coompatible with some basic lib that with nullsafety on.

**Comment by nt4f04uNd** [comment]
@jinfagang if you have some troubles with dependencies you can try to use `dependecy_overrides`, most likely they don't have any breaking changes and just migrated to nnbd

**Comment by chavesgu** [comment]
[https://dart.dev/null-safety/migration-guide](https://dart.dev/null-safety/migration-guide)

**Comment by EgHubs** [comment]
I think it's time for an upgrade now?
`Because audioplayers 0.17.4 depends on path_provider ^1.6.22 and no versions of audioplayers match >0.17.4 <0.18.0, audioplayers ^0.17.4 requires path_provider ^1.6.22.
`

**Comment by stonekase** [comment]
> Yes:
> 
> ```
> Thus, audioplayers >=0.16.2 is incompatible with archive >=3.0.0-nullsafety.0.
> ```
> 
> Doesn't coompatible with some basic lib that with nullsafety on.

You can use my fork pending if my fix is merged as below in your pubspec.yml:

        #audioplayers: ^0.17.4
          audioplayers:
            git:
                url: https://github.com/stonekase/audioplayers.git

**Comment by fzyzcjy** [comment]
`archive` now is null safe! Can we migrate it now? https://pub.dev/packages/archive

**Comment by pcqpcq** [comment]
+1 for this

**Comment by AlabasterAxe** [comment]
@stonekase I'm seeing some build failures using your version on Android (see [this issue](https://github.com/luanpotter/audioplayers/issues/782)) are you seeing this and if so how did you resolve the issues? Thanks in advance!

**Comment by stonekase** [comment]
> @stonekase I'm seeing some build failures using your version on Android (see [this issue](https://github.com/luanpotter/audioplayers/issues/782)) are you seeing this and if so how did you resolve the issues? Thanks in advance!


Please ignore my repo and use :
dependencies:
  audioplayers: ^0.17.4

dependency_overrides:
  path_provider: ^2.0.1

**Comment by deimantasa** [comment]
Any ETA for `null-safety` migration, guys?

**Comment by RR-Reddy** [comment]
This issue is Duplicated  please follow issue  #784

**Comment by luanpotter** [comment]
Fixed by https://github.com/luanpotter/audioplayers/pull/785
