### ISSUE TITLE
In IOS the playback rate can only be set to 0.5/1.0/1.5/2.0. The values in between don't work.

### ISSUE THREAD

**Issue by zvikasan** [luanpotter/audioplayers#778]
In IOS the playback rate can only be set to 0.5/1.0/1.5/2.0. The values in between don't work. So when I try to do:
`advancedPlayer.setPlaybackRate(playbackRate: 1.38)`
It doesn't work. No error is thrown, the playback rate stays unchanged.

**Code to Reproduce**
Just implement the player, load any song and try changing the playback rate to anything other than 0.5/1.0/1.5/2.0.
Try setting playback rate to 0.43 or 1.34 etc.
It works on Android, and doesn't work on IOS

* audioplayers version: 0.17.4
* release or not release: ran the app both in debug and release modes on iPhoneX

**Comment by luanpotter** [comment]
we don't have any special treatments for those values, so I suspect it might be a limitation of the platform. definitely requires some investigating.

**Comment by zvikasan** [comment]
> we don't have any special treatments for those values, so I suspect it might be a limitation of the platform. definitely requires some investigating.

I assume that it is not a platform limitation because eventually I found another package 'assets_audio_player', in which there is no such limitation.

**Comment by GabrielDumbrava** [comment]
Hi @luanpotter and @zvikasan! Do you think you have some time to investigate this in the next week or so? It's a great and helpful package, I would really need a fix for this and I don't have the expertise to look into it myself.

**Comment by luanpotter** [comment]
Fixed by #826
