### ISSUE TITLE
Use of audio cache

### ISSUE THREAD

**Issue by regenin** [luanpotter/audioplayers#779]
I got the sounds from local files. I start the music using the audio cache, but I want to turn it off by clicking the same button. How can I do that.  There is no stop command in the audio cache.

**Comment by erickzanardo** [comment]
Check the documentation https://github.com/luanpotter/audioplayers/blob/master/doc/audio_cache.md

You just need to call stop from the returned audio players instance

**Comment by abdulashifaachu** [comment]
cant load the documentation page of audio cache

**Comment by Gustl22** [comment]
@abdulashifaachu 
AudioCache is integrated in `AudioPlayer().audioCache`. You don't need to care about that anymore, only in special edge cases.
https://github.com/bluefireteam/audioplayers/blob/main/getting_started.md#audiocache
