### ISSUE TITLE
pub get : version solving failed after upgrade to flutter 2.0.0   with lottie ^1.0.0

### ISSUE THREAD

**Issue by front2020** [luanpotter/audioplayers#780]
Because audioplayers >=0.16.2 depends on uuid ^2.2.2 which depends on crypto ^2.0.0, audioplayers >=0.16.2 requires crypto ^2.0.0.
And because archive >=3.0.0 depends on crypto ^3.0.0, audioplayers >=0.16.2 is incompatible with archive >=3.0.0.
And because lottie 1.0.0 depends on archive ^3.0.0 and no versions of lottie match >1.0.0 <2.0.0, audioplayers >=0.16.2 is incompatible with lottie ^1.0.0.
So, because flutter_web_demo depends on both lottie ^1.0.0 and audioplayers ^0.17.4, version solving failed.
pub get failed (1; So, because flutter_web_demo depends on both lottie ^1.0.0 and audioplayers ^0.17.4, version solving failed.)

while using :
dependencies:
  flutter:
    sdk: flutter
  lottie: ^1.0.0
  audioplayers: ^0.17.4
  
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.0, on Mac OS X 10.15.7 19H15 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
[✓] VS Code (version 1.53.2)
[✓] Connected device (3 available)

• No issues found!

**Comment by allanwolski** [comment]
Having the same issue here.

```
Because no versions of printing match >5.0.1 <6.0.0 and printing 5.0.1 depends on pdf ^3.0.1, printing ^5.0.1 requires pdf ^3.0.1.
And because no versions of pdf match >3.0.1 <4.0.0 and pdf 3.0.1 depends on crypto ^3.0.0, printing ^5.0.1 requires crypto ^3.0.0.
And because audioplayers >=0.16.2 depends on uuid ^2.2.2 which depends on crypto ^2.0.0, printing ^5.0.1 is incompatible with audioplayers >=0.16.2.
So, because bsoft_docs depends on both audioplayers ^0.17.0 and printing ^5.0.1, version solving failed.
pub get failed (1; So, because bsoft_docs depends on both audioplayers ^0.17.0 and printing ^5.0.1, version solving failed.)
```

**Comment by luanpotter** [comment]
Fixed by https://github.com/luanpotter/audioplayers/pull/785
