### ISSUE TITLE
update path_provider dependency version

### ISSUE THREAD

**Issue by transitguide** [luanpotter/audioplayers#781]
Need to update the version of path_provider dependency to 2.0.1. Currently, its 1.6.22 which is not allowing the build.

Full error:
because audioplayers >=0.16.2 depends on path_provider ^1.6.22 which depends on path_provider_windows ^0.0.4, audioplayers >=0.16.2 requires path_provider_windows ^0.0.4.
And because shared_preferences >=2.0.0 depends on shared_preferences_windows ^2.0.0 which depends on path_provider_windows ^2.0.0, audioplayers >=0.16.2 is incompatible with shared_preferences >=2.0.0.
ecause audioplayers >=0.16.2 depends on path_provider ^1.6.22 which depends on path_provider_windows ^0.0.4, audioplayers >=0.16.2 requires path_provider_windows ^0.0.4.
And because shared_preferences >=2.0.0 depends on shared_preferences_windows ^2.0.0 which depends on path_provider_windows ^2.0.0, audioplayers >=0.16.2 is incompatible with shared_preferences >=2.0.0.

**Comment by mikes222** [comment]
A quirky and potentially hazardous fix until it is solved:

    dependency_overrides:
        # necessary because audioplayers: 0.17.4 is not updated to use path_provider 2.0.1
        path_provider: '>= 1.6.22 <= 2.0.1'
  
        # necessary because audioplayers: 0.17.4 is not updated to use crypto 3.0.0
        crypto: '>= 2.0.0 <= 3.0.0'
  
        # necessary because audioplayers: 0.17.4 is not updated to use convert 3.0.0
        convert: '>= 2.0.0 <= 3.0.0'

**Comment by allanwolski** [comment]
Having the same issue here.

```
Because no versions of printing match >5.0.1 <6.0.0 and printing 5.0.1 depends on pdf ^3.0.1, printing ^5.0.1 requires pdf ^3.0.1.
And because no versions of pdf match >3.0.1 <4.0.0 and pdf 3.0.1 depends on crypto ^3.0.0, printing ^5.0.1 requires crypto ^3.0.0.
And because audioplayers >=0.16.2 depends on uuid ^2.2.2 which depends on crypto ^2.0.0, printing ^5.0.1 is incompatible with audioplayers >=0.16.2.
So, because bsoft_docs depends on both audioplayers ^0.17.0 and printing ^5.0.1, version solving failed.
pub get failed (1; So, because bsoft_docs depends on both audioplayers ^0.17.0 and printing ^5.0.1, version solving failed.)
```

**Comment by cto-leaps** [comment]
Same here !

**Comment by marcschw** [comment]
Same here - this is critical, it currently blocks upgrade to the newest major firebase branch:

```
Because firebase_core >=1.0.0 depends on firebase_core_platform_interface ^4.0.0 which depends on plugin_platform_interface ^2.0.0, firebase_core >=1.0.0 requires plugin_platform_interface ^2.0.0.

And because path_provider >=1.6.4 <2.0.0-nullsafety depends on path_provider_platform_interface ^1.0.1 which depends on plugin_platform_interface ^1.0.1, firebase_core >=1.0.0 is incompatible with path_provider >=1.6.4 <2.0.0-nullsafety.

And because audioplayers 0.17.4 depends on path_provider ^1.6.22 and no versions of audioplayers match >0.17.4 <0.18.0, firebase_core >=1.0.0 is incompatible with audioplayers ^0.17.4.
```

**Comment by hadi20sa** [comment]
Having the same issue here...

**Comment by iteanjd** [comment]
+1

**Comment by amendgit** [comment]
same here!

**Comment by atakhan** [comment]
> A quirky and potentially hazardous fix until it is solved:
> 
> ```
> dependency_overrides:
>     # necessary because audioplayers: 0.17.4 is not updated to use path_provider 2.0.1
>     path_provider: '>= 1.6.22 <= 2.0.1'
> 
>     # necessary because audioplayers: 0.17.4 is not updated to use crypto 3.0.0
>     crypto: '>= 2.0.0 <= 3.0.0'
> 
>     # necessary because audioplayers: 0.17.4 is not updated to use convert 3.0.0
>     convert: '>= 2.0.0 <= 3.0.0'
> ```

thanks it works!

**Comment by Luancarlos** [comment]
Having the same issue here!

**Comment by Xawery94** [comment]
> A quirky and potentially hazardous fix until it is solved:
> 
> ```
> dependency_overrides:
>     # necessary because audioplayers: 0.17.4 is not updated to use path_provider 2.0.1
>     path_provider: '>= 1.6.22 <= 2.0.1'
> 
>     # necessary because audioplayers: 0.17.4 is not updated to use crypto 3.0.0
>     crypto: '>= 2.0.0 <= 3.0.0'
> 
>     # necessary because audioplayers: 0.17.4 is not updated to use convert 3.0.0
>     convert: '>= 2.0.0 <= 3.0.0'
> ```

It worked for me also, but will be nice if that changes will be in next package version 🚀

**Comment by H4llJ0rdan** [comment]
Same issue here, with firebase_core >=1.0.0.

**Comment by luanpotter** [comment]
Fixed by https://github.com/luanpotter/audioplayers/pull/785
