### ISSUE TITLE
Android: Cannot access built-in declaration 'kotlin.XXXXX' Ensure that you have a dependency on the Kotlin standard library

### ISSUE THREAD

**Issue by AlabasterAxe** [luanpotter/audioplayers#782]
When trying to build on android I get a bunch of errors coming from audioplayers that mention not being able to access various kotlin builtins.

**Full Description**
I try to build the project for android and it doesn't work.

**Code to Reproduce**
This is the repo that reproduces the errors: https://github.com/AlabasterAxe/audio_players, it's just a minimal `flutter create` with audioplayers as a dependency, using @stonekase's fork as the version: https://github.com/stonekase/audioplayers

**Log Errors**
https://gist.github.com/AlabasterAxe/96a99c01df804034f56cfc74090c5913

**Platforms**
Android - Fails
Web - Works

**Comment by stonekase** [comment]
Please Kindly use the below in your pubscpec:

audioplayers: ^0.17.4


dependency_overrides:
  path_provider: ^2.0.1

**Comment by AlabasterAxe** [comment]
Okay great, that seems to me working for me. Thanks!
