### ISSUE TITLE
upgrade uuid dependency version

### ISSUE THREAD

**Issue by transitguide** [luanpotter/audioplayers#783]
Unable to use extended_image library because of uuid dependency version issue.
Need to upgrade uuid to 3.0.0.

Because extended_image >=3.0.0 depends on extended_image_library ^2.0.1 which depends on crypto ^3.0.0, extended_image >=3.0.0 requires crypto ^3.0.0.

And because uuid 2.2.2 depends on crypto ^2.0.0, extended_image >=3.0.0 is incompatible with uuid 2.2.2.

Because every version of audioplayers from git depends on uuid ^2.2.2 and no versions of uuid match >2.2.2 <3.0.0, every version of audioplayers from git requires uuid 2.2.2.

Thus, extended_image >=3.0.0 is incompatible with audioplayers from git.

**Comment by iteanjd** [comment]
+1

**Comment by luanpotter** [comment]
Fixed by https://github.com/luanpotter/audioplayers/pull/785
