### ISSUE TITLE
Can't play same file twice on iOS 

### ISSUE THREAD

**Issue by Kraakhoofd** [luanpotter/audioplayers#787]
### The issue
No issue on Android.
On iOS: I play a Firebase (web) mp3 file, wait for it to finish and then play it again, the playback is instantly completed (oncompletion listener fires, nothing plays). When I don't let it finish, but instead let it play again (so restart) while it is still playing, it will play again correctly.
When I let mp3 file A finish, then play mp3 file B, I can again play mp3 file A.

Code below. As you can see, I use a singleton approach to the helper class.

### Version
Audioplayers 0.17.4
Flutter (Channel beta, 2.0.0, on Microsoft Windows [Version 10.0.18363.1379], locale en-NL)
Occurs on both simulator and physical device

### Code
`typedef void OnError(Exception exception);

String kUrl = "";
bool initialized = false;

List<String> queue = new List();
enum PlayerState { stopped, playing, paused }

class AudioPlayerHelper {
  static final AudioPlayerHelper _instance = new AudioPlayerHelper.internal();

  AudioPlayerHelper.internal();

  factory AudioPlayerHelper() {
    return _instance;
  }

  void playFromFireBase(String firebaseURL) async {
    if (audioPlayer.state == AudioPlayerState.PLAYING) {
      await audioPlayer.stop();
    }

    final Reference ref = FirebaseStorage.instance.ref().child(firebaseURL);

    try {
      String url = await ref.getDownloadURL();
      audioPlayer.play(url, isLocal: false);
    } catch (Exception) {
      Fluttertoast.showToast(
        msg: "Sound not yet recorded or no internet connection",
        toastLength: Toast.LENGTH_SHORT,
        gravity: ToastGravity.BOTTOM,
      );
    }
  }

  Duration duration;
  Duration position;

  AudioPlayer audioPlayer;

  String localFilePath;

  PlayerState playerState = PlayerState.stopped;

  get isPlaying => playerState == PlayerState.playing;

  get isPaused => playerState == PlayerState.paused;

  get durationText =>
      duration != null ? duration.toString().split('.').first : '';

  get positionText =>
      position != null ? position.toString().split('.').first : '';

  bool isMuted = false;

  void setURL(String url) {
    kUrl = url;
  }

  void initAudioPlayer() {
    audioPlayer = new AudioPlayer();
    audioPlayer.onPlayerCompletion.listen((event) {
      print("completed playing file!");
      if (queue.isNotEmpty) {
        String url = queue.elementAt(0);
        queue.removeAt(0);
        playFromFireBase(url);
      }
    });

    audioPlayer.durationHandler = (d) => {duration = d};

    audioPlayer.positionHandler = (p) => {position = p};

    initialized = true;
  }

  Future play() async {
    final result = await audioPlayer.play(kUrl);
    if (result == 1) playerState = PlayerState.playing;
  }

  Future playLocal() async {
    final result = await audioPlayer.play(localFilePath, isLocal: true);
    if (result == 1) playerState = PlayerState.playing;
  }

  Future pause() async {
    final result = await audioPlayer.pause();
    if (result == 1) (playerState = PlayerState.paused);
  }

  Future stop() async {
    final result = await audioPlayer.stop();
    if (result == 1) {
      playerState = PlayerState.stopped;
      position = new Duration();
    }
  }

  void seekToSecond(int second) {
    Duration newDuration = Duration(seconds: second);
    audioPlayer.seek(newDuration);
  }

  void onComplete() {
    playerState = PlayerState.stopped;
  }

  @override
  void dispose() {
    audioPlayer.stop();
  }

  Future<Uint8List> _loadFileBytes(String url, {OnError onError}) async {
    Uint8List bytes;
    try {
      bytes = await readBytes(url);
    } on ClientException {
      rethrow;
    }
    return bytes;
  }

}
`

**Comment by SPlus91** [comment]
Same problem here, please any news for possible fix? Really need it...

**Comment by SPlus91** [comment]
it seems that the bug is not present in version 0.16.1... This is probably a bug introduced with the latest update

**Comment by koji-1009** [comment]
v0.16.1 does not happen this issue.
This problem is occurred v0.17.0.

If you want to know more detail, please check #767.

**Comment by luanpotter** [comment]
With https://github.com/luanpotter/audioplayers/pull/767 merged, is this fixed?

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
