### ISSUE TITLE
duckAudio does nothing on iOS

### ISSUE THREAD

**Issue by billy1380** [luanpotter/audioplayers#789]
**Full Description**
duckAudio does not seem to do anything on iOS... it should allow mixing audio, this does not seem to be the case

**Code to Reproduce**
``` dart
AudioCache _audioCache = AudioCache(
      prefix: "audio/",
      fixedPlayer: AudioPlayer(
        mode: PlayerMode.LOW_LATENCY,
        playerId: "fx",
      ),
      duckAudio: true,
    );

await _audioCache.load("count_down.wav");
await _audioCache.play(
      file,
      duckAudio: true,
    );
```

**Files/URLs/Sources**
Wav file is not supported... but any short audio file will illustrate the point.

**Platforms**
* iOS only, tested with iOS 12 on iphone 6 plus
* Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.7 19H524 darwin-x64,
    locale en-GB)
* audioplayers version: ^0.17.4

I have already looked at the code and the parameter is not even extracted on iOS.

**Comment by luanpotter** [comment]
Fixed by https://github.com/luanpotter/audioplayers/pull/791
