### ISSUE TITLE
bug in version android

### ISSUE THREAD

**Issue by mbfakourii** [luanpotter/audioplayers#795]
hi i can not build version 0.17 my phone in android 21 but minsdk is 23 please cheng to 21 

https://github.com/luanpotter/audioplayers/commit/87313c2d52e80516dc831ab486d84adf3cad06dc#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65a
@luanpotter

**Comment by hatemragab** [comment]
same problem with me!

**Comment by simon-the-shark** [comment]
```
BUILD FAILED in 1m 43s
Running Gradle task 'assembleDebug'...                            105,1s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin audioplayers...
Running Gradle task 'assembleAarRelease'...                      1 505ms

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/shark/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.17.4/android/build.gradle' line: 25

* What went wrong:
A problem occurred evaluating root project 'audioplayers'.
> Failed to apply plugin [id 'kotlin-android']
   > The current Gradle version 4.10.2 is not compatible with the Kotlin Gradle plugin. Please use Gradle 5.3 or newer, or the previous version of the Kotlin plugin.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Exception: The plugin audioplayers could not be built due to the issue above.
```

**Comment by simon-the-shark** [comment]
It's a new error for me, I was able to build my app few days ago

**Comment by JackRichardBusiness** [comment]
I can't build either. Seems like a very new issue.

**Comment by sgg-labs** [comment]
> ```
>    > The current Gradle version 4.10.2 is not compatible with the Kotlin Gradle plugin. Please use Gradle 5.3 or newer, or the previous version of the Kotlin plugin.
> ```
What you describe might be different from the OP's issue, but here is the Gradle version quick fix that worked for me:

**In build.gradle:**
replaced
`    ext.kotlin_version = '1.4.21'`
with
`    ext.kotlin_version = '1.4.31'`
and
`        classpath 'com.android.tools.build:gradle:3.3.0'`
with
`        classpath 'com.android.tools.build:gradle:4.1.2'`

**In gradle-wrapper.properties**
replaced
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip`
with
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip`

**Comment by JackRichardBusiness** [comment]
> > ```
> >    > The current Gradle version 4.10.2 is not compatible with the Kotlin Gradle plugin. Please use Gradle 5.3 or newer, or the previous version of the Kotlin plugin.
> > ```
> 
> What you describe might be different from the OP's issue, but here is the Gradle version quick fix that worked for me:
> 
> **In build.gradle:**
> replaced
> ` ext.kotlin_version = '1.4.21'`
> with
> ` ext.kotlin_version = '1.4.31'`
> and
> ` classpath 'com.android.tools.build:gradle:3.3.0'`
> with
> ` classpath 'com.android.tools.build:gradle:4.1.2'`
> 
> **In gradle-wrapper.properties**
> replaced
> `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip`
> with
> `distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip`
> 
> I'm building with a local copy of the package for now until the issue is fixed in pub.

Hi, thanks for the help. It's very strange that this starting causing issues all of a sudden for me...

**Comment by simon-the-shark** [comment]
Quite interesting is the fact that the problem seems to have resolved itself for now, even though I haven't changed a thing. But that's just my case.

**Comment by tamonmon0417** [comment]
This operation solved the problem for me.
Not sure about the reason.

1. once downgrade the audioplayers to 0.17.0 at pubspec.yaml
```yaml
  audioplayers: 0.17.0
```
then
```
$ flutter clean
$ flutter pub get
$ flutter run
```

2. upgrade  audioplayers to 0.17.3 again
```
  audioplayers: 0.17.3
```
then clean&get again
```
$ flutter clean
$ flutter pub get
$ flutter run
```

**Comment by sgg-labs** [comment]
> This operation solved the problem for me...
>
I repeated your steps with ^0.17.4 instead of 0.17.3 and it also worked. Go figure.

**Comment by searchy2** [comment]
Add a tools override to the AndroidManifest

>     <uses-sdk tools:overrideLibrary="xyz.luan.audioplayers"/>

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.app.flutter.host">

    <!-- The INTERNET permission is required for development. Specifically,
         flutter needs it to communicate with the running application
         to allow setting breakpoints, to provide hot reload, etc.
    -->
    <uses-permission android:name="android.permission.INTERNET"/>

    <uses-sdk tools:overrideLibrary="xyz.luan.audioplayers"/>

    <application
        android:label="App"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

**Comment by luanpotter** [comment]
Closing in lieu of https://github.com/luanpotter/audioplayers/issues/749

**Comment by luanpotter** [comment]
Also that is hardly a "bug". It was an intentional decision and wasn't even done by me...
