### ISSUE TITLE
access audio Player controllers all over the app

### ISSUE THREAD

**Issue by Shubham-Phatale** [luanpotter/audioplayers#796]
I want to create a floating widget of audio player controllers through which i can resume and pause current audio which is playing, i have created that widget successfully but not able to pause or resume audio is there any method through which i can access audio players controller throughout my app. also if i am playing another audio new instance is created but i want to play that audio in same instance. please help

**Comment by erickzanardo** [comment]
Please, follow the issue template when creating issues.

There are many libraries that allow you to share resources across your application, for example Provide, GetIt, I suggest you taking a look on those.
