### ISSUE TITLE
And because no versions of get_storage match >2.0.1 <3.0.0, audioplayers >=0.16.2 is incompatible with get_storage ^2.0.1.

### ISSUE THREAD

**Issue by MisterioRee** [luanpotter/audioplayers#797]
["Cannot user with get_storage after 2.0 upgrade"  ]

**Full Description**
I am using   `get_storage: ^2.0.1`  but it throws and error:
**Because audioplayers >=0.16.2 depends on path_provider ^1.6.22 and get_storage 2.0.1 depends on path_provider ^2.0.1, audioplayers >=0.16.2 is incompatible with get_storage 2.0.1.**

 

**Log Errors**
Because audioplayers >=0.16.2 depends on path_provider ^1.6.22 and get_storage 2.0.1 depends on path_provider ^2.0.1, audioplayers >=0.16.2 is incompatible with get_storage 2.0.1.

And because no versions of get_storage match >2.0.1 <3.0.0, audioplayers >=0.16.2 is incompatible with get_storage ^2.0.1.

So, because project_name depends on both get_storage ^2.0.1 and audioplayers ^0.17.4, version solving failed.
pub get failed (1; So, because project_name depends on both get_storage ^2.0.1 and audioplayers ^0.17.4, version solving failed.)
exit code 1

  
**Platforms**
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version
    10.0.18363.1379], locale en-US)
    • Flutter version 2.0.2 at C:\flutter
    • Framework revision 8962f6dc68 (4 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Muhammad Rehan\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Muhammad Rehan\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\Muhammad Rehan\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.2)
    • VS Code at C:\Users\Muhammad Rehan\AppData\Local\Programs\Microsoft VS
      Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 89.0.4389.82
    • Edge (web)                  • edge          • web-javascript • Microsoft
      Edge 89.0.774.50

**Comment by erickzanardo** [comment]
Duplicated #781
