### ISSUE TITLE
audio is stuttering

### ISSUE THREAD

**Issue by MarcelHH** [luanpotter/audioplayers#809]
audio is stuttering / crackest why? does it have to be a special audio format or something?

**Comment by erickzanardo** [comment]
There are many reasons why this can happen. There isn't any relevant information here to guess what may be happening.

Please, add more information and follow the issue template. Otherwise there isn't much we can do to help.

**Comment by erickzanardo** [comment]
Closing due inactivity, if there is more info that you can add to the issue, comment here and we can re open the issue.
