### ISSUE TITLE
Resume to background playing audio

### ISSUE THREAD

**Issue by femibiwoye** [luanpotter/audioplayers#81]
Assuming i am playing a song and i go out of the page either by pressing the back or the home button, i want to be able to resume back to the music that is playing in the background. Instead if playing multiple song. I am fetching the song with url.

I'm not sure of what to do

**Comment by luanpotter** [comment]
Probably you are using a AudioCache, in this case every time you call `play` a new AudioPlayer instance is created, you can `pause`/`resume` each playing getting a hold of your audioPlayer instance and calling the methods on that (instead of calling play again in the cache). You can also set `fixedPlayer` property if you want always a single player.

**Comment by femibiwoye** [comment]
Thank you very much for your response.

@luanpotter I checked the plugin, there is no property for `fixedPlayer`.

I already removed stop from disposed
`void dispose() {
    //This stops the song when you are leaving the player page
    //_audioPlayer.stop();
    super.dispose();
  }`

If i leave the page while the music is still playing, and i click on another audio file, instead of it to stop the previous playing song and start playing the new song, it plays the new song without stopping the previous song. 
If i check if any song is currently playing, `_audioPlayer` returns null, therefore, i cannot pause or resume a null property.

Thanks

**Comment by mooditech** [comment]
Hi @femibiwoye, I was also having the same issue. Here was my solution: Go into audioplayers.dart and comment out the method where AudioPlayer creates a new instance, or you can just set playerId to itself (playerId = playerId) . Do ctrl-f "creates" to find the method.

 @luanpotter would doing this effect anything within the stability of the plugin? In other words, is it possible to act on the same instance of _audioPlayer without modifying the plugin itself?

**Comment by FadiChaalab** [comment]
Hi, i have the same problem i try it your solution but it didn't work for me i need help.
