### ISSUE TITLE
The following assertion was thrown while handling a gesture: Assertion failed: file:///D:/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.18.1/lib/audio_cache.dart:49:15 !kIsWeb "AudioCache is not available for Flutter Web."

### ISSUE THREAD

**Issue by maryharry** [luanpotter/audioplayers#819]
When the exception was thrown, this was the stack: 
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
packages/audioplayers/audio_cache.dart 49:15                                                                               new
packages/xylophone/main.dart 17:32                                                                                         <fn>
packages/flutter/src/material/ink_well.dart 991:14                                                                         [_handleTap]
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#63710
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(537.3, 282.0)
  finalLocalPosition: Offset(59.3, 9.3)
  button: 1
  sent tap down
================================================================

**Comment by erickzanardo** [comment]
Like the error says, AudioCache is not available on web. Check the readme for more info.

And please, follow the template when opening issues.

**Comment by erickzanardo** [comment]
Like the error says, AudioCache is not available on web. Check the readme for more info.

And please, follow the template when opening issues.
