### ISSUE TITLE
Icestream metadata

### ISSUE THREAD

**Issue by OperKH** [luanpotter/audioplayers#82]
Is it possible to get Icestream metadata?
I want to take a song name from metadata and show it to user.

Here is a description how to request the metadata: https://stackoverflow.com/questions/6061057/developing-the-client-for-the-icecast-server/6072488#6072488

**Comment by OperKH** [comment]
Actually I found another way to solve my issue.
Icecast server supports to get metadata as a JSONP response.
You need to do GET request to `[your server URL]/json.xsl`

So closing this issue.

**Comment by erickzanardo** [comment]
I am glad that you got ir working, thanks for letting us know
