### ISSUE TITLE
Flutter 2.0.2 dependency issues

### ISSUE THREAD

**Issue by nick-uk** [luanpotter/audioplayers#820]
Resolving dependencies issues

**Full Description**
> Resolving dependencies...
> Because every version of flutter_driver from sdk depends on crypto 2.1.5 and uuid >=3.0.0 depends on crypto ^3.0.0, flutter_driver from sdk is incompatible with uuid >=3.0.0.
> And because audioplayers >=0.18.0 depends on uuid ^3.0.1, flutter_driver from sdk is incompatible with audioplayers >=0.18.0.
So, because actions_tool depends on both audioplayers ^0.18.1 and flutter_driver any from sdk, version solving failed.

**Code to Reproduce**
> flutter pub upgrade

**Platforms**
> [✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [✓] Xcode - develop for iOS and macOS
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 4.0)
> [✓] Connected device (1 available)

**Comment by erickzanardo** [comment]
This don't seems to be a problem with Audioplayers itself, flutter_driver is depending on an older version of uuid because of the crypto package.

As far as I know flutter_driver is not ready/used on Flutter 2.0 anymore, integration_test is the tool used now.

**Comment by nick-uk** [comment]
You're right. Thanks a lot your comment solved my issue!

**Comment by erickzanardo** [comment]
Glad to help!
