### ISSUE TITLE
Crashed on Android API level 19 (and possibly any level below 21)

### ISSUE THREAD

**Issue by sgg-labs** [luanpotter/audioplayers#822]
An app built with minSdkVersion 16 crashed in Google Play pre-launch testing on Samsung Galaxy S3 (Android 4.3 SDK 18).

**Full Description**
The issue (see the stack trace below) is with AudioAttributes class, which is added in API level 21 according to this [https://developer.android.com/reference/kotlin/android/media/AudioAttributes.Builder](https://developer.android.com/reference/kotlin/android/media/AudioAttributes.Builder). Apparently lowering minSdkVersion to 16 affects more than just **playBytes** method.

**Log Errors**
```
FATAL EXCEPTION: main
java.lang.NoClassDefFoundError: android.media.AudioAttributes$Builder
	at xyz.luan.audioplayers.WrappedSoundPool$Companion.createSoundPool()
	at xyz.luan.audioplayers.WrappedSoundPool$Companion.access$createSoundPool()
	at xyz.luan.audioplayers.WrappedSoundPool.<clinit>()
	at xyz.luan.audioplayers.AudioplayersPlugin.getPlayer()
	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall()
	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall()
```

**Comment by erickzanardo** [comment]
Thanks for reporting this @sgg-labs this totally slipped way our attention.

@luanpotter this means that the LOW_LATENCY API only works on 21+. How do you wanna procede? Let's add an if API on this and add disclaimer on our README?

**Comment by luanpotter** [comment]
@erickzanardo can we please update the feature parity table? https://github.com/luanpotter/audioplayers/blob/master/feature_parity_table.md

also given the error is not that clear I would prefer adding back the if statements so we can have good messages (both for this and the byte array thing)
