### ISSUE TITLE
Audioplayers maybe using an old Gradle?

### ISSUE THREAD

**Issue by andreclinio** [luanpotter/audioplayers#828]
I was excited about returning my old Flutter project that uses AudioPlayers. I have waited the 3.0.0 version to start
using null safety. Then, when I updated my project to:

```
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.3"

dependencies:
(... )
  audioplayers: ^0.18.3
(...)
```

I have met the following error:
```
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file '/usr/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.18.3/android/build.gradle' line: 25

* What went wrong:
A problem occurred evaluating root project 'audioplayers'.
> Failed to apply plugin [id 'kotlin-android']
   > The current Gradle version 4.10.2 is not compatible with the Kotlin Gradle plugin. Please use Gradle 5.3 or newer, or the previous version of the Kotlin plugin.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s


Exception: The plugin audioplayers could not be built due to the issue above.
```

Have I missed something? Or maybe audioplayers needs some little adjustments?

Regards,

-- André

PS.: All I need in my project is to play some mp3 files. The library used to work like a charm (even on WEB). So, I think I may be missing something...

**Comment by mono424** [comment]
+1 same issue here:
```
* Where:
Build file '/Users/***/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.18.3/android/build.gradle' line: 25

* What went wrong:
A problem occurred evaluating root project 'audioplayers'.
> Failed to apply plugin [id 'kotlin-android']
   > The current Gradle version 4.10.2 is not compatible with the Kotlin Gradle plugin. Please use Gradle 5.3 or newer, or the previous version of the Kotlin plugin.
```

**Comment by simopelo00** [comment]
I got the same error with the same dependencies.

`Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.18.3\android\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating root project 'audioplayers'.
> Failed to apply plugin [id 'kotlin-android']
   > The current Gradle version 4.10.2 is not compatible with the Kotlin Gradle plugin. Please use Gradle 5.3 or newer, or the previous version of the Kotlin plugin.`

**Comment by beerline** [comment]
faced with same problem, but it is appeared when i updated `locatoin:^2.5.4` up to `location:^4.1.1`. [this comment resolve issue](https://github.com/Lyokone/flutterlocation/issues/525#issuecomment-803794520)

**Comment by luanpotter** [comment]
I grepped `4.10.2` on the repo and there are no references to that version. In fact in my local clone the version used is:

```
.gradle/6.1.1/
```

So I imagine this is some issue with your local setup, not AP. But if there is any code change we can do lmk (I'm glad to review a PR).

**Comment by andreclinio** [comment]
Actually, I don't use location library. So I think it is not the same problem here...
I am still trying to understand the problem (if something on my local computer is missing) -- despite the fact that the error signals the AP library.

Any help would be awesome...

**Comment by psrcek** [comment]
I'm getting the same error all of a sudden. The app was building fine yesterday.

if I do `./gradlew --version`, I get the following:

```

------------------------------------------------------------
Gradle 6.1.1
------------------------------------------------------------

Build time:   2020-01-24 22:30:24 UTC
Revision:     a8c3750babb99d1894378073499d6716a1a1fa5d

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.10 (Oracle Corporation 11.0.10+9)
OS:           Linux 5.11.8-artix1-1 amd64
```

**Comment by luanpotter** [comment]
Hum that is very odd...

Can you list the contents of the folder `~/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.18.3/android` ?

Specifically something like `settings.gradle` or a `.gradle/` directory?

Also (after grabbing all the relevant info from that folder) you can try [this](https://github.com/luanpotter/audioplayers/blob/master/troubleshooting.md#build-issues).

**Comment by psrcek** [comment]
```bash
$ ls ~/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.18.3/android
build.gradle  gradle  gradle.properties  gradlew  gradlew.bat  settings.gradle  src
$ cat ~/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.18.3/android/settings.gradle 
rootProject.name = 'audioplayers'
$ ls -la ~/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.18.3/android/.gradle/
total 16
drwxr-xr-x 4 david david 4096 Apr  6 11:52 .
drwxr-xr-x 5 david david 4096 Apr  6 11:52 ..
drwxr-xr-x 5 david david 4096 Apr  6 11:52 4.10.2
drwxr-xr-x 2 david david 4096 Apr  6 11:52 vcs-1
```

**Comment by psrcek** [comment]
Nothing is solved after cleaning and removing the pub cache.

**Comment by andreclinio** [comment]
Maybe this is not exactly solution. But I've tried to reset my project.
```
[user@host] cd myprojectdir
[user@host] flutter create .
```

Some files were created (or recreated) and suddenly audioplayer came back to compile and work properly.
I think this issue is related to some flutter/dart updates as as my project was a littler bit old.

I hope this helps to find a solution.

Regards.

**Comment by andreclinio** [comment]
As far as people can go on this way, I think I can close the issue.

**Comment by erickzanardo** [comment]
Thanks for the feedback @andreclinio.

So it seems that this issues only happens on older Flutter projects, I think we could add a new section on our FAQ warning about this and close this issue. Wdyt @luanpotter ?

**Comment by andreclinio** [comment]
It's ok for me. Waiting for some other feedback...

**Comment by IbrahimYildirim** [comment]
I'm also getting the same error after migrating to null-safety on my existing project. 

Tried ```flutter create .``` as @andreclinio suggested, but didn't work for me.

I deleted all my dependencies in ```pubspec.yaml```, made a ```pub get``` and them added them back with another ```pub get``` and it worked. 

Not sure what kind of sorcery this was, but it worked.

**Comment by andreclinio** [comment]
So, I will close...

**Comment by vjamrich** [comment]
@andreclinio Neither of the provided solutions worked for me. I would also like to add, that the error occurs in release mode and not in debug.

**Comment by andreclinio** [comment]
I had (maybe not the exactly your problem) this issue while running on debug and release modes.
As far as I could see, my flutter project was really old. Maybe some of the android files were obsolete so that the `flutter create .` command were enough for my specific environment.

I understand your concern. Have you already tried to create a small *new* project to see if the problem persists. And hen compare some of the android (manifest etc) file?

**Comment by manju1210** [comment]
same issue here

* What went wrong:
A problem occurred evaluating root project 'audioplayers'.
> Failed to apply plugin [id 'kotlin-android']
   > The current Gradle version 4.10.2 is not compatible with the Kotlin Gradle plugin. Please use Gradle 5.3 or newer, or the previous version of the Kotlin plugin.

**Comment by vjamrich** [comment]
Hey @manju1210 ,

I solved my issue by shifting focus from Audioplayers; while my project was fairly new (compared to other ones in this thread), I found out that the issue was cause by a different dependency which has not been updated for over a year. I don't have a clue why the error specifically mentioned Audioplayers, but I would suggest to look for a problem in any outdated code / dependency.

**Comment by manju1210** [comment]
Thank you for the update
