### ISSUE TITLE
Why not use millisecond?

### ISSUE THREAD

**Issue by catoldcui** [luanpotter/audioplayers#83]
This flutter project is awesome!

But I found the native code uses seconds as a unit, but I am not familiar with the native codes. Is that proper to use millisecond for audioplayers?

**Comment by erickzanardo** [comment]
Hello, glad that you enjoy the project.

This lib uses the [Duration](https://docs.flutter.io/flutter/dart-core/Duration-class.html) class, which let you use milliseconds, second and etc.

Did you encounter any problems using milliseconds?

**Comment by catoldcui** [comment]
Yeah, for flutter, that's feasible. For native codes, they receives seconds like [seek](https://github.com/luanpotter/audioplayers/blob/master/lib/audioplayers.dart#L158-L162), could change to milliseconds? I'd like to sync the lyric up with the music, the seconds would be a rough unit.

**Comment by erickzanardo** [comment]
I unserstood now, Will take a look when I have time :)

Em qui, 10 de jan de 2019 02:43, Catold <notifications@github.com> escreveu:

**Comment by catoldcui** [comment]
Hi there, I found this feature is lying on the [feature/seek-using-millis](https://github.com/luanpotter/audioplayers/tree/feature/seek-using-millis).

Could you share your concern for not merging it? Thanks 😁

**Comment by erickzanardo** [comment]
Hello @catoldcui , I have started implementing it on this branch, but  when testing, the seek was not working. I spent some time trying to figure it out,  but eventually ended up given up, and I still did not had time to get back to this feature :(

I may be get back to it eventually, but am right now quite overwhelmed, sorry for the long wait.

**Comment by catoldcui** [comment]
Thanks for taking on this task. I make it work in my forked repo following your commits. Maybe I could try to help implement it with a PR.

**Comment by erickzanardo** [comment]
That would be great, would be really helpful if you submit a PR :)

**Comment by erickzanardo** [comment]
Resolve and released on `0.10.1`
