### ISSUE TITLE
Web NotAllowedError: play()

### ISSUE THREAD

**Issue by tehsunnliu** [luanpotter/audioplayers#831]
After the page is loaded, when I try to play the sound for the first time, it doesn't play.

**Full Description**
In my case, the user scans the QR Code to log in. After logging in the webpage starts a WebSocket connect to listen to new orders. As soon as the first order is received, when I try to play the sound I get 
`Error: NotAllowedError: play() failed because the user didn't interact with the document first.`

**Code to Reproduce**
To make the code simple I've placed _audioPlayer.resume() inside the build function. In actual code resume() is called on a callback listener.
```
AudioPlayer _audioPlayer;

Future<void> playSound() async {
  await _audioPlayer.resume();
}

@override
void initState() {
  _audioPlayer = AudioPlayer();
  _audioPlayer.setUrl('/assets/sounds/newOrder.mp3').then((value) {
   _audioPlayer.setReleaseMode(ReleaseMode.STOP);
  });
}
@override
Widget build(BuildContext context) {
  playSound();
  ...
}
```

**Log Errors**
In browser console I get this error log
Error: NotAllowedError: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

**Platforms**
* OS: web; Google Chrome
* OS version: Version 89.0.4389.114 (Official Build) (64-bit)
* Device: Ubuntu 20.04
* flutter version: 
```
[✓] Flutter (Channel stable, 2.0.3, on Linux, locale en_GB.UTF-8)
    • Flutter version 2.0.3 at /home/alexliu/snap/flutter/common/flutter
    • Framework revision 4d7946a68d (2 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/alexliu/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /usr/local/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /usr/local/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

* audioplayers version: ^0.17.4.

**Comment by erickzanardo** [comment]
Unfortunately this is a limitation of the web platform, like the error message says, you can play sounds after the user had any interaction with the page. Like clicking on something for example.

**Comment by tehsunnliu** [comment]
Hi Erick, thank you for your response. 
I searched about the problem and found that in html, 
Setting `allow="autoplay"` in iframe tag fixes this problem

Is there anyway we can add this tag through the code?

**Comment by luanpotter** [comment]
flutter doesn't put your app in an iframe though (that I know of)

**Comment by erickzanardo** [comment]
No it doesn't @luanpotter 
@tehsunnliu I am not sure if that is possible, it may be by using some dart js code that adds, but making a page inside an iframe alter the html of its parent page is never easy.

Either way this isn't something that Audioplayers should do IMO

**Comment by tehsunnliu** [comment]
Okay. Guess I've to find some alternative solution. 
Thank you once again.

**Comment by joshykautz** [comment]
Any creative solutions from folks on this? I don't have these issues with browsers like Microsoft Edge, but definitely getting thrown for a loop in Google Chrome.

**Comment by IntegroInfotech** [comment]
> Okay. Guess I've to find some alternative solution.
> Thank you once again.

Will u share the solution which u received to fix this problem???

**Comment by tehsunnliu** [comment]
I'm sorry to say that since it's been a while I faced this problem, I don't exactly remember what alternative solution I used to solve the problem. Due to my tight schedule, I'm unable to review the code again. However, one solution that comes to my mind is finding a way to make users interact with the web page as soon as the page loads. Hope this helps.

**Comment by IntegroInfotech** [comment]
> I'm sorry to say that since it's been a while I faced this problem, I don't exactly remember what alternative solution I used to solve the problem. Due to my tight schedule, I'm unable to review the code again. However, one solution that comes to my mind is finding a way to make users interact with the web page as soon as the page loads. Hope this helps.

Thank u for your reply. It was very useful to find the solution thank u....
