### ISSUE TITLE
issues with google_mobile_ads

### ISSUE THREAD

**Issue by ideasappcolombia** [luanpotter/audioplayers#832]
Hello. We use this excellent plugin for some of our apps, but in the last version (^0.18.3):
- the app crashes in both OS (Android and iOS) because the RAM of the device explote. 
- the banners and the rewarded videos doesn't load when we implement this code:

player.onAudioPositionChanged.listen((Duration  p) => {
    print('Current position: $p');
    setState(() => position = p);
  });

**Comment by erickzanardo** [comment]
Not sure if we can help with that other package as we don't maintain it.

But if you could isolate this RAM issue on a minimal reproducible code, using only audioplayers we could try to look into it. Also, please follow the issue template so we can have all the info to eventually act on the problem.

**Comment by erickzanardo** [comment]
Closing due inactivity, if there is more info that you can add to the issue, comment here and we can re open the issue.
