### ISSUE TITLE
Best practices for real-time processing of audio using audioplayers

### ISSUE THREAD

**Issue by arielelkin** [luanpotter/audioplayers#839]
(Asking here as the [corresponding discussion](https://github.com/luanpotter/audioplayers/discussions/786) didn't get far)

What would be the best way of applying real-time audio effects to audio played by the audioplayers package? A basic use case would be playing back an audio file and applying a reverb effect to it. This would be useful for gaming apps (e.g. spatialisation effects), podcast-playing apps (e.g. time-stretching effects), audio editing apps, etc.

On iOS and macOS, this could be achieved by adding an AVAudioMix instance to the AVPlayer instance managed by WrappedMediaPlayer. This wouldn't necessarily be a breaking change.

Is this doable and worthwhile?

**Comment by erickzanardo** [comment]
Hey @arielelkin I wonder if this is something on the scope of this package. This feel more like a feature for a audio processing than for an audio playing package.

@luanpotter what do you think?

**Comment by luanpotter** [comment]
Yeah I don't think this is in scope, as mentioned [here](https://github.com/luanpotter/audioplayers/blob/master/feature_parity_table.md#other-features) the goal is to play audios, not manipulate. could be a separated package though. we could also update that list to explicitly include this, and if you want to start a new package @arielelkin I can add it as a recommendation on the list
