### ISSUE TITLE
Flutter web in this package will not work on iOS

### ISSUE THREAD

**Issue by sinano1107** [luanpotter/audioplayers#847]
Thanks for the great package.
This package and the code below work fine in chrome on mac.
However, when I run the web application on IOS, the code below does not work
It doesn't work in safari or chrome.
version: 0.18.3

Do you have any suggestions on how to fix this problem?
Thank you very much.

```
AudioPlayer().play(uri);
```

**Comment by erickzanardo** [comment]
Duplicated #813

This is a know issue for some reason our implementation don't work on mobile safari, check the linked issue for updates on this.
