### ISSUE TITLE
The current Gradle version 4.10.2 is not compatible with the Kotlin Gradle plugin. Please use Gradle 5.3 or newer, or the previous version of the Kotlin plugin

### ISSUE THREAD

**Issue by hamberluo** [luanpotter/audioplayers#849]

**Comment by erickzanardo** [comment]
There isn't enough information on this issue for us to act on. Please edit this, or open a new one and please follow the issue template.

Feel free to comment here and we can re open this eventually.

**Comment by hamberluo** [comment]
@erickzanardo you can just edit gradle-wrapper.properties to change gradle version to 5.6.4

**Comment by GuilhermeVendramini** [comment]
Same problem here.

**Comment by illukinati** [comment]
@hamberluo thanks, finally someone nailed it!

**Comment by EireHauler** [comment]
The current Gradle version 4.10.2 is not compatible with the Kotlin Gradle plugin. Please use Gradle 5.3 or newer, or the previous version of the Kotlin plugin.

I have this error.
Please help me.
Thank you.

**Comment by PaoloGi** [comment]
> The current Gradle version 4.10.2 is not compatible with the Kotlin Gradle plugin. Please use Gradle 5.3 or newer, or the previous version of the Kotlin plugin.
> 
> I have this error. Please help me. Thank you.

Updating to the ^0.20.1 version on pubspec.yaml and changing the gradle-wrapper.properties to 5.6.4 solved the issue for me
