### ISSUE TITLE
App Crashes on Android 4.4.4

### ISSUE THREAD

**Issue by baraaaljabban** [luanpotter/audioplayers#850]
[App Crashes on Android 4.4.4 release mode whenever I try to play sound from the app assets using audioCache method ]

**Full Description**
it's working on all other devices very well except  the one that is using Android 4.4.4 
version of the library is audioplayers 0.18.3

**Code to Reproduce**
here is the code that I'm using 
```
 audioCache.play(
                  state.track,
                  mode: PlayerMode.LOW_LATENCY,
                );
```
it's crashing in both PlayerMode the normal one and LOW_LATENCY

**Log Errors**
here is the Log that I got from Firebase in the [Link](https://docs.google.com/document/d/1BkFpym9TigJa17vutuz_qvUByqa3mpNx9jCu656noEc/edit?usp=sharing) .

**Platforms**
[OS] Android 4.4.4 "Samsung Device : core prime"

**Comment by sgg-labs** [comment]
You could try this #854, if you have a device to test it.

**Comment by baraaaljabban** [comment]
Unfortunately  it didn't work for me!

**Comment by zatovagul** [comment]
t works when I use audioplayers 0.18.3 version. But doesn't work with 0.19.0

**Comment by zatovagul** [comment]
> [App Crashes on Android 4.4.4 release mode whenever I try to play sound from the app assets using audioCache method ]
> 
> **Full Description**
> it's working on all other devices very well except the one that is using Android 4.4.4
> version of the library is audioplayers 0.18.3
> 
> **Code to Reproduce**
> here is the code that I'm using
> 
> ```
>  audioCache.play(
>                   state.track,
>                   mode: PlayerMode.LOW_LATENCY,
>                 );
> ```
> 
> it's crashing in both PlayerMode the normal one and LOW_LATENCY
> 
> **Log Errors**
> here is the Log that I got from Firebase in the [Link](https://docs.google.com/document/d/1BkFpym9TigJa17vutuz_qvUByqa3mpNx9jCu656noEc/edit?usp=sharing) .
> 
> **Platforms**
> [OS] Android 4.4.4 "Samsung Device : core prime"

It works when I use audioplayers 0.18.3 version. But doesn't work with 0.19.0

**Comment by erickzanardo** [comment]
This should have been fixed by https://github.com/luanpotter/audioplayers/pull/841 on `0.19.0`.
