### ISSUE TITLE
AudioCache wrong link

### ISSUE THREAD

**Issue by hansiruting** [luanpotter/audioplayers#851]
In the README.md, in the section of AudioCache (https://github.com/luanpotter/audioplayers#audiocache) the link "here" at the end is wrong. It redirect to https://github.com/luanpotter/audioplayers/blob/master/doc/audio_cache.md insted of https://github.com/luanpotter/audioplayers/blob/master/packages/audioplayers/doc/audio_cache.md

**Comment by erickzanardo** [comment]
nice catch, would you be willing to send us a PR?

**Comment by Cyberavater** [comment]
Can you fix the link here as well?
https://pub.dev/packages/audioplayers

**Comment by luanpotter** [comment]
I fixed this already, pub will be updated upon next release.
