### ISSUE TITLE
The getter 'onPlayerStateChanged' isn't defined for the type 'AudioPlayer'.

### ISSUE THREAD

**Issue by MohamedGhoneim** [luanpotter/audioplayers#855]
The getter 'onPlayerStateChanged' isn't defined for the type 'AudioPlayer'.

**Comment by erickzanardo** [comment]
Please follow the issue template. There isn't enough info on this issue. We need reproducible code, audioplayers version, etc.

**Comment by erickzanardo** [comment]
Closing due inactivity, if there is more info that you can add to the issue, comment here and we can re open the issue.
