### ISSUE TITLE
About the audio player not responding after a certain touches while using audio cache

### ISSUE THREAD

**Issue by Havockeyan** [luanpotter/audioplayers#856]
Audio player not responding after some clicks

**Full Description**
 I have created a zylophone app which has to play audio based on click of colour.It does not have any errors and compiles but after clicking certain times that is not responding for the clicks.

**Comment by erickzanardo** [comment]
It seems that for what you are implementing you will probably need an audio pool, we support another package called flame_audio that is a wrapper of audioplayers focused on games, which has an audio pool implementation, I suggest you take a look on it.

Besides that, without any error and a minimal reproducible code there isn't enough information on this issue for us to act on anything.

Please edit this issue and add more information about the problem. 

Try to follow the issue template as it is very complete about the info we would need to investigate a possible bug.

**Comment by ErinKConnor** [comment]
I've had the same issue. With the current version (0.18.3) the app works fine at first but stops working after 10 or so sounds have been played. If I change the version to 0.12.0 the app works just fine. Not sure what's happening.

**Comment by erickzanardo** [comment]
Without any error and a minimal reproducible code there isn't enough information on this issue for us to act on anything.

Closing due inactivity, but feel free to edit this issue, adding the missing information and I can re open.

**Comment by rickgbw** [comment]
Same problem here... after some reproductions on AudioCache, it stops suddenly.

**Comment by Ahmed2120** [comment]
same issue , any one find solution?
