### ISSUE TITLE
Synchronizing multiple players

### ISSUE THREAD

**Issue by SimonEggert** [luanpotter/audioplayers#857]
I am trying to play 5-10 audio files simultaneously and in sync for a simple music mixing app, but cannot seem to get it working consistently. Is there a way to ensure that all players start at the same time?

My approach is to loop over a List of audio files and play them back from local assets using `AudioCache`s. Issue (https://github.com/luanpotter/audioplayers/issues/137) reports a similar problem on Android, but for me iOS seems to be worse. Android has a noticeable delay from time to time too, though. 

The delay and order is slightly different every time I stop and restart the players. Would it help to pause the players immediately after the `AudioCache` played it, then reset all of them to the start with the `seek`-method and after that resume them?

```dart
List<String> instrumentTracks = [
  'instrument1.mp3',
  'instrument2.mp3',
  'instrument3.mp3',
  'instrument4.mp3',
  'instrument5.mp3',
];

List<AudioPlayer> audioPlayers = [];

void playAll() async {
  AudioCache audioCache = AudioCache();

  for (String fileName in instrumentTracks) {
    audioPlayers.add(await audioCache.play(fileName));
  }
}
```

**Platforms**
* OS: android, ios
* OS version: Android 11, iOS 14.4
* Device: both physical and emulators
* flutter version: 2.0.5-stable
* audioplayers version: 0.18.3
* release or not release: release, debug

**Comment by erickzanardo** [comment]
Unfortunately I don't think this is possible with Audioplayers, this requires a level of perfomance that is not the focus of this package (we focus on having a big feature set).

I suggest you trying our sister package ocarina which instead has less features but is focused on perfomance. I am not sure if even ocarina will provide the level of perfomance you will need for a mixing app, but the chances are higher and worth a shot.

Hope this was helpful

**Comment by fdietze** [comment]
I have it working on Android. I'm initializing a list of audioplayers first. Once all of them are initialized, after a quick warmup phase, I call `resume()` in a loop:

(There are some libraries involved here, but you'll get the idea)

```
@freezed
class SyncedAudioPlayer with _$SyncedAudioPlayer {
  const SyncedAudioPlayer._();
  const factory SyncedAudioPlayer({required List<AudioPlayer> players}) =
      _SyncedAudioPlayer;

  AudioPlayerState get state =>
      players.firstOrNull?.state ?? AudioPlayerState.STOPPED;

  Stream<AudioPlayerState> get onPlayerStateChanged =>
      players.firstOrNull?.onPlayerStateChanged ?? Stream.empty();

  Stream<Duration> get onAudioPositionChanged =>
      players.firstOrNull?.onAudioPositionChanged ?? Stream.empty();

  Stream<Duration> get onDurationChanged =>
      players.firstOrNull?.onDurationChanged ?? Stream.empty();

  //TODO: getCurrentPosition should return Duration
  Future<Duration> getCurrentPosition() async => Duration(
      milliseconds: await players.firstOrNull?.getCurrentPosition() ?? 0);

  Future<void> seek(Duration position) =>
      players.mapAsync((p) => p.seek(position));

  Future<void> setVolume(double volume) =>
      players.mapAsync((p) => p.setVolume(volume));

  Future<void> synchronizePositions() async =>
      await seek(await getCurrentPosition());

  Future<void> mute() => setVolume(0);
  Future<void> fullVolume() => setVolume(1);
  Future<void> resume() => players.mapAsync((p) => p.resume());

  Future<void> pause() async {
    await players.mapAsync((p) => p.pause());
    await synchronizePositions();
  }

  Future<void> release() => players.mapAsync((p) => p.release());

  Future<void> warmup() async {
    await mute();
    await resume();
    await pause();
    await fullVolume();
  }
}
```

**Comment by erickzanardo** [comment]
Closing due inactivity, but feel free to comment here and we can re open the issue.

**Comment by svillacreses** [comment]
Any approach or solution to achive this?
