### ISSUE TITLE
multiple subscribers to position updates

### ISSUE THREAD

**Issue by javorosas** [luanpotter/audioplayers#86]
Hi. Fist off, thanks for the great work at forking @rxlabz project and making such great improvements.

I'm building a simple music making app (my first flutter project btw) and after switching from `audioplayer` to `audioplayers` I noticed that `Stream<Duration> onAudioPositionChanged` was changed to a single callback function. I understand this is simpler, but... is it really better?

Passing the stream to multiple stateful widgets would allow them to only rebuild their state when the position changes, and not rebuild the whole widget. I can imagine this being useful especially in games.

Finally I just want to point out once again that I'm a complete n00b in Dart and Flutter, so there might easily be something I'm overlooking . If that's the case, please let me know, otherwise I propose reverting to using streams.

**Comment by erickzanardo** [comment]
@luanpotter can you help us here?

**Comment by luanpotter** [comment]
Hi, @javorosas , thanks for your feedback! I'm glad you are liking audioplayers!

Regarding having multiple subscribers, this feature was not removed at all, instead, it was added to audiplayer after the fork, and therefore we don't have it. It would be awesome to have the ability to support multiple callbacks for every hook we have so far.

It's a simple change that could be done only on the dart side, so, if you are interested, you can contribute with a PR :)

**Comment by luanpotter** [comment]
This was implemented by @LucasCLuk ! :)
