### ISSUE TITLE
Audio Cache Not working in android

### ISSUE THREAD

**Issue by beast98** [luanpotter/audioplayers#862]
For first few clicks on instance of audio cache it plays sound, but later on it starts to throw error

**Comment by beast98** [comment]
![Screen Shot 2021-05-01 at 12 09 47 PM](https://user-images.githubusercontent.com/31199921/116773943-9950bc00-aa76-11eb-8a57-118e13ca8e0f.png)

**Comment by erickzanardo** [comment]
There isn't enough information on this issue for us to act on. Please edit this following the issue template.

**Comment by wenxiangjiang** [comment]
Is it the same as #843 ?

**Comment by beast98** [comment]
Yes

**Comment by luanpotter** [comment]
Closing in lieu of https://github.com/luanpotter/audioplayers/issues/843
