### ISSUE TITLE
player doenst seems to work on android phones or emulator

### ISSUE THREAD

**Issue by barakanjojoz** [luanpotter/audioplayers#863]
[one liner - audioplayers play audio stream on web emulator and ios, but dont play on android ]

**Full Description**
Its a radio app that should play the audio stream onpress, and it works on ios and web emulator, but dont work on android phones or emulator.

**Code to Reproduce**

-- main.dart-- 

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/material.dart';

const url = 'https://paineldj.com.br:20079/stream';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MusicApp(),
    );
  }
}

class MusicApp extends StatefulWidget {
  @override
  _MusicAppState createState() => _MusicAppState();
}

class _MusicAppState extends State<MusicApp> {
  bool playing = false;
  IconData playBtn = Icons.play_arrow;

  AudioPlayer _player;

  @override
  void initState() {
    super.initState();
    _player = AudioPlayer(mode: PlayerMode.LOW_LATENCY);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: double.infinity,
        decoration: BoxDecoration(
          image: DecorationImage(
            image: AssetImage("assets/bg.jpg"),
            fit: BoxFit.cover,
          ),
        ),
        child: Padding(
          padding: EdgeInsets.only(
            top: 48.0,
          ),
          child: Container(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.start,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                Padding(
                  padding: const EdgeInsets.only(left: 12.0),
                  child: Text(
                    "#",
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 38.0,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.only(left: 12.0),
                  child: Text(
                    "#",
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 24.0,
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
                SizedBox(
                  height: 24.0,
                ),
                Center(
                  child: Container(
                    width: double.infinity,
                    height: 150.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(30.0),
                      image: DecorationImage(
                          image: AssetImage("assets/logo.jpg"),
                          fit: BoxFit.fitHeight),
                    ),
                  ),
                ),
                SizedBox(
                  height: 18.0,
                ),
                /* Center(
                  child: Text(
                    "#",
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 32.0,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
                SizedBox(
                  height: 30.0,
                ), */
                Expanded(
                  child: Container(
                    decoration: BoxDecoration(
                      color: Colors.black.withOpacity(0.5),
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(30.0),
                        topRight: Radius.circular(30.0),
                      ),
                    ),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            IconButton(
                              iconSize: 60.0,
                              color: Colors.deepPurple.shade300,
                              onPressed: () {
                                if (!playing) {
                                  _player.play(url);
                                  setState(() {
                                    playBtn = Icons.pause;
                                    playing = true;
                                  });
                                } else {
                                  _player.pause();
                                  setState(() {
                                    playBtn = Icons.play_arrow;
                                    playing = false;
                                  });
                                }
                              },
                              icon: Icon(playBtn),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

**Log Errors**

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
E/AudioAttributes( 4030): Invalid stream type -2147483648 for AudioAttributes
W/SoundPool( 4030): App requested 100 channels
E/AudioplayersPlugin( 4030): Unexpected error!
E/AudioplayersPlugin( 4030): android.os.NetworkOnMainThreadException
E/AudioplayersPlugin( 4030):    at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
E/AudioplayersPlugin( 4030):    at java.net.InetAddress.lookupHostByName(InetAddress.java:431)
E/AudioplayersPlugin( 4030):    at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
E/AudioplayersPlugin( 4030):    at java.net.InetAddress.getAllByName(InetAddress.java:215)
E/AudioplayersPlugin( 4030):    at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
E/AudioplayersPlugin( 4030):    at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:188)
E/AudioplayersPlugin( 4030):    at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:157)
E/AudioplayersPlugin( 4030):    at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:100)
E/AudioplayersPlugin( 4030):    at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:357)
E/AudioplayersPlugin( 4030):    at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:340)
E/AudioplayersPlugin( 4030):    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
E/AudioplayersPlugin( 4030):    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
E/AudioplayersPlugin( 4030):    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:433)
E/AudioplayersPlugin( 4030):    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
E/AudioplayersPlugin( 4030):    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
E/AudioplayersPlugin( 4030):    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
E/AudioplayersPlugin( 4030):    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
E/AudioplayersPlugin( 4030):    at java.net.URL.openStream(URL.java:470)
E/AudioplayersPlugin( 4030):    at xyz.luan.audioplayers.WrappedSoundPool.downloadUrl(WrappedSoundPool.kt:231)
E/AudioplayersPlugin( 4030):    at xyz.luan.audioplayers.WrappedSoundPool.loadTempFileFromNetwork(WrappedSoundPool.kt:220)
E/AudioplayersPlugin( 4030):    at xyz.luan.audioplayers.WrappedSoundPool.getAudioPath(WrappedSoundPool.kt:216)
E/AudioplayersPlugin( 4030):    at xyz.luan.audioplayers.WrappedSoundPool.setUrl(WrappedSoundPool.kt:144)
E/AudioplayersPlugin( 4030):    at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:59)
E/AudioplayersPlugin( 4030):    at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:34)
E/AudioplayersPlugin( 4030):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AudioplayersPlugin( 4030):    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AudioplayersPlugin( 4030):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AudioplayersPlugin( 4030):    at android.os.MessageQueue.nativePollOnce(Native Method)
E/AudioplayersPlugin( 4030):    at android.os.MessageQueue.next(MessageQueue.java:323)
E/AudioplayersPlugin( 4030):    at android.os.Looper.loop(Looper.java:135)
E/AudioplayersPlugin( 4030):    at android.app.ActivityThread.main(ActivityThread.java:5417)
E/AudioplayersPlugin( 4030):    at java.lang.reflect.Method.invoke(Native Method)
E/AudioplayersPlugin( 4030):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AudioplayersPlugin( 4030):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/flutter ( 4030): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(Unexpected error!, null, android.os.NetworkOnMainThreadException
E/flutter ( 4030):      at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
E/flutter ( 4030):      at java.net.InetAddress.lookupHostByName(InetAddress.java:431)
E/flutter ( 4030):      at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
E/flutter ( 4030):      at java.net.InetAddress.getAllByName(InetAddress.java:215)
E/flutter ( 4030):      at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
E/flutter ( 4030):      at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:188)
E/flutter ( 4030):      at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:157)
E/flutter ( 4030):      at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:100)
E/flutter ( 4030):      at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:357)
E/flutter ( 4030):      at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:340)
E/flutter ( 4030):      at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
E/flutter ( 4030):      at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
E/flutter ( 4030):      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:433)
E/flutter ( 4030):      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
E/flutter ( 4030):      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
E/flutter ( 4030):      at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
E/flutter ( 4030):      at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
E/flutter ( 4030):      at java.net.URL.openStream(URL.java:470)
E/flutter ( 4030):      at xyz.luan.audioplayers.WrappedSoundPool.downloadUrl(WrappedSoundPool.kt:231)
E/flutter ( 4030):      at xyz.luan.audioplayers.WrappedSoundPool.loadTempFileFromNetwork(WrappedSoundPool.kt:220)
E/flutter ( 4030):      at xyz.luan.audioplayers.WrappedSoundPool.getAudioPath(WrappedSoundPool.kt:216)
E/flutter ( 4030):      at xyz.luan.audioplayers.WrappedSoundPool.setUrl(WrappedSoundPool.kt:144)
E/flutter ( 4030):      at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:59)
E/flutter ( 4030):      at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:34)
E/flutter ( 4030):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 4030):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 4030):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter ( 4030):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 4030):      at android.os.MessageQueue.next(MessageQueue.java:323)
E/flutter ( 4030):      at android.os.Looper.loop(Looper.java:135)
E/flutter ( 4030):      at android.app.ActivityThread.main(ActivityThread.java:5417)
E/flutter ( 4030):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 4030):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/flutter ( 4030):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/flutter ( 4030): , null)
E/flutter ( 4030): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
E/flutter ( 4030): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter ( 4030): <asynchronous suspension>
E/flutter ( 4030): #2      AudioPlayer._invokeMethod.<anonymous closure> (package:audioplayers/audioplayers.dart)
E/flutter ( 4030): <asynchronous suspension>
E/flutter ( 4030):
E/eglCodecCommon( 4030): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 4030): glUtilsParamSize: unknow param 0x00008741

**Comment by erickzanardo** [comment]
You can't use the LOW_LATENCY mode on streams, removing that mode and using the normal one will probably fix

**Comment by barakanjojoz** [comment]
it doesnt work, i've tried to use low_latency to see if it would solve my problem but no

**Comment by erickzanardo** [comment]
Then please edit the issue to have the code and the log without the low latency mode.

Also please use code blocks to share code and logs, because otherwise is impossible to read the code and the logs will link this issue to other issues because of the `#`

**Comment by barakanjojoz** [comment]
main
```
import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MusicApp(),
    );
  }
}

class MusicApp extends StatefulWidget {
  @override
  _MusicAppState createState() => _MusicAppState();
}

class _MusicAppState extends State<MusicApp> {
  bool playing = false;
  IconData playBtn = Icons.play_arrow;
  final url = 'https://paineldj.com.br:20079/stream';
  AudioPlayer _player;

  @override
  void initState() {
    super.initState();
    _player = AudioPlayer();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: double.infinity,
        decoration: BoxDecoration(
          image: DecorationImage(
            image: AssetImage("assets/bg.jpg"),
            fit: BoxFit.cover,
          ),
        ),
        child: Padding(
          padding: EdgeInsets.only(
            top: 48.0,
          ),
          child: Container(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.start,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                Padding(
                  padding: const EdgeInsets.only(left: 12.0),
                  child: Text(
                    "Radio Santo Ângelo + JM",
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 38.0,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.only(left: 12.0),
                  child: Text(
                    "#",
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 24.0,
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
                SizedBox(
                  height: 24.0,
                ),
                Center(
                  child: Container(
                    width: double.infinity,
                    height: 150.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(30.0),
                      image: DecorationImage(
                          image: AssetImage("assets/logo.jpg"),
                          fit: BoxFit.fitHeight),
                    ),
                  ),
                ),
                SizedBox(
                  height: 18.0,
                ),
                /* Center(
                  child: Text(
                    "Ao vivo",
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 32.0,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
                SizedBox(
                  height: 30.0,
                ), */
                Expanded(
                  child: Container(
                    decoration: BoxDecoration(
                      color: Colors.black.withOpacity(0.5),
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(30.0),
                        topRight: Radius.circular(30.0),
                      ),
                    ),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            IconButton(
                              iconSize: 60.0,
                              color: Colors.deepPurple.shade300,
                              onPressed: () {
                                if (!playing) {
                                  _player.play(url);
                                  setState(() {
                                    playBtn = Icons.pause;
                                    playing = true;
                                  });
                                } else {
                                  _player.pause();
                                  setState(() {
                                    playBtn = Icons.play_arrow;
                                    playing = false;
                                  });
                                }
                              },
                              icon: Icon(playBtn),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

and log

```
PS C:\projeto\radiosantoangelojm\aplicativo> flutter run
Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        87,8s
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                27,1s
E/eglCodecCommon( 4670): glUtilsParamSize: unknow param 0x00008741      
E/eglCodecCommon( 4670): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 4670): glUtilsParamSize: unknow param 0x00008741      
E/eglCodecCommon( 4670): glUtilsParamSize: unknow param 0x00008741      
Syncing files to device Android SDK built for x86...             2.430ms

Flutter run key commands.
r Hot reload. 
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:61214/oSqIXGrWRUo=/

Flutter DevTools, a Flutter debugger and profiler, on Android SDK built for x86 is available at: http://127.0.0.1:9104?uri=http%3A%2F%2F127.0.0.1%3A61214%2FoSqIXGrWRUo%3D%2F

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
E/eglCodecCommon( 4670): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 4670): glUtilsParamSize: unknow param 0x00008741
I/art     ( 4670): Background sticky concurrent mark sweep GC freed 13169(1014KB) AllocSpace objects, 3(60KB) LOS objects, 65% free, 1276KB/3MB, paused 1.983ms total 106.254ms
E/MediaPlayer( 4670): error (1, -2147483648)
E/MediaPlayer( 4670): Error (1,-2147483648)
E/MediaPlayer( 4670): stop called in state 0
E/MediaPlayer( 4670): error (-38, 0)
```

**Comment by barakanjojoz** [comment]
Se vale de alguma coisa, no main > androidmanifest.xml eu ja inseri <uses-permission android:name="android.permission.INTERNET"/> e android:usesCleartextTraffic="true"

**Comment by barakanjojoz** [comment]
se vale de alguma coisa, no main > androidmanifest.xml eu já inseri a permissão de internet e cleartexttraffic, e continua não funcionando

**Comment by erickzanardo** [comment]
This error number is a low-level system error MEDIA_ERROR_SYSTEM (-2147483648) (https://developer.android.com/reference/android/media/MediaPlayer.OnErrorListener.html)

This type of error usually happens on players when for example the device don't have the necessary codecs to read the sound. And since this is working on iOS and other platforms, this helps to support that possibility that your android device don't have the necessary codecs to read this url.

Have you tested on a different android device? Different devices have different codecs so this may be working ok on other devices.

**Comment by barakanjojoz** [comment]
I've tested on emulator and 2 phones by now, and it doesnt play.
What can i do about that codec problem? do you see any possible solution?
I ask that because this app should be a radio player and should be acessible to all.
Anyway, thanks for clarifying my suspicion.

**Comment by erickzanardo** [comment]
Emulators have even worse codec support.

This codec thing is very confusing to us too to be honest. The only solution that we have found when this happens is to change the url to use a format that is more common accepted. Do you have domain of that server, could you verify in which format the sound if being transmitted? If get the format, we could verify if that is supported by Android.

Either, that error code could be caused by other reasons, the codec thing is just the most common so it is worth investigating still.

**Comment by luanpotter** [comment]
Please check [here](https://github.com/luanpotter/audioplayers#supported-formats) for supported formats.

**Comment by zatovagul** [comment]
It works when I use audioplayers 0.18.3 version. But doesn't work with 0.19.0

**Comment by adrianvintu** [comment]
@zatovagul same here, it used to work on an older version, then on 19 the log showed:

```
E/AudioAttributes(16757): Invalid stream type -2147483648 for AudioAttributes
W/SoundPool::StreamManager(16757): StreamMap: requested 100 streams, clamping to 32
E/SoundPool(16757): error loading file:///data/user/0/project/title.mp3
```
I changed
```await AudioUtils.instance.play(widget.pathToSoundFile, mode: PlayerMode.LOW_LATENCY, volume: 5.0);```
to
```await AudioUtils.instance.play(widget.pathToSoundFile, mode: PlayerMode.MEDIA_PLAYER, volume: 5.0);```
and it works!

Devices tested:
Samsung Galaxy S10
Emulator

I got the solution from here: https://github.com/luanpotter/audioplayers/issues/734#issuecomment-768900521

**Comment by drobyshys** [comment]
why it is closed?

**Comment by barakanjojoz** [comment]
hey all, sorry i didnt updated before
as @erickzanardo pointed, the problem in this case was the audio codec of the transmission i was trying to play
unsuported codec equals no sound, so i fixed it contacting my transmission supplier and he managed to fix it.

**Comment by fluttertests** [comment]
> You can't use the LOW_LATENCY mode on streams, removing that mode and using the normal one will probably fix

This one worked for me. Thanks.
