### ISSUE TITLE
Can I use assets with Flutter Web?

### ISSUE THREAD

**Issue by tbarbette** [luanpotter/audioplayers#868]
The feature table says yes at `https://github.com/luanpotter/audioplayers/blob/master/feature_parity_table.md`

But then the main page says to use assets, you must use AudioCache. And then it says:

"In order to play Local Assets, you must use the AudioCache class. AudioCache is not available for Flutter Web."

So, which one is it? :)

**Comment by erickzanardo** [comment]
For web you can just use the AudioPlayer class, and set the url to your local asset

**Comment by tbarbette** [comment]
Thanks! So the sentence "For Local Assets, you have to use the AudioCache class (see below)." and the first one cited above should be removed from the readme, as AudioCache is not needed?

**Comment by erickzanardo** [comment]
Yeah, I think this sentence is miss leading. It is correct that for playing local assets on mobile (and I would be desktop as well) you need to use AudioCache, but for web we can just use AudioPlayers. That parte of the readme can sure be improved.

**Comment by tbarbette** [comment]
What do you call mobile here? Android?
I ended up using the URL on web, and locally loading a byte buffer on Android. But a unified way without manual if cases would be best.

**Comment by erickzanardo** [comment]
Android, iOS. It would indeed, but unfortunately our web support isn't as complete as is for other platforms due to some difficulties that we faced along the way.

**Comment by tbarbette** [comment]
Thanks, I'll close this and maybe update the README along the road? I got a way so it's fine by me :)
