### ISSUE TITLE
Unable to build apk after updating to version 0.18.3

### ISSUE THREAD

**Issue by AminMemariani** [luanpotter/audioplayers#875]
Here is the error log when I hit `flutter build apk`

> Building without sound null safety
> For more information see https://dart.dev/null-safety/unsound-null-safety
> 
>                                                                         
> FAILURE: Build failed with an exception.                                
>                                                                         
> * What went wrong:                                                      
> Could not determine the dependencies of task ':audioplayers:compileReleaseAidl'.
> > Could not resolve all task dependencies for configuration ':audioplayers:releaseCompileClasspath'.
>    > Could not resolve androidx.core:core-ktx:+.                        
>      Required by:                                                       
>          project :audioplayers                                          
>       > Failed to list versions for androidx.core:core-ktx.             
>          > Could not list versions using M2 pattern 'https://storage.googleapis.com/download.flutter.io/[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier])(.[ext])'.
>             > Could not get resource 'https://storage.googleapis.com/download.flutter.io/androidx/core/core-ktx/'.
>                > Could not GET 'https://storage.googleapis.com/download.flutter.io/androidx/core/core-ktx/'. Received status code 403 from server: Forbidden
>                                                                         
> * Try:                                                                  
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>                                                                         
> * Get more help at https://help.gradle.org                              
>                                                                         
> BUILD FAILED in 1m 4s                                                   
> Running Gradle task 'assembleRelease'...                                
> Running Gradle task 'assembleRelease'... Done                      66.3s
> The build failed likely due to AndroidX incompatibilities in a plugin. The tool
> is about to try using Jetifier to solve the incompatibility.
> Building plugin audioplayers...
> Running Gradle task 'assembleAarRelease'...                             
> Running Gradle task 'assembleAarRelease'... Done                  720.2s
> 
> Exception in thread "main" java.util.zip.ZipException: error in opening zip file
> 	at java.util.zip.ZipFile.open(Native Method)
> 	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
> 	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
> 	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
> 	at org.gradle.wrapper.Install.unzip(Install.java:214)
> 	at org.gradle.wrapper.Install.access$600(Install.java:27)
> 	at org.gradle.wrapper.Install$1.call(Install.java:74)
> 	at org.gradle.wrapper.Install$1.call(Install.java:48)
> 	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
> 	at org.gradle.wrapper.Install.createDist(Install.java:48)
> 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
> 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> 
> 
> The plugin audioplayers could not be built due to the issue above.

**Comment by adrianvintu** [comment]
Same for me, ever since I updated to latest gradle

`classpath 'com.android.tools.build:gradle:4.2.0'`

`distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip`

**Comment by AminMemariani** [comment]
This bug fix after updating to the '0.19.0' version and running `flutter upgrade`
