### ISSUE TITLE
Use Audio player in Background

### ISSUE THREAD

**Issue by shubham-cueclad** [luanpotter/audioplayers#88]

**Comment by erickzanardo** [comment]
It is possible to use the audioplayers in the background, if you had problems please provide a description of it.

**Comment by shubham-cueclad** [comment]
Can you give me a short example if possible?

**Comment by erickzanardo** [comment]
You don't need to do anything on the media player for it to work in the background, on Android for example, if you start playing something and hit the home button, the music/audio will continue to play, even with the app on the background.

To controle media player instance, play, resume, stop and etc you check our README, there are examples there.

**Comment by shubham-cueclad** [comment]
Thanks Buddy it worked for me Love you
