### ISSUE TITLE
BUILD FAILED for XCode 12.5

### ISSUE THREAD

**Issue by zilaiyedaren** [luanpotter/audioplayers#880]
pubspec.yaml:
audioplayers: 0.18.2

**Comment by zilaiyedaren** [comment]
Undefined symbols for architecture x86_64:
  "nominal type descriptor for Swift.Int32", referenced from:
      _symbolic _____ s5Int32V in libaudioplayers.a(WrappedMediaPlayer.o)
  "nominal type descriptor for Foundation.NSKeyValueObservation", referenced from:
      _symbolic _____Sg 10Foundation21NSKeyValueObservationC in libaudioplayers.a(WrappedMediaPlayer.o)
  "Foundation.URL._bridgeToObjectiveC() -> __C.NSURL", referenced from:
      @nonobjc __C.AVPlayerItem.init(url: Foundation.URL) -> __C.AVPlayerItem in libaudioplayers.a(WrappedMediaPlayer.o)
  "protocol witness table for Swift.Int : Swift.Equatable in Swift", referenced from:
      closure #3 (__C.AVPlayerItem, Foundation.NSKeyValueObservedChange<__C.AVPlayerItemStatus>) -> () in audioplayers.WrappedMediaPlayer.setUrl(url: Swift.String, isLocal: Swift.Bool, isNotification: Swift.Bool, recordingActive: Swift.Bool, duckAudio: Swift.Bool, onReady: (__C.AVPlayer) -> ()) -> () in libaudioplayers.a(WrappedMediaPlayer.o)
      protocol witness for static Swift.Equatable.== infix(A, A) -> Swift.Bool in conformance __C.AVPlayerItemStatus : Swift.Equatable in __C_Synthesized in libaudioplayers.a(WrappedMediaPlayer.o)
  "type metadata accessor for Foundation.Notification", referenced from:
      reabstraction thunk helper from @escaping @callee_guaranteed (@in_guaranteed Foundation.Notification) -> () to @escaping @callee_unowned @convention(block) (@unowned __C.NSNotification) -> () in libaudioplayers.a(WrappedMediaPlayer.o)

**Comment by erickzanardo** [comment]
Are you using a Mac M1?

**Comment by erickzanardo** [comment]
Closing due inactivity, if there is more info that you can add to the issue, comment here and we can re open the issue.

**Comment by Herryjoeson** [comment]
I encountered this problem, but my computer CPU is not M1 @erickzanardo

**Comment by Herryjoeson** [comment]
pubspec.yaml:
audioplayers: ^0.19.1

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/gaolei/Documents/FlutterSDK_2.2/flutter
    • Framework revision f4abaa0735 (2 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
