### ISSUE TITLE
AudioplayerPlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by salunkeakash** [luanpotter/audioplayers#883]
getting this error while building apk file
 C:\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayer-0.8.1\android\src\main\java\bz\rxla\audioplayer\AudioplayerPlugin.java uses or overrides a deprecated API.

**Comment by erickzanardo** [comment]
It seems that you are using `audioplayer` instead of `audioplayers`. `audioplayer` is a different package from this one.
