### ISSUE TITLE
onPlayerCompletion for AudioCache

### ISSUE THREAD

**Issue by kaanguru** [luanpotter/audioplayers#886]
Status of the player is needed for audio cache

**Full Description**

It's important to **disable the play button** while it's already playing.

Currently, just  `AudioPlayer `has `onPlayerCompletion ` .
That's why; `AudioCache `can not send events from player completions.

AudioCacheState.PLAYING must be implemented to AudioCache too.

**Comment by luanpotter** [comment]
This doesn't make sense, you can just access the player inside the audio cache and have full access to everything. AudioCache is just an audioplayers creator.

Please read the [troubleshooting guide](https://github.com/luanpotter/audioplayers/blob/master/troubleshooting.md#how-to-pausestop-audio) section about this.
