### ISSUE TITLE
getDuration() returns Fatal error: Double value cannot be converted to Int because it is either infinite or NaN: file Swift/x86_64-apple-ios-simulator.swiftinterface, line 32293

### ISSUE THREAD

**Issue by StarBattle08** [luanpotter/audioplayers#887]
I'm trying to get the duration of a track on IOS using getDuration(), and it keeps crashing my simulator.

```await _audioPlayer.setUrl(url);
      
var length = await _audioPlayer.getDuration();
print(length);
      
```

- Iphone 12 pro max simulator running ios 14.4
- Flutter 2.0.6
- audioplayers 0.18.3

**Comment by luanpotter** [comment]
how is the player setup? we need a sample file to reproduce. what is the full trace? please follow the issue template properly.

**Comment by StarBattle08** [comment]
Apparently it's the url that i'm using. I tested it with other URLs and it works fine. Even when i used the example code from github but changed the url, it doesn't work.

if you want to test the url : 
https://kajian.net/kajian-audio/Ceramah/Konsultasisyariah/Akhlak/Cara%20Kirim%20Salam%20dan%20Menjawabnya.mp3?l=10

**Comment by StarBattle08** [comment]
same problem with #881
