### ISSUE TITLE
Target of URI doesn't exist: 'package:audioplayers/audio_cache.dart'.

### ISSUE THREAD

**Issue by shivansh3345** [luanpotter/audioplayers#892]
error: Target of URI doesn't exist: 'package:audioplayers/audio_cache.dart'. (uri_does_not_exist at [xylophone] lib/main.dart:2)

I am getting this error when I try to import the audio_cache packege on Android Studio. Does anyone has a fix for this?

OS: ubuntu 20.04
Editor: Android Studio

**Comment by Faiizii** [comment]
If you see the source code of the repo. you will find that audio cache is moved under src directory. The author has moved all the imports(check below) inside `audioplayers.dart`. So, if you import `audioplayers.dart`, then you don't need to import cache separately.  
```
export 'audioplayers_api.dart';
export 'src/audio_cache.dart';
export 'src/audioplayer.dart';
```

or you can import `package:audioplayers/src/audio_cache.dart`

**Comment by Cyberavater** [comment]
In case, plz update it here:
https://github.com/luanpotter/audioplayers/blob/master/packages/audioplayers/doc/audio_cache.md

**Comment by dvorapa** [comment]
I import this:
```
import 'package:audioplayers/audioplayers.dart';
```
and get these errors:
```
  error • Target of URI doesn't exist:
         'package:audioplayers/audioplayers_web.dart' •
         lib/generated_plugin_registrant.dart:7:8 • uri_does_not_exist
  error • Undefined name 'AudioplayersPlugin' •
         lib/generated_plugin_registrant.dart:13:3 • undefined_identifier
```
since the update to Flutter 2.2.0

**Comment by dvorapa** [comment]
Oh, I just found out the file is generated by Flutter and I can just delete it.

**Comment by luanpotter** [comment]
Fixed here https://github.com/luanpotter/audioplayers/pull/893
