### ISSUE TITLE
AudioPlayerState undefined after upgrading to release 19.0

### ISSUE THREAD

**Issue by remoteportal** [luanpotter/audioplayers#894]
Upgraded from 0.18.3 to 0.19.0 now: undefined name 'AudioPlayerState.'

**Full Description**
I hate to ask this, as I know it's me--the only reason I'm asking as I'm guessing other people may need the answer, also.  
I see that audioplayers.dart now contains three exports, including audioplayers_api.dart, and THAT has this line:

```
export 'src/api/player_state.dart';
```
But yet my project can't find the enum.  As soon as I switch back to 18.3 all is well with the world again.

**Code to Reproduce**
audioplayers: ^0.19.0               <--- set to this
I did a flutter clean, flutter clean, and even exited Android Studio and re-entered. 

**Log Errors**
error: Undefined name 'AudioPlayerState'. (undefined_identifier at [run_sergeant] lib\main.dart:1498)
error: Undefined class 'AudioPlayerState'. (undefined_class at [run_sergeant] lib\main.dart:1498)
error: Undefined class 'AudioPlayerState'. (undefined_class at [run_sergeant] lib\main.dart:2277)

**Files/URLs/Sources**
I know you re-organized the project.  I read the notes.

**Screenshots**
N/A

**Platforms**
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 2.0.5 at E:\src\flutter
    • Framework revision adc687823a (5 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\pete\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Mi 9T (mobile) • 844fb80a • android-arm64  • Android 10 (API 29)
    • Chrome (web)   • chrome   • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)     • edge     • web-javascript • Microsoft Edge 90.0.818.46

• No issues found!

**Comment by luanpotter** [comment]
It's called `PlayerState` now: https://github.com/luanpotter/audioplayers/blob/master/packages/audioplayers/lib/src/api/player_state.dart

**Comment by remoteportal** [comment]
You see!  I thought it was me!  Even though I saw the new file with the new name my mind didn't connect the dots.

**Comment by anasssanba1** [comment]
> It's called `PlayerState` now: https://github.com/luanpotter/audioplayers/blob/master/packages/audioplayers/lib/src/api/player_state.dart

thanks
