### ISSUE TITLE
How to get total duration audio?

### ISSUE THREAD

**Issue by Shubham-Narkhede** [luanpotter/audioplayers#898]
I'm using **audioplayers: ^0.19.0** for playing my audios. Previous I was using lower version so this version supports for **__player.durationHandler_** for getting total length of audio. But updated version doesn't support I think. SO how to get total length of audio url?

**Comment by erickzanardo** [comment]
Our [README](https://github.com/luanpotter/audioplayers#duration-event) has instructions on how to get, have you tried what is stated there?

**Comment by erickzanardo** [comment]
Closing due inactivity, if there is more info that you can add to the issue, comment here and we can re open the issue.
