### ISSUE TITLE
Audioplayers version: (^0.17.4) Not able to get complete length of audio in android

### ISSUE THREAD

**Issue by aedorado** [luanpotter/audioplayers#899]
**Full Description**
Using audioplayers (^0.17.4) I am not able to get the complete length of audiofile in android whereas it works correctly in ios. 

**Code to Reproduce**

```
url = 'https://audio.iskcondesiretree.com/02_-_ISKCON_Swamis/ISKCON_Swamis_-_A_to_C/His_Holiness_Bhakti_Dhira_Damodar_Swami/Chaitanya_Charitamrita/Adi_Lila/BDDS_CC_Adi_Lila_05-01_-_The_Glories_of_Lord_Nityananda.mp3';
audioPlayer.play(url);
audioPlayer.onDurationChanged.listen((d) {
      totalAudioDuration = d;
 });
```

`totalAudioDuration` comes out to be 0 in this case. 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/6378532/120056894-b9b36c80-c05c-11eb-8d2d-025a6cd3d76e.PNG)

**Comment by erickzanardo** [comment]
You are using a somehow outdated version. Please updated to the latest one and if the issue is still happening, comment here or open a new issue.
