### ISSUE TITLE
Time to start audio is to slow

### ISSUE THREAD

**Issue by yagoliveira92** [luanpotter/audioplayers#90]
Hi. I'm using the plugin to play one web radio. I put 'audioplayers` on `initState`, but I'm having a problem: In Android Simulator the song start in 4 seconds after the app start, in release apk the song start after 50 seconds to start.

The link to server song test is that: https://azuracast.tecnocampinfo.com.br/radio/8000/listen.mp3

What do I for optimizing the time to start the song?

**Comment by erickzanardo** [comment]
There sound not be diferences between the emulator and the device, my guess would be a slow network connection on the device?

Is this easily reproducible on the device?

**Comment by yagoliveira92** [comment]
The sound quality not have any difference, the problem is in time to start audio. I put:

``` dart
  void initState() {
    super.initState();
    audioplayers.play("https://azuracast.tecnocampinfo.com.br/radio/8000/listen.mp3");
  }
```
I try in 4G, in Wifi, any other devices, and the audio start after average 50 seconds. In emulate, the audio start after 5 seconds. I do not have any idea what's wrong.

~Se vc for BR comenta ai "uhuuu"~

**Comment by Yeikel200** [comment]
Hi, I have the same problem as you, unlike my time is 30s until it starts to play without stopping. I was looking for and testing the subject and the only plugin that worked was flutter_radio, which starts playing at 5s without stopping, the only drawback is that it is unattended. I tried his example only and it worked properly, but when I implemented the plugin in my project he told me:

WARNING: Configuration 'provided' is obsolete and has been replaced with 'compileOnly'.
It will be removed at the end of 2018.

FAILURE: Build failed with an exception.

What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'flutter_radio' is using version 1.1.51

I already reported this problem in the GitHub of the project but still have not answered or any solution. If I find any other solution, I would like you to inform me.

**Comment by yagoliveira92** [comment]
Hi @Yeikel200, that's good to see other people have a same problem. In the GitHub to project "flutter_radio" Thyago updated the plugin. I cloned the repository and will try using in my project. If work, I report you =D

**Comment by AminPlusPlus** [comment]
https://pub.dartlang.org/packages/flutter_radio#-readme-tab-

its working very good and fast

**Comment by yagoliveira92** [comment]
@AminPlusPlus But there not work in background. I will test and try adapt to `audio_service` for play in background and show media notification. I answer here when I have any progress =D

**Comment by AminPlusPlus** [comment]
@yagoliveira92  but also im using : audioplayers: ^0.8.0 for iOS
because flutter_radio its not working in ios

**Comment by yagoliveira92** [comment]
@AminPlusPlus My problem in use `audioplayers` is the time to start a streaming audio together the app start. The sound start after 50s.

**Comment by AminPlusPlus** [comment]
@yagoliveira92 I had same problems, and when i used flutter_radio it fixed and starting audio 1-2 second maximum

**Comment by AminPlusPlus** [comment]
@yagoliveira92  maybe ->  import import 'dart:async';

**Comment by yagoliveira92** [comment]
@AminPlusPlus I will try and report my results. Thanks for your support =D

**Comment by yagoliveira92** [comment]
@AminPlusPlus I got use the flutter_radio. Thanks for everything =D
