### ISSUE TITLE
Log is very chatty - V/MediaPlayer-JNI, V/MediaPlayerNative

### ISSUE THREAD

**Issue by adrianvintu** [luanpotter/audioplayers#902]
I use ```await _instance.play(fileName)``` and have set ```AudioPlayer.logEnabled = false``` but still get a huge amount of logging: 150 lines for playing a 4.5 seconds file.

I guess this is the Android sytem, but is there any way to reduce the overwelming logging?

V/MediaPlayer-JNI(13416): native_setup
V/MediaPlayerNative(13416): constructor
V/MediaPlayerNative(13416): setListener
V/MediaPlayer-JNI(13416): setVolume: left 1.000000  right 1.000000
V/MediaPlayerNative(13416): MediaPlayer::setVolume(1.000000, 1.000000)
V/MediaPlayer-JNI(13416): setAuxEffectSendLevel: level 0.000000
V/MediaPlayerNative(13416): MediaPlayer::setAuxEffectSendLevel(0.000000)
V/MediaPlayer-JNI(13416): setParameter: key 1400
V/MediaPlayerNative(13416): MediaPlayer::setParameter(1400)
V/MediaPlayer-JNI(13416): setVolume: left 1.000000  right 1.000000
V/MediaPlayerNative(13416): MediaPlayer::setVolume(1.000000, 1.000000)
V/MediaPlayer-JNI(13416): setLooping: 0
V/MediaPlayerNative(13416): MediaPlayer::setLooping
V/MediaPlayer-JNI(13416): setDataSourceFD: fd 104
V/MediaPlayerNative(13416): setDataSource(104, 0, 576460752303423487)
V/MediaPlayer-JNI(13416): setVolume: left 1.000000  right 1.000000
V/MediaPlayerNative(13416): MediaPlayer::setVolume(1.000000, 1.000000)
V/MediaPlayer-JNI(13416): setLooping: 0
V/MediaPlayerNative(13416): MediaPlayer::setLooping
V/MediaPlayerNative(13416): setVideoSurfaceTexture
V/MediaPlayerNative(13416): prepareAsync
V/MediaPlayerNative(13416): message received msg=200, ext1=10973, ext2=0
W/MediaPlayerNative(13416): info/warning (10973, 0)
V/MediaPlayerNative(13416): callback application
V/MediaPlayerNative(13416): back from callback
V/MediaPlayerNative(13416): message received msg=1, ext1=0, ext2=0
V/MediaPlayerNative(13416): MediaPlayer::notify() prepared
V/MediaPlayerNative(13416): callback application
V/MediaPlayerNative(13416): back from callback
V/MediaPlayerNative(13416): invoke 68
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): start
V/MediaPlayerNative(13416): start
V/MediaPlayerNative(13416): message received msg=300, ext1=0, ext2=0
V/MediaPlayerNative(13416): Received SEC_MM_PLAYER_CONTEXT_AWARE
V/MediaPlayerNative(13416): callback application
V/MediaPlayerNative(13416): back from callback
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 0 (msec)
V/MediaPlayerNative(13416): message received msg=6, ext1=0, ext2=0
V/MediaPlayerNative(13416): unrecognized message: (6, 0, 0)
V/MediaPlayerNative(13416): callback application
V/MediaPlayerNative(13416): back from callback
V/MediaPlayer-JNI(13416): getCurrentPosition: 0 (msec)
V/MediaPlayerNative(13416): message received msg=211, ext1=0, ext2=0
V/MediaPlayerNative(13416): unrecognized message: (211, 0, 0)
V/MediaPlayerNative(13416): callback application
V/MediaPlayerNative(13416): back from callback
V/MediaPlayerNative(13416): message received msg=211, ext1=0, ext2=0
V/MediaPlayerNative(13416): unrecognized message: (211, 0, 0)
V/MediaPlayerNative(13416): callback application
V/MediaPlayerNative(13416): back from callback
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 145 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 318 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 522 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 725 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 929 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 1131 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 1332 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 1534 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 1736 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 1938 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 2140 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 2342 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 2544 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 2748 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 2950 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 3153 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 3355 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 3558 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 3761 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 3966 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 4167 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 4369 (msec)
V/MediaPlayerNative(13416): getDuration_l
V/MediaPlayer-JNI(13416): getDuration: 4538 (msec)
V/MediaPlayer-JNI(13416): getCurrentPosition: 4551 (msec)
V/MediaPlayerNative(13416): message received msg=2, ext1=0, ext2=0
V/MediaPlayerNative(13416): playback complete
V/MediaPlayerNative(13416): callback application
V/MediaPlayerNative(13416): back from callback
V/MediaPlayerNative(13416): message received msg=211, ext1=0, ext2=0
V/MediaPlayerNative(13416): unrecognized message: (211, 0, 0)
V/MediaPlayerNative(13416): callback application
V/MediaPlayerNative(13416): back from callback
V/MediaPlayer-JNI(13416): stop
V/MediaPlayerNative(13416): stop
V/MediaPlayerNative(13416): message received msg=8, ext1=0, ext2=0
V/MediaPlayerNative(13416): unrecognized message: (8, 0, 0)
V/MediaPlayerNative(13416): callback application
V/MediaPlayerNative(13416): back from callback
V/MediaPlayer-JNI(13416): reset
V/MediaPlayerNative(13416): reset
V/MediaPlayerNative(13416): message received msg=211, ext1=0, ext2=0
V/MediaPlayerNative(13416): notify(211, 0, 0) callback on disconnected mediaplayer
V/MediaPlayer(13416): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(13416): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(13416): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(13416): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer-JNI(13416): release
V/MediaPlayerNative(13416): setListener
V/MediaPlayerNative(13416): disconnect
V/MediaPlayerNative(13416): destructor
V/MediaPlayerNative(13416): disconnect

**Comment by adrianvintu** [comment]
Sorry, I think it was my mistake.

I set ```AudioPlayer.logEnabled = false``` in main.dart and now the log is zero.

Sorry again, you may close this ticket.

**Comment by erickzanardo** [comment]
Thanks for the follow up

**Comment by adrianvintu** [comment]
@erickzanardo thank you for your great work!

Maybe you can consider AudioPlayer.logEnabled being false as default.

Wish you all the best!

**Comment by adrianvintu** [comment]
@erickzanardo Can you please also remove this from the log?

V/MediaPlayer(28377): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(28377): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(28377): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(28377): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(28377): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(28377): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(28377): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(28377): cleanDrmObj: mDrmObj=null mDrmSessionId=null

**Comment by adrianvintu** [comment]
Sorry, can you please reopen this ticket?

On both Samsung Galaxy S8 and Samsung Galaxy S10 I get full log, as in the first post https://github.com/luanpotter/audioplayers/issues/902#issue-907687734

On the Android Emulator API 27 8.1 with Google Play I only get the DRM log https://github.com/luanpotter/audioplayers/issues/902#issuecomment-855232702

I have downloaded the whole project from https://github.com/luanpotter/audioplayers/

When pressing play on the first widget, I get a huge log on the real devices.

D/ViewRootImpl@a62bfb8[MainActivity](31739): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 530714017792} changed=false
I/MediaPlayer(31739): Need to enable context aware info
V/MediaPlayer-JNI(31739): native_setup
V/MediaPlayerNative(31739): constructor
V/MediaPlayerNative(31739): setListener
V/MediaPlayer-JNI(31739): setVolume: left 1.000000  right 1.000000
V/MediaPlayerNative(31739): MediaPlayer::setVolume(1.000000, 1.000000)
V/MediaPlayer-JNI(31739): setAuxEffectSendLevel: level 0.000000
V/MediaPlayerNative(31739): MediaPlayer::setAuxEffectSendLevel(0.000000)
V/MediaPlayer-JNI(31739): setParameter: key 1400
V/MediaPlayerNative(31739): MediaPlayer::setParameter(1400)
V/MediaPlayer-JNI(31739): setVolume: left 1.000000  right 1.000000
V/MediaPlayerNative(31739): MediaPlayer::setVolume(1.000000, 1.000000)
V/MediaPlayer-JNI(31739): setLooping: 0
V/MediaPlayerNative(31739): MediaPlayer::setLooping
V/MediaPlayer-JNI(31739): setDataSourceFD: fd 101
V/MediaPlayerNative(31739): setDataSource(101, 0, 576460752303423487)
V/MediaPlayer-JNI(31739): setVolume: left 1.000000  right 1.000000
V/MediaPlayerNative(31739): MediaPlayer::setVolume(1.000000, 1.000000)
V/MediaPlayer-JNI(31739): setLooping: 0
V/MediaPlayerNative(31739): MediaPlayer::setLooping
V/MediaPlayerNative(31739): setVideoSurfaceTexture
V/MediaPlayerNative(31739): prepareAsync
V/MediaPlayerNative(31739): message received msg=200, ext1=10973, ext2=0
W/MediaPlayerNative(31739): info/warning (10973, 0)
V/MediaPlayerNative(31739): callback application
V/MediaPlayerNative(31739): back from callback
V/MediaPlayerNative(31739): message received msg=1, ext1=0, ext2=0
V/MediaPlayerNative(31739): MediaPlayer::notify() prepared
V/MediaPlayerNative(31739): callback application
V/MediaPlayerNative(31739): back from callback
V/MediaPlayerNative(31739): invoke 68
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 147305 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 147305 (msec)
D/ViewRootImpl@a62bfb8[MainActivity](31739): ViewPostIme pointer 0
D/ViewRootImpl@a62bfb8[MainActivity](31739): ViewPostIme pointer 1
V/MediaPlayer-JNI(31739): native_setup
V/MediaPlayerNative(31739): constructor
V/MediaPlayerNative(31739): setListener
V/MediaPlayer-JNI(31739): setVolume: left 1.000000  right 1.000000
V/MediaPlayerNative(31739): MediaPlayer::setVolume(1.000000, 1.000000)
V/MediaPlayer-JNI(31739): setAuxEffectSendLevel: level 0.000000
V/MediaPlayerNative(31739): MediaPlayer::setAuxEffectSendLevel(0.000000)
V/MediaPlayer-JNI(31739): setParameter: key 1400
V/MediaPlayerNative(31739): MediaPlayer::setParameter(1400)
V/MediaPlayer-JNI(31739): setVolume: left 1.000000  right 1.000000
V/MediaPlayerNative(31739): MediaPlayer::setVolume(1.000000, 1.000000)
V/MediaPlayer-JNI(31739): setLooping: 0
V/MediaPlayerNative(31739): MediaPlayer::setLooping
V/MediaHTTPService(31739): MediaHTTPService(android.media.MediaHTTPService@307d0b7): Cookies: null
V/MediaPlayer-JNI(31739): setVolume: left 1.000000  right 1.000000
V/MediaPlayerNative(31739): MediaPlayer::setVolume(1.000000, 1.000000)
V/MediaPlayer-JNI(31739): setLooping: 0
V/MediaPlayerNative(31739): MediaPlayer::setLooping
V/MediaPlayerNative(31739): setVideoSurfaceTexture
V/MediaPlayerNative(31739): prepareAsync
V/MediaHTTPService(31739): makeHTTPConnection: CookieManager created: java.net.CookieManager@75d024
V/MediaHTTPService(31739): makeHTTPConnection(android.media.MediaHTTPService@307d0b7): cookieHandler: java.net.CookieManager@75d024 Cookies: null
D/MediaHTTPConnection(31739): setReadTimeOut =  15000ms
V/MediaPlayer-JNI(31739): getPlaybackSettings: 1.000000 1.000000 0 0
V/MediaPlayer-JNI(31739): setPlaybackParams: 1:1.000000 1:1.000000 1:0 1:0
V/MediaPlayerNative(31739): setPlaybackSettings: 1.000000 1.000000 0 0
D/MediaHTTPConnection(31739): setReadTimeout with 15000ms
I/System.out(31739): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(31739): (HTTPLog)-Static: isSBSettingEnabled false
I/MediaHTTPConnection(31739): response code = 200
V/MediaPlayerNative(31739): message received msg=200, ext1=10973, ext2=0
W/MediaPlayerNative(31739): info/warning (10973, 0)
V/MediaPlayerNative(31739): callback application
V/MediaPlayerNative(31739): back from callback
V/MediaPlayerNative(31739): message received msg=1, ext1=0, ext2=0
V/MediaPlayerNative(31739): MediaPlayer::notify() prepared
V/MediaPlayerNative(31739): callback application
V/MediaPlayerNative(31739): back from callback
V/MediaPlayerNative(31739): invoke 68
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): start
V/MediaPlayerNative(31739): start
V/MediaPlayerNative(31739): message received msg=300, ext1=0, ext2=0
V/MediaPlayerNative(31739): Received SEC_MM_PLAYER_CONTEXT_AWARE
V/MediaPlayerNative(31739): callback application
V/MediaPlayerNative(31739): back from callback
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 0 (msec)
V/MediaPlayerNative(31739): message received msg=3, ext1=3, ext2=0
V/MediaPlayerNative(31739): buffering 3
V/MediaPlayerNative(31739): callback application
V/MediaPlayerNative(31739): back from callback
V/MediaPlayerNative(31739): message received msg=6, ext1=0, ext2=0
V/MediaPlayerNative(31739): unrecognized message: (6, 0, 0)
V/MediaPlayerNative(31739): callback application
V/MediaPlayerNative(31739): back from callback
V/MediaPlayer-JNI(31739): getCurrentPosition: 0 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 78 (msec)
V/MediaPlayerNative(31739): message received msg=211, ext1=0, ext2=0
V/MediaPlayerNative(31739): unrecognized message: (211, 0, 0)
V/MediaPlayerNative(31739): callback application
V/MediaPlayerNative(31739): back from callback
V/MediaPlayerNative(31739): message received msg=211, ext1=0, ext2=0
V/MediaPlayerNative(31739): unrecognized message: (211, 0, 0)
V/MediaPlayerNative(31739): callback application
V/MediaPlayerNative(31739): back from callback
V/MediaPlayerNative(31739): message received msg=211, ext1=0, ext2=0
V/MediaPlayerNative(31739): unrecognized message: (211, 0, 0)
V/MediaPlayerNative(31739): callback application
V/MediaPlayerNative(31739): back from callback
V/MediaPlayerNative(31739): message received msg=211, ext1=0, ext2=0
V/MediaPlayerNative(31739): unrecognized message: (211, 0, 0)
V/MediaPlayerNative(31739): callback application
V/MediaPlayerNative(31739): back from callback
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 203 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 407 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 614 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 815 (msec)
V/MediaPlayerNative(31739): message received msg=3, ext1=51, ext2=0
V/MediaPlayerNative(31739): buffering 51
V/MediaPlayerNative(31739): callback application
V/MediaPlayerNative(31739): back from callback
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 1017 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 1221 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 1424 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 1626 (msec)
V/MediaPlayerNative(31739): message received msg=3, ext1=100, ext2=0
V/MediaPlayerNative(31739): buffering 100
V/MediaPlayerNative(31739): callback application
V/MediaPlayerNative(31739): back from callback
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 1828 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 2031 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 2234 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 2438 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 2642 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 2845 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 3049 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 3256 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 3459 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 3662 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 3867 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 4076 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 4285 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 4492 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 4697 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 4908 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 5118 (msec)
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 5325 (msec)
D/ViewRootImpl@a62bfb8[MainActivity](31739): ViewPostIme pointer 0
V/MediaPlayerNative(31739): getDuration_l
V/MediaPlayer-JNI(31739): getDuration: 210077 (msec)
V/MediaPlayer-JNI(31739): getCurrentPosition: 5530 (msec)
D/ViewRootImpl@a62bfb8[MainActivity](31739): ViewPostIme pointer 1
V/MediaPlayer-JNI(31739): stop
V/MediaPlayerNative(31739): stop
V/MediaPlayerNative(31739): message received msg=8, ext1=0, ext2=0
V/MediaPlayer-JNI(31739): reset
V/MediaPlayerNative(31739): reset
V/MediaPlayerNative(31739): unrecognized message: (8, 0, 0)
V/MediaPlayerNative(31739): callback application
V/MediaPlayerNative(31739): back from callback
V/MediaPlayerNative(31739): message received msg=211, ext1=0, ext2=0
V/MediaPlayerNative(31739): unrecognized message: (211, 0, 0)
V/MediaPlayerNative(31739): callback application
V/MediaPlayerNative(31739): back from callback
V/MediaPlayerNative(31739): message received msg=211, ext1=0, ext2=0
V/MediaPlayerNative(31739): notify(211, 0, 0) callback on disconnected mediaplayer
V/MediaPlayer(31739): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(31739): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(31739): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(31739): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer-JNI(31739): release
V/MediaPlayerNative(31739): setListener
V/MediaPlayerNative(31739): disconnect
V/MediaPlayerNative(31739): destructor
V/MediaPlayerNative(31739): disconnect

**Comment by WesleyChung** [comment]
I encounter the same issue too. Any solutions please ?
