### ISSUE TITLE
Migrate jcenter to mavenCentral

### ISSUE THREAD

**Issue by jonafeucht** [luanpotter/audioplayers#905]
As of May 1st `jCenter` has reached EOL, as [announced](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) in Febuary by JFrog.

Since this package depends on jCenter it's [highly recommended](https://blog.gradle.org/jcenter-shutdown) to migrate to mavenCentral.

**Comment by searchy2** [comment]
This issue should be resolved before August to avoid the shutdown causing any errors. 
Also, ASAP to avoid not being able to build because of JFrog's planned brownouts.

**Comment by luanpotter** [comment]
afaik we don't have any native android dependencies; if we "depend" on jcenter it's something coming from flutter, not us

**Comment by erickzanardo** [comment]
> afaik we don't have any native android dependencies; if we "depend" on jcenter it's something coming from flutter, not us

We have some dependencies @luanpotter , some kotlin libs for example.

But I believe we already uses mavenCentral: https://github.com/luanpotter/audioplayers/blob/master/packages/audioplayers/android/build.gradle#L56

**Comment by luanpotter** [comment]
There is a ref to jcenter though, here https://github.com/luanpotter/audioplayers/blob/master/packages/audioplayers/android/build.gradle#L20

But both that and the kt libs were all added by flutter itself. I will try to remove that line and see if it breaks anything, I do agree all our deps should be on maven

**Comment by luanpotter** [comment]
Fixed by https://github.com/luanpotter/audioplayers/pull/992
