### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by park1120** [luanpotter/audioplayers#906]
Suddenly I have a problem for building the app with this plugin.
Please help me.

version
audioplayers: ^0.19.0

flutter: 2.2.1(stable)

Launching lib/main.dart on SM G981N in debug mode...
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /Users/hspark/.gradle/caches/transforms-2/files-2.1/1f500a1b0c855adffc2de852447347d4/jetified-core-ktx-1.6.0-beta02-api.jar!/META-INF/core-ktx_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /Users/hspark/.gradle/caches/transforms-2/files-2.1/27f0e045a224eece0293556f642b885d/jetified-kotlin-stdlib-1.5.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /Users/hspark/.gradle/caches/transforms-2/files-2.1/5c6cb1d14d4171af66531460110a578c/jetified-kotlin-stdlib-common-1.5.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.

**Comment by ZishanK** [comment]
same issue:
Execution failed for task ':audioplayers:compileDebugKotlin'.
it was working fine a few hours ago.

**Comment by L0p3zV4rg4s** [comment]
same issue:
Working fine yesterday (05/03/2021)

**Comment by sureace** [comment]
Same issue. Not able to use this plugin.

**Comment by Thinkcreative-Technologies** [comment]
You can fix it by upgrading to ext.kotlin_version = '1.4.21' inside android/build.gradle

Happy Coding!

**Comment by sinsongdev** [comment]
Fix:
at build.gradle file's 50 line:
from
    implementation "androidx.core:core-ktx:+"
to
    implementation "androidx.core:core-ktx:1.5.0"

**Comment by primemb** [comment]
> You can fix it by upgrading to ext.kotlin_version = '1.4.21' inside android/build.gradle
> 
> Happy Coding!

work for me thank you

**Comment by erickzanardo** [comment]
Duplicated of #908
