### ISSUE TITLE
Kotlin Version incompatible

### ISSUE THREAD

**Issue by hbrhbr** [luanpotter/audioplayers#908]
Execution failed for task ':audioplayers:compileDebugKotlin'.

version
audioplayers: ^0.17.4

flutter: 2.2.1(stable)

e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /Users/hspark/.gradle/caches/transforms-2/files-2.1/1f500a1b0c855adffc2de852447347d4/jetified-core-ktx-1.6.0-beta02-api.jar!/META-INF/core-ktx_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /Users/hspark/.gradle/caches/transforms-2/files-2.1/27f0e045a224eece0293556f642b885d/jetified-kotlin-stdlib-1.5.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /Users/hspark/.gradle/caches/transforms-2/files-2.1/5c6cb1d14d4171af66531460110a578c/jetified-kotlin-stdlib-common-1.5.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.

**Comment by Thinkcreative-Technologies** [comment]
You can fix it by upgrading to  **ext.kotlin_version = '1.4.21'** inside _android/build.gradle_

Happy Coding!

**Comment by sinsongdev** [comment]
Fix:
at build.gradle file's 50 line:
from
    implementation "androidx.core:core-ktx:+"
to
    implementation "androidx.core:core-ktx:1.5.0"

**Comment by sheheryarkhan501** [comment]
tried both not solving, any other solution?
Also ios is having issues as well.

**Comment by L0p3zV4rg4s** [comment]
> You can fix it by upgrading to **ext.kotlin_version = '1.4.21'** inside _android/build.gradle_
> 
> Happy Coding!

This works fine for Android. Thanks!!

**Comment by erickzanardo** [comment]
Like mentioned on the thread, you just need to update your version on your project, you can check our example app on this repository for reference.

**Comment by Adrek** [comment]
> You can fix it by upgrading to **ext.kotlin_version = '1.4.21'** inside _android/build.gradle_
> 
> Happy Coding!

This works for me. I changed 1.3.50 to 1.4.21
