### ISSUE TITLE
After  Android Studio Flutter Plugins update build error occurred 

### ISSUE THREAD

**Issue by universalbugreporter** [luanpotter/audioplayers#909]
Environment Info

Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (7 days ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

Android Studio 4.2.1
Build #AI-202.7660.26.42.7351085, built on May 10, 2021
Runtime version: 11.0.8+10-b944.6842174 amd64

VM: OpenJDK 64-Bit Server VM by N/A
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation

Flutter Plugins Version : 57.0.2

After update Flutter plugins showing following errors

Launching lib\main.dart on Android SDK built for x86 64 in debug mode...
Running Gradle task 'assembleDebug'...
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: C:/Users/username/.gradle/caches/transforms-2/files-2.1/24fa3aa8d2270e5eb067bbe36e9b7xxx/jetified-kotlin-stdlib-1.5.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: C:\Flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.19.0\android\src\main\kotlin\xyz\luan\audioplayers\AudioplayersPlugin.kt: (25, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from C:/Users/username/.gradle/caches/transforms-2/files-2.1/24fa3aa8d2270e5eb067bbe36e9b7xxx/jetified-kotlin-stdlib-1.5.10.jar!/kotlin/Unit.class
e: C:\Flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.19.0\android\src\main\kotlin\xyz\luan\audioplayers\AudioplayersPlugin.kt: (26, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from C:/Users/username/.gradle/caches/transforms-2/files-2.1/24fa3aa8d2270e5eb067bbe36e9b7xxx/jetified-kotlin-stdlib-1.5.10.jar!/kotlin/Unit.class
e: C:\Flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.19.0\android\src\main\kotlin\xyz\luan\audioplayers\AudioplayersPlugin.kt: (27, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.

**Comment by zzx-flutter** [comment]
我也遇到了，难道要降低Android studio plugins Kotlin的版本？

**Comment by bakavic** [comment]
Updating to a newer kotlin version in `build.gradle` seems to solve the issue for me.

```
ext.kotlin_version = '1.4.32'
```

https://stackoverflow.com/a/67801441/3440368
https://stackoverflow.com/a/67835682/3440368

**Comment by mecharan14** [comment]
> Updating to a newer kotlin version in `build.gradle` seems to solve the issue for me.
> 
> ```
> ext.kotlin_version = '1.4.32'
> ```
> 
> https://stackoverflow.com/a/67801441/3440368
> https://stackoverflow.com/a/67835682/3440368

Thank you very much. This worked like a charm.

**Comment by universalbugreporter** [comment]
Thank you @bakavic 
It works.
