### ISSUE TITLE
Can not pause on version 0.8.0

### ISSUE THREAD

**Issue by finzaiko** [luanpotter/audioplayers#91]
I try the current latest version 0.8.0 can not pause correctly, if I do play again it will be back to start again,
on version 0.7.8 work fine.

**Comment by mooditech** [comment]
Are you using audioPlayer.resume()? play() will cause the audio to restart

**Comment by finzaiko** [comment]
Thanks @mooditech 
Yes, I should use `advancedPlayer.resume(),` on playing state it working now,
I try previous version work using `audioCache.play('audio.mp3');` continue last pause
