### ISSUE TITLE
Unable to build project after adding audioplayers dependencies

### ISSUE THREAD

**Issue by noman2002** [luanpotter/audioplayers#910]

**Comment by erickzanardo** [comment]
There isn't enough information on this issue for us to act on. Please edit this following the issue template.

**Comment by lulacanci** [comment]
I have the same issue even using v0.19.0 of this package, after upgrading Flutter to the latest version.

Error received on build is:

e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /.gradle/caches/transforms-2/files-2.1/24fa3aa8d2270e5eb067bbe36e9b7563/jetified-kotlin-stdlib-1.5.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /.gradle/caches/transforms-2/files-2.1/4d4ccf1034ba5937e6e7ba3aa34d2661/jetified-core-ktx-1.6.0-beta02-api.jar!/META-INF/core-ktx_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /.gradle/caches/transforms-2/files-2.1/77bab1911042ab2c6d5cc0b2e2ee053c/jetified-kotlin-stdlib-common-1.5.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: C:\xampp\htdocs\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.19.0\android\src\main\kotlin\xyz\luan\audioplayers\AudioplayersPlugin.kt: (18, 32): Unresolved reference: mutableMapOf
e: C:\xampp\htdocs\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.19.0\android\src\main\kotlin\xyz\luan\audioplayers\AudioplayersPlugin.kt: (25, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.


And so on, hundreds of lines with the same error.

**Comment by erickzanardo** [comment]
@lulacanci check https://github.com/luanpotter/audioplayers/issues/908

**Comment by khalifa007** [comment]
same issue

**Comment by frankcheng2020** [comment]
same issue, please fix.
thanks.

**Comment by khalifa007** [comment]
upgrade to ext.kotlin_version = '1.4.21'

will fix the issue .
