### ISSUE TITLE
kotlin incompatible 

### ISSUE THREAD

**Issue by vagun** [luanpotter/audioplayers#913]
![Screenshot (23)](https://user-images.githubusercontent.com/85579677/121256059-ca1fde80-c8c9-11eb-8a6b-7d68fdc383d8.png)
audioplayers 0.19 is incompatible with Kotlin 1.5.1

**Comment by aikanshboyal** [comment]
Changing the  **ext.kotlin_version**  to **'1.4.32'** worked for me in the **build.gradle** file.

**Comment by timoknapp** [comment]
> Changing the **ext.kotlin_version** to **'1.4.32'** worked for me in the **build.gradle** file.

Thanks @aikanshboyal , this acutally worked for me too.

**Comment by aikanshboyal** [comment]
Do ping me if you find the real reason behind it !! Keep Coding : )

**Comment by Maddumage** [comment]
@aikanshboyal Thanks! it worked for me also.

**Comment by robertflesch** [comment]
> Changing the ext.kotlin_version to '1.4.32' worked for me in the build.gradle file.
This did not solve issue for me. but my issue is slightly different.

* What went wrong:
A problem occurred evaluating root project 'audioplayers'.
> Failed to apply plugin [id 'kotlin-android']
   > The current Gradle version 4.10.2 is not compatible with the Kotlin Gradle plugin. Please use Gradle 5.3 or newer, or the previous version of the Kotlin plugin.

This has got me stopped in my tracks, any insights would be appreciated.

**Comment by erickzanardo** [comment]
Check #908 on how to fix this
