### ISSUE TITLE
Incompatible classes were found in dependencies

### ISSUE THREAD

**Issue by HassamTalha** [luanpotter/audioplayers#916]
The module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.

Hi, I am using audioplayers: ^0.19.0 in my project and getting error for the compiled kotlin version.  Anyone would be happy to resolve the problem with the last stable version of kotlin. 

**Log Errors**
e: C:/Users/Hassam/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.5.10/6b84d926e28493be69daf673e40076f89492ef7/kotlin-stdlib-common-1.5.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: C:/Users/Hassam/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.10/da6a904b132f0402fa4d79169a3c1770598d4702/kotlin-stdlib-1.5.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: C:/Users/Hassam/.gradle/caches/transforms-2/files-2.1/e968e560139bba463e5a44a8785436e2/core-ktx-1.6.0-beta02/jars/classes.jar!/META-INF/core-ktx_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.19.0\android\src\main\kotlin\xyz\luan\audioplayers\AudioplayersPlugin.kt: (18, 32): Unresolved reference: mutableMapOf

e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.19.0\android\src\main\kotlin\xyz\luan\audioplayers\AudioplayersPlugin.kt: (25, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from C:/Users/Hassam/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.10/da6a904b132f0402fa4d79169a3c1770598d4702/kotlin-stdlib-1.5.10.jar!/kotlin/Unit.class

**Files/URLs/Sources**
Please have a look into this repository you will get to know the idea and how to solve it.
https://github.com/hhariri/oreilly-kotlin-course/issues/5

* OS:  android,
* OS version: Android 10, 11
* Device: Nexus 5x Emulator, Samsung galaxy A31
* flutter version: 2.0.4 a gist with the output of `flutter doctor -v` (this is optional).
* audioplayers version: audioplayers: ^0.19.0

**Comment by bnnoor** [comment]
same!

**Comment by davidcz95** [comment]
I have the same, any ideas on how to solve it?

**Comment by erickzanardo** [comment]
Check #908 on how to fix this
