### ISSUE TITLE
Audio not playing on mobile data

### ISSUE THREAD

**Issue by sheheryarkhan501** [luanpotter/audioplayers#917]
Audio works fine on wifi but doesn't play when using mobile data
Can anyone provide help regarding this?

**Comment by erickzanardo** [comment]
I don't believe this is an issue with audio players, have you tried accessing the asset url on the browser for example? Using both Wi-Fi and mobile data?

**Comment by sheheryarkhan501** [comment]
> I don't believe this is an issue with audio players, have you tried accessing the asset url on the browser for example? Using both Wi-Fi and mobile data?

Thanks for replying back. Just checked and the issue is not with audioplayer as you said. The links don't open using mobile data.

**Comment by erickzanardo** [comment]
Thanks for the report, closing this as it isn't an Audioplayers issue
