### ISSUE TITLE
Autostart bug or am I just too stupid

### ISSUE THREAD

**Issue by derRenner** [luanpotter/audioplayers#925]
I have no Problems with android but on ios my audio starts right after opening the screen.

**Full Description**
I think the problem is the cache but i need it cause i am using a file from my assets. I can´t see how i can stop the cache from playing right after loading.

import 'package:audioplayers/audioplayers.dart';
import 'package:feedyourself/theme/colors.dart';
import 'package:flutter/material.dart';

class Podcast extends StatefulWidget {
  final String? audioFile;

  const Podcast({Key? key, this.audioFile}) : super(key: key);

  @override
  _Podcast createState() => _Podcast();
}

class _Podcast extends State<Podcast>
    with WidgetsBindingObserver, TickerProviderStateMixin {
  Duration _duration = new Duration();
  Duration _position = new Duration();
  late AnimationController _animationController;

  bool playing = false;
  AudioPlayer? audioPlayer;
  late AudioCache audioCache;

  @override
  void initState() {
    _animationController =
        AnimationController(vsync: this, duration: Duration(milliseconds: 450));
    super.initState();
    initPlayer();
    WidgetsBinding.instance!.addObserver(this);
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.paused) {
      audioPlayer!.stop();
    } else {
      print(state.toString());
    }
  }

  @override
  void dispose() {
    audioPlayer!.stop();
    audioPlayer!.seek(new Duration(seconds: 0));
    playing = false;
  }

  void initPlayer() {
    audioPlayer = new AudioPlayer();
    audioCache = new AudioCache(fixedPlayer: audioPlayer);
    getAudio(widget.audioFile);
    audioPlayer!.pause();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.fromLTRB(10, 10, 10, 10),
      decoration: BoxDecoration(
        color: FyColor.white,
        borderRadius: BorderRadius.circular(15),
        boxShadow: [
          BoxShadow(
            color: Colors.grey.withOpacity(0.2),
            spreadRadius: 3,
            blurRadius: 2,
            offset: Offset(1, 2), // changes position of shadow
          ),
        ],
      ),
      child: Row(
        children: [
          InkWell(
            onTap: () {
              if (playing) {
                audioPlayer!.pause();
              } else {
                audioPlayer!.resume();
              }
              setState(() {
                playing = !playing;
                playing
                    ? _animationController.forward()
                    : _animationController.reverse();
              });
            },
            child: AnimatedIcon(
              icon: AnimatedIcons.play_pause,
              size: 40,
              color: FyColor.gold,
              progress: _animationController,
            ),
          ),
          Expanded(
            child: slider(),
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text(
                _position.toString().substring(3, 7),
                style: TextStyle(
                  color: FyColor.gold,
                  fontSize: 15.0,
                ),
              ),
              Text(
                '/',
                style: TextStyle(
                  color: FyColor.gold,
                  fontSize: 15.0,
                ),
              ),
              Text(
                _duration.toString().substring(3, 7),
                style: TextStyle(
                  color: FyColor.gold,
                  fontSize: 15.0,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget slider() {
    return Slider(
        activeColor: FyColor.gold,
        inactiveColor: FyColor.gold.withOpacity(0.5),
        value: _position.inSeconds.toDouble(),
        min: 0.0,
        max: _duration.inSeconds.toDouble(),
        onChanged: (double value) {
          setState(() {
            audioPlayer!.seek(new Duration(seconds: value.toInt()));
          });
        });
  }

  void getAudio(String? audioFile) async {
    audioPlayer!.setPlaybackRate(playbackRate: 1.0);
    audioPlayer = await audioCache.play(audioFile!);
    audioPlayer!.pause();

    audioPlayer!.onDurationChanged.listen((Duration dd) {
      setState(() {
        _duration = dd;
      });
    });

    audioPlayer!.onAudioPositionChanged.listen((Duration dd) {
      setState(() {
        _position = dd;
      });
    });
  }
}

**Comment by erickzanardo** [comment]
As far I could read on your code (please correctly format it with code blocks, otherwise it is very hard to read it).

You are calling play on the getAudio method, which is called from the initPlayer which is called on the widget initState, so it auto starting the audio is indeed a side effect that can happen. I believe you need to re think this logic if you don't want to auto play.
