### ISSUE TITLE
Gradle version error

### ISSUE THREAD

**Issue by giorgi-abashidze** [luanpotter/audioplayers#926]
how can I fix this?

A problem occurred evaluating root project 'audioplayers'.
> Failed to apply plugin [id 'kotlin-android']
   > The current Gradle version 4.10.2 is not compatible with the Kotlin Gradle plugin. Please use Gradle 5.3 or newer, or the previous version of the K
otlin plugin.

**Comment by dungnc** [comment]
I had this issue too.
* Where:
Build file '/Users/hung/Desktop/developer/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.19.0/android/build.gradle' line: 25

`* What went wrong:
A problem occurred evaluating root project 'audioplayers'.
> Failed to apply plugin [id 'kotlin-android']
   > The current Gradle version 4.10.2 is not compatible with the Kotlin Gradle plugin. Please use Gradle 5.3 or newer, or the previous version of the Kotlin plugin.`

**Comment by ywmluclt** [comment]
I had this issue too.

**Comment by Tanelo** [comment]
I have this issue too !!!
Please fix it

**Comment by searchy2** [comment]
This issue along with #923 is because of not specifying a specific version of kotlin core
![image](https://user-images.githubusercontent.com/19896174/124018533-922e2780-d9ad-11eb-9808-163418dd20f7.png)

Like the warning says, builds now break because androidx.core:core-ktx:1.7.0-alpha01 is incompatible with older kotlin plugin versions.

**Comment by sjrphx** [comment]
I also have the issue. The suggested fix of changing the Kotlin version doesn't fix it. Please advise.

**Comment by 2weeks0** [comment]
> I also have the issue. The suggested fix of changing the Kotlin version doesn't fix it. Please advise.

i fixed it by changing version to 1.5.0. try it.
`implementation "androidx.core:core-ktx:1.5.0"`

**Comment by searchy2** [comment]
Please try v1.5.0 and let me know if it works. If so, I can update my PR to use v1.5.0

**Comment by searchy2** [comment]
@luanpotter should we use v1.5.0 instead just to be safe? Some users report that v1.6.0 doesn't work either from the comments above.

**Comment by Lix-ai** [comment]
Same issue, out of the blue...

**Comment by Tanelo** [comment]
> Same issue, out of the blue...

What do you mean ? Isn't the update audioplayers: ^0.19.1 Working ?

**Comment by zendamacf** [comment]
After updating to ^0.19.1, this still seems to be happening:

```
* Where:
Build file '/home/zach/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.19.1/android/build.gradle' line: 25

* What went wrong:
A problem occurred evaluating root project 'audioplayers'.
> Failed to apply plugin [id 'kotlin-android']
   > The current Gradle version 4.10.2 is not compatible with the Kotlin Gradle plugin. Please use Gradle 5.3 or newer, or the previous version of the Kotlin plugin.
```

For reference, here are the Gradle versions I'm using:
 - android/build.gradle:
    ```
    buildscript {
        ext.kotlin_version = '1.4.21'
        repositories {
            google()
            jcenter()
        }
    
        dependencies {
            classpath 'com.android.tools.build:gradle:4.2.0'
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
            classpath 'com.google.gms:google-services:4.0.1'
        }
    }
    ```

 - android/gradle/wrapper/gradle-wrapper.properties
    ```
    distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip
    ```

Any help would be greatly appreciated.

**Comment by sjrphx** [comment]
> Please try v1.5.0 and let me know if it works. If so, I can update my PR to use v1.5.0

Changing to v 1.5.0 and resending the Gradle still didn't work for me.

**Comment by guilherme-v** [comment]
ok.. in my case this error only showed up after creating aa `settings_aar.gradle` file in app's module:

```
1. Copy `settings.gradle` as `settings_aar.gradle`
2. Remove the following code from `settings_aar.gradle`:

    def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
    def properties = new Properties()

    assert localPropertiesFile.exists()
    localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

    def flutterSdkPath = properties.getProperty("flutter.sdk")
    assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
    apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"
```

The solution was:
1. in your app/build.gradle add:
```
configurations.all {
    resolutionStrategy { force 'androidx.core:core-ktx:1.6.0' }
}
```
2. Delete `settings_aar.gradle` (if you had created that like me)
