### ISSUE TITLE
Flutter 2.x - Audio not playing in background

### ISSUE THREAD

**Issue by ponnamkarthik** [luanpotter/audioplayers#936]
on iOS audio pauses playing when app went to background

I am thing issue is in ios physical device on simulator it working fine

**Comment by luanpotter** [comment]
Please check the troubleshooting guide, there is a section about that: https://github.com/luanpotter/audioplayers/blob/master/troubleshooting.md#ios

**Comment by erickzanardo** [comment]
Closing due inactivity, if there is more info that you can add to the issue, comment here and we can re open the issue.
