### ISSUE TITLE
AudioPlayer plays over itself

### ISSUE THREAD

**Issue by amicharski** [luanpotter/audioplayers#937]
**Full Description**
I created an AudioController for a puzzle game that I made. The AudioController is a Singleton object. It behaves normally if I were to go from the title screen to Level 0, but when I advance from Level 0 to Level 1, the Level 0 music keeps on playing and the Level 1 music starts. But when I advance from Level 1 to Level 2, the Level 1 music stops and the Level 2 music plays, but the Level 0 music is still playing. And then when I go from Level 2 to Level 3, the Level 2 music stops, and the Level 3 music starts, while the Level 0 music is still playing. This continues throughout the rest of the game. When the game finishes, it goes back to the title screen and the Level 0 music still plays.

**Code to Reproduce**
```dart
import 'package:audioplayers/audioplayers.dart';

import 'main.dart';

class AudioController {
  static final AudioController _audioController = AudioController._internal();
  AudioCache? _musicCache;
  AudioPlayer _instance = AudioPlayer(mode: PlayerMode.LOW_LATENCY, playerId: 'main');

  factory AudioController(){
    return _audioController;
  }

  AudioController._internal(){
    doNothing();
    //print("Audio Controller is now implemented");
  }

  Future<void> playLoop(int song) async {
    if(_musicCache == null) {
      _musicCache = AudioCache(prefix: "assets/");
    }
    int? result = await _instance.stop();
    print("STOP PLAYING RESULT: $result");
    if(song == -1){
      _instance = await _musicCache!.play("intro.mp3");
    } else {
      _instance = await _musicCache!.loop("alpha$song.ogg");
    }
  }

  void pauseMusic(){
    print("music paused");
    _instance.pause();
  }
}
```
These are the times I use the AudioController in my code:
```dart
//main.dart
AudioController audioController = AudioController();

void doNothing(){}

void main() async {
  runApp(DBall());
}

class DBall extends StatefulWidget {

  Future<InitializationStatus> _initGoogleMobileAds() {
    // TODO: Initialize Google Mobile Ads SDK
    return MobileAds.instance.initialize();
  }

  @override
  _DBallState createState() => _DBallState();
}

class _DBallState extends State<DBall> with SingleTickerProviderStateMixin {
  bool gameComplete = GameView.lvlQuantity < GameView.lvl;
  late ConfettiController _controller;
  late BannerAd _bannerAd;
  bool _isBannerAdReady = false;

  void playIntroAudio() async {
    _controller = ConfettiController(duration: Duration(seconds: 5));
    if(gameComplete){
      _controller.play();
      GameView.lvl = 0;
      GameView.lvlComplete.value = false;
    }
    audioController.playLoop(-1);
  }
...
```
```dart
//view.dart
class _GameViewState extends State<GameView> {
  late Level level;
  late BannerAd _bannerAd;
  bool _isBannerAdReady = false;
  late BannerAd _bannerAd2;
  bool _isBannerAd2Ready = false;
  Color _backgroundColor = Color(0xFF151515);
  AudioController audioController = AudioController();

  Color setBackgroundFX(){
    print('Floor value: ${(GameView.lvl/2).floor()%3+1}');
    if(!GameView.lvlComplete.value){
      audioController.playLoop((GameView.lvl/2).floor()%3+1);
...
```
<details>
<summary>Logs</summary>
`flutter run --verbose`
I couldn't fit everything into here so I had to upload it as a text file to my school drive: http://elvis.rowan.edu/~michar52/misc/audioplayerslogs
</details>
**Platforms**
* OS: Android
* OS version: 30
* Device: Emulator Google Pixel XL
* flutter version: 2.3.0-16.0.pre
* dart version: 2.14.0-136.0.dev
* audioplayers version: 0.19.0
* release or not release: debug

**Comment by luanpotter** [comment]
That is not a bug, that is how `AudioCache` works. if you want to use the same player, please set the `AudioCache.fixedPlayer` property.

**Comment by Lelelo1** [comment]
@ luanpotter 
> That is not a bug, that is how `AudioCache` works. if you want to use the same player, please set the `AudioCache.fixedPlayer` property.

![Screenshot 2021-08-04 at 11 51 50](https://user-images.githubusercontent.com/42244983/128160992-fa6aef92-fdbb-434a-8a43-dd4bea02604c.png)

In the docs it says a new instance is created (version `^0.17.4`).. if i'ts not set.
