### ISSUE TITLE
 Build failed with an exception

### ISSUE THREAD

**Issue by limuyi1** [luanpotter/audioplayers#940]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':path_provider'.
> Could not resolve all artifacts for configuration ':path_provider:classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.11.
     Required by:
         project :path_provider > com.android.tools.build:gradle:3.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:builder:3.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.analytics-library:shared:26.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.lint:lint-gradle-api:26.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:gradle-api:3.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > androidx.databinding:databinding-compiler-common:3.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:builder:3.3.0 > com.android.tools:sdk-common:26.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:builder:3.3.0 > com.android.tools:common:26.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:builder:3.3.0 > com.android.tools.build:manifest-merger:26.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:builder:3.3.0 > com.android.tools.analytics-library:tracker:26.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:builder:3.3.0 > com.android.tools:sdklib:26.3.0 > com.android.tools:repository:26.3.0
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.11.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.11/kotlin-stdlib-jdk8-1.3.11.pom'.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.11/kotlin-stdlib-jdk8-1.3.11.pom'.
               > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.0.0.1, repo.maven.apache.org/0:0:0:0:0:0:0:1] failed: Connection refused: connect
   > Could not resolve org.apache.httpcomponents:httpmime:4.5.2.
     Required by:
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.analytics-library:crash:26.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:builder:3.3.0 > com.android.tools:sdklib:26.3.0
      > Could not resolve org.apache.httpcomponents:httpmime:4.5.2.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/apache/httpcomponents/httpmime/4.5.2/httpmime-4.5.2.pom'.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/org/apache/httpcomponents/httpmime/4.5.2/httpmime-4.5.2.pom'.
               > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.0.0.1, repo.maven.apache.org/0:0:0:0:0:0:0:1] failed: Connection refused: connect
   > Could not resolve org.apache.httpcomponents:httpcore:4.4.5.
     Required by:
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.analytics-library:crash:26.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:builder:3.3.0 > com.android.tools:sdklib:26.3.0
      > Could not resolve org.apache.httpcomponents:httpcore:4.4.5.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/apache/httpcomponents/httpcore/4.4.5/httpcore-4.4.5.pom'.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/org/apache/httpcomponents/httpcore/4.4.5/httpcore-4.4.5.pom'.
               > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.0.0.1, repo.maven.apache.org/0:0:0:0:0:0:0:1] failed: Connection refused: connect
   > Could not resolve org.apache.httpcomponents:httpclient:4.5.2.
     Required by:
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.analytics-library:crash:26.3.0
      > Could not resolve org.apache.httpcomponents:httpclient:4.5.2.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.pom'.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.pom'.
               > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.0.0.1, repo.maven.apache.org/0:0:0:0:0:0:0:1] failed: Connection refused: connect
   > Could not resolve org.jetbrains.kotlin:kotlin-reflect:1.3.11.
     Required by:
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.lint:lint-gradle-api:26.3.0
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build:builder:3.3.0 > com.android.tools:sdk-common:26.3.0
      > Could not resolve org.jetbrains.kotlin:kotlin-reflect:1.3.11.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-reflect/1.3.11/kotlin-reflect-1.3.11.pom'.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-reflect/1.3.11/kotlin-reflect-1.3.11.pom'.
               > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.0.0.1, repo.maven.apache.org/0:0:0:0:0:0:0:1] failed: Connection refused: connect
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.2.20.
     Required by:
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build.jetifier:jetifier-core:1.0.0-beta02
         project :path_provider > com.android.tools.build:gradle:3.3.0 > com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta02
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.2.20.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.2.20/kotlin-stdlib-1.2.20.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.2.20/kotlin-stdlib-1.2.20.pom'.
               > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.0.0.1, repo.maven.apache.org/0:0:0:0:0:0:0:1] failed: Connection refused: connect
> Could not get unknown property 'android' for project ':path_provider' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 4s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin audioplayers...
Running Gradle task 'assembleAarRelease'...

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.19.0\android\build.gradle' line: 36

* What went wrong:
A problem occurred evaluating root project 'audioplayers'.
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 6.5. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in D:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.19.0\android\gradle\wrapper\gradle-wrapper.properties to gradle-6.5-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

Exception: The plugin audioplayers could not be built due to the issue above.

**Comment by erickzanardo** [comment]
This seems to be rather a problem with your connection (or with the maven server connection) and not with audioplayers, look at this section of your log:

```
> Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.11/kotlin-stdlib-jdk8-1.3.11.pom'.
> Could not HEAD 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.11/kotlin-stdlib-jdk8-1.3.11.pom'.
> Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.0.0.1, repo.maven.apache.org/0:0:0:0:0:0:0:1] failed: Connection refused: connect
```

**Comment by adamburnet** [comment]
Removing this dependency from the pubspec.yaml fixed my build issues. Something stopped playing nice just recently.

**Comment by limuyi1** [comment]
@adamburnet Installation error，I can't solve it

**Comment by adamburnet** [comment]
My issue was unrelated to this one. My mistake.
