### ISSUE TITLE
 Cannot execute AudioPlayer in kotlin compiler.

### ISSUE THREAD

**Issue by Dzaky02** [luanpotter/audioplayers#942]
[ Execution failed for task ':audioplayers:compileDebugKotlin'.]

**Full Description**
I've made a new flutter project with Android Studio and choose only swift and kotlin language (withouth java and objective C checklist). I just made a single Elevated Button to tested out audio player. And it not run at all, not even started the aplication. It's crash from the begining.

**Code to Reproduce**
![image](https://user-images.githubusercontent.com/30130167/124387471-0b5cb000-dd09-11eb-8984-1831aa6990d9.png)

![image](https://user-images.githubusercontent.com/30130167/124387493-1f081680-dd09-11eb-8c29-d822fa1625f1.png)

![image](https://user-images.githubusercontent.com/30130167/124387521-32b37d00-dd09-11eb-82b5-c34aa72b6c2c.png)

**Log Errors**
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':audioplayers:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by UdayKiranBayya** [comment]
The problem of the crash is due to the incompatible kotlin binary version that's used by your dependencies metadata.
* Just get into the 'build.gradle' file, found at "android/build.gradle" location of your flutter project's root directory.
`dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.0"
    }
`
Change the jetbrains:kotlin classpath as I done above. Change it's version to 1.5.0.
* For more information https://stackoverflow.com/a/59916349/14279556

**Comment by Dzaky02** [comment]
> 
> 
> The problem of the crash is due to the incompatible kotlin binary version that's used by your dependencies metadata.
> 
>     * Just get into the 'build.gradle' file, found at "android/build.gradle" location of your flutter project's root directory.
>       `dependencies { classpath 'com.android.tools.build:gradle:4.1.0' classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.0" } `
>       Change the jetbrains:kotlin classpath as I done above. Change it's version to 1.5.0.
> 
>     * For more information https://stackoverflow.com/a/59916349/14279556
> 
>     * Hope this solved your problem.

Thanks for saving my day!
