### ISSUE TITLE
AudioPlayer.setPlaybackRate don't work.

### ISSUE THREAD

**Issue by GaNuiGLPK** [luanpotter/audioplayers#946]
["AudioPlayer.setPlaybackRate don't work.]

**Full Description**
I want to setPlaybackRate, but when to set  AudioPlayer.setPlaybackRate = 0.5  or 1.0, speed no difference.

**Comment by luanpotter** [comment]
Please follow the issue template, this post is missing crucial information and therefore cannot be addressed.
