### ISSUE TITLE
Audio player is taking too much time to load even small audio file , please can u suggest any way to improve loading time

### ISSUE THREAD

**Issue by khurram40** [luanpotter/audioplayers#953]

**Comment by luanpotter** [comment]
Are you using the pre-load functions? AudioCache? AudioPool? Please add more details to your question as it's too vague to answer.

**Comment by khurram40** [comment]
No, I'm not using these functions, just passing the URL to player.
                        await audioPlayer.play(baseUrl+widget.data.maleAudio);
