### ISSUE TITLE
When Adding dependency audioplayers: ^0.18.3 Getting error Execution failed for task ':audioplayers:compileReleaseKotlin'.

### ISSUE THREAD

**Issue by vikramaggarwal13** [luanpotter/audioplayers#955]
Getting error Execution failed for task ':audioplayers:compileReleaseKotlin'.

Flutter Stable version is 2.2.3 
FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':audioplayers:compileReleaseKotlin'.

> Compilation error. See log for more details

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 34s

dependencies added below 
  audioplayers: ^0.18.3
  shared_preferences: 
  http: 
  sqflite: ^1.3.1+1
  path_provider: 
  package_info: ^0.4.3
  url_launcher: ^5.5.3
  android_multiple_identifier: ^1.0.3 
  share: ^0.6.5
  get_ip: ^0.4.0
  paytm: ^0.0.5
  flutter_launcher_icons: "^0.9.0"
  qr_flutter: ^3.2.0
  barcode_scan: ^3.0.1
  image_picker: ^0.6.0+9
  smooth_star_rating: ^1.1.0+1
  location: ^3.0.2

**Comment by MahMoos** [comment]
I have the same error.
Flutter 2.2.0 • channel stable
`e: /Users/abc/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.19.1/android/src/main/kotlin/xyz/luan/audioplayers/WrappedSoundPool.kt: (239, 30): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.`

my `kotlin_version = '1.1.50'`

**Comment by vikramaggarwal13** [comment]
This solved my too Thanks

**Comment by vikramaggarwal13** [comment]
Done
