### ISSUE TITLE
setVolume doesn't work. 

### ISSUE THREAD

**Issue by JamesQing2021** [luanpotter/audioplayers#958]
When I try to use setVolume method, I found it doesn't work. Even I set setVolume(0), Nothing changed

I searched issues before, I found some similar issues. But none of them could work for me

audioplayers version: 0.18.3

Could someone have a solution about this??

**Comment by NemanjaLugi** [comment]
For me, the setVolume method is partly working. When audio player playback is active setVolume works fine, but when is stopped/paused setVolume does not work.

**Comment by amanpreeto7** [comment]
@NemanjaLugi Can you please explain more as I cannot set Volume

**Comment by luanpotter** [comment]
Just tested this on `0.20.0` on the example app, I can pause, setVolume, resume, no problem. Please follow the issue template so your issue contains all the necessary information so we can properly troubleshoot.

**Comment by superwebarmy** [comment]
I’m facing the same problem
