### ISSUE TITLE
Is there a function to get player state?

### ISSUE THREAD

**Issue by IrosTheBeggar** [luanpotter/audioplayers#96]
Is there a function to get the player state (playing/paused/errored)?   Right now I'm keeping track of state in a variable, but it's complicating things because I use the multiple players feature for gapless playback.

**Comment by luanpotter** [comment]
Yes, @IrosTheBeggar , thankfully recently @renancaraujo added this feature for us.
You can use:

```dart
  AudioPlayer player = new AudioPlayer(/* ... */);
  // ...
  player.state // gets an AudioPlayerState representing the current state
```

Or even register an `audioPlayerStateChangeHandler` to listen to state changes.
