### ISSUE TITLE
Audio not working on certain devices

### ISSUE THREAD

**Issue by Do-Repo** [luanpotter/audioplayers#963]
I get errors when launching the app and trying to play audio on my Huawei Y6 II (android 6) , the audio won't start and I get these errors:

`
Launching lib\main.dart on CAM L21 in debug mode...
lib\main.dart:1
Parameter format not correct -

√  Built build\app\outputs\flutter-apk\app-debug.apk.

Connecting to VM Service at ws://127.0.0.1:53182/gDtxebCclSk=/ws
I/BD.Reporter(21143): com.huawei.bd.IBDService$Stub$Proxy@5a36bc8

26
I/System  (21143): core_booster, getBoosterConfig = false
E/MediaPlayer(21143): error (1, -2147483648)
E/MediaPlayer(21143): Error (1,-2147483648)
I/MediaPlayer(21143): [HSM] stayAwake false uid: 10108, pid: 21143
E/MediaPlayer(21143): pause called in state 0
E/MediaPlayer(21143): error (-38, 0)
E/MediaPlayer(21143): Attempt to perform seekTo in wrong state: mPlayer=0x558be7c400, mCurrentState=0
E/MediaPlayer(21143): error (-38, 0)
I/MediaPlayer(21143): [HSM] stayAwake false uid: 10108, pid: 21143
E/MediaPlayer(21143): Error (-38,0)
I/MediaPlayer(21143): [HSM] stayAwake false uid: 10108, pid: 21143
E/MediaPlayer(21143): Error (-38,0)
I/MediaPlayer(21143): [HSM] stayAwake false uid: 10108, pid: 21143
`

However on my Pixel 3a XL API 29 emulator, everything works completely fine, I don't think the problem is in my code, however let me know if you want any additional info

**Comment by luanpotter** [comment]
Have you tried the example app? What audio exactly are you trying to play?? Please follow the issue template and properly format code and logs so this issue can be addressed.

**Comment by Do-Repo** [comment]
The example app works fine, even though I'm still getting the same logs
`
I/BD.Reporter( 1395): com.huawei.bd.IBDService$Stub$Proxy@9d41e14
I/MediaPlayer( 1395): setDataSource(59, 0, 576460752303423487)
I/MediaPlayer( 1395): setDataSource(https://luan.xyz/files/audio/ambient_c_motion.mp3)
W/MediaPlayer( 1395): info/warning (1001, 0)
2
I/System  ( 1395): core_booster, getBoosterConfig = false
I/MediaPlayer( 1395): [HSM] stayAwake true uid: 10109, pid: 1395
I/MediaPlayer( 1395): Pid:1395 MediaPlayer::start
I/MediaPlayer( 1395): [HSM] stayAwake false uid: 10109, pid: 1395

`
But on the emulator its different
`
Launching lib\main.dart on Android SDK built for x86 in debug mode...
lib\main.dart:1
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:54645/JseIti_OCc8=/ws
D/EGL_emulation(22615): eglMakeCurrent: 0xde3c92a0: ver 2 0 (tinfo 0xd620f7a0)
W/players.exampl(22615): Accessing hidden method Lsun/misc/Unsafe;->getUnsafe()Lsun/misc/Unsafe; (greylist,core-platform-api, linking, allowed)
W/players.exampl(22615): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
W/players.exampl(22615): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/players.exampl(22615): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
V/MediaHTTPService(22615): MediaHTTPService(android.media.MediaHTTPService@195d337): Cookies: null
V/MediaHTTPService(22615): makeHTTPConnection: CookieManager created: java.net.CookieManager@6afe0a4
V/MediaHTTPService(22615): makeHTTPConnection(android.media.MediaHTTPService@195d337): cookieHandler: java.net.CookieManager@6afe0a4 Cookies: null

`

The audio I'm trying to play are just http mp3 links, which used to work and still do work fine on the emulator but not anymore on my Huawei Y6 II , which is not the case for the example app

**Comment by Do-Repo** [comment]
This problem definitely isn't from my end, since I just tried previous versions of my app I got from my repo history and its not working, meanwhile it used to work before, exactly 11 days ago according to GitHub

**Comment by erickzanardo** [comment]
You mentioned that this mp3 is a hosted file. Isn't there a chance that the file changed somehow?

It is not that uncommon for the same file to play ok on some devices and fail on different ones. Different devices have different codecs bundled with them, which affects the player.

**Comment by Do-Repo** [comment]
Looking at the api`s repo there has been changes 6 days ago, I'll look into that and let you know, however failing on some devices and not on others because of the audio file is highly unlikely, and if so there would have been more specific errors I guess

**Comment by erickzanardo** [comment]
I do agree with you that there should be more specific errors, but unfortunately this is something that breaks on the Android native MediaPlayer, and from our experience that part of the android API don't give us much to work on, so there isn't much that we can do from the plugin side.

**Comment by Do-Repo** [comment]
Yes, the API developers have made some changes to the CDN references, thus affecting the audio files I think... They have made changes in the links so I'm closing this issue assuming its the API's fault, however I still have no idea what this means:

`
I/System (21143): core_booster, getBoosterConfig = false
E/MediaPlayer(21143): error (1, -2147483648)
E/MediaPlayer(21143): Error (1,-2147483648)
I/MediaPlayer(21143): [HSM] stayAwake false uid: 10108, pid: 21143
E/MediaPlayer(21143): pause called in state 0
E/MediaPlayer(21143): error (-38, 0)
E/MediaPlayer(21143): Attempt to perform seekTo in wrong state: mPlayer=0x558be7c400, mCurrentState=0
E/MediaPlayer(21143): error (-38, 0)
I/MediaPlayer(21143): [HSM] stayAwake false uid: 10108, pid: 21143
E/MediaPlayer(21143): Error (-38,0)
I/MediaPlayer(21143): [HSM] stayAwake false uid: 10108, pid: 21143
E/MediaPlayer(21143): Error (-38,0)
I/MediaPlayer(21143): [HSM] stayAwake false uid: 10108, pid: 21143
`

Which are warnings I only get just recently when debugging on the Huawei Y6 II
