### ISSUE TITLE
playing raw audio file from assets

### ISSUE THREAD

**Issue by BwesShr** [luanpotter/audioplayers#97]
Hi I am trying to play raw file from assets in the app. I found it through audiocache but it doesnot allow puse stop control. I tried with the code below but, didn't work.
final result =
          await audioPlayer.play('assets/sounds/song.mp3', isLocal: true);

**Comment by luanpotter** [comment]
Hi, @BwesShr , thanks for commenting! AudioPlauer alone won't play from asset, you do need AudioCache. However, AudioCache returns a brand new instance of AudioPlayer every time you call it, and you can use that to pause and stop and resume as desired.

Example:

```dart
    AudioPlayer player = await cache.play('asset_file.mp3');
    // ...
    player.pause();
    player.stop();
    player.resume();
```

If you want even more control, you can set or even override the fixedPlayer property, for more details about the cache please check the guide [here](https://github.com/luanpotter/audioplayers/blob/master/doc/audio_cache.md).

**Comment by BwesShr** [comment]
thnx for the prompt reply... it was helpful...
