### ISSUE TITLE
Can't get duration in android Devices. 

### ISSUE THREAD

**Issue by shishankbarua** [luanpotter/audioplayers#970]
I am using  audioplayers: 0.16.1 version. It's playing sound but not getting duration and position. So Slider seek and pause then play is not working. I have check in log , we are not getting Duration and we when tap on Slider seek. It's showing error. 

the getter 'inMilliseconds' was called on null 

enum PlayerState { stopped, playing, paused }
enum PlayingRouteState { speakers, earpiece }

class AudioPlayerWidget extends StatefulWidget {
 final MediaModel model;
  final PlayerMode mode;

 AudioPlayerWidget(
      {Key key, @required this.model, this.mode = PlayerMode.MEDIA_PLAYER})
      : super(key: key);

  @override
  State<StatefulWidget> createState() {
    return _PlayerWidgetState(model, mode);
  }
}

class _PlayerWidgetState extends State<AudioPlayerWidget> {
  MediaModel model;
  PlayerMode mode;
  AudioPlayer _audioPlayer;
  AudioPlayerState _audioPlayerState;
  Duration _duration;
  Duration _position;

  PlayerState _playerState = PlayerState.stopped;
  PlayingRouteState _playingRouteState = PlayingRouteState.speakers;
  StreamSubscription _durationSubscription;
  StreamSubscription _positionSubscription;
  StreamSubscription _playerCompleteSubscription;
  StreamSubscription _playerErrorSubscription;
  StreamSubscription _playerStateSubscription;
  StreamSubscription<PlayerControlCommand> _playerControlCommandSubscription;

  get _isPlaying => _playerState == PlayerState.playing;

  get _isPaused => _playerState == PlayerState.paused;

  get _durationText => _duration?.toString()?.split('.')?.first ?? '';

  get _positionText => _position?.toString()?.split('.')?.first ?? '';

  get _isPlayingThroughEarpiece =>
      _playingRouteState == PlayingRouteState.earpiece;

  _PlayerWidgetState(this.model, this.mode);

  @override
  void initState() {
    super.initState();
    _initAudioPlayer();
    AudioPlayer.logEnabled = true;
    // print(_durationText);
  }

  @override
  void dispose() {
    _audioPlayer.dispose();
    _durationSubscription?.cancel();
    _positionSubscription?.cancel();
    _playerCompleteSubscription?.cancel();
    _playerErrorSubscription?.cancel();
    _playerStateSubscription?.cancel();
    _playerControlCommandSubscription?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      // mainAxisSize: MainAxisSize.min,
      children: <Widget>[

        Row(
          //  mainAxisSize: MainAxisSize.min,
          children: [
            _buildPlayPause(),
            SizedBox(
              width: 10,
            ),
            _buildDuration(),
            Expanded(
              flex: 1,
              child: Slider(
                activeColor: Colors.orange,
                inactiveColor: lightGray,
                onChanged: (v) {
                  final Position = v * _duration.inMilliseconds;
                  _audioPlayer.seek(Duration(milliseconds: Position.round()));
                },
                value: (_position != null &&
                        _duration != null &&
                        _position.inMilliseconds > 0 &&
                        _position.inMilliseconds < _duration.inMilliseconds)
                    ? _position.inMilliseconds / _duration.inMilliseconds
                    : 0.0,
              ),
            ),
            IconButton(
              padding: const EdgeInsets.all(0.0),
              onPressed: _earpieceOrSpeakersToggle,
              iconSize: 26.0,
              icon: _isPlayingThroughEarpiece
                  ? Icon(Icons.volume_off)
                  : Icon(Icons.volume_up),
              color: lightGray,
            ),
            _menuButton(),
          ],
        ),

      ],
    );
  }

  GestureDetector _menuButton() {
    return GestureDetector(
      onTap: () {
        print(model.imageBase64);
      },
      child: SvgPicture.asset(
        'assets/icons/dot_menu.svg',
        width: 15,
        height: 15,
        color: Colors.black,
      ),
    );
  }

  Widget _buildDuration() {
    return Text(
      _position != null
          ? '${formatDuration(_position)}  / ${formatDuration(_duration)}'
          : '',
      style: TextStyle(fontSize: 15.0),
    );
  }

  /*Widget _buildAudioDuration() {
    return Text(
      _position != null ? '${formatDuration(_duration)}' : '',
      style: TextStyle(fontSize: 15.0),
    );
  }*/

  Widget _buildPlayPause() {
    return Container(
        padding: EdgeInsets.all(5),
        decoration: BoxDecoration(
          color: appColor,
          borderRadius: BorderRadius.circular(80.0),
        ),
        child: GestureDetector(
          onTap: () => _isPlaying ? _pause() : _play(),
          child: Icon(
            _isPlaying ? Icons.pause : Icons.play_arrow,
            size: 25,
            color: white,
          ),
        ));
  }

  void _initAudioPlayer() {
    _audioPlayer = AudioPlayer(mode: mode);
      _durationSubscription = _audioPlayer.onDurationChanged.listen((duration) {
        setState(() => _duration = duration);
      if (Theme.of(context).platform == TargetPlatform.iOS) {
        // (Optional) listen for notification updates in the background
        _audioPlayer.startHeadlessService();

        // set at least title to see the notification bar on ios.
        _audioPlayer.setNotification(
          title: 'App Name',
          artist: 'Artist or blank',
          albumTitle: 'Name or blank',
          imageUrl: 'url or blank',
          // forwardSkipInterval: const Duration(seconds: 30), // default is 30s
          // backwardSkipInterval: const Duration(seconds: 30), // default is 30s
          duration: duration,
          elapsedTime: Duration(seconds: 0),
          hasNextTrack: true,
          hasPreviousTrack: false,
        );
      }
    });

    _positionSubscription =
        _audioPlayer.onAudioPositionChanged.listen((p) => setState(() {
              _position = p;
            }));

    _playerCompleteSubscription =
        _audioPlayer.onPlayerCompletion.listen((event) {
      _onComplete();
      setState(() {
        _position = _duration;
      });
    });

    _playerErrorSubscription = _audioPlayer.onPlayerError.listen((msg) {
      print('audioPlayer error : $msg');
      setState(() {
        _playerState = PlayerState.stopped;
        _duration = Duration(seconds: 0);
        _position = Duration(seconds: 0);
      });
    });

    _playerControlCommandSubscription =
        _audioPlayer.onPlayerCommand.listen((command) {
      print('command');
    });

    _audioPlayer.onPlayerStateChanged.listen((state) {
      if (!mounted) return;
      setState(() {
        _audioPlayerState = state;
        print('audio_status------------->' + _audioPlayerState.toString());
      });
    });

    _audioPlayer.onNotificationPlayerStateChanged.listen((state) {
      if (!mounted) return;
      setState(() => _audioPlayerState = state);
    });

    _playingRouteState = PlayingRouteState.speakers;
  }

  Future<int> _play() async {
    print("url ${widget.model.imageBase64}");
    final playPosition = (_position != null &&
            _duration != null &&
            _position.inMilliseconds > 0 &&
            _position.inMilliseconds < _duration.inMilliseconds)
        ? _position
        : null;
    final result = await _audioPlayer.play(widget.model.imageBase64, isLocal: true);
    if (result == 1) setState(() => _playerState = PlayerState.playing);
   // _audioPlayer.setPlaybackRate(playbackRate: 1.0);
    return result;
  }

  Future<int> _pause() async {
    final result = await _audioPlayer.pause();
    if (result == 1) setState(() => _playerState = PlayerState.paused);
    
  }

**Comment by erickzanardo** [comment]
You are using quite an outdated version of Audioplayers, I believe this was fixed on newer versions already.

**Comment by shishankbarua** [comment]
It's working now without update. Just remove mode:playerMode.MEDIA_PLAYER
Thank you.
