### ISSUE TITLE
Module 'audioplayers' not found

### ISSUE THREAD

**Issue by kenaitian** [luanpotter/audioplayers#974]
**Describe the bug**
Module "AudioPlayers" not found

**To Reproduce**
1. Visit app 'https://github.com/kenaitian/xylophone-flutter'
2. Clone 
3. Open project folder xylophone-flutter/ios/Runner.xcworkspace
4. See error when you run

**Expected behavior**
App should render screen with button "Click Me" and makes a sound upon clicking that button.

**Screenshots**
![Screen Shot 2021-08-01 at 12 43 58 PM](https://user-images.githubusercontent.com/63857624/127778892-1fd6da47-6076-4c21-a0e5-0d1fa99071f9.png)

**Desktop:**
 - OS: macOS Big Sur 
    Version 11.5.1 

**Smartphone:**
 - Device: iPhone 11
 - OS: iOS 14.6

**Additional context**
Do the following in order to elect the proper device that you want to retrieve the crash log from as your iPhone would've been connected to the Mac and synced:
1. Hit Command+Shift+G and navigate to ~/Library/Logs/CrashReporter/MobileDevice/
2. Look for files with the app name you want the crash reports from, copy that out of the folder, or copy multiple logs and zip them up for your review

**Comment by erickzanardo** [comment]
There isn't enough information to act on this issue, please edit it and follow the template.

**Comment by kenaitian** [comment]
The app works perfectly fine on Android after upgrading pre 1.12 Android projects but it errs with “Module 'audioplayers' not found” in Xcode…

dependencies:
audioplayers: ^0.19.1

**Comment by StarBattle08** [comment]
Open the xcworkspace file and try again

**Comment by kenaitian** [comment]
> Open the xcworkspace file and try again

that was ttried as well among other exhaustive options...

**Comment by youannis-aziz** [comment]
I have exactly the same issue, any solution?

**Comment by peter100u** [comment]
我有完全相同的问题，有什么解决方案吗？

**Comment by NuteIla** [comment]
I have the exact same issue, appreciate any solutions!

**Comment by ag84ark** [comment]
For me, it worked after `flutter clean`, `flutter build ios`. I had this problem when I was trying to archive, on run was working without problem. Also did the clean from Xcode.
Hope it helps someone.
