### ISSUE TITLE
how to stop local audio player?

### ISSUE THREAD

**Issue by shree-krishna-gapi** [luanpotter/audioplayers#975]
import 'dart:io';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: ExampleApp()));
}

class ExampleApp extends StatefulWidget {
  @override
  _ExampleAppState createState() => _ExampleAppState();
}

class _ExampleAppState extends State<ExampleApp> {
  AudioCache audioCache = AudioCache();
  @override
  void initState() {
    super.initState();
    if (kIsWeb) {
      // Calls to Platform.isIOS fails on web
      return;
    }
    if (Platform.isIOS) {
      audioCache.fixedPlayer?.notificationService.startHeadlessService();
    }
  }
  AudioPlayer player = new AudioPlayer();
  String mp3Uri = "audio.mp3";
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
      ),
      body: Center(
        child:    Column(
          children: [
            _Btn(
              txt: 'Play',
              onPressed: () async {
                final bytes = await (await audioCache.loadAsFile('audio.mp3'))
                    .readAsBytes();
                audioCache.playBytes(bytes);
              },
            ),
            _Btn(
              txt: 'Stop',
              onPressed: () async {
                //TODO:// How to stop audioCache
              },
            ),
          ],
        ),
      ),
    );
  }
}

class _Btn extends StatelessWidget {
  final String txt;
  final VoidCallback onPressed;

  const _Btn({Key? key, required this.txt, required this.onPressed})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ButtonTheme(
      minWidth: 48.0,
      child: ElevatedButton(child: Text(txt), onPressed: onPressed),
    );
  }
}

**Comment by erickzanardo** [comment]
Please correctly follow the issue template and provide info in the description about the issue

**Comment by shree-krishna-gapi** [comment]
@erickzanardo i edit the example project in this simple step, it's work good but i can't find stop event would you please find out. thank you.

**Comment by shree-krishna-gapi** [comment]
i get solution thanks
