### ISSUE TITLE
Error: PlatformException(Unimplemented, null, The audioplayers plugin for web doesn't implement the method 'seek', null)

### ISSUE THREAD

**Issue by Duraibabu-Ramanathan** [luanpotter/audioplayers#991]
Hello,I tried to use a Slider Widget for Seeking the audio in Flutter Web.
The Method i used to Seek is audioPlayer.seek()
it throws me an error 
Like this:
Error: PlatformException(Unimplemented,
null, The audioplayers plugin for web
doesn't implement the method 'seek',
null)

**Comment by luanpotter** [comment]
yeah, because `seek` wasn't implemented on web. check the [feature parity table](https://github.com/luanpotter/audioplayers/blob/master/feature_parity_table.md) for more details.

however this was then implemented on #983, and released on 0.20.0

so should work now.
