### ISSUE TITLE
Exception: The plugin audioplayers could not be built

### ISSUE THREAD

**Issue by hbrhbr** [luanpotter/audioplayers#995]
`audioplayers-0.17.4`

The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.

Building plugin audioplayers...
Running Gradle task 'assembleAarRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'audioplayers'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

Exception: The plugin audioplayers could not be built due to the issue above.

**Comment by roskimlong** [comment]
I met that issues too any solution? :(

**Comment by Navneetsinh53** [comment]
Today, I'm facing same issue with audioplayers: ^0.18.3. It was working fine till yesterday.

**Comment by Malrok** [comment]
I had issues building my project today, it uses this plugin as a transient dependency.  
Following this solution worked for me: https://stackoverflow.com/a/69031863/1843141  
Hopefully this will be fixed in an updated version soon.

**Comment by Navneetsinh53** [comment]
@Malrok Thank you , By changing compileSdkVersion from 29 to 31 issue is resolved for me.

**Comment by luanpotter** [comment]
we should add this to the FAQ

**Comment by luanpotter** [comment]
Actually this is fixed by the new version (0.20.0), so I don't think we need to add it to the FAQ at all.

**Comment by crushman1** [comment]
I had to downgrade to version 0.16.0. because my project is not setup for null safety yet and too big to migrate over a weekend.
