### ISSUE TITLE
android build failed

### ISSUE THREAD

**Issue by Benife** [luanpotter/audioplayers#996]
hi.
my android project build failed.

Launching lib\main.dart on SM G991N in debug mode...
lib\main.dart:1
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: C:/Users/hslee/.gradle/caches/transforms-2/files-2.1/4e3a30d5bfda97eb1b490c47c38ed9c3/jetified-kotlin-stdlib-1.5.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: C:/Users/hslee/.gradle/caches/transforms-2/files-2.1/c08200713eddc7ba4cf0a833d1096a8a/jetified-core-ktx-1.6.0-api.jar!/META-INF/core-ktx_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: C:/Users/hslee/.gradle/caches/transforms-2/files-2.1/c33b678f162fde69bf1da34545627087/jetified-kotlin-stdlib-common-1.5.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: D:\dev_tool\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.19.1\android\src\main\kotlin\xyz\luan\audioplayers\AudioplayersPlugin.kt: (18, 32): Unresolved reference: mutableMapOf

audioplayers: ^0.19.1

please help me

**Comment by moepoi** [comment]
Same issue too

**Comment by lizhuoyuan** [comment]
Maybe because of this version issue
```
 implementation "androidx.core:core-ktx:+"
```

**Comment by Benife** [comment]
@lizhuoyuan thank you for answer. but, i try that androidx.core:core-ktx:+ to androidx.core:core-ktx:1.6.0.
i'm not working.

**Comment by nicolasvahidzein** [comment]
I am having that issue as well, i will try upgrading to the latest version to see if it fixes it but how did this come about? It makes no sense.

**Comment by nicolasvahidzein** [comment]
version 19.0.0 has the same bug this is a big problem. Please look into this asap.

**Comment by nicolasvahidzein** [comment]
> Maybe because of this version issue
> 
> ```
>  implementation "androidx.core:core-ktx:+"
> ```
> 
> chang this line `androidx.core:core-ktx:+` to `androidx.core:core-ktx:1.6.0` in the build.gradle
> 
> Then I can run normally.
> 
> If it’s just because the version of audioplayers is not the latest, please change to the latest version and execute flutter clean

This bypass works BTW but it is not the preferred solution at all.

**Comment by MalanDev** [comment]
Same issue too

**Comment by anasssanba1** [comment]
another solution is to update kotlin version in build.gradle from this : ext.kotlin_version = '1.3.50'  to   ext.kotlin_version = '1.4.32'

**Comment by luanpotter** [comment]
I imagine [this](https://github.com/luanpotter/audioplayers/pull/992) fixes it right?

**Comment by luanpotter** [comment]
Fixed by #992

**Comment by nicolasvahidzein** [comment]
Yes fixed indeed by version 0.20.0. Thanks a ton!!!

**Comment by cgs** [comment]
I'm using 0.20.1 and I'm still seeing this error
